import {roleCanOpenOperatorHref} from "@/components/ops/role-policy";
import Link from "next/link";
import {getOpsRequestContext,assertStoreInSessionScope} from "@/lib/server/ops-request-context";
import {accessTask} from "@/lib/ops/store-tasks";
import {taskRoles,type CameraWindow,type CameraFinding} from "@/lib/ops/store-task-types";
import {TaskForm,TaskFiles,TaskCompletion,TaskRecipients,TaskSeen} from "@/components/workspace/store-task-forms";
import styles from "@/components/workspace/store-tasks.module.css";
import {formatOperationsDateTime} from "@/lib/ops/local-time";
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{offset?:string}>}) {
 const {session,repository:r,actor}=await getOpsRequestContext(taskRoles),{id}=await params;
 const {task:t,access,eligible}=await accessTask(r,session.organizationId,id,actor.actorId!),store=await assertStoreInSessionScope(session,t.storeId);
 const offset=Math.max(0,Math.min(100000,Number((await searchParams).offset)||0));
 const [messages,files]=await Promise.all([r.listTaskMessages(session.organizationId,id,offset),r.listFilesForEntity(session.organizationId,'store_task',id)]);
 const person=async(id:string|null)=>{if(!id)return '';const m=await r.getMembership(session.organizationId,id);return m?(await r.getUserInOrganization(session.organizationId,m.userId))?.displayName??'Assigned person':'';};
 const [handler,requester,fallback]=await Promise.all([person(t.claimantId??t.assigneeId),person(t.requesterId),person(t.fallbackId)]);
 const canComplete=t.status==='open'&&(t.claimantId??t.assigneeId)===actor.actorId;
 const canClaim=t.status==='open'&&!t.claimantId&&(t.assignment==='person'?t.assigneeId===actor.actorId:eligible);
 const latestResult=messages.find(m=>m.kind==='complete');
 const fmt=(s:string)=>formatOperationsDateTime(s,store.timeZone??'America/New_York');
 return <div className={styles.page}><TaskSeen id={id} at={t.updatedAt}/><header><Link href="/app/tasks">← Tasks</Link><p><Link href={`/app/stores/${t.storeId}/tasks`}>Store {store.storeNumber} · {store.name}</Link></p><h1>{t.title}</h1></header>
 <section className={styles.panel}><span className={styles.tag}>{t.status==='closed'?'Closed':t.status==='review'?(t.requesterId===actor.actorId?'Awaiting your review':'Awaiting requester review'):t.assignment==='local'?'Store action needed':t.claimantId?'In progress':'Open'}</span><dl className={styles.facts}><div><dt>Next action</dt><dd>{t.status==='closed'?'No further action':t.status==='review'?'Review findings':handler?'Complete the check':'Take this task'}</dd></div><div><dt>Responsible</dt><dd>{t.status==='review'?requester:handler||(t.assignment==='local'?'Someone at the store':'Anyone responsible for this store')}</dd></div><div><dt>Due</dt><dd>{fmt(t.dueAt)}{t.status!=='closed'&&t.dueAt<new Date().toISOString()?' · Overdue':''}</dd></div><div><dt>If overdue, alert</dt><dd>{fallback}</dd></div></dl><p className={styles.muted}>Requested by {requester} · {t.priority==='urgent'?'Urgent':'Routine'}</p><h2>What to do</h2><p className={styles.summary}>{t.instructions}</p>
 {!canComplete&&t.kind==='camera'?<div>{(JSON.parse(t.windowsJson) as CameraWindow[]).map((w,i)=><p key={i}><strong>Window {i+1}{w.area?` · ${w.area}`:''}</strong><br/>{fmt(w.start)} – {fmt(w.end)}</p>)}</div>:null}
 <div className={styles.actions}>{t.workOrderId?<Link href={`/app/work-orders/${t.workOrderId}`}>Work order</Link>:null}{t.invoiceId&&roleCanOpenOperatorHref(session.role,`/app/invoices/${t.invoiceId}`)?<Link href={`/app/invoices/${t.invoiceId}`}>Invoice</Link>:null}{t.visitId?<Link href={`/app/visits/${t.visitId}`}>Visit</Link>:null}{t.assetId?<Link href={`/app/equipment/${t.assetId}`}>Equipment</Link>:null}</div>
 {canClaim&&!canComplete?<TaskForm action="claim" id={id} version={t.version}><button className={styles.primary}>I’ll take it</button></TaskForm>:null}</section>
 {canComplete?<section className={styles.panel}><h2>Record findings</h2><TaskCompletion task={t} timeZone={store.timeZone}/></section>:null}
 {t.status==='review'&&t.requesterId===actor.actorId?<section className={styles.panel}><h2>{t.result==='attention'?'Needs attention':t.result==='unable'?'Couldn’t complete':'Findings ready'}</h2>{latestResult?<p className={styles.summary}>{latestResult.body}</p>:null}<p><a href="#task-history">View detailed findings and history</a></p><TaskForm action="review" id={id} version={t.version}><label>Review note <span className={styles.muted}>Optional</span><textarea name="body" rows={2}/></label><button className={styles.primary}>Reviewed — close task</button></TaskForm><details><summary>Send back for more information</summary><TaskForm action="send_back" id={id} version={t.version}><label>What else is needed?<textarea name="body" required rows={3}/></label><label>New due date<input type="datetime-local" name="dueAt" required/></label><button>Send back</button></TaskForm></details></section>:null}
 <section className={styles.panel}><h2>Photos and paperwork</h2>{files.length?<ul>{files.map(f=><li key={f.id}><a href={`/api/ops/tasks/${id}/files/${f.id}`} target="_blank" rel="noreferrer">{f.originalName}</a></li>)}</ul>:<p className={styles.muted}>No files attached yet.</p>}</section>
 <section className={styles.panel}><h2 id="task-history">Replies and history</h2>{t.status!=='closed'?<TaskForm action="reply" id={id} version={t.version}><label>Reply<textarea name="body" required rows={3} maxLength={6000}/></label><TaskFiles/><button>Send reply</button></TaskForm>:null}<ol className={styles.thread}>{messages.map(m=><li key={m.id}><strong>{m.actorName}</strong><p className={styles.muted}>{m.kind.replaceAll('_',' ')} · {fmt(m.createdAt)}</p><p>{m.body}</p>{(JSON.parse(m.findingsJson) as CameraFinding[]).map((f,i)=><div className={styles.window} key={i}><strong>Window {i+1} · {f.result==='unavailable'?'No footage':f.result}</strong>{f.start?<p>Observed {fmt(f.start)} – {fmt(f.end)}</p>:null}<p>{f.notes}</p></div>)}</li>)}</ol><div className={styles.actions}>{offset>0?<Link href={`?offset=${Math.max(0,offset-50)}`}>Newer</Link>:null}{messages.length===50?<Link href={`?offset=${offset+50}`}>Older</Link>:null}</div></section>
 {t.status!=='closed'&&(access.supervisor||t.requesterId===actor.actorId)?<details className={styles.panel}><summary>Reassign task</summary><TaskForm action="reassign" id={id} version={t.version}><TaskRecipients storeId={t.storeId} initialAssignment={t.assignment} initialAssignee={t.assigneeId??''} fallbackId={t.fallbackId}/><label>Reason<textarea name="body" required rows={2}/></label><button>Save assignment</button></TaskForm></details>:null}</div>;
}
