import {describe,it,expect} from "vitest";
import {createOpsFixtureRepository} from "@/lib/ops/fixture-repository";
import {buildNorthlinePresentationFixture} from "@/lib/ops/fixtures";
import {recordWorkOrderCost} from "@/lib/ops/work-recording-commands";
import {receiveInvoice,resolveInvoiceReview} from "@/lib/ops/financial-control-commands";
import {DatabaseSync,type SQLInputValue} from "node:sqlite";
import {readFileSync,readdirSync} from "node:fs";
import {buildOpsSeedStatements} from "@/lib/ops/seed";
import {createOpsSqlRepository} from "@/lib/ops/sql-repository";
import type {OpsSqlDriver,SqlRow} from "@/lib/ops/sql-driver";
import type {OpsRepository,OpsStatement} from "@/lib/ops/repository";
const org="org-northline-demo",workId="wo-northline-103",vendorId="vendor-northline-forecourt";
const actor={organizationId:org,actorType:"user" as const,actorId:"membership-northline-facilities",actorName:"Test manager"};
const reviewer={...actor,actorId:"membership-northline-executive"};
function fixture(){const f=buildNorthlinePresentationFixture();f.costLines=f.costLines.filter(c=>c.workOrderId!==workId);f.authorizations=f.authorizations.filter(a=>a.workOrderId!==workId);f.invoiceLineAllocations=f.invoiceLineAllocations.filter(a=>a.workOrderId!==workId);f.warrantyCases=f.warrantyCases.filter(a=>a.workOrderId!==workId);const w=f.workOrders.find(w=>w.id===workId)!;w.internalReviewThresholdMinor=undefined;w.status="closed";return f;}
function record(repository:OpsRepository,amountMinor:number,providerType:"internal"|"vendor",breakdown?:Array<{kind:"parts"|"labor";amountMinor:number}>){return recordWorkOrderCost({repository},{organizationId:org,workOrderId:workId,kind:"other",amountMinor,providerType,vendorId:providerType==="vendor"?vendorId:undefined,description:"Known expense",serviceDate:"2026-09-01",actor,breakdown});}
function invoice(repository:OpsRepository,amountMinor:number){return receiveInvoice({organizationId:org,workOrderId:workId,vendorId,vendorInvoiceNumber:"SIMPLE-COST",invoiceDate:"2026-09-01",currency:"USD",lines:[{category:"other_fee",description:"Service",amount:{amountMinor,currency:"USD"}}],actor,automatic:true,optionalControls:true},{repository});}
async function costs(repository:OpsRepository){return (await repository.getWorkOrderDetail({organizationId:org},workId))!.costs;}
async function mismatch(repository:OpsRepository){await record(repository,8500,"internal");const previous=await record(repository,60000,"vendor",[{kind:"parts",amountMinor:20000},{kind:"labor",amountMinor:40000}]);const bill=await invoice(repository,65000);expect(bill.flagCount).toBe(1);expect((await costs(repository)).reduce((s,c)=>s+c.amountMinor,0)).toBe(68500);const flag=(await repository.listInvoiceExceptions(org,bill.invoiceId))[0];expect(flag.kind).toBe("cost_match");await expect(resolveInvoiceReview({organizationId:org,invoiceId:bill.invoiceId,exceptionId:flag.id,actor:reviewer,decision:"accept_as_billed",reason:"Reviewed original invoice"},{repository})).rejects.toMatchObject({code:"VALIDATION"});await resolveInvoiceReview({organizationId:org,invoiceId:bill.invoiceId,exceptionId:flag.id,actor:reviewer,decision:"accept_as_billed",reason:"Invoice replaces earlier estimate",costChoice:previous.id},{repository});const rows=await costs(repository);expect(rows.reduce((s,c)=>s+c.amountMinor,0)).toBe(73500);expect(rows.filter(c=>c.reversesCostId)).toHaveLength(2);expect(rows.find(c=>c.id===previous.id)?.amountMinor).toBe(20000);expect((await repository.getWorkOrder(org,workId))?.status).toBe("closed");await expect(resolveInvoiceReview({organizationId:org,invoiceId:bill.invoiceId,exceptionId:flag.id,actor:reviewer,decision:"accept_as_billed",reason:"Retry",costChoice:previous.id},{repository})).rejects.toMatchObject({code:"CONFLICT"});expect((await costs(repository)).reduce((s,c)=>s+c.amountMinor,0)).toBe(73500);}
describe("simple work costs",()=>{
 it("uses the assigned vendor after completion without asking for a vendor",async()=>{const f=fixture();f.assignments.filter(a=>a.workOrderId===workId).forEach(a=>a.status="completed");const r=createOpsFixtureRepository(f);await recordWorkOrderCost({repository:r},{organizationId:org,workOrderId:workId,kind:"other",amountMinor:5000,providerType:"vendor",description:"Service call",serviceDate:"2026-09-01",actor});expect((await costs(r))[0].vendorId).toBe(vendorId);});
 it("rejects a different vendor and an unassigned vendor cost",async()=>{const f=fixture();const r=createOpsFixtureRepository(f);const input={organizationId:org,workOrderId:workId,kind:"other" as const,amountMinor:5000,providerType:"vendor" as const,description:"Service call",serviceDate:"2026-09-01",actor};await expect(recordWorkOrderCost({repository:r},{...input,vendorId:"wrong-vendor"})).rejects.toMatchObject({code:"CONFLICT"});f.assignments=f.assignments.filter(a=>a.workOrderId!==workId);await expect(recordWorkOrderCost({repository:createOpsFixtureRepository(f)},input)).rejects.toMatchObject({code:"VALIDATION"});expect(await costs(r)).toHaveLength(0);});
 it("flags an invoice from another vendor after the assignment completed",async()=>{const f=fixture();f.assignments.filter(a=>a.workOrderId===workId).forEach(a=>a.status="completed");const r=createOpsFixtureRepository(f);const other=f.vendors.find(v=>v.id!==vendorId)!;const bill=await receiveInvoice({organizationId:org,workOrderId:workId,vendorId:other.id,vendorInvoiceNumber:"WRONG-VENDOR",invoiceDate:"2026-09-01",currency:"USD",lines:[{category:"other_fee",description:"Service",amount:{amountMinor:5000,currency:"USD"}}],actor,automatic:true,optionalControls:true},{repository:r});expect((await r.listInvoiceExceptions(org,bill.invoiceId)).some(flag=>flag.kind==="allocation_mismatch")).toBe(true);expect(await costs(r)).toHaveLength(0);});
 it("retains vendor line descriptions and groups the amounts",async()=>{const r=createOpsFixtureRepository(fixture());await recordWorkOrderCost({repository:r},{organizationId:org,workOrderId:workId,kind:"other",amountMinor:12500,providerType:"vendor",vendorId,description:"Invoice entry",serviceDate:"2026-09-01",actor,breakdown:[{kind:"other",description:"Service call",amountMinor:5000},{kind:"other",description:"Compressor repair",amountMinor:7500}]});const rows=await costs(r);expect(rows.map(row=>row.description)).toEqual(["Service call","Compressor repair"]);expect(new Set(rows.map(row=>row.costGroupId)).size).toBe(1);const bill=await invoice(r,12500);expect(bill.flagCount).toBe(0);expect(await costs(r)).toHaveLength(2);expect((await costs(r)).every(row=>row.invoiceId===bill.invoiceId)).toBe(true);});
 it("copies invoice line descriptions and amounts into costs",async()=>{const r=createOpsFixtureRepository(fixture());const bill=await receiveInvoice({organizationId:org,workOrderId:workId,vendorId,vendorInvoiceNumber:"ITEMIZED",invoiceDate:"2026-09-01",currency:"USD",lines:[{category:"other_fee",description:"Service call",amount:{amountMinor:5000,currency:"USD"}},{category:"part",description:"Compressor",amount:{amountMinor:7500,currency:"USD"}}],actor,automatic:true,optionalControls:true},{repository:r});expect(bill.flagCount).toBe(0);expect((await costs(r)).map(row=>[row.description,row.amountMinor])).toEqual([["Service call",5000],["Compressor",7500]]);});
 it("records only known internal expenses on closed work",async()=>{const r=createOpsFixtureRepository(fixture());await record(r,8500,"internal");expect((await costs(r))[0]).toMatchObject({amountMinor:8500,kind:"other",providerType:"internal"});expect((await r.getWorkOrder(org,workId))?.status).toBe("closed");});
 it("rejects a breakdown that does not equal the total without saving",async()=>{const r=createOpsFixtureRepository(fixture());await expect(record(r,8500,"internal",[{kind:"parts",amountMinor:8000}])).rejects.toMatchObject({code:"VALIDATION"});expect(await costs(r)).toHaveLength(0);});
 it("adds a clean invoice once alongside internal expenses",async()=>{const r=createOpsFixtureRepository(fixture());await record(r,8500,"internal");const bill=await invoice(r,60000);expect(bill.flagCount).toBe(0);expect((await costs(r)).reduce((s,c)=>s+c.amountMinor,0)).toBe(68500);expect((await costs(r)).find(c=>c.invoiceId===bill.invoiceId)?.providerType).toBe("vendor");await expect(invoice(r,60000)).rejects.toMatchObject({code:"CONFLICT"});await expect(record(r,60000,"vendor")).rejects.toMatchObject({code:"CONFLICT"});});
 it("links a matching manual vendor cost without adding it again",async()=>{const r=createOpsFixtureRepository(fixture());const cost=await record(r,60000,"vendor");const bill=await invoice(r,60000);expect(bill.flagCount).toBe(0);expect(await costs(r)).toHaveLength(1);expect((await costs(r))[0]).toMatchObject({id:cost.id,amountMinor:60000,invoiceId:bill.invoiceId});});
 it("reviews a difference and keeps the original history",async()=>{await mismatch(createOpsFixtureRepository(fixture()));});
 it("preserves cost matching, corrections and totals in SQLite",async()=>{const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");const params=(s:OpsStatement)=>s.params.map(v=>v==null?null:typeof v==="boolean"?Number(v):v as SQLInputValue);const driver:OpsSqlDriver={dialect:"sqlite",async query<Row extends SqlRow>(s:OpsStatement){return {rows:db.prepare(s.sql).all(...params(s)) as Row[],affectedRows:0}},async atomic(ss){db.exec("BEGIN");try{for(const s of ss)db.prepare(s.sql).run(...params(s));db.exec("COMMIT");}catch(e){db.exec("ROLLBACK");throw e;}}};try{for(const name of readdirSync("drizzle").filter(n=>/^\d.*\.sql$/.test(n)).sort())db.exec(readFileSync(`drizzle/${name}`,"utf8"));await driver.atomic(buildOpsSeedStatements(fixture()));await mismatch(createOpsSqlRepository(driver,"d1"));expect(db.prepare("PRAGMA foreign_key_check").all()).toEqual([]);}finally{db.close();}},60000);
});
