import { describe,expect,it } from "vitest";
import { createOpsFixtureRepository } from "@/lib/ops/fixture-repository";
import { buildNorthlinePresentationFixture } from "@/lib/ops/fixtures";
import { invoiceUploadRegression,uploadActor } from "./helpers/invoice-upload-regression";
import { matchInvoiceExtraction,saveInvoiceUpload,recordInvoiceUpload,reviewInvoiceUpload } from "@/lib/ops/invoice-upload-commands";
import type { InvoiceExtraction } from "@/lib/ops/invoice-extraction";
function harness(threshold:number|null=5000){const fixture=buildNorthlinePresentationFixture();const work=fixture.workOrders.find(w=>w.id==="wo-northline-103")!;work.internalReviewThresholdMinor=threshold ?? undefined;work.internalReviewCurrency="USD";fixture.costLines=fixture.costLines.filter(c=>c.workOrderId!==work.id);fixture.authorizations=fixture.authorizations.filter(a=>a.workOrderId!==work.id);fixture.invoiceLineAllocations=fixture.invoiceLineAllocations.filter(a=>a.workOrderId!==work.id);fixture.warrantyCases=fixture.warrantyCases.filter(c=>c.workOrderId!==work.id);const vendor=fixture.vendors.find(v=>v.id===fixture.assignments.find(a=>a.workOrderId===work.id)!.vendorId)!;const store=fixture.stores.find(s=>s.id===work.storeId)!;const repository=createOpsFixtureRepository(fixture);const data:InvoiceExtraction={documentKind:"invoice",invoiceCount:1,vendorName:vendor.name,invoiceNumber:"AUTO-CLEAN",invoiceDate:"2026-09-28",currency:"USD",workOrderNumber:work.number,storeNumber:store.storeNumber,storeName:null,serviceAddress:null,totalMinor:5000,uncertainFields:[],lines:[{category:"travel",description:"Service trip",amountMinor:5000}]};return {repository,data};}
async function upload(repository:ReturnType<typeof createOpsFixtureRepository>){return saveInvoiceUpload(repository,uploadActor,{id:"file-new",organizationId:uploadActor.organizationId,storageKey:"test",sha256:"a".repeat(64),originalName:"a.pdf",contentType:"application/pdf",byteLength:100,status:"available",createdAt:new Date().toISOString()});}
describe("invoice-first intake",()=>{
 it("persists, reviews, records and deduplicates",async()=>{await invoiceUploadRegression(createOpsFixtureRepository(buildNorthlinePresentationFixture()));});
 it("records a clean match at the threshold without optional authorization or contract",async()=>{const {repository,data}=harness();const row=await recordInvoiceUpload(repository,uploadActor,await upload(repository),data);expect(row.status).toBe("recorded");const lineIds=new Set(repository.snapshot().invoiceLines.filter(l=>l.invoiceId===row.invoiceId).map(l=>l.id));expect(repository.snapshot().invoiceLineAllocations.filter(a=>lineIds.has(a.invoiceLineId)).every(a=>a.method==="exact_work_order"&&!a.confirmedByMembershipId&&!a.siteVisitWorkOrderId)).toBe(true);expect((await repository.getInvoice(uploadActor.organizationId,row.invoiceId!))?.status).toBe("received");expect(repository.snapshot().invoiceExceptions.filter(e=>e.invoiceId===row.invoiceId)).toHaveLength(0);});
 it("records without an internal flag amount",async()=>{const {repository,data}=harness(null);data.totalMinor=500000;data.lines[0].amountMinor=500000;const row=await recordInvoiceUpload(repository,uploadActor,await upload(repository),data);expect((await repository.getInvoice(uploadActor.organizationId,row.invoiceId!))?.status).toBe("received");expect(repository.snapshot().invoiceExceptions.filter(e=>e.invoiceId===row.invoiceId)).toHaveLength(0);});
 it("flags above the internal threshold without approving payment",async()=>{const {repository,data}=harness(4999);const row=await recordInvoiceUpload(repository,uploadActor,await upload(repository),data);const invoice=await repository.getInvoice(uploadActor.organizationId,row.invoiceId!);expect(invoice).toMatchObject({status:"exception",approvedForPayment:{amountMinor:0}});expect(repository.snapshot().invoiceExceptions.find(e=>e.invoiceId===row.invoiceId)?.summary).toContain("internal flag");});
 it.each([{workOrderNumber:null},{vendorName:"Someone else"},{storeNumber:"999"},{totalMinor:6000},{uncertainFields:["total"]},{documentKind:"credit" as const},{invoiceCount:2}])("requires review for %j",async patch=>{const {repository,data}=harness();expect((await matchInvoiceExtraction(repository,uploadActor.organizationId,{...data,...patch})).issues.length).toBeGreaterThan(0);});
 it("denies foreign and read-only actors",async()=>{const {repository}=harness();const row=await upload(repository);await expect(reviewInvoiceUpload(repository,{...uploadActor,organizationId:"other"},row,["Review"])).rejects.toMatchObject({code:"FORBIDDEN"});await expect(reviewInvoiceUpload(repository,{...uploadActor,actorId:"membership-northline-finance"},row,["Review"])).rejects.toMatchObject({code:"FORBIDDEN"});});
 it("does not reopen recorded uploads",async()=>{const {repository,data}=harness();const row=await recordInvoiceUpload(repository,uploadActor,await upload(repository),data);await expect(reviewInvoiceUpload(repository,uploadActor,row,["Reopen"])).rejects.toMatchObject({code:"CONFLICT"});});
 it("records concurrent retries only once",async()=>{const {repository,data}=harness();const row=await upload(repository);const results=await Promise.all([recordInvoiceUpload(repository,uploadActor,row,data),recordInvoiceUpload(repository,uploadActor,row,data)]);expect(results[0].invoiceId).toBe(results[1].invoiceId);expect(repository.snapshot().invoices.filter(i=>i.vendorInvoiceNumber===data.invoiceNumber)).toHaveLength(1);});
 it("keeps a corrected clean invoice clear of optional-control flags",async()=>{const {repository,data}=harness();const saved=await upload(repository),row=await reviewInvoiceUpload(repository,uploadActor,saved,["Check location"],{...data,storeNumber:"999"});const recorded=await recordInvoiceUpload(repository,uploadActor,row,data,{workOrderId:"wo-northline-103",vendorId:"vendor-northline-forecourt",reason:"Checked the service location against the original"});expect((await repository.getInvoice(uploadActor.organizationId,recorded.invoiceId!))?.status).toBe("received");expect(recorded.extractedJson).toContain("999");expect(repository.snapshot().auditEvents.some(e=>e.aggregateId===row.id&&e.eventType==="invoice_upload.recorded"&&e.payloadJson.includes("Checked the service location"))).toBe(true);});

});
