ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "fk_ops_pm_occurrences_org" FOREIGN KEY ("organization_id") REFERENCES "public"."ops_organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "fk_ops_pm_occurrences_plan" FOREIGN KEY ("organization_id","plan_id") REFERENCES "public"."ops_pm_plans"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "fk_ops_pm_occurrences_store" FOREIGN KEY ("organization_id","store_id") REFERENCES "public"."ops_stores"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "fk_ops_pm_occurrences_asset" FOREIGN KEY ("organization_id","asset_id") REFERENCES "public"."ops_assets"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "fk_ops_pm_occurrences_work" FOREIGN KEY ("organization_id","work_order_id") REFERENCES "public"."ops_work_orders"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_plans" ADD CONSTRAINT "fk_ops_pm_plans_org" FOREIGN KEY ("organization_id") REFERENCES "public"."ops_organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_plans" ADD CONSTRAINT "fk_ops_pm_plans_store" FOREIGN KEY ("organization_id","store_id") REFERENCES "public"."ops_stores"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_plans" ADD CONSTRAINT "fk_ops_pm_plans_asset" FOREIGN KEY ("organization_id","asset_id") REFERENCES "public"."ops_assets"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "chk_ops_pm_occurrences_status" CHECK ("ops_pm_occurrences"."status" IN ('upcoming', 'unscheduled', 'proposed', 'scheduled', 'due', 'completed', 'completed_early', 'completed_on_time', 'completed_late', 'missed', 'waived', 'cancelled'));--> statement-breakpoint
ALTER TABLE "ops_pm_occurrences" ADD CONSTRAINT "chk_ops_pm_occurrences_completion" CHECK ("ops_pm_occurrences"."status" NOT IN ('completed', 'completed_early', 'completed_on_time', 'completed_late') OR "ops_pm_occurrences"."completed_at" IS NOT NULL);--> statement-breakpoint
ALTER TABLE "ops_pm_plans" ADD CONSTRAINT "chk_ops_pm_plans_target" CHECK ("ops_pm_plans"."store_id" IS NOT NULL OR "ops_pm_plans"."asset_id" IS NOT NULL OR nullif(btrim("ops_pm_plans"."category_key"), '') IS NOT NULL);