import { DecisionScope } from "./decision-scope";
import Link from "next/link";
import type { DecisionContextModel } from "@/app/app/_data/decision-context";
import styles from "./lifecycle-record-stack.module.css";

export function DecisionContext({ model }: { model: DecisionContextModel }) {
  return <section className={styles.section} id="decision-context">
    <header className={styles.sectionHeading}><h2>Recent issues</h2><Link href={model.fullHistoryHref}>Full equipment history →</Link></header>
    <DecisionScope choices={model.choices} /><nav className={`${styles.scope} ${styles.desktopScope}`} aria-label="Decision equipment scope">{model.choices.map((choice) => <Link href={choice.href} key={choice.href} aria-current={choice.selected ? "page" : undefined} scroll={false}>{choice.label}</Link>)}</nav>
    <nav className={styles.scope} aria-label="Decision history period">{model.periods.map((choice) => <Link href={choice.href} key={choice.href} aria-current={choice.selected ? "page" : undefined} scroll={false}>{choice.label}</Link>)}</nav>
    <h3>{model.title}</h3>
    {model.notice ? <p role="status">{model.notice}</p> : <>
      <p>{model.period} · Recorded work cost</p>
      <div className={styles.spending}><div><span>Whole equipment</span><Link href={model.wholeHref}><strong>{model.wholeCost}</strong></Link></div>{model.selectedComponent ? <div><span>Selected component scope · included in the whole-equipment total</span><a href="#decision-costs"><strong>{model.selectedCost}</strong></a></div> : <div><span>Source cost lines</span><a href="#decision-costs">Review {model.costCount} recorded lines ↓</a></div>}</div>
      <details className={styles.evidence}><summary>History notes</summary><ul className={styles.facts}>{model.facts.map((fact) => <li key={fact.text}>{fact.text} <Link href={fact.href}>See evidence</Link></li>)}</ul></details>
      {model.pending.length ? <aside className={styles.notice}><strong>Unresolved warranty reviews in this equipment scope</strong>{model.pending.map((row) => <p key={row.href}><Link href={row.href}>{row.label} →</Link></p>)}</aside> : null}
      <section className={styles.evidence} id="decision-repairs" aria-label="Recent issue records">
        <div className={styles.repairTable}><table><thead><tr><th>Issue</th><th>Repair and outcome</th><th>Recorded cost</th></tr></thead><tbody>{model.rows.map(row => <tr key={row.id}><td data-label="Issue"><Link className={styles.rowLink} href={row.href}><small>{row.date} · {row.number}</small><strong>{row.problem}</strong><span>{row.scope}</span><small>{row.provider}</small></Link></td><td data-label="Repair and outcome"><Link className={styles.rowLink} href={row.href}>{row.repairs.map((repair, index) => <span key={index}>{repair.action}</span>)}<span>{row.outcome}</span><small>{row.verification}</small></Link></td><td data-label="Recorded cost"><Link className={styles.rowLink} href={row.href}><strong>{row.cost}</strong><small>Open work order →</small></Link></td></tr>)}</tbody></table></div>
        {!model.rows.length ? <p>No issues in this scope and period.</p> : null}
        <nav className={styles.scope} aria-label="Decision history pages">{model.pages.map(row => <Link key={row.href} href={row.href}>{row.label}</Link>)}</nav>
      </section>
      <section className={styles.evidence} id="replacement-references"><header className={styles.sectionHeading}><div><h2>{model.selectedComponent ? "Component replacement references" : "Similar replacement costs"}</h2><span>{model.showOlder ? "All saved dates" : "Last 12 months"} · through {model.referenceAsOf} · {model.referenceCount} sources</span></div><Link href={model.referenceToggleHref} scroll={false}>{model.showOlder ? "Last 12 months" : `Show older records (${model.olderCount})`}</Link></header>
        {model.references.length ? <div className={styles.repairTable}><table><thead><tr><th>Source and equipment</th><th>Amount and date</th><th>Includes</th></tr></thead><tbody>{model.references.map(row => <tr key={row.id}><td><Link className={styles.rowLink} href={row.href}><strong>{row.kind}</strong><span>{row.equipment}</span><small>{row.store} · {row.match}</small></Link></td><td><Link className={styles.rowLink} href={row.href}><strong>{row.amount}</strong><span>{row.date}{row.older ? " · Older reference" : ""}</span><small>{row.status}</small></Link></td><td><span>{row.installation}</span><details><summary>Scope</summary><p>{row.scope}</p><Link href={row.href}>Open source →</Link></details></td></tr>)}</tbody></table></div> : <p>No matching replacement sources {model.showOlder ? "are saved" : "in the last 12 months"} for this scope.</p>}
        <nav className={styles.scope} aria-label="Replacement reference pages">{model.referencePages.map(page => <Link href={page.href} key={page.href}>{page.label}</Link>)}</nav>
      </section>
      <details className={styles.evidence}><summary>Cost lines supporting this scope’s {model.selectedCost}</summary><span id="decision-costs" /><p>Service dates determine the period. Work without a component stays in its own bucket. Invoice amounts and repair-item subtotals are not added to these cost lines.</p><ul>{model.costs.map((row) => <li key={row.id}>{row.date} · {row.amount} · {row.description} · <Link href={row.href}>{row.work} — recorded cost</Link></li>)}</ul><nav className={styles.scope} aria-label="Decision cost pages">{model.costPages.map((page) => <Link href={page.href} key={page.href}>{page.label}</Link>)}</nav>{model.costCount > model.costs.length ? <p>Showing {model.costs.length} of {model.costCount} cost lines. The total includes every page.</p> : null}{!model.costs.length ? <p>No amounts recorded. This is not a measured zero.</p> : null}</details>
      <details className={styles.evidence}><summary>Warranty terms and references ({model.warranty.length})</summary>{model.warranty.length ? model.warranty.map((row) => <article key={row.id}><h3>{row.label}</h3><p>{row.detail}</p>{row.href ? <Link href={row.href}>Review the warranty source →</Link> : null}</article>) : <p>No warranty terms are recorded for this scope. Obtain the terms before assuming coverage.</p>}</details>
      <details className={styles.evidence}><summary>Open work and current options ({model.currentWork.length})</summary>{model.currentWork.map((row) => <p key={row.href}><Link href={`${row.href}?view=service`}>{row.label} — review service and quotes</Link></p>)}{!model.currentWork.length ? <p>No open work recorded for this scope.</p> : null}{model.rows.filter((row) => row.quotes.length).map((row) => <article key={row.id}><h3>{row.number}</h3>{row.quotes.map((quote) => <p key={quote}>{quote}</p>)}<Link href={`${row.href}&view=service&path=bids`}>Review these options →</Link></article>)}</details>
    </>}
  </section>;
}
