"use client";
import { useState, type FormEvent } from "react";
import Link from "next/link";
import type { ImportEntity, ImportPreview } from "@/lib/ops/import-preview";
import styles from "./setup-workspaces.module.css";

export function ImportPreviewWorkspace({ organizationName }: { organizationName: string }) {
  const [entity, setEntity] = useState<ImportEntity>("stores"); const [preview, setPreview] = useState<ImportPreview>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setPreview(undefined); const response = await fetch("/api/ops/imports/preview", { method: "POST", body: new FormData(event.currentTarget) }); const body = await response.json() as ImportPreview & { error?: string }; setLoading(false); if (!response.ok) { setError(body.error ?? "The file could not be validated."); return; } setPreview(body); }
  function downloadErrors() { if (!preview) return; const rows = [["row","status","errors","warnings"], ...preview.rows.filter((row) => row.status !== "ready").map((row) => [String(row.rowNumber),row.status,row.errors.join(" | "),row.warnings.join(" | ")])]; const csv = rows.map((row) => row.map((value) => `"${value.replaceAll('"','""')}"`).join(",")).join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `${preview.entity}-import-errors.csv`; link.click(); URL.revokeObjectURL(link.href); }
  return <section className={styles.workspace}><header className={styles.heading}><div><p>Company onboarding</p><h1>Validate data imports</h1><span>Preview store, vendor, or equipment records before anything is written to {organizationName}.</span></div><Link href="/app/admin">Back to setup</Link></header>
    <div className={styles.statusWarning}><strong>Dry-run preview only</strong><span>This workspace validates, normalizes, and reports errors. It does not create or change records.</span></div>
    <form className={styles.controls} onSubmit={submit}><label>Import type<select name="entity" value={entity} onChange={(event) => { setEntity(event.target.value as ImportEntity); setPreview(undefined); }}><option value="stores">Stores</option><option value="vendors">Vendors</option><option value="equipment">Equipment quantities</option></select></label><label>CSV file<input className={styles.fileInput} name="file" type="file" accept=".csv,text/csv" required/></label><button className={styles.uploadButton} type="submit" disabled={loading}>{loading ? "Validating…" : "Validate file"}</button></form>
    <div className={styles.explainer}><strong>Start with the current template.</strong><span><a href={`/api/ops/imports/template?entity=${entity}`}>Download {entity} CSV template</a>. Lists inside a cell use semicolons so the file remains portable.</span></div>
    {error ? <div className={styles.statusWarning}><strong>Preview could not run</strong><span>{error}</span></div> : null}
    {preview ? <><div className={styles.summary}><div><small>Rows</small><strong>{preview.summary.total}</strong></div><div><small>Ready</small><strong>{preview.summary.ready}</strong></div><div><small>Warnings</small><strong className={styles.warningText}>{preview.summary.warning}</strong></div><div><small>Errors</small><strong className={styles.errorText}>{preview.summary.error}</strong></div></div><div className={styles.tableWrap}><table><caption>CSV validation results</caption><thead><tr><th>Row</th><th>Status</th><th>Identity</th><th>Validation result</th></tr></thead><tbody>{preview.rows.map((row) => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td><strong className={row.status === "error" ? styles.errorText : row.status === "warning" ? styles.warningText : undefined}>{row.status}</strong></td><td><strong>{row.values.store_number || row.values.vendor_code || "—"}</strong><small>{row.values.name || row.values.equipment_type || ""}</small></td><td>{row.errors.length ? <span className={styles.errorText}>{row.errors.join(" ")}</span> : row.warnings.length ? <span className={styles.warningText}>{row.warnings.join(" ")}</span> : "Ready for a future apply step"}</td></tr>)}</tbody></table></div>{preview.summary.error || preview.summary.warning ? <div className={styles.explainer}><button className={styles.uploadButton} type="button" onClick={downloadErrors}>Download error report</button><span>Correct the source file and run the preview again.</span></div> : null}</> : <div className={styles.empty}>Upload a template-based CSV to see row-by-row validation.</div>}
  </section>;
}
