"use client";
import {useEffect,useState,type FormEvent,type ReactNode} from "react";
import {useRouter} from "next/navigation";
import {StorePicker} from "@/components/ops/store-picker";
import {taskRoleLabels,type TaskPerson,type CameraWindow,type StoreTask} from "@/lib/ops/store-task-types";
import {cameraInput,formatCameraTime} from "@/lib/ops/store-task-time";
import styles from "./store-tasks.module.css";
function clockValue(value:FormDataEntryValue|null) {return typeof value==='string'?value:'';}
export function TaskForm({children,action,id,version,onPrepare}:{children:ReactNode;action:string;id?:string;version?:number;onPrepare?:(f:FormData)=>void}) {
 const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const f=new FormData(e.currentTarget);f.set('action',action);if(id)f.set('id',id);if(version)f.set('version',String(version));onPrepare?.(f);const r=await fetch('/api/ops/tasks',{method:'POST',body:f}),data=await r.json() as {id:string;error?:string};if(!r.ok)throw new Error(data.error??'Could not save. Try again.');if(action==='create')router.push(`/app/tasks/${data.id}`);else {if(action==='reply')form.reset();router.refresh();}}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className={styles.form}><fieldset disabled={busy}>{children}</fieldset>{error?<p role="alert" className={styles.error}>{error}</p>:null}{busy?<p role="status">Saving…</p>:null}</form>;
}
export function TaskFiles(){return <label>Photos and paperwork <span className={styles.muted}>Optional · Up to 5 files, 8 MB total</span><input type="file" name="files" multiple accept="application/pdf,image/jpeg,image/png,image/webp,text/plain"/></label>;}
export function TaskRecipients({storeId,initialAssignee='',initialAssignment='person',fallbackId=''}:{storeId:string;initialAssignee?:string;initialAssignment?:string;fallbackId?:string}) {
 const [selectedId,setSelectedId]=useState(initialAssignee),[fallbackValue,setFallbackValue]=useState(fallbackId),[people,setPeople]=useState<TaskPerson[]>([]),[search,setSearch]=useState(''),[assignment,setAssignment]=useState(initialAssignment),[selected,setSelected]=useState<TaskPerson|null>(null),[fallback,setFallback]=useState<TaskPerson|null>(null),[error,setError]=useState('');
 useEffect(()=>{if(!storeId)return;const controller=new AbortController();const timer=setTimeout(()=>{fetch(`/api/ops/tasks?${new URLSearchParams({store:storeId,q:search})}`,{signal:controller.signal}).then(async r=>{const d=await r.json() as {people:TaskPerson[];error?:string};if(!r.ok)throw new Error(d.error);setPeople(d.people);setSelected(p=>p??d.people.find(p=>p.id===initialAssignee)??null);setFallback(p=>p??d.people.find(p=>p.id===fallbackId)??null);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});},200);return()=>{clearTimeout(timer);controller.abort();};},[storeId,search,initialAssignee,fallbackId]);
 const choices=[...people,...[selected,fallback].filter((p):p is TaskPerson=>!!p&&!people.some(x=>x.id===p.id))];
 return <><label>Who should handle it?<select name="assignment" value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="person">A specific person</option><option value="responsible">Anyone responsible for this store</option><option value="local">Someone at the store</option></select></label>
 <label>Find a person<input type="search" placeholder="Search by name" value={search} onChange={e=>setSearch(e.target.value)} disabled={!storeId}/></label>
 {assignment==='person'?<label>Assign to<select name="assigneeId" required value={selectedId} onChange={e=>{setSelectedId(e.target.value);setSelected(choices.find(p=>p.id===e.target.value)??null);}}><option value="">Choose a person</option>{choices.map(p=><option value={p.id} key={p.id}>{p.name} · {taskRoleLabels[p.role]??p.role}</option>)}</select></label>:<p className={styles.muted}>{assignment==='local'?'A person assigned to this store can take the task.':'Anyone with responsibility for this store can take the task.'}</p>}
 <label>If overdue, alert<select name="fallbackId" required value={fallbackValue} onChange={e=>{setFallbackValue(e.target.value);setFallback(choices.find(p=>p.id===e.target.value)??null);}}><option value="">Choose a person</option>{choices.map(p=><option value={p.id} key={p.id}>{p.name} · {taskRoleLabels[p.role]??p.role}</option>)}</select></label>{error?<p role="alert">{error}</p>:null}</>;
}
export function NewTaskForm({stores,storeId='',sources={},windows=[],fallbackId=''}:{stores:Array<{id:string;storeNumber:string;name:string;formattedAddress?:string}>;storeId?:string;sources?:Record<string,string>;windows?:CameraWindow[];fallbackId?:string}) {
 const [store,setStore]=useState(storeId),[kind,setKind]=useState(windows.length||sources.visitId?'camera':sources.assetId?'equipment':'general'),[count,setCount]=useState(Math.max(1,windows.length));
 const [timeZone,setTimeZone]=useState('');
 useEffect(()=>{if(!store)return;const c=new AbortController();fetch(`/api/ops/tasks?${new URLSearchParams({store})}`,{signal:c.signal}).then(r=>r.json() as Promise<{timeZone?:string}>).then(d=>setTimeZone(d.timeZone??'')).catch(()=>{});return()=>c.abort();},[store]);
 const local=(s?:string)=>s?cameraInput(s,timeZone||undefined):'';
 return <TaskForm action="create" onPrepare={f=>{if(kind==='camera')f.set('windows',JSON.stringify(Array.from({length:count},(_,i)=>({start:clockValue(f.get(`start${i}`)),end:clockValue(f.get(`end${i}`)),area:f.get(`area${i}`)??''}))));}}>
 {Object.entries(sources).map(([k,v])=><input key={k} type="hidden" name={k} value={v}/>)}
 <section><h2>What needs doing?</h2>{Object.keys(sources).length&&storeId?<><input type="hidden" name="storeId" value={store}/></>:<StorePicker initial={stores.map(s=>({value:s.id,label:`Store ${s.storeNumber} · ${s.name}`,description:s.formattedAddress}))} defaultStoreId={store} searchable onSelect={setStore}/>}
 <label>Task type<select name="kind" value={kind} onChange={e=>setKind(e.target.value)}><option value="general">General task</option><option value="camera">Camera review</option><option value="equipment">Equipment check</option></select></label>
 <label>Title<input name="title" maxLength={160} required placeholder={kind==='camera'?'Check vendor arrival and departure':kind==='equipment'?'Check the beer cave temperature':'What needs doing?'}/></label>
 <label>{kind==='camera'?'What should they look for?':kind==='equipment'?'Equipment / location and what to check':'Instructions'}<textarea name="instructions" required maxLength={4000} rows={4}/></label>
 {kind==='camera'?<><h3>Times to review</h3><p className={styles.muted}>Time shown on camera. Enter each period exactly as displayed.</p>{sources.visitId?<p className={styles.muted}>Suggested from the visit in store time. Adjust to match the camera clock.</p>:null}{Array.from({length:count},(_,i)=><div className={styles.window} key={i}><h4>Window {i+1}</h4><div className={styles.pair}><label>From<input type="datetime-local" name={`start${i}`} required defaultValue={local(windows[i]?.start)}/></label><label>To<input type="datetime-local" name={`end${i}`} required defaultValue={local(windows[i]?.end)}/></label></div><label>Camera or area <span className={styles.muted}>Optional</span><input name={`area${i}`} maxLength={160} defaultValue={windows[i]?.area}/></label></div>)}<div className={styles.actions}><button type="button" disabled={count>=12} onClick={()=>setCount(count+1)}>Add time window</button>{count>1?<button type="button" onClick={()=>setCount(count-1)}>Remove last window</button>:null}</div></>:null}</section>
 <section key={store}><h2>Who handles it?</h2><TaskRecipients storeId={store} fallbackId={fallbackId}/></section><section><h2>Timing and files</h2><div className={styles.pair}><label>Due · store time {timeZone}<input type="datetime-local" name="dueAt" required/></label><label>Priority<select name="priority" defaultValue="routine"><option value="routine">Routine</option><option value="urgent">Urgent</option></select></label></div><label className={styles.check}><input type="checkbox" name="notifyRequester" defaultChecked/>Let me know when this is done</label><TaskFiles/></section><button type="submit" className={styles.primary}>Send task</button></TaskForm>;
}
export function TaskCompletion({task,timeZone}:{task:StoreTask;timeZone?:string}) {
 const windows=JSON.parse(task.windowsJson) as CameraWindow[];
 return <TaskForm action="complete" id={task.id} version={task.version} onPrepare={f=>f.set('findings',JSON.stringify(windows.map((_,i)=>({start:clockValue(f.get(`observedStart${i}`)),end:clockValue(f.get(`observedEnd${i}`)),result:f.get(`finding${i}`),notes:f.get(`notes${i}`)}))))}>
 {windows.map((w,i)=><div className={styles.window} key={i}><h3>Window {i+1}{w.area?` · ${w.area}`:''}</h3><p>{formatCameraTime(w.start,timeZone)} – {formatCameraTime(w.end,timeZone)}</p><label>What did you find?<select name={`finding${i}`} required defaultValue=""><option value="" disabled>Choose a finding</option><option value="matches">Matches the request</option><option value="different">Doesn’t match</option><option value="partial">Partly confirmed</option><option value="unavailable">No footage available</option></select></label><div className={styles.pair}><label>Observed start <span className={styles.muted}>Time shown on camera</span><input type="datetime-local" name={`observedStart${i}`}/></label><label>Observed end <span className={styles.muted}>Time shown on camera</span><input type="datetime-local" name={`observedEnd${i}`}/></label></div><label>Window findings<textarea name={`notes${i}`} required maxLength={2000} rows={2}/></label></div>)}
 <label>{task.kind==='equipment'?'Findings / readings':'Summary of findings'}<textarea name="body" required rows={3} maxLength={6000}/></label><TaskFiles/><fieldset className={styles.results}><legend>Result</legend><label><input type="radio" name="result" value="done" required/>Done — no issues</label><label><input type="radio" name="result" value="attention"/>Needs attention</label><label><input type="radio" name="result" value="unable"/>Couldn’t complete</label></fieldset><button className={styles.primary} type="submit">Send findings</button></TaskForm>;
}
export function TaskSeen({id,at}:{id:string;at:string}) {useEffect(()=>{const f=new FormData();f.set('action','seen');f.set('id',id);f.set('seenAt',at);void fetch('/api/ops/tasks',{method:'POST',body:f});},[id,at]);return null;}
