import Link from "next/link";
import { domainLabel } from "@/lib/product/domain-label";
import type { WarrantyQueuePage, WarrantyQueueView } from "@/lib/ops/warranty-queue-query";
import styles from "./invoice-queue-workspace.module.css";
const titles={all:"All warranty cases",open:"Open cases",diagnosis:"Diagnosis requested",held:"Invoice holds",exposure:"Amounts flagged"};
export function WarrantyQueueWorkspace({result,view,page,search,currency,scopeLabel,canCreate}:{result:WarrantyQueuePage;view:WarrantyQueueView;page:number;search:string;currency:string;scopeLabel:string;canCreate:boolean}){
 const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(n/100);
 const href=(v:WarrantyQueueView,p=1)=>`/app/warranties?${new URLSearchParams({view:v,currency,...(search?{q:search}:{}),...(p>1?{page:String(p)}:{})})}#warranty-register`;
 return <div className={styles.page}><header className={styles.header}><div><p>Warranty review</p><h1>Warranty center</h1><p>{scopeLabel}</p></div>{canCreate?<div className={styles.actions}><Link href="/app/warranties/rules/new">Add warranty rule</Link></div>:null}</header>
 <section className={styles.metrics} aria-label="Warranty source views">{(["open","diagnosis","held","exposure"] as const).map(v=><Link key={v} href={href(v)} aria-current={view===v?"page":undefined}><span>{titles[v]}</span><strong>{v==="exposure"?money(result.exposureMinor):result.counts[v]}</strong><span>{v==="exposure"?`${result.counts.exposure} source record${result.counts.exposure===1?"":"s"} →`:"View cases →"}</span></Link>)}</section>
 <form action="/app/warranties" className={styles.search}><input type="hidden" name="view" value={view}/><label>Search warranty cases<input name="q" defaultValue={search} placeholder="Work order, store or problem" maxLength={160}/></label><label>Currency<input name="currency" defaultValue={currency} maxLength={3} pattern="[A-Za-z]{3}" required/></label><button type="submit">Search</button><Link href={href("all")}>All cases ({result.counts.all})</Link></form>
 <p className={styles.note}>Flagged amounts need review. They are not confirmed credits or deductions.</p>
 <section className={styles.surface} id="warranty-register"><header><h2>{titles[view]}</h2><span>{result.rows.length?(page-1)*25+1:0}–{result.rows.length?(page-1)*25+result.rows.length:0} of {result.totalCount}</span></header><div className={styles.tableWrap}>{result.rows.length?<table><caption>{titles[view]}</caption><thead><tr><th>Work / store</th><th>Warranty review</th><th>{view==="exposure"?"Flagged amount":"Invoice hold"}</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.id}><td data-label="Work / store"><Link href={`/app/work-orders/${r.workId}`}>{r.workNumber}</Link><span>Store {r.storeNumber} · {r.storeName}</span></td><td data-label="Warranty review"><Link href={`/app/warranties/${r.caseId}`}>Open case</Link><span>{r.diagnosis?"Diagnosis requested":domainLabel(r.coverage)}{r.status==="closed"?" · Closed":""}</span>{r.detail?<p>{r.detail}</p>:null}</td><td data-label={view==="exposure"?"Flagged amount":"Invoice hold"}>{view==="exposure"?money(r.amountMinor??0):r.held?"On hold":"No hold"}</td></tr>)}</tbody></table>:<p className={styles.empty}>No matching {view==="exposure"?"flagged amounts":"warranty cases"}.</p>}</div></section>
 <nav className={styles.pagination} aria-label="Warranty pages">{page>1?<Link href={href(view,page-1)}>← Back</Link>:null}<span>Page {page} of {Math.max(1,Math.ceil(result.totalCount/25))}</span>{result.nextOffset!==undefined?<Link href={href(view,page+1)}>Next →</Link>:null}</nav></div>;
}
