import {formatOperationsDate} from "@/lib/ops/local-time";
import Link from "next/link";
import { notFound } from "next/navigation";
import { loadOperatorSession } from "@/app/app/_data/operator-loader";
import { getServerOpsRepository } from "@/lib/server/ops-repository-provider";
import { coverageViews, type CoverageView } from "@/lib/ops/warranty-directory";
import { roleCanAccessListRoute } from "@/components/ops/role-policy";
import styles from "./warranty-center.module.css";
export type WarrantySearch = { tab?:string; view?:string; q?:string; offset?:string; vendor?:string };
export async function WarrantyCenter({searchParams,fixedStore}:{searchParams:Promise<WarrantySearch>;fixedStore?:string}) {
 const q=await searchParams,session=await loadOperatorSession(),repo=await getServerOpsRepository();
 if(!fixedStore&&!roleCanAccessListRoute(session.role,"warranties"))notFound();
 const scope=fixedStore?{...session,storeIds:[fixedStore]}:session;
 const tab=q.tab==="coverage"||fixedStore&&!q.tab?"coverage":q.tab==="history"?"history":"attention",view:CoverageView=coverageViews.includes(q.view as CoverageView)?q.view as CoverageView:"active",search=q.q?.trim().slice(0,160)??"",offset=Math.min(100000,Math.max(0,Math.floor(Number(q.offset)||0)));
 const caseView=tab==="history"?"history":q.view==="held"?"held":q.view==="diagnosis"?"diagnosis":q.view==="all"?"all":"open";
 const [directory,cases]=await Promise.all([repo.listWarrantyDirectory(scope,{today:new Date().toISOString().slice(0,10),view,search,vendorId:q.vendor,limit:25,offset:tab==="coverage"?offset:0}),repo.listWarrantyQueue(scope,{view:caseView,currency:"USD",search,vendorId:q.vendor,limit:25,offset:tab==="coverage"?0:offset})]);
 const base=fixedStore?`/app/stores/${encodeURIComponent(fixedStore)}/warranties`:"/app/warranties";
 const href=(t:string,v=view,o=0)=>base+"?"+new URLSearchParams({tab:t,...(t==="coverage"?{view:v}:t===tab&&o?{view:caseView}:{}),...(search?{q:search}:{}),...(q.vendor?{vendor:q.vendor}:{}),...(o?{offset:String(o)}:{})});
 const editable=["executive","facilities","regional"].includes(session.role),total=tab==="coverage"?directory.totalCount:cases.totalCount,next=tab==="coverage"?directory.nextOffset:cases.nextOffset;
 return <div className={styles.page}>
 {!fixedStore?<header className={styles.header}><div><p className={styles.eyebrow}>{session.scopeLabel}</p><h1>Warranties</h1><p>Coverage, repairs, and the next step.{q.vendor?" · Selected vendor":""}</p></div>{editable?<Link className={styles.button} href="/app/warranties/new">Add warranty</Link>:null}</header>:null}
 <section className={styles.metrics} aria-label="Warranty summary"><Link href={href("coverage","active")}><span>Active coverage</span><strong>{directory.counts.active}</strong><span>View warranties →</span></Link><Link href={href("coverage","expiring")}><span>Ending in 90 days</span><strong>{directory.counts.expiring}</strong><span>Review dates →</span></Link><Link href={href("attention")}><span>Open cases</span><strong>{cases.counts.open}</strong><span>Review next steps →</span></Link></section>
 <nav className={styles.tabs} aria-label="Warranty views">{([['attention','Needs attention'],['coverage','Coverage'],['history','Case history']] as const).map(([t,label])=><Link key={t} href={href(t)} aria-current={tab===t?"page":undefined}>{label}</Link>)}</nav>
 <form className={styles.filters} action={base}><input type="hidden" name="tab" value={tab}/>{tab!=="coverage"?<input type="hidden" name="view" value={caseView}/>:null}{q.vendor?<input type="hidden" name="vendor" value={q.vendor}/>:null}<label>Search<input name="q" defaultValue={search} placeholder="Equipment, store number, name or address" maxLength={160}/></label>{tab==="coverage"?<label>Show<select name="view" defaultValue={view}><option value="active">Active coverage</option><option value="expiring">Ending in 90 days</option><option value="review">Amended terms to review</option><option value="expired">Expired coverage</option><option value="all">All coverage</option></select></label>:null}<button>Search</button>{search?<Link href={base+`?tab=${tab}`}>Clear</Link>:null}</form>
 <section className={styles.surface}><header className={styles.sectionHead}><h2>{tab==="coverage"?"Warranty coverage":tab==="history"?"Resolved cases":caseView==="held"?"Cases with an invoice hold":caseView==="diagnosis"?"Diagnosis needed":caseView==="all"?"All warranty cases":"Open warranty cases"}</h2><span>{total} {tab==="coverage"?`coverage record${total===1?"":"s"}`:`case${total===1?"":"s"}`}</span></header><div className={styles.tableWrap}>
 {tab==="coverage"?<table className={styles.table}><thead><tr><th>Equipment / store</th><th>Warranty / provider</th><th>Coverage dates</th><th>Status</th></tr></thead><tbody>{directory.items.map(r=><tr key={r.id}><td><Link href={`/app/equipment/${r.assetId}`}>{r.assetName}</Link><small>Store {r.storeNumber} · {r.storeName}</small>{r.component?<small>{r.component}</small>:null}</td><td><Link href={`/app/warranties/coverage/${r.id}`}>{r.title}</Link><small>{r.provider}</small></td><td>{formatOperationsDate(r.start)} – {formatOperationsDate(r.end)}</td><td><span className={styles.badge} data-state={r.status}>{r.status}</span></td></tr>)}</tbody></table>:<table className={styles.table}><thead><tr><th>Equipment / store</th><th>Stage</th><th>Owner / next action</th><th>{tab==="history"?"Closed":"Follow-up"}</th></tr></thead><tbody>{cases.rows.map(r=><tr key={r.id}><td><Link href={`/app/warranties/${r.caseId}`}>{r.assetName??r.workNumber}</Link><small>Store {r.storeNumber} · {r.storeName}</small><small>{r.workNumber}</small></td><td><span className={styles.badge}>{r.status==="closed"?"Closed":r.status==="completed"?"Verify repair":r.status==="routed"?"Repair arranged":r.diagnosis?"Check coverage":r.coverage==="not_covered"?"Not covered":"Coverage confirmed"}</span></td><td>{r.owner??"Facilities"}<small>{tab==="history"?"Review outcome and history":r.nextAction??"Review warranty case"}</small></td><td>{tab==="history"?(r.closedOn?formatOperationsDate(r.closedOn):"Not recorded"):(r.followUpOn?formatOperationsDate(r.followUpOn):"Not set")}{tab!=="history"&&r.followUpOn&&r.followUpOn<new Date().toISOString().slice(0,10)?<small style={{color:"#ac392d",fontWeight:650}}>Overdue</small>:null}</td></tr>)}</tbody></table>}
 {!total?<div className={styles.empty}><strong>{tab==="coverage"?"No matching warranties":tab==="history"?"No resolved cases yet":"No open warranty cases"}</strong><p>{tab==="coverage"?"Add coverage from an equipment record or use Add warranty.":"Warranty reviews linked to work orders appear here."}</p>{editable&&tab==="coverage"?<Link href={`/app/warranties/new${fixedStore?`?store=${encodeURIComponent(fixedStore)}`:""}`}>Add warranty</Link>:null}</div>:null}</div></section>
 <nav className={styles.pagination} aria-label="Warranty pages">{offset>0?<Link href={href(tab,view,Math.max(0,offset-25))}>← Previous</Link>:<span/>}<span>{total?`${offset+1}–${Math.min(offset+25,total)} of ${total}`:"0 records"}</span>{next!==undefined?<Link href={href(tab,view,next)}>Next →</Link>:<span/>}</nav>
 {tab==="coverage"?<p className={styles.muted}>Active means within the recorded dates. Confirm the terms before arranging a covered repair.{directory.counts.review>0?<> <Link href={href("coverage","review")}>{directory.counts.review} amended terms need review.</Link></>:null}</p>:null}
 {editable?<Link href={`/app/warranties/rules${fixedStore?`?store=${encodeURIComponent(fixedStore)}`:q.vendor?`?vendor=${encodeURIComponent(q.vendor)}`:""}`}>{fixedStore?"Vendor defaults & store exceptions":"Manage vendor warranty rules"} →</Link>:null}
 </div>;
}
