import { masterDocuments } from "@/lib/ops/compliance-documents";
import Link from "next/link";
import { notFound } from "next/navigation";
import { loadOperatorSession } from "../../_data/operator-loader";
import { getServerOpsRepository } from "@/lib/server/ops-repository-provider";
import styles from "@/components/workspace/compliance.module.css";
export default async function InspectionPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{notice?:string;error?:string}>}) {
 const session=await loadOperatorSession(),r=await getServerOpsRepository(),{id}=await params,q=await searchParams;
 const i=await r.getInspection(session.organizationId,id);if(!i)notFound();
 const store=await r.getStoreDetail(session,i.storeId);if(!store)notFound();
 const s=await r.getComplianceSchedule(session.organizationId,i.scheduleId);if(!s)notFound();
 const [files,history,delivery,owner,vendor,work,cycles]=await Promise.all([i.workOrderId?r.listFilesForEntity(i.organizationId,"work_order",i.workOrderId):[],r.inspectionHistory(i.organizationId,i.id),r.inspectionDelivery(i.organizationId,i.id),s.membershipId?r.getMembership(i.organizationId,s.membershipId):null,s.vendorId?r.getVendor(i.organizationId,s.vendorId):null,i.workOrderId?r.getWorkOrder(i.organizationId,i.workOrderId):null,r.queryInspections(session,{today:new Date().toISOString().slice(0,10),scheduleId:s.id,limit:25})]);
 const templates=masterDocuments(i);
 const user=owner?await r.getUserInOrganization(i.organizationId,owner.userId):null;
 const edit=["facilities","regional","store_manager"].includes(session.role),review=["facilities","regional"].includes(session.role);
 const status=i.status==="passed"?"Reviewed & closed":i.status==="performed"?"Performed · awaiting review":i.status==="action_needed"?"Corrective action needed":"Pending inspection";
 const hidden=<><input type="hidden" name="inspectionId" value={i.id}/><input type="hidden" name="version" value={i.version}/></>;
 return <div className={styles.page}><header><Link href="/app/compliance">← Compliance</Link><h1>{s.name}</h1><p>Store {store.storeNumber} · {store.name}</p></header>
 {q.notice?<p role="status" className={styles.notice}>{q.notice}</p>:null}{q.error?<p role="alert" className={styles.notice}>{q.error}</p>:null}
 <section className={styles.panel}><div className={styles.header}><h2>{status}</h2><span className={styles.tag}>Due {i.dueDate}</span></div><dl className={styles.facts}><div><dt>Assigned to</dt><dd>{vendor?.name??user?.displayName??"Internal team"}</dd></div><div><dt>Evidence required</dt><dd>{s.evidenceLabel}{!s.evidenceRequired?" (optional file)":""}</dd></div><div><dt>Escalation</dt><dd>{s.escalationTo}<p>{new Date(Date.parse(i.dueDate)-s.escalationDays*86400000).toISOString().slice(0,10)}</p></dd></div><div><dt>Schedule</dt><dd>{s.status==="paused"?"Paused · ":""}{s.intervalUnit==="once"?"One time":`Every ${s.intervalCount} ${s.intervalUnit}`}</dd></div><div><dt>Performed</dt><dd>{i.completedAt??"Not recorded"}</dd></div><div><dt>Document expires</dt><dd>{i.documentExpiresOn??"Not recorded"}</dd></div></dl>
 {s.requirementSource?<p><strong>Requirement:</strong> {s.requirementSource}</p>:null}{s.instructions?<p>{s.instructions}</p>:null}{s.assetId?<p><Link href={`/app/equipment/${s.assetId}`}>Equipment history</Link></p>:null}
 <div className={styles.filters}>{work?<Link href={`/app/work-orders/${work.id}`}>{work.number} · {work.status.replaceAll("_"," ")}</Link>:<p>Work is prepared {s.leadDays} days before due.</p>}{i.correctiveWorkOrderId?<Link href={`/app/work-orders/${i.correctiveWorkOrderId}`}>Open corrective work</Link>:null}</div>
 {i.resultNote?<p><strong>Latest result:</strong> {i.resultNote}</p>:null}
 </section>
 <section className={styles.panel}><h2>Instructions & blank forms</h2><p>Download, print and upload the completed copy below.</p>{templates.length?<ul>{templates.map(f=><li key={f.id}><a href={`/api/ops/compliance/${i.id}/files/${f.id}`}>{f.originalName}</a></li>)}</ul>:<p>No blank forms attached for this inspection.</p>}</section>
 <section className={styles.panel}><h2>Completed paperwork & photos</h2>{files.length?<ul>{files.map(f=><li key={f.id}><a href={`/api/ops/compliance/${i.id}/files/${f.id}`}>{f.originalName}</a></li>)}</ul>:<p>No documents or photos attached.</p>}</section>
 {edit?<section className={styles.panel}><h2>{i.completedAt?"Update result or add paperwork":"Record inspection"}</h2><form action="/api/ops/compliance" method="post" encType="multipart/form-data" className={styles.form}>{hidden}<input type="hidden" name="action" value="result"/>
 <div className={styles.pair}><label>Result<select name="status" defaultValue={review?i.status==="pending"?"performed":i.status:"performed"}><option value="performed">Performed — paperwork / review pending</option><option value="action_needed">Failed / corrective action needed</option>{review?<option value="passed">Passed — reviewed and close</option>:null}</select></label><label>Performed date<input type="date" name="performedDate" required defaultValue={i.completedAt??new Date().toISOString().slice(0,10)} max={new Date().toISOString().slice(0,10)}/></label></div>
 <label>Result / review notes<textarea name="note" required rows={3} maxLength={4000} defaultValue=""/></label><label>Report, certificate or photos<input type="file" name="attachments" multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.txt"/><small>PDF, JPG, PNG, WebP or text · Up to 5 files · 8 MB total. Earlier uploads stay on record.</small></label><label>Document expiration (optional)<input type="date" name="documentExpiresOn" defaultValue={i.documentExpiresOn}/></label><button type="submit">Save inspection result</button><small>Performed does not mean reviewed. Required evidence and corrective work must be resolved before closure.</small></form></section>:null}
 {review&&i.status==="action_needed"&&!i.correctiveWorkOrderId?<section className={styles.panel}><h2>Corrective work</h2><form action="/api/ops/compliance" method="post" className={styles.form}>{hidden}<input type="hidden" name="action" value="correction"/><label>What needs fixing?<textarea name="problem" required maxLength={4000} defaultValue={i.resultNote}/></label><button type="submit">Create corrective work order</button></form></section>:null}
 <section className={styles.panel}><h2>Inspection history</h2><ol className={styles.history}>{history.map(h=>{const data=JSON.parse(h.payloadJson);return <li key={h.id}><strong>{h.eventType.replaceAll("inspection.","").replaceAll("_"," ")}</strong><p>{h.actorName} · {h.occurredAt.slice(0,16).replace("T"," ")} UTC</p>{data.note?<p>{data.note}</p>:null}{data.status?<small>Result: {data.status.replaceAll("_"," ")}</small>:null}</li>;})}</ol>{!history.length?<p>No results recorded yet.</p>:null}<details><summary>Other inspection dates</summary><ul>{cycles.items.map(row=><li key={row.id}><Link href={`/app/compliance/${row.id}`}>{row.dueDate} · {row.status.replaceAll("_"," ")}</Link></li>)}</ul></details></section>
 <details className={styles.panel}><summary>Master forms for new inspection dates</summary><p>Replacing these files affects newly generated inspection dates. Existing inspections keep their saved copies.</p><ul>{masterDocuments(s).map(f=><li key={f.id}>{f.originalName}</li>)}</ul>{review?<form action="/api/ops/compliance" method="post" encType="multipart/form-data" className={styles.form}>{hidden}<input type="hidden" name="action" value="templates"/><label>Replace master forms<input type="file" name="templates" multiple required accept=".pdf,.png,.jpg,.jpeg,.webp,.txt"/></label><small>PDF, JPG, PNG, WebP or text · Up to 5 files · 8 MB total.</small><button type="submit">Save master forms</button></form>:null}</details>
 <details className={styles.panel}><summary>Delivery and schedule settings</summary><ul>{delivery.map(d=><li key={d.id}>{d.topic.endsWith("authorization")?"Vendor work order":"Inspection reminder"}: {d.status}</li>)}</ul>{!delivery.length?<p>No messages queued yet.</p> :null}{review?<form action="/api/ops/compliance" method="post">{hidden}<input type="hidden" name="action" value="pause"/><input type="hidden" name="scheduleStatus" value={s.status==="active"?"paused":"active"}/><button type="submit">{s.status==="active"?"Pause schedule":"Resume schedule"}</button></form>:null}</details>
 </div>;
}
