import type { OrganizationScope } from "./repository";
import type { OpsSqlDriver, SqlRow } from "./sql-driver";
import { scopeWhere } from "./sql-scope";
import { dashboardPageBounds } from "./dashboard-query";
import { WARRANTY_REVIEW_TITLE } from "./warranty-review";
import { quoteRoundCopy } from "./attention-projection";
import { ACCOUNTABILITY_EXCEPTION_KINDS, attentionCursor, readAttentionCursor, validateAttentionQuery, type AttentionAccess, type AttentionPage, type AttentionQuery, type AttentionQueueRow } from "./attention-query";

/** Six source populations are grouped and scoped before counting or selecting a page. */
export async function queryAttention(driver: OpsSqlDriver, scope: OrganizationScope, access: AttentionAccess, query: AttentionQuery): Promise<AttentionPage> {
  validateAttentionQuery(query);
  const params: unknown[] = [];
  const bind = (value: unknown) => { params.push(value); return "?"; };
  const instant = (column: string) => driver.dialect === "postgres" ? `to_char(${column} AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')` : `strftime('%Y-%m-%dT%H:%M:%fZ',${column})`;
  const overdue = (column: string) => `${instant(column)} <= ${bind(new Date(query.asOf).toISOString())}`;
  const finance = access.role === "finance_reviewer";
  const companywide = scope.storeIds === undefined && scope.regionIds === undefined;
  const financialTasks = "('resolve_invoice_exception','respond_service_discrepancy')";
  const financialExceptions = "('unmatched_invoice','amount_above_authorization')";
  const allFinancial = access.role === "executive" || access.role === "facilities_admin";
  const taskRole = finance ? `t.task_type IN ${financialTasks}` : ["vendor_user", "store_employee", "internal_technician"].includes(access.role) ? "1=0" : allFinancial ? "1=1" : `t.task_type NOT IN ${financialTasks}`;
  const exceptionRole = finance ? `e.kind IN ${financialExceptions}` : allFinancial ? "1=1" : `e.kind NOT IN ${financialExceptions}`;
  const columns = ["id", "source_kind", "work_order_id", "service_request_id", "vendor_id", "store_id", "title", "reason", "owner", "due_at", "priority", "lane", "group_name", "completed_at", "warranty_id", "source_count", "requested_count", "submitted_count", "missed_count"];
  const select = (values: Record<string, string>) => columns.map(column => `${values[column] ?? (["source_count", "requested_count", "submitted_count", "missed_count"].includes(column) ? "0" : "NULL")} AS ${column}`).join(",");
  const scoped = `WITH scoped_stores AS (SELECT s.id,s.organization_id,s.store_number,s.name FROM ops_stores s WHERE ${scopeWhere(scope, "s", params)}),
    scoped_work AS (SELECT w.id,w.organization_id,w.store_id,w.number,w.accountable_party FROM ops_work_orders w JOIN scoped_stores s ON s.organization_id=w.organization_id AND s.id=w.store_id),
    scoped_requests AS (SELECT r.id,r.organization_id,r.store_id,r.reference FROM ops_requests r JOIN scoped_stores s ON s.organization_id=r.organization_id AND s.id=r.store_id),
    warranty_ranked AS (SELECT c.id,c.organization_id,c.work_order_id, CASE WHEN c.closed_at IS NULL AND (c.diagnosis_required=true OR c.coverage_decision='pending_diagnosis') THEN 0 WHEN c.closed_at IS NULL THEN 1 ELSE 2 END AS tier FROM ops_warranty_cases c JOIN scoped_work w ON w.organization_id=c.organization_id AND w.id=c.work_order_id),
    warranty_targets AS (SELECT c.organization_id,c.work_order_id,MIN(c.id) AS id FROM warranty_ranked c WHERE c.tier=(SELECT MIN(x.tier) FROM warranty_ranked x WHERE x.organization_id=c.organization_id AND x.work_order_id=c.work_order_id) GROUP BY c.organization_id,c.work_order_id HAVING COUNT(*)=1),
    visible_tasks AS (SELECT t.*,COALESCE(w.store_id,r.store_id) AS scoped_store_id, CASE WHEN t.task_type='review_warranty' THEN c.id ELSE NULL END AS warranty_id FROM ops_workflow_tasks t LEFT JOIN scoped_work w ON w.organization_id=t.organization_id AND w.id=t.work_order_id LEFT JOIN scoped_requests r ON r.organization_id=t.organization_id AND r.id=t.service_request_id LEFT JOIN warranty_targets c ON c.organization_id=t.organization_id AND c.work_order_id=t.work_order_id WHERE t.organization_id=${bind(scope.organizationId)} AND t.status IN ('open','in_progress') AND (w.id IS NOT NULL OR (t.work_order_id IS NULL AND r.id IS NOT NULL)) AND ${taskRole}),
    quote_requests AS (SELECT q.* FROM ops_work_order_estimate_requests q JOIN scoped_work w ON w.organization_id=q.organization_id AND w.id=q.work_order_id WHERE q.status IN ('requested','opened','submitted')),
    quote_rounds AS (SELECT q.organization_id,q.work_order_id,COUNT(*) AS requested_count,SUM(CASE WHEN q.status='submitted' THEN 1 ELSE 0 END) AS submitted_count,SUM(CASE WHEN ${overdue("q.due_at")} THEN 1 ELSE 0 END) AS missed_count,MIN(q.due_at) AS due_at,COUNT(*)+(SELECT COUNT(*) FROM ops_vendor_estimate_proposals p JOIN quote_requests r ON r.organization_id=p.organization_id AND r.id=p.request_id WHERE r.organization_id=q.organization_id AND r.work_order_id=q.work_order_id) AS source_count FROM quote_requests q GROUP BY q.organization_id,q.work_order_id)`;
  const task = `SELECT ${select({ id: "t.id", source_kind: "'workflow_task'", work_order_id: "t.work_order_id", service_request_id: "t.service_request_id", store_id: "t.scoped_store_id", title: "t.title", reason: "t.reason", owner: "t.assignee_name", due_at: "t.due_at", priority: "t.priority", lane: `CASE WHEN t.assignee_type='vendor' THEN 'waiting' WHEN t.assignee_type='user' THEN CASE WHEN t.assignee_id=${bind(access.membershipId ?? "")} THEN 'mine' ELSE 'team' END WHEN t.assignee_type='role' THEN CASE WHEN t.assignee_role=${bind(access.role)} THEN 'mine' ELSE 'waiting' END ELSE 'team' END`, group_name: `CASE WHEN t.task_type IN ${financialTasks} THEN 'financial' WHEN t.task_type IN ('record_service_outcome','verify_repair','close_verified_work') THEN 'completion' ELSE 'work_vendor' END`, completed_at: "COALESCE(t.completed_at,t.cancelled_at)", warranty_id: "t.warranty_id", source_count: "1+CASE WHEN t.source_follow_up_id IS NULL THEN 0 ELSE 1 END+CASE WHEN t.source_approval_request_id IS NULL THEN 0 ELSE 1 END" })} FROM visible_tasks t WHERE ${access.canOpenWarranty ? "1=1" : "t.warranty_id IS NULL"} AND ${access.canOpenRequest ? "1=1" : "t.work_order_id IS NOT NULL OR t.warranty_id IS NOT NULL"}`;
  const follow = `SELECT ${select({ id: "f.id", source_kind: "'follow_up'", work_order_id: "f.work_order_id", store_id: "w.store_id", title: "f.next_action", reason: "CASE WHEN f.source_visit_id IS NULL THEN 'A manager-created follow-up remains open.' ELSE 'Required by the latest recorded service outcome.' END", owner: "f.accountable_party", due_at: "f.due_at", priority: `CASE WHEN ${overdue("f.due_at")} THEN 'critical' ELSE 'normal' END`, lane: "'team'", group_name: "'completion'", source_count: "1" })} FROM ops_follow_ups f JOIN scoped_work w ON w.organization_id=f.organization_id AND w.id=f.work_order_id WHERE f.status='open' AND NOT EXISTS (SELECT 1 FROM visible_tasks t WHERE t.organization_id=f.organization_id AND t.source_follow_up_id=f.id)`;
  const exception = `SELECT ${select({ id: "e.id", source_kind: "'exception'", work_order_id: "e.work_order_id", vendor_id: "e.vendor_id", store_id: "e.store_id", title: "e.summary", reason: "e.kind", owner: `CASE WHEN e.kind IN ${financialExceptions} THEN 'Finance review' ELSE 'Facilities coordinator' END`, due_at: "e.detected_at", priority: "CASE WHEN e.severity='urgent' THEN 'critical' ELSE 'high' END", lane: finance ? "'mine'" : "'team'", group_name: `CASE WHEN e.kind IN ${financialExceptions} THEN 'financial' ELSE 'service_record' END`, source_count: "1" })} FROM ops_exceptions e WHERE e.organization_id=${bind(scope.organizationId)} AND e.status<>'resolved' AND (e.store_id IN (SELECT id FROM scoped_stores) ${companywide ? "OR e.store_id IS NULL" : ""}) AND ${exceptionRole} ${access.accountabilityOnly ? `AND e.kind IN (${ACCOUNTABILITY_EXCEPTION_KINDS.map(kind => bind(kind)).join(",")})` : ""}`;
  const reminder = `SELECT ${select({ id: "r.id", source_kind: "'vendor_reminder'", vendor_id: "r.vendor_id", title: "r.title", reason: "COALESCE(r.note,'Vendor relationship follow-up is still open.')", owner: "r.accountable_party", due_at: "r.due_at", priority: `CASE WHEN ${overdue("r.due_at")} THEN 'critical' ELSE 'normal' END`, lane: "'team'", group_name: "'vendor_relationship'", source_count: "1" })} FROM ops_vendor_reminders r WHERE r.organization_id=${bind(scope.organizationId)} AND r.status='open' AND ${companywide && !finance && !access.accountabilityOnly ? "1=1" : "1=0"}`;
  const quote = `SELECT ${select({ id: "'quote-round-' || q.work_order_id", source_kind: "'quote_round'", work_order_id: "q.work_order_id", store_id: "w.store_id", owner: "w.accountable_party", due_at: "q.due_at", priority: "CASE WHEN q.missed_count>0 THEN 'critical' WHEN q.submitted_count>0 THEN 'high' ELSE 'normal' END", lane: "CASE WHEN q.missed_count>0 OR q.submitted_count>0 THEN 'team' ELSE 'waiting' END", group_name: "'work_vendor'", source_count: "q.source_count", requested_count: "q.requested_count", submitted_count: "q.submitted_count", missed_count: "q.missed_count" })} FROM quote_rounds q JOIN scoped_work w ON w.organization_id=q.organization_id AND w.id=q.work_order_id WHERE ${finance ? "1=0" : "1=1"}`;
  const hold = `SELECT ${select({ id: "h.id", source_kind: "'held_work'", work_order_id: "h.work_order_id", store_id: "w.store_id", title: "'Reconsider approved held work'", reason: "'The review date for work waiting on a suitable visit is approaching or overdue.'", owner: "'Facilities coordinator'", due_at: "h.deadline_at", priority: `CASE WHEN ${overdue("h.deadline_at")} THEN 'critical' ELSE 'low' END`, lane: `CASE WHEN ${overdue("h.deadline_at")} THEN 'team' ELSE 'upcoming' END`, group_name: "'work_vendor'", source_count: "1" })} FROM ops_work_order_visit_holds h JOIN scoped_work w ON w.organization_id=h.organization_id AND w.id=h.work_order_id WHERE h.status='active' AND ${finance ? "1=0" : "1=1"}`;
  const filtered = `SELECT a.*,${instant("a.due_at")} AS normalized_due,CASE WHEN ${overdue("a.due_at")} THEN 0 ELSE 1 END AS overdue_order,CASE a.priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END AS priority_order FROM candidates a WHERE ${query.lane ? `a.lane=${bind(query.lane)}` : "1=1"} AND ${query.group ? `a.group_name=${bind(query.group)}` : "1=1"}`;
  const cursor = readAttentionCursor(query.cursor);
  const { limit, offset } = dashboardPageBounds(query);
  const idOrder = driver.dialect === "postgres" ? 'id COLLATE "C"' : "id COLLATE BINARY";
  const cursorWhere = cursor ? `WHERE (overdue_order,priority_order,COALESCE(normalized_due,'9999-12-31T00:00:00.000Z'),${idOrder}) > (${cursor.map(value => bind(value)).join(",")})` : "";
  const sql = `${scoped}, candidates AS (${[task, follow, exception, reminder, quote, hold].join(" UNION ALL ")}), filtered AS (${filtered}),
    totals AS (SELECT COUNT(*) AS total_count,COALESCE(SUM(CASE WHEN lane='mine' THEN 1 ELSE 0 END),0) AS mine_count,COALESCE(SUM(CASE WHEN source_kind NOT IN ('exception','vendor_reminder') THEN 1 ELSE 0 END),0) AS follow_up_count FROM filtered),
    visible AS (SELECT * FROM filtered ${cursorWhere} ORDER BY overdue_order,priority_order,COALESCE(normalized_due,'9999-12-31T00:00:00.000Z'),${idOrder} LIMIT ${bind(limit + 1)} OFFSET ${bind(cursor ? 0 : offset)})
    SELECT a.*,t.total_count,t.mine_count,t.follow_up_count,w.number AS work_number,r.reference AS request_reference,v.name AS vendor_name,s.store_number,s.name AS store_name,wt.task_type FROM totals t LEFT JOIN visible a ON 1=1 LEFT JOIN scoped_work w ON w.id=a.work_order_id LEFT JOIN scoped_requests r ON r.id=a.service_request_id LEFT JOIN scoped_stores s ON s.id=a.store_id LEFT JOIN ops_vendors v ON v.organization_id=${bind(scope.organizationId)} AND v.id=a.vendor_id LEFT JOIN visible_tasks wt ON wt.id=a.id AND a.source_kind='workflow_task' ORDER BY a.overdue_order,a.priority_order,COALESCE(a.normalized_due,'9999-12-31T00:00:00.000Z'),a.${idOrder}`;
  const result = await driver.query({ sql, params });
  const rows = result.rows.filter(row => row.id != null).map(attentionRow);
  const items = rows.slice(0, limit);
  return { items, totalCount: Number(result.rows[0]?.total_count ?? 0), mineCount: Number(result.rows[0]?.mine_count ?? 0), followUpCount: Number(result.rows[0]?.follow_up_count ?? 0), nextCursor: rows.length > limit ? attentionCursor(items.at(-1)!, query.asOf) : undefined };
}

function attentionRow(row: SqlRow): AttentionQueueRow {
  const text = (key: string) => row[key] == null ? undefined : String(row[key]);
  const id = String(row.id), sourceKind = String(row.source_kind) as AttentionQueueRow["sourceKind"];
  const workOrderId = text("work_order_id"), serviceRequestId = text("service_request_id"), vendorId = text("vendor_id");
  const copy = sourceKind === "quote_round" ? quoteRoundCopy(Number(row.requested_count), Number(row.submitted_count), Number(row.missed_count)) : undefined;
  const linkHref = sourceKind === "workflow_task" ? row.warranty_id ? `/app/warranties/${row.warranty_id}#diagnosis` : workOrderId ? `/app/work-orders/${encodeURIComponent(workOrderId)}?view=accountability#workflow-tasks` : `/app/requests/${encodeURIComponent(serviceRequestId!)}`
    : sourceKind === "vendor_reminder" ? `/app/vendors/${encodeURIComponent(vendorId!)}#vendor-reminders`
      : sourceKind === "quote_round" ? `/app/work-orders/${encodeURIComponent(workOrderId!)}?view=service&path=bids#bid-requests`
        : sourceKind === "held_work" ? `/app/work-orders/${encodeURIComponent(workOrderId!)}?view=service#visit-hold` : `/app/action-center/${encodeURIComponent(id)}`;
  return { id, sourceKind, sourceCount: Number(row.source_count), workOrderId, serviceRequestId, vendorId, storeId: text("store_id"),
    title: row.task_type === "review_warranty" ? WARRANTY_REVIEW_TITLE : copy?.title ?? String(row.title), reason: copy?.reason ?? String(row.reason), owner: String(row.owner),
    dueAt: text("normalized_due"), completedAt: row.completed_at ? new Date(String(row.completed_at)).toISOString() : undefined,
    priority: String(row.priority) as AttentionQueueRow["priority"], lane: String(row.lane) as AttentionQueueRow["lane"], group: String(row.group_name) as AttentionQueueRow["group"], linkHref,
    storeLabel: row.store_id ? row.store_number ? `Store ${row.store_number} · ${row.store_name}` : "Unknown store" : undefined, workNumber: text("work_number"), requestReference: text("request_reference"), vendorName: text("vendor_name") };
}
