import {capitalPlanFrom,monthAfter,validateCapitalQuery,type CapitalPage,type CapitalPrice,type CapitalQuery} from "./capital-planning";
import type {OrganizationScope} from "./repository";
import {scopeWhere} from "./sql-scope";
import type {OpsSqlDriver} from "./sql-driver";
export async function queryCapital(driver:OpsSqlDriver,scope:OrganizationScope,q:CapitalQuery):Promise<CapitalPage> {
  validateCapitalQuery(q);const params:unknown[]=[],clauses=[scopeWhere(scope,"s",params),"a.status<>'retired'","NOT EXISTS(SELECT 1 FROM ops_replacement_events e WHERE e.organization_id=a.organization_id AND e.asset_id=a.id AND e.status='completed')"];
  if(q.storeId){clauses.push("s.id=?");params.push(q.storeId);}if(q.regionId){clauses.push("s.region_id=?");params.push(q.regionId);}if(q.category){clauses.push("a.category_key=?");params.push(q.category);}if(q.search){clauses.push("(LOWER(a.name) LIKE ? OR LOWER(a.asset_tag) LIKE ? OR s.search_text LIKE ?)");params.push(...Array(3).fill(`%${q.search.toLowerCase()}%`));}
  const cte=`WITH plans AS (SELECT COALESCE(p.id,l.id) AS id,a.organization_id,a.id AS asset_id,a.store_id,COALESCE(p.version,0) AS version,CASE WHEN p.id IS NOT NULL THEN p.target_month ELSE CAST(l.planned_for_year AS TEXT) END AS target_month,CASE WHEN p.id IS NOT NULL THEN p.amount_minor ELSE a.replacement_estimate_minor END AS amount_minor,COALESCE(p.currency,a.replacement_currency,'USD') AS currency,COALESCE(p.cost_basis,'Planning estimate') AS cost_basis,p.source_id,COALESCE(p.priority,'flexible') AS priority,COALESCE(p.owner,'Facilities') AS owner,COALESCE(p.reason,l.user_reason) AS reason,COALESCE(p.status,'planned') AS status,COALESCE(p.created_at,CAST(l.decided_at AS TEXT)) AS created_at,a.name AS asset_name,a.asset_tag,a.category_key,s.store_number,s.name AS store_name,CASE WHEN p.id IS NULL THEN l.planned_for_year ELSE NULL END AS legacy_year FROM ops_assets a JOIN ops_stores s ON s.organization_id=a.organization_id AND s.id=a.store_id LEFT JOIN ops_capital_plans p ON p.organization_id=a.organization_id AND p.asset_id=a.id AND p.version=(SELECT MAX(p2.version) FROM ops_capital_plans p2 WHERE p2.organization_id=a.organization_id AND p2.asset_id=a.id) LEFT JOIN ops_lifecycle_recommendations l ON l.organization_id=a.organization_id AND l.asset_id=a.id AND l.version=(SELECT MAX(l2.version) FROM ops_lifecycle_recommendations l2 WHERE l2.organization_id=a.organization_id AND l2.asset_id=a.id) WHERE ${clauses.join(" AND ")} AND (p.status IN ('considering','planned','approved') OR p.id IS NULL AND l.user_decision IN ('replace','defer')))`;
  const end=monthAfter(q.start,q.months),bucket="CASE WHEN target_month IS NULL THEN 'undated' WHEN length(target_month)=4 THEN target_month WHEN target_month < ? THEN 'overdue' ELSE target_month END";
  const buckets=(await driver.query({sql:`${cte} SELECT ${bucket} AS month,COUNT(*) AS count,COALESCE(SUM(amount_minor),0) AS amount_minor,SUM(CASE WHEN amount_minor IS NULL THEN 1 ELSE 0 END) AS missing FROM plans WHERE currency=? AND (target_month IS NULL OR length(target_month)=4 OR target_month<?) GROUP BY 1 ORDER BY month`,params:[...params,q.start,q.currency,end]})).rows;
  const currencies=(await driver.query({sql:`${cte} SELECT DISTINCT currency FROM plans ORDER BY currency`,params})).rows.map(r=>String(r.currency));
  let filter="currency=? AND (target_month IS NULL OR length(target_month)=4 OR target_month<?)",values:unknown[]=[...params,q.currency,end];
  if(q.month){filter=q.month==="undated"?"currency=? AND target_month IS NULL":q.month==="overdue"?"currency=? AND length(target_month)=7 AND target_month<?":"currency=? AND target_month=?";values=[...params,q.currency,...(q.month==="undated"?[]:[q.month==="overdue"?q.start:q.month])];}
  const total=Number((await driver.query({sql:`${cte} SELECT COUNT(*) AS total FROM plans WHERE ${filter}`,params:values})).rows[0]?.total??0);
  const rows=(await driver.query({sql:`${cte} SELECT * FROM plans WHERE ${filter} ORDER BY COALESCE(target_month,'9999'),asset_id LIMIT 25 OFFSET ?`,params:[...values,Math.max(0,q.offset??0)]})).rows;
  return {total,currencies,buckets:buckets.map(r=>({month:String(r.month),count:Number(r.count),amountMinor:Number(r.amount_minor),missing:Number(r.missing)})),items:rows.map(r=>({...capitalPlanFrom(r),assetName:String(r.asset_name),assetTag:String(r.asset_tag),storeNumber:String(r.store_number),storeName:String(r.store_name),category:String(r.category_key),legacyYear:r.legacy_year==null?undefined:Number(r.legacy_year)}))};
}
export async function queryCapitalPrices(driver:OpsSqlDriver,org:string,assetId:string):Promise<CapitalPrice[]> {
  const rows=(await driver.query({sql:`SELECT e.id,e.approved_amount_minor AS amount_minor,e.currency,'Approved amount' AS basis,e.work_order_id FROM ops_replacement_events e WHERE e.organization_id=? AND e.asset_id=? AND e.status='approved'
  UNION ALL SELECT p.id,p.amount_minor,p.currency,'Selected quote' AS basis,p.work_order_id FROM ops_vendor_estimate_proposals p JOIN ops_work_order_estimate_requests r ON r.organization_id=p.organization_id AND r.id=p.request_id AND r.vendor_id=p.vendor_id JOIN ops_work_orders w ON w.organization_id=p.organization_id AND w.id=p.work_order_id WHERE p.organization_id=? AND w.asset_id=? AND r.decision_kind='replacement_quote' AND r.status='selected' AND p.revision=(SELECT MAX(p2.revision) FROM ops_vendor_estimate_proposals p2 WHERE p2.organization_id=p.organization_id AND p2.request_id=p.request_id)
  UNION ALL SELECT id,amount_minor,currency,'Reported price' AS basis,work_order_id FROM ops_work_prices WHERE organization_id=? AND asset_id=? AND kind='replace' AND scope_kind='whole'`,params:[org,assetId,org,assetId,org,assetId]})).rows;
  return rows.map(r=>({id:String(r.id),amountMinor:Number(r.amount_minor),currency:String(r.currency),basis:String(r.basis),label:String(r.basis),href:`/app/work-orders/${r.work_order_id}?view=service`}));
}

export async function capitalFilters(driver:OpsSqlDriver,scope:OrganizationScope) {
 const params:unknown[]=[],where=scopeWhere(scope,"s",params);
 const stores=(await driver.query({sql:`SELECT s.id,s.store_number,s.name FROM ops_stores s WHERE ${where} ORDER BY s.store_number,s.id LIMIT 250`,params})).rows;
 const regions=(await driver.query({sql:`SELECT DISTINCT r.id,r.name FROM ops_regions r JOIN ops_stores s ON s.organization_id=r.organization_id AND s.region_id=r.id WHERE ${where} ORDER BY r.name,r.id LIMIT 250`,params})).rows;
 const categories=(await driver.query({sql:`SELECT DISTINCT a.category_key FROM ops_assets a JOIN ops_stores s ON s.organization_id=a.organization_id AND s.id=a.store_id WHERE ${where} ORDER BY a.category_key LIMIT 250`,params})).rows;
 return {stores:stores.map(s=>({id:String(s.id),label:`${s.store_number} · ${s.name}`})),regions:regions.map(r=>({id:String(r.id),label:String(r.name)})),categories:categories.map(a=>String(a.category_key))};
}
