import { and, eq, getTableName, inArray, type InferSelectModel } from "drizzle-orm";
import type { SQLiteTable } from "drizzle-orm/sqlite-core";
import { drizzle } from "drizzle-orm/d1";
import {
  opsAssetComponents,
  opsComponentLifecycleEvents,
  opsAssets,
  opsAssetReplacementOverrides,
  opsApprovalDecisions,
  opsApprovalPolicies,
  opsApprovalRequests,
  opsAuditEvents,
  opsCostLines,
  opsComponentTemplates,
  opsDivisions,
  opsEntityFiles,
  opsExceptions,
  opsEquipmentTemplates,
  opsFiles,
  opsFollowUps,
  opsWorkflowTasks,
  opsWorkflowTaskSlaPauses,
  opsWorkflowTaskSlaResumes,
  opsInvoiceAllocations,
  opsInvoiceReferences,
  opsMemberships,
  opsOrganizations,
  opsOutboxMessages,
  opsNotificationRules,
  opsMaintenancePrograms,
  opsChecklistTemplates,
  opsPmOccurrences,
  opsPmPlans,
  opsPmWorkItems,
  opsChecklistResponses,
  opsServiceRuns,
  opsRouteStops,
  opsServiceRunWorkOrders,
  opsServiceRunResponses,
  opsVendorWarrantyProfiles,
  opsWarrantyRules,
  opsWarrantyCoverageLines,
  opsRepairItems,
  opsAppliedWarranties,
  opsWarrantyAmendments,
  opsManufacturerWarranties,
  opsWarrantyCases,
  opsQuotes,
  opsAuthorizations,
  opsAccountingInvoiceSources,
  opsInvoices,
  opsInvoiceLines,
  opsInvoiceLineAllocations,
  opsInvoiceExceptions,
  opsInvoiceAdjustments,
  opsServiceDiscrepancies,
  opsValueEvents,
  opsPublicTokens,
  opsRegions,
  opsRequestImpactAssessments,
  opsRequests,
  opsReplacementBenchmarks,
  opsReplacementEvents,
  opsLifecycleRecommendations,
  opsReplacementProfiles,
  opsScopeGrants,
  opsSiteVisitWorkOrders,
  opsWorkOrderVerifications,
  opsStores,
  opsTaxonomyNodes,
  opsUsers,
  opsVendorCoverage,
  opsVendorQualifications,
  opsVendorComplianceDocuments,
  opsVendorComplianceAlerts,
  opsVendorContracts,
  opsContractVersions,
  opsContractScopes,
  opsRateCardLines,
  opsServiceLevelPolicies,
  opsSchedulingPolicies,
  opsVendorCapacity,
  opsVendorEstimateProposals,
  opsVendorResponses,
  opsVendorSpecialties,
  opsVendors,
  opsVendorReminders,
  opsVisitEvidence,
  opsVisitSessions,
  opsWorkOrderAssignments,
  opsWorkOrderVisitHolds,
  opsWorkOrderEstimateRequests,
  opsWorkOrderIssuances,
  opsWorkOrders,
} from "../../db/ops-schema";
import type { IsoDateTime, OpsFixture, OpsId } from "./types";

function optional<T>(value: T | null): T | undefined {
  return value ?? undefined;
}

function parseStringArray(value: string) {
  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : [];
  } catch {
    return [];
  }
}

function parseStringRecord(value: string) {
  try {
    const parsed = JSON.parse(value) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, string> : {};
  } catch { return {}; }
}

function parseJsonArray<T>(value: string): T[] {
  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? parsed as T[] : [];
  } catch {
    return [];
  }
}

function locationCapturedAt(payloadJson: string, fallback: IsoDateTime) {
  try {
    const parsed = JSON.parse(payloadJson) as { capturedAt?: unknown; clientCapturedAt?: unknown };
    const capturedAt = parsed.clientCapturedAt ?? parsed.capturedAt;
    return typeof capturedAt === "string" ? capturedAt : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Compatibility projection for the current presentation layer.
 *
 * The durable source remains D1 and every query is tenant-bounded. New
 * production views should use OpsRepository read models instead of expanding
 * this snapshot facade; it exists so the current presenter can move off the
 * process-local fixture without making writes disappear across isolates.
 */
export async function loadOpsFixtureSnapshotFromD1(
  binding: D1Database,
  organizationId: OpsId,
  asOf: IsoDateTime,
  options: { includedTables?: ReadonlySet<string>; auditEventTypes?: readonly string[] } = {},
): Promise<OpsFixture> {
  const db = drizzle(binding);
  const tenant = <TColumn extends { _: { data: string } }>(column: TColumn) => eq(column as never, organizationId);

  const read = async <T extends SQLiteTable & { organizationId: Parameters<typeof tenant>[0] }>(table: T): Promise<InferSelectModel<T>[]> => {
    if (options.includedTables && !options.includedTables.has(getTableName(table))) return [];
    return await db.select().from(table as never).where(tenant(table.organizationId)) as unknown as InferSelectModel<T>[];
  };

  const [
    organizations,
    divisionRows,
    regionRows,
    taxonomyRows,
    equipmentTemplateRows,
    componentTemplateRows,
    storeRows,
    userRows,
    membershipRows,
    scopeGrantRows,
    vendorRows,
    vendorReminderRows,
    specialtyRows,
    coverageRows,
    qualificationRows,
    complianceDocumentRows,
    complianceAlertRows,
    vendorContractRows,
    contractVersionRows,
    contractScopeRows,
    rateCardRows,
    serviceLevelRows,
    schedulingPolicyRows,
    vendorCapacityRows,
    requestRows,
    requestImpactRows,
    workOrderRows,
    workOrderVisitHoldRows,
    approvalPolicyRows,
    approvalRequestRows,
    approvalDecisionRows,
    assignmentRows,
    issuanceRows,
    responseRows,
    estimateRequestRows,
    estimateProposalRows,
    visitRows,
    siteVisitWorkOrderRows,
    workOrderVerificationRows,
    evidenceRows,
    fileRows,
    entityFileRows,
    followUpRows,
    workflowTaskRows,
    workflowTaskSlaPauseRows,
    workflowTaskSlaResumeRows,
    exceptionRows,
    replacementProfileRows,
    assetRows,
    replacementBenchmarkRows,
    replacementOverrideRows,
    replacementEventRows,
    lifecycleRecommendationRows,
    componentRows,
    componentLifecycleEventRows,
    maintenanceProgramRows,
    checklistTemplateRows,
    pmPlanRows,
    pmOccurrenceRows,
    pmWorkItemRows,
    checklistResponseRows,
    serviceRunRows,
    routeStopRows,
    serviceRunWorkOrderRows,
    serviceRunResponseRows,
    vendorWarrantyProfileRows,
    warrantyRuleRows,
    warrantyCoverageLineRows,
    repairItemRows,
    appliedWarrantyRows,
    warrantyAmendmentRows,
    manufacturerWarrantyRows,
    warrantyCaseRows,
    quoteRows,
    authorizationRows,
    invoiceV2Rows,
    invoiceLineRows,
    accountingInvoiceSourceRows,
    invoiceLineAllocationRows,
    invoiceExceptionRows,
    invoiceAdjustmentRows,
    serviceDiscrepancyRows,
    valueEventRows,
    costRows,
    invoiceRows,
    allocationRows,
    auditRows,
    outboxRows,
    notificationRuleRows,
    tokenRows,
  ] = await Promise.all([
    db.select().from(opsOrganizations).where(eq(opsOrganizations.id, organizationId)),
    read(opsDivisions),
    read(opsRegions),
    read(opsTaxonomyNodes),
    read(opsEquipmentTemplates),
    read(opsComponentTemplates),
    read(opsStores),
    db.select({ id: opsUsers.id, email: opsUsers.email, displayName: opsUsers.displayName, status: opsUsers.status, createdAt: opsUsers.createdAt })
      .from(opsUsers)
      .innerJoin(opsMemberships, and(eq(opsMemberships.userId, opsUsers.id), eq(opsMemberships.organizationId, organizationId))),
    read(opsMemberships),
    read(opsScopeGrants),
    read(opsVendors),
    read(opsVendorReminders),
    read(opsVendorSpecialties),
    read(opsVendorCoverage),
    read(opsVendorQualifications),
    read(opsVendorComplianceDocuments),
    read(opsVendorComplianceAlerts),
    read(opsVendorContracts),
    read(opsContractVersions),
    read(opsContractScopes),
    read(opsRateCardLines),
    read(opsServiceLevelPolicies),
    read(opsSchedulingPolicies),
    read(opsVendorCapacity),
    read(opsRequests),
    read(opsRequestImpactAssessments),
    read(opsWorkOrders),
    read(opsWorkOrderVisitHolds),
    read(opsApprovalPolicies),
    read(opsApprovalRequests),
    read(opsApprovalDecisions),
    read(opsWorkOrderAssignments),
    read(opsWorkOrderIssuances),
    read(opsVendorResponses),
    read(opsWorkOrderEstimateRequests),
    read(opsVendorEstimateProposals),
    read(opsVisitSessions),
    read(opsSiteVisitWorkOrders),
    read(opsWorkOrderVerifications),
    read(opsVisitEvidence),
    read(opsFiles),
    read(opsEntityFiles),
    read(opsFollowUps),
    read(opsWorkflowTasks),
    read(opsWorkflowTaskSlaPauses),
    read(opsWorkflowTaskSlaResumes),
    read(opsExceptions),
    read(opsReplacementProfiles),
    read(opsAssets),
    read(opsReplacementBenchmarks),
    read(opsAssetReplacementOverrides),
    read(opsReplacementEvents),
    read(opsLifecycleRecommendations),
    read(opsAssetComponents),
    read(opsComponentLifecycleEvents),
    read(opsMaintenancePrograms),
    read(opsChecklistTemplates),
    read(opsPmPlans),
    read(opsPmOccurrences),
    read(opsPmWorkItems),
    read(opsChecklistResponses),
    read(opsServiceRuns),
    read(opsRouteStops),
    read(opsServiceRunWorkOrders),
    read(opsServiceRunResponses),
    read(opsVendorWarrantyProfiles),
    read(opsWarrantyRules),
    read(opsWarrantyCoverageLines),
    read(opsRepairItems),
    read(opsAppliedWarranties),
    read(opsWarrantyAmendments),
    read(opsManufacturerWarranties),
    read(opsWarrantyCases),
    read(opsQuotes),
    read(opsAuthorizations),
    read(opsInvoices),
    read(opsInvoiceLines),
    read(opsAccountingInvoiceSources),
    read(opsInvoiceLineAllocations),
    read(opsInvoiceExceptions),
    read(opsInvoiceAdjustments),
    read(opsServiceDiscrepancies),
    read(opsValueEvents),
    read(opsCostLines),
    read(opsInvoiceReferences),
    read(opsInvoiceAllocations),
    options.auditEventTypes ? db.select().from(opsAuditEvents).where(and(tenant(opsAuditEvents.organizationId), inArray(opsAuditEvents.eventType, [...options.auditEventTypes]))) : read(opsAuditEvents),
    read(opsOutboxMessages),
    read(opsNotificationRules),
    read(opsPublicTokens),
  ]);

  const users = [...new Map(userRows.map((row) => [row.id, row])).values()];
  return {
    asOf,
    organizations: organizations as OpsFixture["organizations"],
    divisions: divisionRows as OpsFixture["divisions"],
    regions: regionRows.map((row) => ({ ...row, divisionId: optional(row.divisionId) })) as OpsFixture["regions"],
    taxonomyNodes: taxonomyRows.map((row) => ({ ...row, parentNodeId: optional(row.parentNodeId), canonicalKey: optional(row.canonicalKey), aliases: parseStringArray(row.aliasesJson) })) as OpsFixture["taxonomyNodes"],
    equipmentTemplates: equipmentTemplateRows.map((row) => ({ ...row, defaultExpectedLifeYears: optional(row.defaultExpectedLifeYears) })) as OpsFixture["equipmentTemplates"],
    componentTemplates: componentTemplateRows.map((row) => ({ ...row, parentComponentTemplateId: optional(row.parentComponentTemplateId) })) as OpsFixture["componentTemplates"],
    stores: storeRows.map((row) => ({
      ...row,
      divisionId: optional(row.divisionId),
      regionId: optional(row.regionId),
      address2: optional(row.address2),
      aliases: parseStringArray(row.aliasesJson),
      latitudeE6: optional(row.latitudeE6),
      longitudeE6: optional(row.longitudeE6),
      timeZone: optional(row.timeZone),
    })) as OpsFixture["stores"],
    users: users as OpsFixture["users"],
    memberships: membershipRows as OpsFixture["memberships"],
    scopeGrants: scopeGrantRows as OpsFixture["scopeGrants"],
    vendors: vendorRows.map((row) => ({ ...row, dispatchPhone: optional(row.dispatchPhone) })) as OpsFixture["vendors"],
    vendorReminders: vendorReminderRows.map((row) => ({ ...row, note: optional(row.note), createdByActorId: optional(row.createdByActorId), completedByActorType: optional(row.completedByActorType), completedByActorId: optional(row.completedByActorId), completedByActorName: optional(row.completedByActorName), completedAt: optional(row.completedAt), completionNote: optional(row.completionNote) })) as OpsFixture["vendorReminders"],
    vendorSpecialties: specialtyRows.map((row) => ({ ...row, searchAliases: parseStringArray(row.searchAliasesJson) })) as OpsFixture["vendorSpecialties"],
    vendorCoverage: coverageRows.map((row) => ({ ...row, preferredRank: optional(row.preferredRank) })) as OpsFixture["vendorCoverage"],
    vendorQualifications: qualificationRows.map((row) => ({ ...row, workType: optional(row.workType), serviceType: optional(row.serviceType), assetType: optional(row.assetType), componentType: optional(row.componentType), manufacturerAuthorization: optional(row.manufacturerAuthorization), regionId: optional(row.regionId), storeId: optional(row.storeId), maximumJobAmount: row.maximumJobAmountMinor == null ? undefined : { amountMinor: row.maximumJobAmountMinor, currency: row.currency ?? "USD" }, requiredLicense: optional(row.requiredLicense), requiredCertification: optional(row.requiredCertification), expiresAt: optional(row.expiresAt) })) as OpsFixture["vendorQualifications"],
    vendorComplianceDocuments: complianceDocumentRows.map((row) => ({ ...row, issuer: optional(row.issuer), reference: optional(row.reference), effectiveAt: optional(row.effectiveAt), expiresAt: optional(row.expiresAt), storedFileId: optional(row.storedFileId) })) as OpsFixture["vendorComplianceDocuments"],
    vendorComplianceAlerts: complianceAlertRows.map((row) => ({ ...row, reminderId: optional(row.reminderId) })) as OpsFixture["vendorComplianceAlerts"],
    vendorContracts: vendorContractRows as OpsFixture["vendorContracts"],
    contractVersions: contractVersionRows.map((row) => ({ ...row, effectiveEndsAt: optional(row.effectiveEndsAt), renewalAt: optional(row.renewalAt), noticeDays: optional(row.noticeDays), priceEscalationAt: optional(row.priceEscalationAt), supersedesContractVersionId: optional(row.supersedesContractVersionId), nteAmount: row.nteAmountMinor == null ? undefined : { amountMinor: row.nteAmountMinor, currency: row.currency }, evidenceRequirements: parseStringArray(row.evidenceRequirementsJson), complianceRequirements: parseStringArray(row.complianceRequirementsJson), warrantyLaborDays: optional(row.warrantyLaborDays), warrantyPartsDays: optional(row.warrantyPartsDays), warrantyTravelDays: optional(row.warrantyTravelDays) })) as OpsFixture["contractVersions"],
    contractScopes: contractScopeRows as OpsFixture["contractScopes"],
    rateCardLines: rateCardRows.map((row) => ({ ...row, amount: { amountMinor: row.amountMinor, currency: row.currency }, effectiveEndsAt: optional(row.effectiveEndsAt) })) as OpsFixture["rateCardLines"],
    serviceLevelPolicies: serviceLevelRows as OpsFixture["serviceLevelPolicies"],
    schedulingPolicies: schedulingPolicyRows as OpsFixture["schedulingPolicies"],
    vendorCapacity: vendorCapacityRows.map((row) => ({ ...row, specialEquipment: parseStringArray(row.specialEquipmentJson) })) as OpsFixture["vendorCapacity"],
    requests: requestRows.map((row) => ({ ...row, version: Number(row.version ?? 0), reporterEmployeeId: optional(row.reporterEmployeeId), acknowledgedAt: optional(row.acknowledgedAt), acknowledgedByActorType: optional(row.acknowledgedByActorType), acknowledgedByActorId: optional(row.acknowledgedByActorId), acknowledgedByActorName: optional(row.acknowledgedByActorName), linkedWorkOrderId: optional(row.linkedWorkOrderId), linkedAt: optional(row.linkedAt), linkedByActorType: optional(row.linkedByActorType), linkedByActorId: optional(row.linkedByActorId), linkedByActorName: optional(row.linkedByActorName), convertedWorkOrderId: optional(row.convertedWorkOrderId) })) as OpsFixture["requests"],
    requestImpactAssessments: requestImpactRows.map((row) => ({
      ...row,
      reviewDisposition: optional(row.reviewDisposition),
      productInventoryValue: row.productInventoryValueMinor == null ? undefined : { amountMinor: row.productInventoryValueMinor, currency: row.productInventoryCurrency ?? "USD" },
      capacityUnavailableBps: optional(row.capacityUnavailableBps),
      revenueFunctionImpact: optional(row.revenueFunctionImpact),
      estimatedDailyRevenueExposure: row.estimatedDailyRevenueExposureMinor == null ? undefined : { amountMinor: row.estimatedDailyRevenueExposureMinor, currency: row.estimatedDailyRevenueExposureCurrency ?? "USD" },
      estimatedDowntimeMinutes: optional(row.estimatedDowntimeMinutes),
      notes: optional(row.notes),
      assessedByActorId: optional(row.assessedByActorId),
    })) as OpsFixture["requestImpactAssessments"],
    workOrders: workOrderRows.map((row) => ({
      ...row,
      version: Number(row.version ?? 0),
      requestId: optional(row.requestId),
      authorizedScope: optional(row.authorizedScope),
      categoryKey: optional(row.categoryKey),
      taxonomyNodeId: optional(row.taxonomyNodeId),
      assetId: optional(row.assetId),
      componentId: optional(row.componentId),
      internalAccountableType: optional(row.internalAccountableType),
      internalAccountableId: optional(row.internalAccountableId),
      dueAt: optional(row.dueAt),
      escalationTo: optional(row.escalationTo),
      nte: row.nteAmountMinor == null ? undefined : { amountMinor: row.nteAmountMinor, currency: row.nteCurrency ?? "USD" },
      repairEstimate: row.repairEstimateAmountMinor == null ? undefined : { amountMinor: row.repairEstimateAmountMinor, currency: row.repairEstimateCurrency ?? "USD" },
      estimatedServiceExtensionMonths: optional(row.estimatedServiceExtensionMonths),
      vendorServiceTicketNumber: optional(row.vendorServiceTicketNumber),
      vendorInvoiceNumber: optional(row.vendorInvoiceNumber),
      externalAccountingPo: optional(row.externalAccountingPo),
      resolvedAt: optional(row.resolvedAt),
      closedAt: optional(row.closedAt),
    })) as OpsFixture["workOrders"],
    workOrderVisitHolds: workOrderVisitHoldRows.map((row) => ({ ...row, internalReviewThreshold: row.internalReviewThresholdMinor == null ? undefined : { amountMinor: row.internalReviewThresholdMinor, currency: row.currency ?? "USD" }, claimedVisitId: optional(row.claimedVisitId), claimedVendorId: optional(row.claimedVendorId), claimedAt: optional(row.claimedAt), plannedReviewAppointmentId: optional(row.plannedReviewAppointmentId), plannedReviewSelectedAt: optional(row.plannedReviewSelectedAt), plannedReviewSelectedByMembershipId: optional(row.plannedReviewSelectedByMembershipId), createdByMembershipId: optional(row.createdByMembershipId) })) as OpsFixture["workOrderVisitHolds"],
    approvalPolicies: approvalPolicyRows.map((row) => ({ ...row, categoryKey: optional(row.categoryKey), maxAmountMinor: optional(row.maxAmountMinor), escalationRole: optional(row.escalationRole), supersedesPolicyId: optional(row.supersedesPolicyId), createdByMembershipId: optional(row.createdByMembershipId) })) as OpsFixture["approvalPolicies"],
    approvalRequests: approvalRequestRows.map((row) => ({ ...row, categoryKey: optional(row.categoryKey), amount: { amountMinor: row.amountMinor, currency: row.currency }, escalationRole: optional(row.escalationRole), requestedByMembershipId: optional(row.requestedByMembershipId), reason: optional(row.reason), dueAt: optional(row.dueAt), parentApprovalRequestId: optional(row.parentApprovalRequestId) })) as OpsFixture["approvalRequests"],
    approvalDecisions: approvalDecisionRows.map((row) => ({ ...row, decidedByMembershipId: optional(row.decidedByMembershipId), reason: optional(row.reason), escalatedToRole: optional(row.escalatedToRole) })) as OpsFixture["approvalDecisions"],
    assignments: assignmentRows.map((row) => ({ ...row, vendorId: optional(row.vendorId), internalMembershipId: optional(row.internalMembershipId), supersedesAssignmentId: optional(row.supersedesAssignmentId) })) as OpsFixture["assignments"],
    issuances: issuanceRows as OpsFixture["issuances"],
    vendorResponses: responseRows.map((row) => ({ ...row, proposedAt: optional(row.proposedAt), message: optional(row.message) })) as OpsFixture["vendorResponses"],
    estimateRequests: estimateRequestRows.map((row) => ({ ...row, dueAt: optional(row.dueAt), openedAt: optional(row.openedAt), respondedAt: optional(row.respondedAt), decisionAt: optional(row.decisionAt) })) as OpsFixture["estimateRequests"],
    estimateProposals: estimateProposalRows.map((row) => ({ ...row, amount: { amountMinor: row.amountMinor, currency: row.currency }, exclusions: optional(row.exclusions), leadTimeDays: optional(row.leadTimeDays), validUntil: optional(row.validUntil) })) as OpsFixture["estimateProposals"],
    visits: visitRows.map((row) => ({
      ...row,
      vendorId: optional(row.vendorId),
      internalMembershipId: optional(row.internalMembershipId),
      workOrderId: optional(row.workOrderId),
      unmatchedReason: optional(row.unmatchedReason),
      technicianPhoneOrPin: optional(row.technicianPhoneOrPin),
      crewCount: Number(row.crewCount ?? 1),
      additionalTechnicianNames: parseStringArray(row.additionalTechnicianNamesJson),
      vehicleIdentifier: optional(row.vehicleIdentifier),
      arrivalNote: optional(row.arrivalNote),
      endedChannel: optional(row.endedChannel),
      checkedOutAt: optional(row.checkedOutAt),
      outcome: optional(row.outcome),
      outcomeNotes: optional(row.outcomeNotes),
      observedDurationSeconds: optional(row.observedDurationSeconds),
    })) as OpsFixture["visits"],
    siteVisitWorkOrders: siteVisitWorkOrderRows.map((row) => ({
      ...row,
      linkedByActorId: optional(row.linkedByActorId),
      selectionSource: row.selectionSource,
      workOrderHoldId: optional(row.workOrderHoldId),
      outcome: optional(row.outcome),
      outcomeNotes: optional(row.outcomeNotes),
      outcomeRecordedByActorType: optional(row.outcomeRecordedByActorType),
      outcomeRecordedByActorId: optional(row.outcomeRecordedByActorId),
      outcomeRecordedByActorName: optional(row.outcomeRecordedByActorName),
      outcomeRecordedAt: optional(row.outcomeRecordedAt),
      followUpId: optional(row.followUpId),
      vendorFollowUpTiming: optional(row.vendorFollowUpTiming),
    })) as OpsFixture["siteVisitWorkOrders"],
    workOrderVerifications: workOrderVerificationRows.map((row) => ({
      ...row,
      cycle: Number(row.cycle),
      basis: optional(row.basis),
      verificationScope: optional(row.verificationScope),
      reason: optional(row.reason),
    })) as OpsFixture["workOrderVerifications"],
    visitEvidence: evidenceRows.map((row) => ({
      id: row.id,
      organizationId: row.organizationId,
      visitId: row.visitId,
      kind: row.kind,
      channel: row.channel,
      observedAt: row.observedAt,
      payloadJson: row.payloadJson,
      location: row.locationResult ? {
        result: row.locationResult,
        latitudeE6: optional(row.latitudeE6),
        longitudeE6: optional(row.longitudeE6),
        accuracyM: optional(row.accuracyM),
        distanceM: optional(row.distanceM),
        capturedAt: locationCapturedAt(row.payloadJson, row.observedAt),
      } : undefined,
    })) as OpsFixture["visitEvidence"],
    files: fileRows as OpsFixture["files"],
    entityFiles: entityFileRows as OpsFixture["entityFiles"],
    followUps: followUpRows.map((row) => ({ ...row, sourceVisitId: optional(row.sourceVisitId), completedAt: optional(row.completedAt) })) as OpsFixture["followUps"],
    workflowTasks: workflowTaskRows.map((row) => ({ ...row, workOrderId: optional(row.workOrderId), serviceRequestId: optional(row.serviceRequestId), assigneeId: optional(row.assigneeId), assigneeRole: optional(row.assigneeRole), dueAt: optional(row.dueAt), noSlaReason: optional(row.noSlaReason), applicableSlaClock: optional(row.applicableSlaClock), sourceFollowUpId: optional(row.sourceFollowUpId), sourceApprovalRequestId: optional(row.sourceApprovalRequestId), createdByActorId: optional(row.createdByActorId), startedByActorType: optional(row.startedByActorType), startedByActorId: optional(row.startedByActorId), startedByActorName: optional(row.startedByActorName), startedAt: optional(row.startedAt), completedByActorType: optional(row.completedByActorType), completedByActorId: optional(row.completedByActorId), completedByActorName: optional(row.completedByActorName), completedAt: optional(row.completedAt), cancelledByActorType: optional(row.cancelledByActorType), cancelledByActorId: optional(row.cancelledByActorId), cancelledByActorName: optional(row.cancelledByActorName), cancelledAt: optional(row.cancelledAt), resolutionNote: optional(row.resolutionNote) })) as OpsFixture["workflowTasks"],
    workflowTaskSlaPauses: workflowTaskSlaPauseRows.map((row) => { const { affectedClocksJson, ...pause } = row; return { ...pause, ownerId: optional(row.ownerId), affectedClocks: parseStringArray(affectedClocksJson), expectedResumeAt: optional(row.expectedResumeAt), pausedByActorId: optional(row.pausedByActorId) }; }) as OpsFixture["workflowTaskSlaPauses"],
    workflowTaskSlaResumes: workflowTaskSlaResumeRows.map((row) => ({ ...row, resumedByActorId: optional(row.resumedByActorId), note: optional(row.note) })) as OpsFixture["workflowTaskSlaResumes"],
    exceptions: exceptionRows.map((row) => ({ ...row, storeId: optional(row.storeId), workOrderId: optional(row.workOrderId), visitId: optional(row.visitId), vendorId: optional(row.vendorId) })) as OpsFixture["exceptions"],
    replacementProfiles: replacementProfileRows.map((row) => ({ ...row, taxonomyNodeId: optional(row.taxonomyNodeId), matchKeys: parseStringArray(row.matchKeysJson), attributes: parseStringRecord(row.attributesJson), expectedLifeYears: optional(row.expectedLifeYears) })) as OpsFixture["replacementProfiles"],
    assets: assetRows.map((row) => ({
      ...row,
      taxonomyNodeId: optional(row.taxonomyNodeId),
      equipmentTemplateId: optional(row.equipmentTemplateId),
      groupPath: parseStringArray(row.groupPathJson),
      manufacturer: optional(row.manufacturer),
      model: optional(row.model),
      serialNumber: optional(row.serialNumber),
      supplier: optional(row.supplier),
      installedAt: optional(row.installedAt),
      expectedLifeYears: optional(row.expectedLifeYears),
      warrantyEndsAt: optional(row.warrantyEndsAt),
      replacementProfileId: optional(row.replacementProfileId),
      replacementAttributes: parseStringRecord(row.replacementAttributesJson),
      replacementAdjustmentBps: optional(row.replacementAdjustmentBps),
      replacementEstimate: row.replacementEstimateMinor == null ? undefined : { amountMinor: row.replacementEstimateMinor, currency: row.replacementCurrency ?? "USD" },
      retiredAt: optional(row.retiredAt),
      replacedByAssetId: optional(row.replacedByAssetId),
    })) as OpsFixture["assets"],
    replacementBenchmarks: replacementBenchmarkRows.map((row) => ({ ...row, sourceWorkOrderId: optional(row.sourceWorkOrderId), sourceEstimateProposalId: optional(row.sourceEstimateProposalId), sourceAssetId: optional(row.sourceAssetId), sourceVendorId: optional(row.sourceVendorId), equipmentAmount: { amountMinor: row.equipmentAmountMinor, currency: row.currency }, installationAmount: { amountMinor: row.installationAmountMinor, currency: row.currency }, otherAmount: { amountMinor: row.otherAmountMinor, currency: row.currency }, totalAmount: { amountMinor: row.totalAmountMinor, currency: row.currency }, supersededAt: optional(row.supersededAt), notes: optional(row.notes) })) as OpsFixture["replacementBenchmarks"],
    assetReplacementOverrides: replacementOverrideRows.map((row) => ({ ...row, sourceBenchmarkId: optional(row.sourceBenchmarkId), amount: { amountMinor: row.amountMinor, currency: row.currency }, supersededAt: optional(row.supersededAt) })) as OpsFixture["assetReplacementOverrides"],
    replacementEvents: replacementEventRows.map((row) => ({ ...row, approvedAmount: { amountMinor: row.approvedAmountMinor, currency: row.currency }, completedAt: optional(row.completedAt), finalAmount: row.finalAmountMinor == null ? undefined : { amountMinor: row.finalAmountMinor, currency: row.currency }, replacementAssetId: optional(row.replacementAssetId) })) as OpsFixture["replacementEvents"],
    lifecycleRecommendations: lifecycleRecommendationRows.map((row) => ({ ...row, workOrderId: optional(row.workOrderId), inputsJson: typeof row.inputsJson === "string" ? row.inputsJson : JSON.stringify(row.inputsJson), missingData: parseStringArray(row.missingDataJson), actualOutcome: optional(row.actualOutcome), actualOutcomeAt: optional(row.actualOutcomeAt), replacementEventId: optional(row.replacementEventId) })) as OpsFixture["lifecycleRecommendations"],
    components: componentRows.map((row) => ({ ...row, parentComponentId: optional(row.parentComponentId), partNumber: optional(row.partNumber), serialNumber: optional(row.serialNumber), installedAt: optional(row.installedAt), warrantyEndsAt: optional(row.warrantyEndsAt), removedAt: optional(row.removedAt), replacedByComponentId: optional(row.replacedByComponentId) })) as OpsFixture["components"],
    componentLifecycleEvents: componentLifecycleEventRows.map((row) => ({ ...row, serialNumber: optional(row.serialNumber), rootCause: optional(row.rootCause), laborCost: { amountMinor: Number(row.laborCostMinor), currency: row.currency }, partCost: { amountMinor: Number(row.partCostMinor), currency: row.currency }, expectedLifeMonths: optional(row.expectedLifeMonths), warrantyEndsAt: optional(row.warrantyEndsAt) })) as OpsFixture["componentLifecycleEvents"],
    maintenancePrograms: maintenanceProgramRows.map((row) => ({ ...row, applicableAssetTypes: parseStringArray(row.applicableAssetTypesJson), scheduleAnchorAt: optional(row.scheduleAnchorAt), seasonalStartMonth: optional(row.seasonalStartMonth), seasonalEndMonth: optional(row.seasonalEndMonth), requiredEvidenceKinds: parseStringArray(row.requiredEvidenceKindsJson), supersedesProgramId: optional(row.supersedesProgramId) })) as OpsFixture["maintenancePrograms"],
    checklistTemplates: checklistTemplateRows.map((row) => ({ ...row, items: parseJsonArray(row.itemsJson) })) as OpsFixture["checklistTemplates"],
    pmPlans: pmPlanRows.map((row) => ({ ...row, programId: optional(row.programId), programVersion: optional(row.programVersion), storeId: optional(row.storeId), assetId: optional(row.assetId), assetSelectionRule: optional(row.assetSelectionRule), categoryKey: optional(row.categoryKey), preferredVendorId: optional(row.preferredVendorId), backupVendorId: optional(row.backupVendorId), contractVersionId: optional(row.contractVersionId), effectiveStartsAt: optional(row.effectiveStartsAt), effectiveEndsAt: optional(row.effectiveEndsAt), accessRequirements: optional(row.accessRequirements), programAuthorizationMinor: optional(row.programAuthorizationMinor), budgetMinor: optional(row.budgetMinor), currency: optional(row.currency), serviceLevelPolicyId: optional(row.serviceLevelPolicyId), schedulingMode: optional(row.schedulingMode), escalationRules: optional(row.escalationRules), cadenceOverrideReason: optional(row.cadenceOverrideReason), cadenceOverriddenAt: optional(row.cadenceOverriddenAt), cadenceOverriddenByMembershipId: optional(row.cadenceOverriddenByMembershipId) })) as OpsFixture["pmPlans"],
    pmOccurrences: pmOccurrenceRows.map((row) => ({ ...row, assetId: optional(row.assetId), workOrderId: optional(row.workOrderId), programId: optional(row.programId), programVersion: optional(row.programVersion), planVersion: optional(row.planVersion), proposedAt: optional(row.proposedAt), committedAt: optional(row.committedAt), completedAt: optional(row.completedAt), result: optional(row.result), exceptionReason: optional(row.exceptionReason), recurrenceKey: optional(row.recurrenceKey), createdAt: optional(row.createdAt) })) as OpsFixture["pmOccurrences"],
    pmWorkItems: pmWorkItemRows.map((row) => ({ ...row, componentId: optional(row.componentId), result: optional(row.result), deficiency: optional(row.deficiency), followUpId: optional(row.followUpId), correctiveWorkOrderId: optional(row.correctiveWorkOrderId), costAllocationMinor: optional(row.costAllocationMinor), completedAt: optional(row.completedAt) })) as OpsFixture["pmWorkItems"],
    checklistResponses: checklistResponseRows.map((row) => ({ ...row, passed: optional(row.passed), numericValue: optional(row.numericValue), textValue: optional(row.textValue), measurementUnit: optional(row.measurementUnit), evidenceFileIds: parseStringArray(row.evidenceFileIdsJson), recordedByActorId: optional(row.recordedByActorId) })) as OpsFixture["checklistResponses"],
    serviceRuns: serviceRunRows.map((row) => ({ ...row, expectedWorkValue: { amountMinor: row.expectedWorkValueMinor, currency: row.currency }, estimatedOpportunity: { amountMinor: row.estimatedOpportunityMinor, currency: row.currency }, requiredQualifications: parseStringArray(row.requiredQualificationsJson), createdByActorId: optional(row.createdByActorId), committedStartsAt: optional(row.committedStartsAt), committedEndsAt: optional(row.committedEndsAt), acceptedAt: optional(row.acceptedAt), completedAt: optional(row.completedAt) })) as OpsFixture["serviceRuns"],
    routeStops: routeStopRows.map((row) => ({ ...row, committedArrivalAt: optional(row.committedArrivalAt), accessRequirements: optional(row.accessRequirements), siteVisitId: optional(row.siteVisitId) })) as OpsFixture["routeStops"],
    serviceRunWorkOrders: serviceRunWorkOrderRows.map((row) => ({ ...row, occurrenceId: optional(row.occurrenceId), removalReason: optional(row.removalReason) })) as OpsFixture["serviceRunWorkOrders"],
    serviceRunResponses: serviceRunResponseRows.map((row) => ({ ...row, requestedStartsAt: optional(row.requestedStartsAt), requestedStopChangesJson: optional(row.requestedStopChangesJson), requestedWorkOrderChangesJson: optional(row.requestedWorkOrderChangesJson), reasonCode: optional(row.reasonCode), reasonDetail: optional(row.reasonDetail), economicImpact: { amountMinor: row.economicImpactMinor, currency: row.currency }, resultingPlanJson: optional(row.resultingPlanJson) })) as OpsFixture["serviceRunResponses"],
    vendorWarrantyProfiles: vendorWarrantyProfileRows.map((row) => ({ ...row, effectiveEndsAt: optional(row.effectiveEndsAt) })) as OpsFixture["vendorWarrantyProfiles"],
    warrantyRules: warrantyRuleRows.map((row) => ({ ...row, contractVersionId: optional(row.contractVersionId), quoteId: optional(row.quoteId), authorizationId: optional(row.authorizationId), tradeKey: optional(row.tradeKey), workType: optional(row.workType), serviceType: optional(row.serviceType), assetType: optional(row.assetType), componentType: optional(row.componentType), manufacturer: optional(row.manufacturer), model: optional(row.model), vendorSuppliedPart: optional(row.vendorSuppliedPart), customerSuppliedPart: optional(row.customerSuppliedPart), regionId: optional(row.regionId), storeId: optional(row.storeId), effectiveEndsAt: optional(row.effectiveEndsAt) })) as OpsFixture["warrantyRules"],
    warrantyCoverageLines: warrantyCoverageLineRows.map((row) => ({ ...row, warrantyRuleId: optional(row.warrantyRuleId), vendorWarrantyProfileId: optional(row.vendorWarrantyProfileId), startDate: optional(row.startDate), endDate: optional(row.endDate), obligatedVendorId: optional(row.obligatedVendorId), deductible: { amountMinor: row.deductibleMinor, currency: row.currency }, maximumCoverage: row.maximumCoverageMinor == null ? undefined : { amountMinor: row.maximumCoverageMinor, currency: row.currency }, conditions: optional(row.conditions), exclusions: optional(row.exclusions) })) as OpsFixture["warrantyCoverageLines"],
    repairItems: repairItemRows.map((row) => ({ ...row, contractVersionId: optional(row.contractVersionId), componentId: optional(row.componentId), removedComponentId: optional(row.removedComponentId), installedComponentId: optional(row.installedComponentId), partManufacturer: optional(row.partManufacturer), partModel: optional(row.partModel), serialNumber: optional(row.serialNumber), verificationDate: optional(row.verificationDate), laborCost: { amountMinor: row.laborCostMinor, currency: row.currency }, partCost: { amountMinor: row.partCostMinor, currency: row.currency }, rootCause: optional(row.rootCause) })) as OpsFixture["repairItems"],
    appliedWarranties: appliedWarrantyRows.map((row) => ({ ...row, obligatedVendorId: optional(row.obligatedVendorId), coveredCharges: parseStringArray(row.coveredChargesJson), contractVersionId: optional(row.contractVersionId), ruleSource: optional(row.ruleSource) })) as OpsFixture["appliedWarranties"],
    warrantyAmendments: warrantyAmendmentRows as OpsFixture["warrantyAmendments"],
    manufacturerWarranties: manufacturerWarrantyRows.map((row) => ({ ...row, componentId: optional(row.componentId), model: optional(row.model), serialNumber: optional(row.serialNumber), authorizedProviderRule: optional(row.authorizedProviderRule), claimRequirements: optional(row.claimRequirements), installingVendorId: optional(row.installingVendorId), administrator: optional(row.administrator), supportingFileId: optional(row.supportingFileId) })) as OpsFixture["manufacturerWarranties"],
    warrantyCases: warrantyCaseRows.map((row) => ({ ...row, requestId: optional(row.requestId), componentId: optional(row.componentId), priorRepairItemId: optional(row.priorRepairItemId), appliedWarrantyId: optional(row.appliedWarrantyId), manufacturerWarrantyId: optional(row.manufacturerWarrantyId), obligatedVendorId: optional(row.obligatedVendorId), vendorResponseDueAt: optional(row.vendorResponseDueAt), closedAt: optional(row.closedAt) })) as OpsFixture["warrantyCases"],
    quotes: quoteRows.map((row) => ({ ...row, contractVersionId: optional(row.contractVersionId), subtotal: { amountMinor: row.subtotalMinor, currency: row.currency }, tax: { amountMinor: row.taxMinor, currency: row.currency }, fees: { amountMinor: row.feesMinor, currency: row.currency }, total: { amountMinor: row.totalMinor, currency: row.currency }, expiresAt: optional(row.expiresAt), supersedesQuoteId: optional(row.supersedesQuoteId) })) as OpsFixture["quotes"],
    authorizations: authorizationRows.map((row) => ({ ...row, authorizedAmount: { amountMinor: row.authorizedAmountMinor, currency: row.currency }, contractVersionId: optional(row.contractVersionId), supersedesAuthorizationId: optional(row.supersedesAuthorizationId) })) as OpsFixture["authorizations"],
    accountingInvoiceSources: accountingInvoiceSourceRows.map((row) => ({ ...row, invoiceId: optional(row.invoiceId) })) as OpsFixture["accountingInvoiceSources"],
    invoices: invoiceV2Rows.map((row) => ({ ...row, contractVersionId: optional(row.contractVersionId), subtotal: { amountMinor: row.subtotalMinor, currency: row.currency }, tax: { amountMinor: row.taxMinor, currency: row.currency }, fees: { amountMinor: row.feesMinor, currency: row.currency }, total: { amountMinor: row.totalMinor, currency: row.currency }, approvedForPayment: { amountMinor: row.approvedForPaymentMinor, currency: row.currency }, paidAmount: { amountMinor: row.paidAmountMinor, currency: row.currency }, exceptionReason: optional(row.exceptionReason), supportingFileId: optional(row.supportingFileId), submittedByMembershipId: optional(row.submittedByMembershipId) })) as OpsFixture["invoices"],
    invoiceLines: invoiceLineRows.map((row) => ({ ...row, unitAmount: { amountMinor: row.unitAmountMinor, currency: row.currency }, lineAmount: { amountMinor: row.lineAmountMinor, currency: row.currency }, contractRateCardLineId: optional(row.contractRateCardLineId) })) as OpsFixture["invoiceLines"],
    invoiceLineAllocations: invoiceLineAllocationRows.map((row) => ({ ...row, workItemId: optional(row.workItemId), repairItemId: optional(row.repairItemId), siteVisitWorkOrderId: optional(row.siteVisitWorkOrderId), assetId: optional(row.assetId), componentId: optional(row.componentId), tradeKey: optional(row.tradeKey), amount: { amountMinor: row.amountMinor, currency: row.currency }, confirmedByMembershipId: optional(row.confirmedByMembershipId), confirmedAt: optional(row.confirmedAt) })) as OpsFixture["invoiceLineAllocations"],
    invoiceExceptions: invoiceExceptionRows.map((row) => ({ ...row, invoiceLineId: optional(row.invoiceLineId), amount: { amountMinor: row.amountMinor, currency: row.currency }, resolvedAt: optional(row.resolvedAt), resolutionReason: optional(row.resolutionReason) })) as OpsFixture["invoiceExceptions"],
    invoiceAdjustments: invoiceAdjustmentRows.map((row) => ({ ...row, amount: { amountMinor: row.amountMinor, currency: row.currency } })) as OpsFixture["invoiceAdjustments"],
    serviceDiscrepancies: serviceDiscrepancyRows.map((row) => ({ ...row, invoiceId: optional(row.invoiceId), siteVisitWorkOrderId: optional(row.siteVisitWorkOrderId), vendorResponse: optional(row.vendorResponse), resolution: optional(row.resolution), resolvedAt: optional(row.resolvedAt) })) as OpsFixture["serviceDiscrepancies"],
    valueEvents: valueEventRows.map((row) => ({ ...row, amount: { amountMinor: row.amountMinor, currency: row.currency }, workOrderId: optional(row.workOrderId), invoiceLineId: optional(row.invoiceLineId), serviceRunId: optional(row.serviceRunId), contractVersionId: optional(row.contractVersionId), warrantyCaseId: optional(row.warrantyCaseId), assetId: optional(row.assetId), approvalDecisionId: optional(row.approvalDecisionId) })) as OpsFixture["valueEvents"],
    costLines: costRows.map((row) => ({ ...row, amount: { amountMinor: row.amountMinor, currency: row.currency } })) as OpsFixture["costLines"],
    invoiceReferences: invoiceRows.map((row) => ({ ...row, grossAmount: { amountMinor: row.grossAmountMinor, currency: row.currency }, operatorWorkOrderNumber: optional(row.operatorWorkOrderNumber) })) as OpsFixture["invoiceReferences"],
    invoiceAllocations: allocationRows.map((row) => ({ ...row, amount: { amountMinor: row.amountMinor, currency: row.currency }, confirmedByMembershipId: optional(row.confirmedByMembershipId), confirmedAt: optional(row.confirmedAt) })) as OpsFixture["invoiceAllocations"],
    auditEvents: auditRows.map((row) => ({ ...row, actorId: optional(row.actorId) })) as OpsFixture["auditEvents"],
    outboxMessages: outboxRows as OpsFixture["outboxMessages"],
    notificationRules: notificationRuleRows.map((row) => ({ ...row, updatedByMembershipId: optional(row.updatedByMembershipId) })) as OpsFixture["notificationRules"],
    publicTokens: tokenRows.map((row) => ({ ...row, usedAt: optional(row.usedAt), revokedAt: optional(row.revokedAt) })) as OpsFixture["publicTokens"],
  };
}
