import type { OpsClock, OpsCommandServices, OpsIdSource } from "./commands";
import { atomicWorkOrderMutation } from "./concurrency";
import { OpsDomainError } from "./errors";
import type { OpsStatement } from "./repository";
import type { ActorContext, InvoiceAdjustment, InvoiceException, InvoiceLineCategory, Money, OpsId, ValueEvent } from "./types";
import { buildCreateTaskStatements,buildWorkflowTaskProjectionStatement,buildWorkflowTaskRecord,isOpenWorkflowTask } from "./workflow-task-commands";

const systemClock: OpsClock = { now: () => new Date().toISOString() };
const randomIds: OpsIdSource = { next: (prefix) => `${prefix}-${crypto.randomUUID()}` };
const reviewerRoles = new Set(["finance_reviewer", "executive"]);
const receiverRoles = new Set(["finance_reviewer", "facilities_admin", "executive"]);
const invoiceLineCategories=new Set<InvoiceLineCategory>(["labor","part","travel","diagnostic","equipment_rental","disposal","permit","tax","other_fee"]);

function services(input: OpsCommandServices) { return { repository: input.repository, clock: input.clock ?? systemClock, ids: input.ids ?? randomIds }; }
function insert(table: string, values: Record<string, unknown>): OpsStatement { const entries=Object.entries(values).filter(([,value])=>value!==undefined); return{sql:`INSERT INTO ${table} (${entries.map(([key])=>key).join(", ")}) VALUES (${entries.map(()=>"?").join(", ")})`,params:entries.map(([,value])=>value)}; }
function required(value:string,label:string){const clean=value.trim();if(!clean)throw new OpsDomainError("VALIDATION",`${label} is required`);return clean;}
function money(value:Money,label:string){if(!Number.isSafeInteger(value.amountMinor)||value.amountMinor<0||!value.currency.trim())throw new OpsDomainError("VALIDATION",`${label} must use non-negative integer minor units and a currency`);return value;}
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes),(byte)=>byte.toString(16).padStart(2,"0")).join("");}
function auditAndOutbox(input:{organizationId:OpsId;aggregateType:string;aggregateId:OpsId;eventType:string;actor:ActorContext;occurredAt:string;payload:unknown;ids:OpsIdSource}){const payloadJson=JSON.stringify(input.payload);return[insert("ops_audit_events",{id:input.ids.next("audit"),organization_id:input.organizationId,aggregate_type:input.aggregateType,aggregate_id:input.aggregateId,event_type:input.eventType,actor_type:input.actor.actorType,actor_id:input.actor.actorId,actor_name:input.actor.actorName,occurred_at:input.occurredAt,payload_json:payloadJson}),insert("ops_outbox_messages",{id:input.ids.next("outbox"),organization_id:input.organizationId,topic:`ops.${input.eventType}`,aggregate_type:input.aggregateType,aggregate_id:input.aggregateId,payload_json:payloadJson,status:"pending",available_at:input.occurredAt,created_at:input.occurredAt,attempt_count:0})];}

export interface ReceiveInvoiceLineInput{category:InvoiceLineCategory;description:string;amount:Money;quantityThousandths?:number}
export interface ReceiveInvoiceFileInput{id:OpsId;storageKey:string;sha256:string;originalName:string;contentType:string;byteLength:number}

/**
 * Receives a source invoice, matches it to one exact Work Order, and records
 * factual review flags. It never deducts, approves payment, or changes the
 * Work Order's operational resolution.
 */
export async function receiveInvoice(input:{organizationId:OpsId;invoiceId?:OpsId;vendorId:OpsId;contractVersionId?:OpsId;workOrderId:OpsId;vendorInvoiceNumber:string;invoiceDate:string;currency:string;lines:ReceiveInvoiceLineInput[];supportingFile?:ReceiveInvoiceFileInput;actor:ActorContext},dependencies:OpsCommandServices){
  const{repository,clock,ids}=services(dependencies);const now=clock.now();
  if(input.actor.organizationId!==input.organizationId||input.actor.actorType!=="user"||!input.actor.actorId)throw new OpsDomainError("FORBIDDEN","An authenticated invoice receiver is required");
  const membership=await repository.getMembership(input.organizationId,input.actor.actorId);if(!membership||membership.status!=="active"||!receiverRoles.has(membership.role))throw new OpsDomainError("FORBIDDEN","Finance, Facilities, or executive access is required to receive an Invoice");
  const [workOrder,vendor,invoices]=await Promise.all([repository.getWorkOrder(input.organizationId,input.workOrderId),repository.getVendor(input.organizationId,input.vendorId),repository.listInvoices(input.organizationId)]);if(!workOrder)throw new OpsDomainError("NOT_FOUND","Work Order not found");if(!vendor||vendor.status==="inactive")throw new OpsDomainError("NOT_FOUND","Approved Vendor not found");
  const invoiceNumber=required(input.vendorInvoiceNumber,"Vendor invoice number");if(invoices.some((invoice)=>invoice.vendorId===vendor.id&&invoice.vendorInvoiceNumber.trim().toLocaleLowerCase("en-US")===invoiceNumber.toLocaleLowerCase("en-US")))throw new OpsDomainError("CONFLICT","This Vendor invoice number has already been received");
  if(!/^\d{4}-\d{2}-\d{2}$/.test(input.invoiceDate)||!Number.isFinite(Date.parse(`${input.invoiceDate}T00:00:00.000Z`)))throw new OpsDomainError("VALIDATION","Invoice date is invalid");const currency=required(input.currency,"Currency").toUpperCase();if(!input.lines.length)throw new OpsDomainError("VALIDATION","At least one Invoice Line is required");
  const cleanLines=input.lines.map((line,index)=>{if(!invoiceLineCategories.has(line.category))throw new OpsDomainError("VALIDATION","Invoice Line category is invalid");money(line.amount,`Invoice Line ${index+1}`);if(line.amount.currency!==currency)throw new OpsDomainError("VALIDATION","All Invoice Lines must use the Invoice currency");const quantity=line.quantityThousandths??1000;if(!Number.isSafeInteger(quantity)||quantity<=0)throw new OpsDomainError("VALIDATION","Invoice Line quantity is invalid");return{...line,description:required(line.description,`Invoice Line ${index+1} description`),quantityThousandths:quantity}});
  const subtotal=cleanLines.filter((line)=>line.category!=="tax"&&line.category!=="other_fee").reduce((sum,line)=>sum+line.amount.amountMinor,0);const tax=cleanLines.filter((line)=>line.category==="tax").reduce((sum,line)=>sum+line.amount.amountMinor,0);const fees=cleanLines.filter((line)=>line.category==="other_fee").reduce((sum,line)=>sum+line.amount.amountMinor,0);const total=subtotal+tax+fees;if(!Number.isSafeInteger(total))throw new OpsDomainError("VALIDATION","Invoice total is outside the supported range");
  const contract=input.contractVersionId?await repository.getContractVersion(input.organizationId,input.contractVersionId):null;if(input.contractVersionId&&(!contract||contract.vendorId!==vendor.id))throw new OpsDomainError("CONFLICT","Contract Version does not belong to the selected Vendor");
  const [authorizations,activeAssignment,warrantyCases,visits,tasks]=await Promise.all([repository.listAuthorizationsForWorkOrder(input.organizationId,workOrder.id),repository.getActiveAssignment(input.organizationId,workOrder.id),repository.listWarrantyCases(input.organizationId),repository.listSiteVisitWorkOrdersForWorkOrder(input.organizationId,workOrder.id),repository.listWorkflowTasksForWorkOrder(input.organizationId,workOrder.id)]);const latestAuthorization=authorizations[0];const rateLines=contract?await repository.listRateCardLines(input.organizationId,contract.id):[];
  const invoiceId=input.invoiceId??ids.next("invoice");
  const statements:OpsStatement[]=[
    insert("ops_invoices",{id:invoiceId,organization_id:input.organizationId,vendor_id:vendor.id,contract_version_id:contract?.id,vendor_invoice_number:invoiceNumber,invoice_date:input.invoiceDate,subtotal_minor:subtotal,tax_minor:tax,fees_minor:fees,total_minor:total,approved_for_payment_minor:0,paid_amount_minor:0,currency,status:"received",supporting_file_id:input.supportingFile?.id,submitted_by_membership_id:membership.id,created_at:now}),
    // The optional safeguard and the spend ledger now share one source id.
    // This keeps invoice review, work-order cost evidence, and drill-throughs
    // from presenting two different invoice universes.
    insert("ops_invoice_references",{id:invoiceId,organization_id:input.organizationId,vendor_id:vendor.id,invoice_number:invoiceNumber,invoice_date:input.invoiceDate,gross_amount_minor:total,currency,operator_work_order_number:workOrder.number,match_status:"confirmed",created_at:now}),
    insert("ops_invoice_allocations",{id:ids.next("invoice-reference-allocation"),organization_id:input.organizationId,invoice_reference_id:invoiceId,work_order_id:workOrder.id,amount_minor:total,currency,confirmed_by_membership_id:membership.id,confirmed_at:now}),
  ];
  if(input.supportingFile){if(!/^[a-f0-9]{64}$/i.test(input.supportingFile.sha256)||!Number.isSafeInteger(input.supportingFile.byteLength)||input.supportingFile.byteLength<1)throw new OpsDomainError("VALIDATION","Invoice file metadata is invalid");statements.unshift(insert("ops_files",{id:input.supportingFile.id,organization_id:input.organizationId,storage_key:required(input.supportingFile.storageKey,"Invoice storage key"),sha256:input.supportingFile.sha256.toLowerCase(),original_name:required(input.supportingFile.originalName,"Invoice file name"),content_type:required(input.supportingFile.contentType,"Invoice content type"),byte_length:input.supportingFile.byteLength,status:"available",created_at:now}));statements.push(insert("ops_entity_files",{id:ids.next("file-link"),organization_id:input.organizationId,file_id:input.supportingFile.id,entity_type:"invoice",entity_id:invoiceId,purpose:"invoice",visibility:"internal",created_at:now}))}
  const lineRecords=cleanLines.map((line,index)=>({id:ids.next("invoice-line"),...line,lineNumber:index+1}));for(const line of lineRecords){statements.push(insert("ops_invoice_lines",{id:line.id,organization_id:input.organizationId,invoice_id:invoiceId,line_number:line.lineNumber,category:line.category,description:line.description,quantity_thousandths:line.quantityThousandths,unit_amount_minor:line.amount.amountMinor,line_amount_minor:line.amount.amountMinor,currency,created_at:now}),insert("ops_invoice_line_allocations",{id:ids.next("invoice-allocation"),organization_id:input.organizationId,invoice_line_id:line.id,work_order_id:workOrder.id,site_visit_work_order_id:visits.at(-1)?.id,asset_id:workOrder.assetId,component_id:workOrder.componentId,store_id:workOrder.storeId,trade_key:workOrder.categoryKey,amount_minor:line.amount.amountMinor,currency,method:"manual",confirmed_by_membership_id:membership.id,confirmed_at:now}))}
  const flags:Array<{kind:InvoiceException["kind"];summary:string;amountMinor:number;lineId?:OpsId;facts:Record<string,unknown>}>=[];if(activeAssignment?.vendorId&&activeAssignment.vendorId!==vendor.id)flags.push({kind:"allocation_mismatch",summary:"Selected Vendor does not match the active Work Order assignment. Confirm the relationship before approval.",amountMinor:total,facts:{assignedVendorId:activeAssignment.vendorId,invoiceVendorId:vendor.id}});if(latestAuthorization&&total>latestAuthorization.authorizedAmount.amountMinor)flags.push({kind:"authorization",summary:"Invoice total exceeds the latest immutable Authorization. Review scope and any Change Order; no deduction has been made.",amountMinor:total-latestAuthorization.authorizedAmount.amountMinor,facts:{authorizationId:latestAuthorization.id,authorizedAmount:latestAuthorization.authorizedAmount,invoiceTotalMinor:total}});if(!latestAuthorization)flags.push({kind:"authorization",summary:"No immutable Authorization is linked to this Work Order. Review authority before payment approval.",amountMinor:total,facts:{authorizationId:null}});
  for(const line of lineRecords.filter((item)=>item.category==="travel")){const tripRates=rateLines.filter((rate)=>rate.chargeType==="trip"&&rate.effectiveStartsAt<=`${input.invoiceDate}T23:59:59.999Z`&&(!rate.effectiveEndsAt||rate.effectiveEndsAt>=`${input.invoiceDate}T00:00:00.000Z`));if(!tripRates.length)flags.push({kind:"unsupported_trip_charge",lineId:line.id,summary:"No matching trip rate was found in the selected Contract Version. Flag for human review of Vendor policy; no deduction has been made.",amountMinor:line.amount.amountMinor,facts:{contractVersionId:contract?.id,tripRateFound:false}});else if(line.amount.amountMinor>Math.max(...tripRates.map((rate)=>rate.amount.amountMinor)))flags.push({kind:"contract_rate",lineId:line.id,summary:"Trip line is above the matching Contract rate. Flag for human review; the billed amount remains unchanged.",amountMinor:line.amount.amountMinor-Math.max(...tripRates.map((rate)=>rate.amount.amountMinor)),facts:{rateCardLineIds:tripRates.map((rate)=>rate.id),billedAmount:line.amount}})}
  const openWarranty=warrantyCases.find((item)=>item.workOrderId===workOrder.id&&item.invoiceHold&&!item.closedAt);if(openWarranty)flags.push({kind:"warranty_hold",summary:"An open Warranty Case requires diagnosis and responsibility review before financial approval.",amountMinor:total,facts:{warrantyCaseId:openWarranty.id,coverageDecision:openWarranty.coverageDecision,customerChargeStatus:openWarranty.customerChargeStatus}});
  const priorInvoiceForWorkOrder=(await Promise.all(invoices.map(async(invoice)=>{
    const priorLines=await repository.listInvoiceLines(input.organizationId,invoice.id);
    const priorAllocations=(await Promise.all(priorLines.map((line)=>repository.listInvoiceLineAllocations(input.organizationId,line.id)))).flat();
    return priorAllocations.some((allocation)=>allocation.workOrderId===workOrder.id)?invoice:undefined;
  }))).find((invoice)=>invoice&&invoice.vendorInvoiceNumber.trim().toLocaleLowerCase("en-US")!==invoiceNumber.toLocaleLowerCase("en-US"));
  if(priorInvoiceForWorkOrder)flags.push({kind:"duplicate_invoice",summary:"Another invoice is already allocated to this exact work order. Confirm this invoice covers separate work, a separate visit, or a valid remaining balance; no deduction has been made.",amountMinor:total,facts:{priorInvoiceId:priorInvoiceForWorkOrder.id,priorVendorInvoiceNumber:priorInvoiceForWorkOrder.vendorInvoiceNumber,priorInvoiceDate:priorInvoiceForWorkOrder.invoiceDate,workOrderId:workOrder.id,matchBasis:"exact_work_order_allocation"}});
  
  for(const flag of flags){const exceptionId=ids.next("invoice-exception");statements.push(insert("ops_invoice_exceptions",{id:exceptionId,organization_id:input.organizationId,invoice_id:invoiceId,invoice_line_id:flag.lineId,kind:flag.kind,status:"open",summary:flag.summary,amount_minor:flag.amountMinor,currency,detected_at:now}),insert("ops_value_events",{id:ids.next("value-event"),organization_id:input.organizationId,category:"identified_exposure",event_type:`invoice_${flag.kind}`,amount_minor:flag.amountMinor,currency,work_order_id:workOrder.id,invoice_line_id:flag.lineId,contract_version_id:contract?.id,warranty_case_id:openWarranty?.id,asset_id:workOrder.assetId,source_decision:"Invoice review flag only; validity, deduction, and payment approval are not determined",deduplication_key:`invoice:${invoiceId}:line:${flag.lineId??"invoice"}:${flag.kind}`,occurred_at:now}),...auditAndOutbox({organizationId:input.organizationId,aggregateType:"invoice",aggregateId:invoiceId,eventType:"invoice.review_flagged",actor:input.actor,occurredAt:now,payload:{kind:flag.kind,lineId:flag.lineId,amountMinor:flag.amountMinor,evidence:flag.facts,reviewOnly:true,deductionCreated:false,approvedForPaymentChanged:false},ids}))}
  if(flags.length){statements.push({sql:"UPDATE ops_invoices SET status = ?, exception_reason = ? WHERE organization_id = ? AND id = ?",params:[openWarranty?"warranty_hold":"exception",`${flags.length} review ${flags.length===1?"flag":"flags"}; no deductions or payment approvals were made`,input.organizationId,invoiceId]});const task=buildWorkflowTaskRecord({id:ids.next("workflow-task"),organizationId:input.organizationId,workOrderId:workOrder.id,actor:input.actor,createdAt:now,draft:{taskType:"resolve_invoice_exception",title:"Review Invoice evidence and flags",reason:`${flags.length} factual Invoice review ${flags.length===1?"flag requires":"flags require"} a human decision`,assigneeType:"role",assigneeRole:"finance_reviewer",assigneeName:"Finance review",priority:"high",blocking:false,requiredForProgress:false,dueAt:new Date(Date.parse(now)+24*60*60_000).toISOString(),applicableSlaClock:"invoice_submission",completionCriteria:"Review source Invoice, Contract Version, Authorization, Visits, warranty evidence, and record an explicit decision for every flag",escalationDestination:"Finance director"}});statements.push(...buildCreateTaskStatements({task,actor:input.actor,ids}),buildWorkflowTaskProjectionStatement(input.organizationId,workOrder.id,[...tasks.filter(isOpenWorkflowTask),task]))}
  statements.push(...auditAndOutbox({organizationId:input.organizationId,aggregateType:"invoice",aggregateId:invoiceId,eventType:"invoice.received",actor:input.actor,occurredAt:now,payload:{workOrderId:workOrder.id,workOrderNumber:workOrder.number,vendorId:vendor.id,contractVersionId:contract?.id,lineCount:lineRecords.length,totalMinor:total,flagCount:flags.length,matchedBy:"exact_operator_work_order",paymentExecuted:false,operationalResolutionChanged:false},ids}));
  if(flags.length)await atomicWorkOrderMutation({repository,workOrder,now,statements});else await repository.atomicWrite(statements);return{invoiceId,total:{amountMinor:total,currency},flagCount:flags.length,status:flags.length?(openWarranty?"warranty_hold":"exception"):"received",paymentExecuted:false,operationalResolutionChanged:false};
}

/**
 * Creates a review fact only. Automated analysis is never authorized to create
 * a deduction, reduce approved-for-payment, or claim realized value.
 */
export async function flagInvoiceReview(input:{organizationId:OpsId;invoiceId:OpsId;invoiceLineId?:OpsId;actor:ActorContext;kind:InvoiceException["kind"];summary:string;amount:Money;evidence:Record<string,unknown>},dependencies:OpsCommandServices){
  const{repository,clock,ids}=services(dependencies);const now=clock.now();const invoice=await repository.getInvoice(input.organizationId,input.invoiceId);if(!invoice)throw new OpsDomainError("NOT_FOUND","Invoice not found");
  if(input.actor.organizationId!==input.organizationId||!["system","user"].includes(input.actor.actorType))throw new OpsDomainError("FORBIDDEN","Invoice safeguard actor is invalid");money(input.amount,"Exception amount");if(input.amount.currency!==invoice.total.currency)throw new OpsDomainError("VALIDATION","Exception currency must match the Invoice");
  const exceptionId=ids.next("invoice-exception");const deduplicationKey=`invoice:${invoice.id}:line:${input.invoiceLineId??"invoice"}:flag:${input.kind}`;
  const valueEventId=ids.next("value-event");
  await repository.atomicWrite([
    insert("ops_invoice_exceptions",{id:exceptionId,organization_id:input.organizationId,invoice_id:invoice.id,invoice_line_id:input.invoiceLineId,kind:input.kind,status:"open",summary:required(input.summary,"Review summary"),amount_minor:input.amount.amountMinor,currency:input.amount.currency,detected_at:now}),
    {sql:"UPDATE ops_invoices SET status = ?, exception_reason = ? WHERE organization_id = ? AND id = ?",params:[input.kind==="warranty_hold"?"warranty_hold":input.kind==="service_discrepancy_hold"?"discrepancy_hold":"exception",input.summary,input.organizationId,invoice.id]},
    insert("ops_value_events",{id:valueEventId,organization_id:input.organizationId,category:"identified_exposure",event_type:`invoice_${input.kind}`,amount_minor:input.amount.amountMinor,currency:input.amount.currency,invoice_line_id:input.invoiceLineId,contract_version_id:invoice.contractVersionId,source_decision:"Automated or analyst review flag only; validity and deduction are not determined",deduplication_key:deduplicationKey,occurred_at:now}),
    ...auditAndOutbox({organizationId:input.organizationId,aggregateType:"invoice",aggregateId:invoice.id,eventType:"invoice.review_flagged",actor:input.actor,occurredAt:now,payload:{exceptionId,invoiceLineId:input.invoiceLineId,kind:input.kind,amount:input.amount,evidence:input.evidence,reviewOnly:true,deductionCreated:false,approvedForPaymentChanged:false,operationalResolutionChanged:false},ids}),
  ]);
  return{exceptionId,valueEventId,status:"open" as const,reviewOnly:true};
}

export type InvoiceReviewDecision="accept_as_billed"|"deduct"|"waive_flag";

/**
 * The only path that may turn a proposed deduction into an adjustment. It
 * requires a separate authenticated reviewer, a reason, and an immutable
 * decision fence; even then it never changes Work Order resolution or pays an
 * invoice.
 */
export async function resolveInvoiceReview(input:{organizationId:OpsId;invoiceId:OpsId;exceptionId:OpsId;actor:ActorContext;decision:InvoiceReviewDecision;reason:string;deductionAmount?:Money},dependencies:OpsCommandServices){
  const{repository,clock,ids}=services(dependencies);const now=clock.now();const invoice=await repository.getInvoice(input.organizationId,input.invoiceId);if(!invoice)throw new OpsDomainError("NOT_FOUND","Invoice not found");
  if(input.actor.organizationId!==input.organizationId||input.actor.actorType!=="user"||!input.actor.actorId)throw new OpsDomainError("FORBIDDEN","An authenticated finance reviewer is required");const membership=await repository.getMembership(input.organizationId,input.actor.actorId);if(!membership||membership.status!=="active"||!reviewerRoles.has(membership.role))throw new OpsDomainError("FORBIDDEN","Finance reviewer or executive access is required");if(invoice.submittedByMembershipId===membership.id)throw new OpsDomainError("FORBIDDEN","The invoice submitter cannot make the financial review decision");
  const exceptions=await repository.listInvoiceExceptions(input.organizationId,invoice.id);const exception=exceptions.find((item)=>item.id===input.exceptionId);if(!exception)throw new OpsDomainError("NOT_FOUND","Invoice exception not found");if(exception.status!=="open")throw new OpsDomainError("CONFLICT","Invoice exception already has a decision");const reason=required(input.reason,"Decision reason");
  const existingAdjustments=await repository.listInvoiceAdjustments(input.organizationId,invoice.id);const existingDeductions=existingAdjustments.filter((item)=>["deduction","credit"].includes(item.kind)).reduce((sum,item)=>sum+item.amount.amountMinor,0);const deduction=input.decision==="deduct"?money(input.deductionAmount??exception.amount,"Deduction amount"):{amountMinor:0,currency:invoice.total.currency};if(deduction.currency!==invoice.total.currency||deduction.amountMinor>exception.amount.amountMinor)throw new OpsDomainError("VALIDATION","Deduction cannot exceed the flagged amount or use another currency");if(input.decision!=="deduct"&&input.deductionAmount)throw new OpsDomainError("VALIDATION","Only an explicit deduct decision may include a deduction amount");
  const remainingOpen=exceptions.filter((item)=>item.id!==exception.id&&item.status==="open");const approvedForPayment=Math.max(0,invoice.total.amountMinor-existingDeductions-deduction.amountMinor);const status=input.decision==="waive_flag"?"waived":"resolved";const fenceKey=`__ops_internal__/invoice-exception:${exception.id}:resolution`;const adjustment:InvoiceAdjustment|undefined=input.decision==="deduct"?{id:ids.next("invoice-adjustment"),organizationId:input.organizationId,invoiceId:invoice.id,kind:"deduction",amount:deduction,reason,createdByMembershipId:membership.id,createdAt:now}:undefined;const valueEvent:ValueEvent|undefined=adjustment?{id:ids.next("value-event"),organizationId:input.organizationId,category:"realized_verified",eventType:exception.kind==="duplicate_invoice"?"duplicate_invoice_prevented":exception.kind==="contract_rate"?"rate_card_violation_corrected":exception.kind==="warranty_hold"?"warranty_credit_received":exception.kind==="unsupported_trip_charge"?"unsupported_trip_charge_rejected":"invoice_deduction_approved",amount:deduction,invoiceLineId:exception.invoiceLineId,contractVersionId:invoice.contractVersionId,sourceDecision:`Human finance decision ${exception.id}`,deduplicationKey:`invoice-exception:${exception.id}:deduction`,occurredAt:now}:undefined;
  const statements:OpsStatement[]=[insert("ops_idempotency_keys",{organization_id:input.organizationId,key:fenceKey,command:"invoice_exception.resolve",result_id:exception.id,request_hash:await sha256(`${exception.id}:${input.decision}:${deduction.amountMinor}`),created_at:now,expires_at:"9999-12-31T23:59:59.999Z"}),{sql:"UPDATE ops_invoice_exceptions SET status = ?, resolved_at = ?, resolution_reason = ? WHERE organization_id = ? AND id = ? AND status = ?",params:[status,now,reason,input.organizationId,exception.id,"open"]}];
  if(adjustment)statements.push(insert("ops_invoice_adjustments",{id:adjustment.id,organization_id:adjustment.organizationId,invoice_id:adjustment.invoiceId,kind:adjustment.kind,amount_minor:adjustment.amount.amountMinor,currency:adjustment.amount.currency,reason:adjustment.reason,created_by_membership_id:adjustment.createdByMembershipId,created_at:adjustment.createdAt}));if(valueEvent)statements.push(insert("ops_value_events",{id:valueEvent.id,organization_id:valueEvent.organizationId,category:valueEvent.category,event_type:valueEvent.eventType,amount_minor:valueEvent.amount.amountMinor,currency:valueEvent.amount.currency,invoice_line_id:valueEvent.invoiceLineId,contract_version_id:valueEvent.contractVersionId,source_decision:valueEvent.sourceDecision,deduplication_key:valueEvent.deduplicationKey,occurred_at:valueEvent.occurredAt}));
  statements.push({sql:"UPDATE ops_invoices SET approved_for_payment_minor = ?, status = ?, exception_reason = ? WHERE organization_id = ? AND id = ?",params:[remainingOpen.length?invoice.approvedForPayment.amountMinor:approvedForPayment,remainingOpen.length?"exception":"approved_for_payment",remainingOpen.length?"Additional review flags remain open":null,input.organizationId,invoice.id]},...auditAndOutbox({organizationId:input.organizationId,aggregateType:"invoice",aggregateId:invoice.id,eventType:"invoice.review_decided",actor:input.actor,occurredAt:now,payload:{exceptionId:exception.id,decision:input.decision,reason,deduction,adjustmentId:adjustment?.id,valueEventId:valueEvent?.id,operationalResolutionChanged:false,paymentExecuted:false,segregationOfDutiesChecked:true},ids}));
  await repository.atomicWrite(statements);return{invoiceId:invoice.id,exceptionId:exception.id,decision:input.decision,adjustment,valueEvent,approvedForPayment:{amountMinor:remainingOpen.length?invoice.approvedForPayment.amountMinor:approvedForPayment,currency:invoice.total.currency},paymentExecuted:false,operationalResolutionChanged:false};
}
