import type { OrganizationScope } from "./repository";
import type { OpsSqlDriver, SqlRow } from "./sql-driver";
import { scopeWhere } from "./sql-scope";
import { dashboardPageBounds } from "./dashboard-query";
import { invoiceRecordSections, validateInvoiceRecordQuery, type InvoiceRecordPage, type InvoiceRecordQuery, type InvoiceRecordRow, type InvoiceRecordHeader } from "./invoice-record-query";

export async function queryInvoiceRecord(driver: OpsSqlDriver, scope: OrganizationScope, invoiceId: string, query: InvoiceRecordQuery): Promise<InvoiceRecordPage> {
  validateInvoiceRecordQuery(query);
  const pg = driver.dialect === "postgres", params: unknown[] = [], stores = scopeWhere(scope, "s", params);
  const bind = (v: unknown) => { params.push(v); return "?"; }, unrestricted = scope.storeIds === undefined && scope.regionIds === undefined;
  const json = pg ? "CASE WHEN s.payload_json IS JSON OBJECT THEN CAST(s.payload_json AS JSONB) ELSE '{}'::jsonb END" : "CASE WHEN json_valid(s.payload_json) THEN s.payload_json ELSE '{}' END";
  const jsonValue = (key: string) => pg ? `(s.payload->'delivery'->>'${key}')` : `json_extract(s.payload,'$.delivery.${key}')`;
  const binary = pg ? 'COLLATE "C"' : "COLLATE BINARY", dateSort = (s: string) => pg ? s : `julianday(${s})`;
  const rowFields = ["id", "kind", "label", "detail", "status", "date", "amount_minor", "currency", "line_id", "line_number", "work_id", "work_number", "work_status", "store_id", "store_number", "visit_id", "visit_date", "unavailable_visit", "actor"];
  const row = (values: Record<string, string>) => rowFields.map(k => `${pg && (k === "date" || k === "visit_date") ? `CAST(${values[k] ?? "NULL"} AS TIMESTAMPTZ)` : values[k] ?? "NULL"} AS ${k}`).join(",");
  const allRows = [
    `SELECT 'items' AS section,${row({ id: "l.id", kind: "'item'", label: "l.description", detail: "l.category", status: "CAST((SELECT COUNT(*) FROM allocations a WHERE a.invoice_line_id=l.id) AS TEXT)||CASE WHEN (SELECT COUNT(*) FROM allocations a WHERE a.invoice_line_id=l.id)=1 THEN ' match' ELSE ' matches' END", date: "l.created_at", amount_minor: "l.line_amount_minor", currency: "l.currency", line_id: "l.id", line_number: "l.line_number" })} FROM lines l`,
    `SELECT 'matches',${row({ id: "a.id", kind: "'match'", label: "a.work_number", detail: "l.description", status: "CASE WHEN a.confirmed_at IS NULL THEN 'Awaiting review' ELSE 'Confirmed match' END", date: "a.confirmed_at", amount_minor: "a.amount_minor", currency: "a.currency", line_id: "l.id", line_number: "l.line_number", work_id: "a.work_order_id", work_number: "a.work_number", work_status: "a.work_status", store_id: "a.store_id", store_number: "a.store_number", visit_id: "a.valid_visit_id", visit_date: "a.visit_date", unavailable_visit: "CASE WHEN a.site_visit_work_order_id IS NOT NULL AND a.valid_visit_id IS NULL THEN 1 ELSE 0 END" })} FROM allocations a JOIN lines l ON l.id=a.invoice_line_id`,
    `SELECT 'evidence',${row({ id: "a.id", kind: "'authorization'", label: "a.authorization_type", detail: "a.authorized_scope", status: "CASE WHEN a.supersedes_authorization_id IS NULL THEN 'Recorded' ELSE 'Amendment' END", date: "a.authorized_at", amount_minor: "a.authorized_amount_minor", currency: "a.currency", work_id: "a.work_order_id", work_number: "w.number", actor: "a.approver_name" })} FROM authorizations a JOIN linked_work w ON w.id=a.work_order_id`,
    `SELECT 'evidence',${row({ id: "c.id", kind: "'warranty'", label: `CASE WHEN c.diagnosis_required=${pg ? "true" : "1"} THEN 'Diagnosis needed' ELSE 'Diagnosis recorded' END`, detail: `CASE WHEN c.invoice_hold=${pg ? "true" : "1"} THEN 'Invoice on hold' ELSE 'No warranty hold' END`, status: "c.coverage_decision", date: "c.created_at", work_id: "c.work_order_id", work_number: "w.number" })} FROM warranties c JOIN linked_work w ON w.id=c.work_order_id`,
    `SELECT 'flags',${row({ id: "e.id", kind: "'flag'", label: "e.kind", detail: "e.summary", status: "e.status", date: "e.detected_at", amount_minor: "e.amount_minor", currency: "e.currency", actor: "e.resolution_reason" })} FROM flags e`,
    `SELECT 'history',${row({ id: "a.id", kind: "'adjustment'", label: "a.kind", detail: "a.reason", status: "'Recorded'", date: "a.created_at", amount_minor: "a.amount_minor", currency: "a.currency", actor: "COALESCE(u.display_name,'Recorded reviewer')" })} FROM adjustments a LEFT JOIN ops_memberships m ON m.organization_id=a.organization_id AND m.id=a.created_by_membership_id LEFT JOIN ops_users u ON u.id=m.user_id`,
    `SELECT 'history',${row({ id: "v.id", kind: "'benefit'", label: "v.event_type", detail: "v.source_decision", status: "'Confirmed benefit'", date: "v.occurred_at", amount_minor: "v.amount_minor", currency: "v.currency" })} FROM benefits v`,
    `SELECT 'history',${row({ id: "e.id", kind: "'audit'", label: "e.event_type", detail: "'Invoice event'", status: "'Recorded'", date: "e.occurred_at", actor: "e.actor_name" })} FROM ops_audit_events e JOIN parent i ON i.organization_id=e.organization_id AND i.id=e.aggregate_id WHERE e.aggregate_type='invoice'`,
    ...(query.accounting && unrestricted ? [`SELECT 'history',${row({ id: "s.id", kind: "'accounting'", label: "'Accounting source'", detail: "s.external_invoice_id", status: "s.match_state", date: "s.updated_at" })} FROM sources s`] : []),
  ].join(" UNION ALL ");
  const ctes = `WITH scoped_stores AS MATERIALIZED (SELECT s.* FROM ops_stores s WHERE ${stores}),
    candidate AS MATERIALIZED (SELECT i.* FROM ops_invoices i WHERE i.organization_id=${bind(scope.organizationId)} AND i.id=${bind(invoiceId)}),
    candidate_lines AS MATERIALIZED (SELECT l.* FROM ops_invoice_lines l JOIN candidate i ON i.organization_id=l.organization_id AND i.id=l.invoice_id),
    candidate_allocations AS MATERIALIZED (SELECT a.* FROM ops_invoice_line_allocations a JOIN candidate_lines l ON l.organization_id=a.organization_id AND l.id=a.invoice_line_id),
    parent AS MATERIALIZED (SELECT i.*,v.id AS valid_vendor_id,v.name AS vendor_name,c.source_agreement_reference,c.version AS agreement_version,
      CASE WHEN i.contract_version_id IS NOT NULL AND c.id IS NULL THEN 1 ELSE 0 END AS unavailable_agreement
      FROM candidate i LEFT JOIN ops_vendors v ON v.organization_id=i.organization_id AND v.id=i.vendor_id
      LEFT JOIN ops_contract_versions c ON c.organization_id=i.organization_id AND c.id=i.contract_version_id AND c.vendor_id=i.vendor_id
      WHERE ${unrestricted ? "1=1" : "EXISTS (SELECT 1 FROM candidate_allocations)"}
      AND NOT EXISTS (SELECT 1 FROM candidate_allocations a WHERE NOT EXISTS (SELECT 1 FROM ops_work_orders w JOIN scoped_stores s ON s.organization_id=w.organization_id AND s.id=w.store_id WHERE w.organization_id=a.organization_id AND w.id=a.work_order_id AND w.store_id=a.store_id))),
    lines AS MATERIALIZED (SELECT l.* FROM candidate_lines l JOIN parent i ON i.id=l.invoice_id),
    allocations AS MATERIALIZED (SELECT a.*,w.number AS work_number,w.status AS work_status,s.store_number,v.id AS valid_visit_id,v.checked_in_at AS visit_date
      FROM candidate_allocations a JOIN lines l ON l.id=a.invoice_line_id JOIN ops_work_orders w ON w.organization_id=a.organization_id AND w.id=a.work_order_id AND w.store_id=a.store_id
      JOIN scoped_stores s ON s.organization_id=a.organization_id AND s.id=a.store_id
      LEFT JOIN ops_site_visit_work_orders vw ON vw.organization_id=a.organization_id AND vw.id=a.site_visit_work_order_id AND vw.work_order_id=a.work_order_id
      LEFT JOIN ops_visit_sessions v ON v.organization_id=a.organization_id AND v.id=vw.visit_id AND v.store_id=a.store_id),
    linked_work AS MATERIALIZED (SELECT w.* FROM ops_work_orders w JOIN parent i ON i.organization_id=w.organization_id WHERE EXISTS (SELECT 1 FROM allocations a WHERE a.work_order_id=w.id)),
    authorizations AS (SELECT a.* FROM ops_authorizations a JOIN linked_work w ON w.organization_id=a.organization_id AND w.id=a.work_order_id),
    warranties AS (SELECT c.* FROM ops_warranty_cases c JOIN linked_work w ON w.organization_id=c.organization_id AND w.id=c.work_order_id),
    flags AS MATERIALIZED (SELECT e.* FROM ops_invoice_exceptions e JOIN parent i ON i.organization_id=e.organization_id AND i.id=e.invoice_id),
    adjustments AS (SELECT a.* FROM ops_invoice_adjustments a JOIN parent i ON i.organization_id=a.organization_id AND i.id=a.invoice_id),
    benefits AS (SELECT v.* FROM ops_value_events v JOIN lines l ON l.organization_id=v.organization_id AND l.id=v.invoice_line_id WHERE v.category='realized_verified' AND (v.work_order_id IS NULL OR EXISTS (SELECT 1 FROM linked_work w WHERE w.id=v.work_order_id))),
    sources AS MATERIALIZED (SELECT s.*,${json} AS payload FROM ops_accounting_invoice_sources s JOIN parent i ON i.organization_id=s.organization_id AND i.id=s.invoice_id),
    match_summary AS (SELECT i.id,CASE WHEN i.status='void' OR EXISTS (SELECT 1 FROM sources s WHERE ${jsonValue("kind")}='bill' AND ${pg ? "s.payload->'delivery'->'maintenance'='false'::jsonb" : "json_type(s.payload,'$.delivery.maintenance')='false'"}) THEN 1 ELSE 0 END AS excluded,
      CASE WHEN NOT EXISTS (SELECT 1 FROM lines l WHERE l.currency<>i.currency) AND COALESCE((SELECT SUM(line_amount_minor) FROM lines),0)=i.total_minor THEN 1 ELSE 0 END AS reconciles,
      COALESCE((SELECT SUM(amount_minor) FROM allocations a WHERE a.confirmed_at IS NOT NULL AND a.amount_minor>0 AND a.currency=i.currency AND (SELECT SUM(x.amount_minor) FROM allocations x WHERE x.invoice_line_id=a.invoice_line_id AND x.confirmed_at IS NOT NULL AND x.amount_minor>0 AND x.currency=i.currency)<=(SELECT l.line_amount_minor FROM lines l WHERE l.id=a.invoice_line_id)),0) AS confirmed_minor FROM parent i),
    supported AS MATERIALIZED (SELECT a.* FROM allocations a CROSS JOIN parent i CROSS JOIN match_summary m WHERE m.excluded=0 AND m.reconciles=1 AND a.confirmed_at IS NOT NULL AND a.amount_minor>0 AND a.currency=i.currency AND (SELECT SUM(x.amount_minor) FROM allocations x WHERE x.invoice_line_id=a.invoice_line_id AND x.confirmed_at IS NOT NULL AND x.amount_minor>0 AND x.currency=i.currency)<=(SELECT l.line_amount_minor FROM lines l WHERE l.id=a.invoice_line_id)),
    all_rows AS MATERIALIZED (${allRows}),
    counts AS (SELECT ${invoiceRecordSections.map(k => `(SELECT COUNT(*) FROM all_rows WHERE section='${k}') AS ${k}_count`).join(",")},(SELECT COUNT(*) FROM flags WHERE status='open') AS open_flags),
    filtered AS (SELECT * FROM all_rows WHERE section=${bind(query.section)}${query.section === "matches" && query.line ? ` AND line_id=${bind(query.line)}` : ""}${query.section === "flags" && query.flag ? ` AND id=${bind(query.flag)}` : ""}${query.section === "flags" && query.open ? " AND status='open'" : ""}${query.section === "matches" && query.match ? ` AND id=${bind(query.match)}` : ""}${query.section === "matches" && query.basis === "linked" ? " AND EXISTS (SELECT 1 FROM supported a WHERE a.id=all_rows.id)" : ""}),
    selected AS (SELECT ${rowFields.map(k => query.section === "items" && query.basis === "unmatched" && k === "amount_minor" ? "CASE WHEN f.amount_minor>COALESCE((SELECT SUM(a.amount_minor) FROM supported a WHERE a.invoice_line_id=f.id),0) THEN f.amount_minor-COALESCE((SELECT SUM(a.amount_minor) FROM supported a WHERE a.invoice_line_id=f.id),0) ELSE 0 END AS amount_minor" : `f.${k}`).join(",")} FROM filtered f${query.section === "items" && query.basis === "unmatched" ? " WHERE (SELECT excluded FROM match_summary)=0 AND f.amount_minor>COALESCE((SELECT SUM(a.amount_minor) FROM supported a WHERE a.invoice_line_id=f.id),0)" : ""}),
    total AS (SELECT COUNT(*) AS total_count FROM selected)`;
  const { limit, offset } = dashboardPageBounds(query);
  const order = query.section === "items" ? "line_number ASC" : `${dateSort("COALESCE(date,'1970-01-01')")} DESC`;
  const sql = `${ctes},visible AS (SELECT * FROM selected ORDER BY ${order},id ${binary},kind ${binary} LIMIT ${bind(limit)} OFFSET ${bind(offset)})
    SELECT i.id AS invoice_id,i.vendor_invoice_number,i.version,i.submitted_by_membership_id,i.invoice_date,i.status AS invoice_status,i.exception_reason,i.valid_vendor_id,i.vendor_name,i.source_agreement_reference,i.agreement_version,i.unavailable_agreement,
      i.total_minor,i.approved_for_payment_minor,i.paid_amount_minor,i.currency AS invoice_currency,m.excluded,m.reconciles,m.confirmed_minor,c.*,t.total_count,
      ${rowFields.map(k => `v.${k} AS row_${k}`).join(",")}
      FROM parent i JOIN match_summary m ON m.id=i.id CROSS JOIN counts c CROSS JOIN total t LEFT JOIN visible v ON 1=1
      ORDER BY ${query.section === "items" ? "v.line_number ASC" : `${dateSort("COALESCE(v.date,'1970-01-01')")} DESC`},v.id ${binary},v.kind ${binary}`;
  const result = await driver.query({ sql, params }), r = result.rows[0];
  if (!r) return { invoice: null, rows: [], totalCount: 0 };
  const optional = (r: SqlRow, key: string) => r[key] == null ? undefined : String(r[key]);
  const iso = (r: SqlRow, key: string) => r[key] == null ? undefined : new Date(String(r[key])).toISOString();
  const currency = String(r.invoice_currency), totalMinor = Number(r.total_minor), excluded = Number(r.excluded) === 1, reconciles = Number(r.reconciles) === 1;
  const linkedMinor = !excluded && reconciles ? Number(r.confirmed_minor) : 0, needsReview = !excluded && (!reconciles || linkedMinor < totalMinor);
  const invoice: InvoiceRecordHeader = { id: String(r.invoice_id), number: String(r.vendor_invoice_number), version: Number(r.version), submittedByMembershipId: optional(r, "submitted_by_membership_id"), date: new Date(String(r.invoice_date)).toISOString().slice(0, 10), status: String(r.invoice_status), reason: optional(r, "exception_reason"), vendorId: optional(r, "valid_vendor_id"), vendorName: optional(r, "vendor_name"), agreement: r.source_agreement_reference == null ? undefined : `${r.source_agreement_reference} · Version ${r.agreement_version}`, unavailableAgreement: Number(r.unavailable_agreement) === 1,
    total: { amountMinor: totalMinor, currency }, approved: { amountMinor: Number(r.approved_for_payment_minor), currency }, paid: { amountMinor: Number(r.paid_amount_minor), currency }, linked: { amountMinor: linkedMinor, currency }, unmatched: { amountMinor: needsReview ? Math.max(0, totalMinor - linkedMinor) : 0, currency }, itemsReconcile: reconciles, reportingState: excluded ? "excluded" : needsReview ? "needs_review" : "matched", counts: Object.fromEntries(invoiceRecordSections.map(k => [k, Number(r[`${k}_count`])])) as InvoiceRecordHeader["counts"], openFlags: Number(r.open_flags) };
  const rows: InvoiceRecordRow[] = result.rows.filter(r => r.row_id != null).map(r => ({ id: String(r.row_id), kind: String(r.row_kind), label: String(r.row_label), detail: String(r.row_detail), status: String(r.row_status), date: iso(r, "row_date"), amount: r.row_amount_minor == null ? undefined : { amountMinor: Number(r.row_amount_minor), currency: String(r.row_currency) }, lineId: optional(r, "row_line_id"), lineNumber: r.row_line_number == null ? undefined : Number(r.row_line_number), workId: optional(r, "row_work_id"), workNumber: optional(r, "row_work_number"), workStatus: optional(r, "row_work_status"), storeId: optional(r, "row_store_id"), storeNumber: optional(r, "row_store_number"), visitId: optional(r, "row_visit_id"), visitDate: iso(r, "row_visit_date"), unavailableVisit: r.row_unavailable_visit == null ? undefined : Number(r.row_unavailable_visit) === 1, actor: optional(r, "row_actor") }));
  return { invoice, rows, totalCount: Number(r.total_count), nextOffset: offset + limit < Number(r.total_count) ? offset + limit : undefined };
}
