import type {OpsFixture} from "./types";
import type {OrganizationScope} from "./repository";
import type {OpsSqlDriver} from "./sql-driver";
import {scopeWhere} from "./sql-scope";
import {latestCapitalPlan} from "./capital-planning";
export interface LifecycleQueueQuery {view:"review"|"history";search?:string;storeId?:string;regionId?:string;category?:string;offset?:number;}
export interface LifecycleQueueRow {id:string;name:string;tag:string;storeId:string;storeNumber:string;storeName:string;problem:string;workId?:string;repairMinor?:number;currency:string;decision?:string;decidedAt?:string;}
export interface LifecycleQueuePage {items:LifecycleQueueRow[];total:number;}
const terminal=["closed","cancelled","completed_pending_review","resolved"];
export function lifecycleQueueFromFixture(f:OpsFixture,scope:OrganizationScope,q:LifecycleQueueQuery):LifecycleQueuePage {
 const stores=f.stores.filter(s=>s.organizationId===scope.organizationId&&(scope.storeIds===undefined||scope.storeIds.includes(s.id))&&(scope.regionIds===undefined||scope.regionIds.includes(s.regionId??""))&&(!q.storeId||s.id===q.storeId)&&(!q.regionId||s.regionId===q.regionId));
 const rows=f.assets.filter(a=>a.organizationId===scope.organizationId&&stores.some(s=>s.id===a.storeId)&&(!q.category||a.categoryKey===q.category)).flatMap(a=>{
  const s=stores.find(s=>s.id===a.storeId)!;
  if(q.search&&![a.name,a.assetTag,s.name,s.storeNumber,s.address1,s.address2,s.city,s.state,s.postalCode,...s.aliases].join(" ").toLowerCase().includes(q.search.toLowerCase()))return [];
  const work=f.workOrders.filter(w=>w.organizationId===scope.organizationId&&w.assetId===a.id&&w.priority!=="planned"&&!f.pmOccurrences.some(p=>p.organizationId===scope.organizationId&&p.workOrderId===w.id)&&w.repairEstimate).sort((x,y)=>y.createdAt.localeCompare(x.createdAt)||y.id.localeCompare(x.id))[0];
  const decision=f.lifecycleRecommendations.filter(l=>l.organizationId===scope.organizationId&&l.assetId===a.id).sort((x,y)=>y.version-x.version)[0];
  const event=f.replacementEvents.filter(e=>e.organizationId===scope.organizationId&&e.assetId===a.id&&e.status!=="cancelled").sort((x,y)=>y.approvedAt.localeCompare(x.approvedAt))[0],plan=latestCapitalPlan(f,scope.organizationId,a.id);
  const resolved=decision&&work&&(decision.workOrderId===work.id||decision.decidedAt>=work.createdAt)&&decision.userDecision!=="investigate";
  if(q.view==="review"?(!work||terminal.includes(work.status)||a.status==="retired"||resolved||event||plan?.status==="planned"):(!decision&&!event&&!plan))return [];
  return [{id:a.id,name:a.name,tag:a.assetTag,storeId:s.id,storeNumber:s.storeNumber,storeName:s.name,problem:work?.problem??"Proactive replacement planning",workId:work?.id,repairMinor:work?.repairEstimate?.amountMinor,currency:work?.repairEstimate?.currency??"USD",decision:event?`Replacement ${event.status}`:plan?plan.status==="planned"?"Replacement planned":"Plan removed":decision?.userDecision,decidedAt:event?.approvedAt??plan?.createdAt??decision?.decidedAt}];
 }).sort((a,b)=>a.storeNumber.localeCompare(b.storeNumber)||a.id.localeCompare(b.id));
 return {items:rows.slice(q.offset??0,(q.offset??0)+25),total:rows.length};
}
export async function queryLifecycleQueue(driver:OpsSqlDriver,scope:OrganizationScope,q:LifecycleQueueQuery):Promise<LifecycleQueuePage> {
 const params:unknown[]=[],clauses=[scopeWhere(scope,"s",params)];
 for(const [value,column] of [[q.storeId,"s.id"],[q.regionId,"s.region_id"],[q.category,"a.category_key"]])if(value){clauses.push(`${column}=?`);params.push(value);}
 if(q.search){clauses.push("(LOWER(a.name) LIKE ? OR LOWER(a.asset_tag) LIKE ? OR s.search_text LIKE ?)");params.push(...Array(3).fill(`%${q.search.toLowerCase()}%`));}
 clauses.push(q.view==="review"?"w.id IS NOT NULL AND w.status NOT IN ('closed','cancelled','completed_pending_review','resolved') AND a.status<>'retired' AND e.id IS NULL AND (p.id IS NULL OR p.status<>'planned') AND NOT (l.id IS NOT NULL AND ((l.work_order_id IS NOT NULL AND l.work_order_id=w.id) OR l.decided_at>=w.created_at) AND l.user_decision<>'investigate')":"(l.id IS NOT NULL OR e.id IS NOT NULL OR p.id IS NOT NULL)");
 const base=`FROM ops_assets a JOIN ops_stores s ON s.organization_id=a.organization_id AND s.id=a.store_id LEFT JOIN ops_work_orders w ON w.organization_id=a.organization_id AND w.id=(SELECT w2.id FROM ops_work_orders w2 WHERE w2.organization_id=a.organization_id AND w2.asset_id=a.id AND w2.priority<>'planned' AND NOT EXISTS(SELECT 1 FROM ops_pm_occurrences pm WHERE pm.organization_id=w2.organization_id AND pm.work_order_id=w2.id) AND w2.repair_estimate_amount_minor IS NOT NULL ORDER BY w2.created_at DESC,w2.id DESC LIMIT 1) LEFT JOIN ops_lifecycle_recommendations l ON l.organization_id=a.organization_id AND l.asset_id=a.id AND l.version=(SELECT MAX(l2.version) FROM ops_lifecycle_recommendations l2 WHERE l2.organization_id=a.organization_id AND l2.asset_id=a.id) LEFT JOIN ops_capital_plans p ON p.organization_id=a.organization_id AND p.asset_id=a.id AND p.version=(SELECT MAX(p2.version) FROM ops_capital_plans p2 WHERE p2.organization_id=a.organization_id AND p2.asset_id=a.id) LEFT JOIN ops_replacement_events e ON e.organization_id=a.organization_id AND e.id=(SELECT e2.id FROM ops_replacement_events e2 WHERE e2.organization_id=a.organization_id AND e2.asset_id=a.id AND e2.status<>'cancelled' ORDER BY e2.approved_at DESC,e2.id DESC LIMIT 1) WHERE ${clauses.join(" AND ")}`;
 const total=Number((await driver.query({sql:`SELECT COUNT(*) AS total ${base}`,params})).rows[0]?.total??0);
 const rows=(await driver.query({sql:`SELECT a.id,a.name,a.asset_tag,a.store_id,s.store_number,s.name AS store_name,w.id AS work_id,w.problem,w.repair_estimate_amount_minor AS repair_minor,w.repair_estimate_currency AS currency,CASE WHEN e.id IS NOT NULL THEN 'Replacement '||e.status WHEN p.id IS NOT NULL THEN CASE WHEN p.status='planned' THEN 'Replacement planned' ELSE 'Plan removed' END ELSE l.user_decision END AS decision,COALESCE(CAST(e.approved_at AS TEXT),p.created_at,CAST(l.decided_at AS TEXT)) AS decided_at ${base} ORDER BY s.store_number,a.id LIMIT 25 OFFSET ?`,params:[...params,Math.max(0,q.offset??0)]})).rows;
 return {total,items:rows.map(r=>({id:String(r.id),name:String(r.name),tag:String(r.asset_tag),storeId:String(r.store_id),storeNumber:String(r.store_number),storeName:String(r.store_name),problem:r.problem?String(r.problem):"Proactive replacement planning",workId:r.work_id?String(r.work_id):undefined,repairMinor:r.repair_minor==null?undefined:Number(r.repair_minor),currency:String(r.currency??"USD"),decision:r.decision?String(r.decision):undefined,decidedAt:r.decided_at?String(r.decided_at):undefined}))};
}
