import { supportedInvoiceAllocationSql } from "./invoice-linking-sql";
import type { OrganizationScope } from "./repository";
import type { OpsSqlDriver,SqlRow } from "./sql-driver";
import { scopeWhere } from "./sql-scope";
import { pmScheduleScope } from "./pm-schedule-query";
import { dashboardPageBounds } from "./dashboard-query";
import { validatePmReviewQuery,type PmReviewQuery,type PmReviewPage,type PmReviewRow,type PmReviewSourceRow } from "./pm-review-query";

export async function queryPmReview(driver:OpsSqlDriver,scope:OrganizationScope,query:PmReviewQuery):Promise<PmReviewPage>{
  validatePmReviewQuery(query);
  const pg=driver.dialect==="postgres",params:unknown[]=[],bind=(v:unknown)=>{params.push(v);return "?";};
  const scoped=scopeWhere(pmScheduleScope(scope,query),"s",params),binary=pg?'COLLATE "C"':"COLLATE BINARY",instant=(s:string)=>pg?s:`julianday(${s})`;
  const json=pg?"CASE WHEN d.facts_json IS JSON OBJECT THEN CAST(d.facts_json AS JSONB) ELSE '{}'::jsonb END":"CASE WHEN json_valid(d.facts_json) THEN d.facts_json ELSE '{}' END";
  const value=(key:string)=>pg?`CASE WHEN jsonb_typeof(c.facts->'${key}')='string' THEN c.facts->>'${key}' END`:`CASE WHEN json_type(c.facts,'$.${key}')='text' THEN json_extract(c.facts,'$.${key}') END`;
  const reviewFilter=query.review?` AND c.id=${bind(query.review)}`:"",programFilter=query.program?` AND g.id=${bind(query.program)}`:"";
  const refs=(key:string,kind:string)=>{
    const array=pg?`CASE WHEN jsonb_typeof(r.facts->'${key}')='array' THEN r.facts->'${key}' ELSE '[]'::jsonb END`:`CASE WHEN json_type(r.facts,'$.${key}')='array' THEN json_extract(r.facts,'$.${key}') ELSE '[]' END`;
    return `SELECT r.id AS review_id,'${kind}' AS kind,${pg?"v.value#>>'{}'":"CAST(v.value AS TEXT)"} AS ref_id FROM parents r CROSS JOIN ${pg?`jsonb_array_elements(${array}) v(value)`:`json_each(${array}) v`} WHERE ${pg?"jsonb_typeof(v.value)='string' AND (v.value#>>'{}')<>''":"v.type='text' AND CAST(v.value AS TEXT)<>''"}`;
  };
  const ctes=`WITH scoped_stores AS MATERIALIZED (SELECT s.* FROM ops_stores s WHERE ${scoped}),
    scoped_work AS MATERIALIZED (SELECT w.* FROM ops_work_orders w JOIN scoped_stores s ON s.organization_id=w.organization_id AND s.id=w.store_id),
    candidates AS MATERIALIZED (SELECT d.*,w.store_id,s.store_number,s.name AS store_name,${json} AS facts FROM ops_service_discrepancies d JOIN scoped_work w ON w.organization_id=d.organization_id AND w.id=d.work_order_id JOIN scoped_stores s ON s.id=w.store_id WHERE d.status NOT IN ('resolved','closed')),
    parents AS MATERIALIZED (SELECT c.*,g.id AS program_id,g.name AS program_name,COALESCE(${value("periodLabel")},'Recorded review period') AS period_label FROM candidates c JOIN ops_maintenance_programs g ON g.organization_id=c.organization_id AND g.id=${value("programId")}
      WHERE ${value("reconciliationKind")}='pm_billed_vs_observed' AND ${value("storeId")}=c.store_id${reviewFilter}${programFilter}
      AND EXISTS (SELECT 1 FROM ops_pm_occurrences o JOIN ops_pm_plans p ON p.organization_id=o.organization_id AND p.id=o.plan_id AND (p.store_id IS NULL OR p.store_id=o.store_id) WHERE o.organization_id=c.organization_id AND o.store_id=c.store_id AND o.work_order_id=c.work_order_id AND p.program_id=g.id)),
    refs AS MATERIALIZED (SELECT DISTINCT review_id,kind,ref_id FROM (${refs("billedInvoiceIds","invoice")} UNION ALL ${refs("missingOccurrenceIds","occurrence")} UNION ALL ${refs("observedVisitIds","visit")} UNION ALL SELECT id,'invoice',invoice_id FROM parents WHERE invoice_id IS NOT NULL) input_refs),
    program_occurrences AS MATERIALIZED (SELECT r.id AS review_id,o.* FROM parents r JOIN ops_pm_occurrences o ON o.organization_id=r.organization_id AND o.store_id=r.store_id JOIN scoped_work w ON w.organization_id=o.organization_id AND w.id=o.work_order_id AND w.store_id=o.store_id JOIN ops_pm_plans p ON p.organization_id=o.organization_id AND p.id=o.plan_id AND (p.store_id IS NULL OR p.store_id=o.store_id) AND p.program_id=r.program_id),
    valid_invoices AS MATERIALIZED (SELECT r.id AS review_id,i.* FROM parents r JOIN refs f ON f.review_id=r.id AND f.kind='invoice' JOIN ops_invoices i ON i.organization_id=r.organization_id AND i.id=f.ref_id
      WHERE EXISTS (SELECT 1 FROM ops_invoice_lines l JOIN ops_invoice_line_allocations a ON a.organization_id=l.organization_id AND a.invoice_line_id=l.id WHERE l.organization_id=i.organization_id AND l.invoice_id=i.id)
      AND NOT EXISTS (SELECT 1 FROM ops_invoice_lines l JOIN ops_invoice_line_allocations a ON a.organization_id=l.organization_id AND a.invoice_line_id=l.id WHERE l.organization_id=i.organization_id AND l.invoice_id=i.id AND (a.store_id<>r.store_id OR NOT EXISTS (SELECT 1 FROM scoped_work w WHERE w.organization_id=a.organization_id AND w.id=a.work_order_id AND w.store_id=r.store_id)))
      AND EXISTS (SELECT 1 FROM ops_invoice_lines l JOIN ops_invoice_line_allocations a ON a.organization_id=l.organization_id AND a.invoice_line_id=l.id WHERE l.organization_id=i.organization_id AND l.invoice_id=i.id AND EXISTS (SELECT 1 FROM program_occurrences o WHERE o.review_id=r.id AND o.work_order_id=a.work_order_id))),
    invoice_allocations AS MATERIALIZED (SELECT i.review_id,i.id AS invoice_id,a.*,i.currency AS invoice_currency,CASE WHEN ${supportedInvoiceAllocationSql(pg,"i","l","a")} THEN a.amount_minor ELSE 0 END AS linked_minor FROM valid_invoices i JOIN ops_invoice_lines l ON l.organization_id=i.organization_id AND l.invoice_id=i.id JOIN ops_invoice_line_allocations a ON a.organization_id=l.organization_id AND a.invoice_line_id=l.id WHERE EXISTS (SELECT 1 FROM program_occurrences o WHERE o.review_id=i.review_id AND o.work_order_id=a.work_order_id)),
    cohort_occurrences AS MATERIALIZED (SELECT o.* FROM program_occurrences o WHERE EXISTS (SELECT 1 FROM invoice_allocations a WHERE a.review_id=o.review_id AND a.work_order_id=o.work_order_id) OR EXISTS (SELECT 1 FROM refs f WHERE f.review_id=o.review_id AND f.kind='occurrence' AND f.ref_id=o.id)),
    cohort_visits AS MATERIALIZED (SELECT r.id AS review_id,v.* FROM parents r JOIN ops_visit_sessions v ON v.organization_id=r.organization_id AND v.store_id=r.store_id WHERE EXISTS (SELECT 1 FROM cohort_occurrences o WHERE o.review_id=r.id AND (o.work_order_id=v.work_order_id OR EXISTS (SELECT 1 FROM ops_site_visit_work_orders l WHERE l.organization_id=v.organization_id AND l.visit_id=v.id AND l.work_order_id=o.work_order_id)))),
    visited_work AS MATERIALIZED (SELECT DISTINCT o.review_id,o.work_order_id FROM cohort_occurrences o WHERE EXISTS (SELECT 1 FROM cohort_visits v WHERE v.review_id=o.review_id AND (v.work_order_id=o.work_order_id OR EXISTS (SELECT 1 FROM ops_site_visit_work_orders l WHERE l.organization_id=o.organization_id AND l.visit_id=v.id AND l.work_order_id=o.work_order_id)))),
    allocation_facts AS MATERIALIZED (SELECT a.*,CASE WHEN EXISTS (SELECT 1 FROM visited_work w WHERE w.review_id=a.review_id AND w.work_order_id=a.work_order_id) THEN 0 ELSE 1 END AS missing FROM invoice_allocations a),
    amounts AS MATERIALIZED (SELECT review_id,CASE WHEN COUNT(DISTINCT invoice_currency)=1 THEN MIN(invoice_currency) END AS currency,CASE WHEN COUNT(DISTINCT invoice_currency)=1 THEN SUM(linked_minor) END AS amount_minor,CASE WHEN COUNT(DISTINCT invoice_currency)=1 THEN SUM(CASE WHEN missing=1 THEN linked_minor ELSE 0 END) END AS missing_amount_minor FROM allocation_facts GROUP BY review_id),
    review_rows AS MATERIALIZED (SELECT r.id AS review_id,r.store_id,r.store_number,r.store_name,r.program_id,r.program_name,r.created_at,r.period_label,m.currency,m.amount_minor,m.missing_amount_minor,
      (SELECT COUNT(*) FROM valid_invoices i WHERE i.review_id=r.id) AS invoice_count,(SELECT COUNT(*) FROM cohort_visits v WHERE v.review_id=r.id) AS visit_count,
      (SELECT COUNT(*) FROM cohort_occurrences o WHERE o.review_id=r.id) AS occurrence_count,(SELECT COUNT(*) FROM cohort_occurrences o WHERE o.review_id=r.id AND NOT EXISTS (SELECT 1 FROM visited_work w WHERE w.review_id=o.review_id AND w.work_order_id=o.work_order_id)) AS missing_count,
      (SELECT COUNT(*) FROM refs f WHERE f.review_id=r.id AND ((f.kind='invoice' AND NOT EXISTS (SELECT 1 FROM valid_invoices i WHERE i.review_id=r.id AND i.id=f.ref_id)) OR (f.kind='occurrence' AND NOT EXISTS (SELECT 1 FROM program_occurrences o WHERE o.review_id=r.id AND o.id=f.ref_id)) OR (f.kind='visit' AND NOT EXISTS (SELECT 1 FROM cohort_visits v WHERE v.review_id=r.id AND v.id=f.ref_id)))) AS unavailable_links
      FROM parents r LEFT JOIN amounts m ON m.review_id=r.id)`;
  const fields=["review_id","store_id","store_number","store_name","program_id","program_name","created_at","period_label","currency","amount_minor","missing_amount_minor","invoice_count","visit_count","occurrence_count","missing_count","unavailable_links"];
  const sourceFields=["source_id","source_label","source_detail","source_date","source_status","source_currency","source_amount","work_id","work_number"];
  const sourceSelect=(v:Record<string,string>)=>sourceFields.map(key=>`${v[key]??"NULL"} AS ${key}`).join(",");
  let selected:string;
  if(query.kind==="reviews")selected="SELECT * FROM review_rows";
  else if(query.kind==="invoices")selected=`SELECT ${sourceSelect({source_id:"i.id",source_label:"i.vendor_invoice_number",source_detail:"'Linked invoice amount'",source_date:"i.invoice_date",source_status:"i.status",source_currency:"CASE WHEN COUNT(DISTINCT a.invoice_currency)=1 THEN MIN(a.invoice_currency) END",source_amount:"CASE WHEN COUNT(DISTINCT a.invoice_currency)=1 THEN SUM(a.linked_minor) END"})} FROM valid_invoices i JOIN allocation_facts a ON a.review_id=i.review_id AND a.invoice_id=i.id${query.missing?" WHERE a.missing=1":""} GROUP BY i.id,i.vendor_invoice_number,i.invoice_date,i.status`;
  else if(query.kind==="occurrences")selected=`SELECT ${sourceSelect({source_id:"o.id",source_label:"w.number",source_detail:"r.program_name",source_date:"o.due_at",source_status:"CASE WHEN v.work_order_id IS NULL THEN 'No visit recorded' ELSE 'Visit recorded' END",work_id:"w.id",work_number:"w.number"})} FROM cohort_occurrences o JOIN scoped_work w ON w.organization_id=o.organization_id AND w.id=o.work_order_id JOIN review_rows r ON r.review_id=o.review_id LEFT JOIN visited_work v ON v.review_id=o.review_id AND v.work_order_id=o.work_order_id${query.missing?" WHERE v.work_order_id IS NULL":""}`;
  else selected=`SELECT ${sourceSelect({source_id:"v.id",source_label:"v.technician_name",source_detail:"COALESCE(v.provider_name,v.purpose)",source_date:"v.checked_in_at",source_status:"v.status"})} FROM cohort_visits v`;
  const {limit,offset}=dashboardPageBounds(query),review=query.kind==="reviews",order=review?`${instant("created_at")} DESC,review_id ${binary}`:`${instant("source_date")} DESC,source_id ${binary}`;
  const sql=`${ctes},selected AS (${selected}),total AS (SELECT COUNT(*) AS total_count FROM selected),visible AS (SELECT * FROM selected ORDER BY ${order} LIMIT ${bind(limit)} OFFSET ${bind(offset)})
    ${review?`SELECT v.*,t.total_count FROM total t LEFT JOIN visible v ON 1=1 ORDER BY ${instant("v.created_at")} DESC,v.review_id ${binary}`:`SELECT ${fields.map(k=>`r.${k}`).join(",")},${sourceFields.map(k=>`v.${k}`).join(",")},t.total_count FROM total t LEFT JOIN review_rows r ON 1=1 LEFT JOIN visible v ON 1=1 ORDER BY ${instant("v.source_date")} DESC,v.source_id ${binary}`}`;
  const result=await driver.query({sql,params}),first=result.rows[0]??{},totalCount=Number(first.total_count??0),optional=(r:SqlRow,k:string)=>r[k]==null?undefined:String(r[k]);
  const map=(r:SqlRow):PmReviewRow=>({id:String(r.review_id),storeId:String(r.store_id),storeNumber:String(r.store_number),storeName:String(r.store_name),programId:String(r.program_id),programName:String(r.program_name),createdAt:new Date(String(r.created_at)).toISOString(),periodLabel:String(r.period_label),invoiceCount:Number(r.invoice_count),visitCount:Number(r.visit_count),occurrenceCount:Number(r.occurrence_count),missingCount:Number(r.missing_count),unavailableLinks:Number(r.unavailable_links),currency:optional(r,"currency"),amountMinor:r.amount_minor==null?undefined:Number(r.amount_minor),missingAmountMinor:r.missing_amount_minor==null?undefined:Number(r.missing_amount_minor)});
  const sources:PmReviewSourceRow[]=review?[]:result.rows.filter(r=>r.source_id!=null).map(r=>({id:String(r.source_id),label:String(r.source_label),detail:String(r.source_detail),date:query.kind==="invoices"?new Date(String(r.source_date)).toISOString().slice(0,10):new Date(String(r.source_date)).toISOString(),status:String(r.source_status),currency:optional(r,"source_currency"),amountMinor:r.source_amount==null?undefined:Number(r.source_amount),workId:optional(r,"work_id"),workNumber:optional(r,"work_number")}));
  return {reviews:review?result.rows.filter(r=>r.review_id!=null).map(map):[],sources,parent:!review&&first.review_id!=null?map(first):null,totalCount,nextOffset:offset+limit<totalCount?offset+limit:undefined};
}
