import type { OpsRepository, OpsStatement } from "./repository";
import type { OpsFixture } from "./types";
import { assertOpsFixture } from "./fixtures";

function insert(table: string, value: Record<string, unknown>): OpsStatement {
  const entries = Object.entries(value).filter(([, item]) => item !== undefined);
  return { sql: `INSERT OR IGNORE INTO ${table} (${entries.map(([key]) => key).join(", ")}) VALUES (${entries.map(() => "?").join(", ")})`, params: entries.map(([, item]) => item) };
}

export function buildOpsSeedStatements(fixture: OpsFixture): OpsStatement[] {
  assertOpsFixture(fixture);
  const statements: OpsStatement[] = [];
  const push = (table: string, rows: Record<string, unknown>[]) => rows.forEach((row) => statements.push(insert(table, row)));
  push("ops_organizations", fixture.organizations.map((row) => ({ id: row.id, name: row.name, slug: row.slug, time_zone: row.timeZone, work_order_prefix: row.workOrderPrefix, created_at: row.createdAt })));
  push("ops_divisions", fixture.divisions.map((row) => ({ id: row.id, organization_id: row.organizationId, code: row.code, name: row.name, created_at: row.createdAt })));
  push("ops_regions", fixture.regions.map((row) => ({ id: row.id, organization_id: row.organizationId, division_id: row.divisionId, code: row.code, name: row.name, created_at: row.createdAt })));
  push("ops_taxonomy_nodes", fixture.taxonomyNodes.map((row) => ({ id: row.id, organization_id: row.organizationId, parent_node_id: row.parentNodeId, node_kind: row.nodeKind, canonical_key: row.canonicalKey, name: row.name, aliases_json: JSON.stringify(row.aliases), depth: row.depth, sort_order: row.sortOrder, active: row.active ? 1 : 0, created_at: row.createdAt })));
  push("ops_equipment_templates", fixture.equipmentTemplates.map((row) => ({ id: row.id, organization_id: row.organizationId, taxonomy_node_id: row.taxonomyNodeId, name: row.name, default_expected_life_years: row.defaultExpectedLifeYears, active: row.active ? 1 : 0, created_at: row.createdAt })));
  push("ops_component_templates", fixture.componentTemplates.map((row) => ({ id: row.id, organization_id: row.organizationId, equipment_template_id: row.equipmentTemplateId, parent_component_template_id: row.parentComponentTemplateId, name: row.name, sort_order: row.sortOrder, created_at: row.createdAt })));
  push("ops_stores", fixture.stores.map((row) => ({ id: row.id, organization_id: row.organizationId, division_id: row.divisionId, region_id: row.regionId, store_number: row.storeNumber, name: row.name, address_1: row.address1, address_2: row.address2, city: row.city, state: row.state, postal_code: row.postalCode, aliases_json: JSON.stringify(row.aliases), search_text: [row.storeNumber,row.name,row.address1,row.address2,row.city,row.state,row.postalCode,...row.aliases].filter(Boolean).join(" ").toLocaleLowerCase("en-US"), latitude_e6: row.latitudeE6, longitude_e6: row.longitudeE6, geofence_radius_m: row.geofenceRadiusM, location_policy_enabled: row.locationPolicyEnabled ? 1 : 0, time_zone: row.timeZone, status: row.status, created_at: row.createdAt })));
  push("ops_users", fixture.users.map((row) => ({ id: row.id, email: row.email, display_name: row.displayName, status: row.status, created_at: row.createdAt })));
  push("ops_memberships", fixture.memberships.map((row) => ({ id: row.id, organization_id: row.organizationId, user_id: row.userId, role: row.role, status: row.status, created_at: row.createdAt })));
  push("ops_scope_grants", fixture.scopeGrants.map((row) => ({ id: row.id, organization_id: row.organizationId, membership_id: row.membershipId, scope_kind: row.scopeKind, scope_id: row.scopeId, permission: row.permission, created_at: row.createdAt })));
  push("ops_vendors", fixture.vendors.map((row) => ({ id: row.id, organization_id: row.organizationId, code: row.code, name: row.name, dispatch_email: row.dispatchEmail, dispatch_phone: row.dispatchPhone, status: row.status, preferred: row.preferred ? 1 : 0, search_text: [row.name,...fixture.vendorSpecialties.filter((item) => item.organizationId === row.organizationId && item.vendorId === row.id).flatMap((item) => [item.displayName,...item.searchAliases])].join(" ").toLocaleLowerCase("en-US"), created_at: row.createdAt })));
  push("ops_vendor_reminders", fixture.vendorReminders.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, title: row.title, note: row.note, accountable_party: row.accountableParty, due_at: row.dueAt, escalation_to: row.escalationTo, status: row.status, created_by_actor_type: row.createdByActorType, created_by_actor_id: row.createdByActorId, created_by_actor_name: row.createdByActorName, created_at: row.createdAt, completed_by_actor_type: row.completedByActorType, completed_by_actor_id: row.completedByActorId, completed_by_actor_name: row.completedByActorName, completed_at: row.completedAt, completion_note: row.completionNote })));
  push("ops_vendor_specialties", fixture.vendorSpecialties.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, canonical_key: row.canonicalKey, display_name: row.displayName, search_aliases_json: JSON.stringify(row.searchAliases) })));
  push("ops_vendor_coverage", fixture.vendorCoverage.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, scope_kind: row.scopeKind, scope_id: row.scopeId, preferred_rank: row.preferredRank })));
  push("ops_vendor_qualifications", fixture.vendorQualifications.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, trade_key: row.tradeKey, work_type: row.workType, service_type: row.serviceType, asset_type: row.assetType, component_type: row.componentType, pm_work: row.pmWork ? 1 : 0, emergency_response: row.emergencyResponse ? 1 : 0, warranty_work: row.warrantyWork ? 1 : 0, manufacturer_authorization: row.manufacturerAuthorization, region_id: row.regionId, store_id: row.storeId, after_hours: row.afterHours ? 1 : 0, maximum_job_amount_minor: row.maximumJobAmount?.amountMinor, currency: row.maximumJobAmount?.currency, required_license: row.requiredLicense, required_certification: row.requiredCertification, effective_at: row.effectiveAt, expires_at: row.expiresAt, status: row.status, created_at: row.createdAt })));
  push("ops_vendor_compliance_documents", fixture.vendorComplianceDocuments.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, document_type: row.documentType, issuer: row.issuer, reference: row.reference, effective_at: row.effectiveAt, expires_at: row.expiresAt, review_status: row.reviewStatus, blocking: row.blocking ? 1 : 0, stored_file_id: row.storedFileId, created_at: row.createdAt })));
  push("ops_vendor_compliance_alerts", (fixture.vendorComplianceAlerts ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, document_id: row.documentId, stage: row.stage, expires_at: row.expiresAt, reminder_id: row.reminderId, created_at: row.createdAt })));
  push("ops_vendor_contracts", fixture.vendorContracts.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, name: row.name, owner_membership_id: row.ownerMembershipId, status: row.status, created_at: row.createdAt })));
  push("ops_contract_versions", fixture.contractVersions.map((row) => ({ id: row.id, organization_id: row.organizationId, contract_id: row.contractId, vendor_id: row.vendorId, version: row.version, source_agreement_reference: row.sourceAgreementReference, status: row.status, effective_starts_at: row.effectiveStartsAt, effective_ends_at: row.effectiveEndsAt, renewal_at: row.renewalAt, notice_days: row.noticeDays, price_escalation_at: row.priceEscalationAt, supersedes_contract_version_id: row.supersedesContractVersionId, currency: row.currency, preferred_provider: row.preferredProvider ? 1 : 0, exclusive_provider: row.exclusiveProvider ? 1 : 0, reactive_work_allowed: row.reactiveWorkAllowed ? 1 : 0, emergency_work_allowed: row.emergencyWorkAllowed ? 1 : 0, pm_work_allowed: row.pmWorkAllowed ? 1 : 0, subcontractor_policy: row.subcontractorPolicy, scheduling_mode: row.schedulingMode, reserved_capacity_minutes: row.reservedCapacityMinutes, nte_amount_minor: row.nteAmount?.amountMinor, materials_markup_bps: row.materialsMarkupBps, route_discount_bps: row.routeDiscountBps, evidence_requirements_json: JSON.stringify(row.evidenceRequirements), compliance_requirements_json: JSON.stringify(row.complianceRequirements), warranty_labor_days: row.warrantyLaborDays, warranty_parts_days: row.warrantyPartsDays, warranty_travel_days: row.warrantyTravelDays, created_by_membership_id: row.createdByMembershipId, created_at: row.createdAt })));
  push("ops_contract_scopes", fixture.contractScopes.map((row) => ({ id: row.id, organization_id: row.organizationId, contract_version_id: row.contractVersionId, scope_kind: row.scopeKind, scope_id: row.scopeId, included: row.included ? 1 : 0 })));
  push("ops_rate_card_lines", fixture.rateCardLines.map((row) => ({ id: row.id, organization_id: row.organizationId, contract_version_id: row.contractVersionId, charge_type: row.chargeType, description: row.description, unit: row.unit, amount_minor: row.amount.amountMinor, currency: row.amount.currency, effective_starts_at: row.effectiveStartsAt, effective_ends_at: row.effectiveEndsAt })));
  push("ops_service_level_policies", fixture.serviceLevelPolicies.map((row) => ({ id: row.id, organization_id: row.organizationId, contract_version_id: row.contractVersionId, priority: row.priority, response_minutes: row.responseMinutes, arrival_minutes: row.arrivalMinutes, completion_minutes: row.completionMinutes, calendar: row.calendar })));
  push("ops_scheduling_policies", fixture.schedulingPolicies.map((row) => ({ id: row.id, organization_id: row.organizationId, contract_version_id: row.contractVersionId, maximum_route_minutes: row.maximumRouteMinutes, maximum_stores: row.maximumStores, maximum_travel_minutes: row.maximumTravelMinutes, maximum_utilization_bps: row.maximumUtilizationBps, per_stop_buffer_minutes: row.perStopBufferMinutes, travel_buffer_bps: row.travelBufferBps, documentation_buffer_minutes: row.documentationBufferMinutes, uncertainty_buffer_bps: row.uncertaintyBufferBps, emergency_reserve_minutes: row.emergencyReserveMinutes })));
  push("ops_vendor_capacity", fixture.vendorCapacity.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, region_id: row.regionId, trade_key: row.tradeKey, starts_at: row.startsAt, ends_at: row.endsAt, crew_minutes: row.crewMinutes, committed_minutes: row.committedMinutes, maximum_route_minutes: row.maximumRouteMinutes, maximum_stores: row.maximumStores, maximum_travel_minutes: row.maximumTravelMinutes, blackout: row.blackout ? 1 : 0, emergency_reserve_minutes: row.emergencyReserveMinutes, variable_work_limit_minutes: row.variableWorkLimitMinutes, special_equipment_json: JSON.stringify(row.specialEquipment), created_at: row.createdAt })));
  push("ops_requests", fixture.requests.map((row) => ({ id: row.id, organization_id: row.organizationId, reference: row.reference, store_id: row.storeId, reporter_name: row.reporterName, reporter_employee_id: row.reporterEmployeeId, problem: row.problem, priority: row.priority, status: row.status, version: row.version ?? 0, submitted_at: row.submittedAt, acknowledged_at: row.acknowledgedAt, acknowledged_by_actor_type: row.acknowledgedByActorType, acknowledged_by_actor_id: row.acknowledgedByActorId, acknowledged_by_actor_name: row.acknowledgedByActorName, linked_work_order_id: row.linkedWorkOrderId, linked_at: row.linkedAt, linked_by_actor_type: row.linkedByActorType, linked_by_actor_id: row.linkedByActorId, linked_by_actor_name: row.linkedByActorName, converted_work_order_id: row.convertedWorkOrderId })));
  push("ops_request_impact_assessments", fixture.requestImpactAssessments.map((row) => ({ id: row.id, organization_id: row.organizationId, request_id: row.requestId, store_id: row.storeId, assessment_kind: row.assessmentKind, review_disposition: row.reviewDisposition, store_operating_state: row.storeOperatingState, safety_concern: row.safetyConcern, product_inventory_risk: row.productInventoryRisk, product_inventory_value_minor: row.productInventoryValue?.amountMinor, product_inventory_currency: row.productInventoryValue?.currency, customers_affected: row.customersAffected, compliance_impact: row.complianceImpact, capacity_unavailable_bps: row.capacityUnavailableBps, redundant_equipment: row.redundantEquipment, revenue_function_impact: row.revenueFunctionImpact, estimated_daily_revenue_exposure_minor: row.estimatedDailyRevenueExposure?.amountMinor, estimated_daily_revenue_exposure_currency: row.estimatedDailyRevenueExposure?.currency, estimated_downtime_minutes: row.estimatedDowntimeMinutes, confidence: row.confidence, source: row.source, notes: row.notes, assessed_by_actor_type: row.assessedByActorType, assessed_by_actor_id: row.assessedByActorId, assessed_by_actor_name: row.assessedByActorName, assessed_at: row.assessedAt })));
  push("ops_work_orders", fixture.workOrders.map((row) => ({ id: row.id, organization_id: row.organizationId, number: row.number, store_id: row.storeId, request_id: row.requestId, problem: row.problem, authorized_scope: row.authorizedScope, category_key: row.categoryKey, taxonomy_node_id: row.taxonomyNodeId, asset_id: row.assetId, component_id: row.componentId, priority: row.priority, status: row.status, version: row.version ?? 0, internal_accountable_party: row.internalAccountableParty ?? "Facilities coordinator", internal_accountable_type: row.internalAccountableType, internal_accountable_id: row.internalAccountableId, accountable_party: row.accountableParty, next_action: row.nextAction, due_at: row.dueAt, escalation_to: row.escalationTo, nte_amount_minor: row.nte?.amountMinor, nte_currency: row.nte?.currency, repair_estimate_amount_minor: row.repairEstimate?.amountMinor, repair_estimate_currency: row.repairEstimate?.currency, estimated_service_extension_months: row.estimatedServiceExtensionMonths, vendor_service_ticket_number: row.vendorServiceTicketNumber, vendor_invoice_number: row.vendorInvoiceNumber, external_accounting_po: row.externalAccountingPo, created_at: row.createdAt, resolved_at: row.resolvedAt, closed_at: row.closedAt })));
  push("ops_work_order_visit_holds", (fixture.workOrderVisitHolds ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, posture: row.posture, status: row.status, internal_review_threshold_minor: row.internalReviewThreshold?.amountMinor, currency: row.internalReviewThreshold?.currency, deadline_at: row.deadlineAt, version: row.version, claimed_visit_id: row.claimedVisitId, claimed_vendor_id: row.claimedVendorId, claimed_at: row.claimedAt, planned_review_appointment_id: row.plannedReviewAppointmentId, planned_review_selected_at: row.plannedReviewSelectedAt, planned_review_selected_by_membership_id: row.plannedReviewSelectedByMembershipId, created_by_membership_id: row.createdByMembershipId, created_by_name: row.createdByName, created_at: row.createdAt, updated_at: row.updatedAt })));
  push("ops_approval_policies", fixture.approvalPolicies.map((row) => ({ id: row.id, organization_id: row.organizationId, policy_key: row.policyKey, version: row.version, name: row.name, scope_kind: row.scopeKind, scope_id: row.scopeId, category_key: row.categoryKey, min_amount_minor: row.minAmountMinor, max_amount_minor: row.maxAmountMinor, currency: row.currency, required_role: row.requiredRole, escalation_role: row.escalationRole, status: row.status, supersedes_policy_id: row.supersedesPolicyId, created_by_membership_id: row.createdByMembershipId, created_at: row.createdAt })));
  push("ops_approval_requests", fixture.approvalRequests.map((row) => ({ id: row.id, organization_id: row.organizationId, subject_type: row.subjectType, subject_id: row.subjectId, store_id: row.storeId, category_key: row.categoryKey, amount_minor: row.amount.amountMinor, currency: row.amount.currency, policy_id: row.policyId, policy_key: row.policyKey, policy_version: row.policyVersion, policy_name: row.policyName, policy_scope_kind: row.policyScopeKind, policy_scope_id: row.policyScopeId, required_role: row.requiredRole, escalation_role: row.escalationRole, requested_by_membership_id: row.requestedByMembershipId, requested_by_name: row.requestedByName, reason: row.reason, requested_at: row.requestedAt, due_at: row.dueAt, parent_approval_request_id: row.parentApprovalRequestId })));
  push("ops_approval_decisions", fixture.approvalDecisions.map((row) => ({ id: row.id, organization_id: row.organizationId, approval_request_id: row.approvalRequestId, decision: row.decision, decided_by_membership_id: row.decidedByMembershipId, decided_by_name: row.decidedByName, decided_by_role: row.decidedByRole, reason: row.reason, escalated_to_role: row.escalatedToRole, decided_at: row.decidedAt })));
  push("ops_work_order_assignments", fixture.assignments.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, kind: row.kind, vendor_id: row.vendorId, internal_membership_id: row.internalMembershipId, status: row.status, assigned_at: row.assignedAt, supersedes_assignment_id: row.supersedesAssignmentId })));
  push("ops_work_order_issuances", fixture.issuances.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, assignment_id: row.assignmentId, revision: row.revision, immutable_payload_json: row.immutablePayloadJson, channel: row.channel, issued_at: row.issuedAt })));
  push("ops_vendor_responses", fixture.vendorResponses.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, assignment_id: row.assignmentId, issuance_id: row.issuanceId, response: row.response, responder_name: row.responderName, proposed_at: row.proposedAt, message: row.message, responded_at: row.respondedAt })));
  push("ops_service_appointments", (fixture.serviceAppointments ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, assignment_id: row.assignmentId, issuance_id: row.issuanceId, source_vendor_response_id: row.sourceVendorResponseId, status: row.status, proposed_by: row.proposedBy, starts_at: row.startsAt, note: row.note, created_by_membership_id: row.createdByMembershipId, created_at: row.createdAt })));
  push("ops_vendor_continuations", (fixture.vendorContinuations ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, vendor_response_id: row.vendorResponseId, action: row.action, message: row.message, created_by_membership_id: row.createdByMembershipId, created_at: row.createdAt })));
  push("ops_work_order_estimate_requests", fixture.estimateRequests.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, vendor_id: row.vendorId, kind: row.kind, decision_kind: row.decisionKind ?? "service_bid", requested_scope: row.requestedScope, status: row.status, channel: row.channel, requested_at: row.requestedAt, due_at: row.dueAt, opened_at: row.openedAt, responded_at: row.respondedAt, decision_at: row.decisionAt })));
  push("ops_vendor_estimate_proposals", fixture.estimateProposals.map((row) => ({ id: row.id, organization_id: row.organizationId, request_id: row.requestId, work_order_id: row.workOrderId, vendor_id: row.vendorId, revision: row.revision, amount_minor: row.amount.amountMinor, currency: row.amount.currency, scope: row.scope, exclusions: row.exclusions, lead_time_days: row.leadTimeDays, valid_until: row.validUntil, submitted_at: row.submittedAt })));
  push("ops_visit_sessions", fixture.visits.map((row) => ({ id: row.id, organization_id: row.organizationId, store_id: row.storeId, provider_kind: row.providerKind, vendor_id: row.vendorId, internal_membership_id: row.internalMembershipId, work_order_id: row.workOrderId, unmatched_reason: row.unmatchedReason, technician_name: row.technicianName, technician_phone_or_pin: row.technicianPhoneOrPin, crew_count: row.crewCount ?? 1, additional_technician_names_json: JSON.stringify(row.additionalTechnicianNames ?? []), vehicle_identifier: row.vehicleIdentifier, arrival_note: row.arrivalNote, provider_name: row.providerName, purpose: row.purpose, status: row.status, started_channel: row.startedChannel, ended_channel: row.endedChannel, checked_in_at: row.checkedInAt, checked_out_at: row.checkedOutAt, outcome: row.outcome, outcome_notes: row.outcomeNotes, observed_duration_seconds: row.observedDurationSeconds })));
  push("ops_visit_evidence", fixture.visitEvidence.map((row) => ({ id: row.id, organization_id: row.organizationId, visit_id: row.visitId, kind: row.kind, channel: row.channel, observed_at: row.observedAt, location_result: row.location?.result, latitude_e6: row.location?.latitudeE6, longitude_e6: row.location?.longitudeE6, accuracy_m: row.location?.accuracyM, distance_m: row.location?.distanceM, payload_json: row.payloadJson })));
  push("ops_files", fixture.files.map((row) => ({ id: row.id, organization_id: row.organizationId, storage_key: row.storageKey, sha256: row.sha256, original_name: row.originalName, content_type: row.contentType, byte_length: row.byteLength, status: row.status, created_at: row.createdAt })));
  push("ops_entity_files", fixture.entityFiles.map((row) => ({ id: row.id, organization_id: row.organizationId, file_id: row.fileId, entity_type: row.entityType, entity_id: row.entityId, purpose: row.purpose, visibility: row.visibility, created_at: row.createdAt })));
  push("ops_follow_ups", fixture.followUps.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, source_visit_id: row.sourceVisitId, accountable_party: row.accountableParty, next_action: row.nextAction, due_at: row.dueAt, escalation_to: row.escalationTo, status: row.status, created_at: row.createdAt, completed_at: row.completedAt })));
  push("ops_site_visit_work_orders", fixture.siteVisitWorkOrders.map((row) => ({ id: row.id, organization_id: row.organizationId, visit_id: row.visitId, work_order_id: row.workOrderId, ordinal: row.ordinal, linked_by_actor_type: row.linkedByActorType, linked_by_actor_id: row.linkedByActorId, linked_by_actor_name: row.linkedByActorName, linked_at: row.linkedAt, selection_source: row.selectionSource ?? "assigned_work", work_order_hold_id: row.workOrderHoldId, outcome: row.outcome, outcome_notes: row.outcomeNotes, outcome_recorded_by_actor_type: row.outcomeRecordedByActorType, outcome_recorded_by_actor_id: row.outcomeRecordedByActorId, outcome_recorded_by_actor_name: row.outcomeRecordedByActorName, outcome_recorded_at: row.outcomeRecordedAt, follow_up_id: row.followUpId, vendor_follow_up_timing: row.vendorFollowUpTiming })));
  push("ops_work_order_verifications", fixture.workOrderVerifications.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, site_visit_work_order_id: row.siteVisitWorkOrderId, outcome: row.outcome, outcome_recorded_at: row.outcomeRecordedAt, cycle: row.cycle, decision: row.decision, basis: row.basis, verification_scope: row.verificationScope, reason: row.reason, decided_by_membership_id: row.decidedByMembershipId, decided_by_name: row.decidedByName, decided_at: row.decidedAt })));
  push("ops_workflow_tasks", fixture.workflowTasks.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, service_request_id: row.serviceRequestId, task_type: row.taskType, title: row.title, reason: row.reason, assignee_type: row.assigneeType, assignee_id: row.assigneeId, assignee_role: row.assigneeRole, assignee_name: row.assigneeName, priority: row.priority, status: row.status, blocking: row.blocking, required_for_progress: row.requiredForProgress, due_at: row.dueAt, no_sla_reason: row.noSlaReason, applicable_sla_clock: row.applicableSlaClock, completion_criteria: row.completionCriteria, escalation_destination: row.escalationDestination, escalation_level: row.escalationLevel, source_follow_up_id: row.sourceFollowUpId, source_approval_request_id: row.sourceApprovalRequestId, created_by_actor_type: row.createdByActorType, created_by_actor_id: row.createdByActorId, created_by_actor_name: row.createdByActorName, created_at: row.createdAt, started_by_actor_type: row.startedByActorType, started_by_actor_id: row.startedByActorId, started_by_actor_name: row.startedByActorName, started_at: row.startedAt, completed_by_actor_type: row.completedByActorType, completed_by_actor_id: row.completedByActorId, completed_by_actor_name: row.completedByActorName, completed_at: row.completedAt, cancelled_by_actor_type: row.cancelledByActorType, cancelled_by_actor_id: row.cancelledByActorId, cancelled_by_actor_name: row.cancelledByActorName, cancelled_at: row.cancelledAt, resolution_note: row.resolutionNote })));
  push("ops_workflow_task_sla_pauses", fixture.workflowTaskSlaPauses.map((row) => ({ id: row.id, organization_id: row.organizationId, workflow_task_id: row.workflowTaskId, work_order_id: row.workOrderId, reason_code: row.reasonCode, reason_detail: row.reasonDetail, owner_type: row.ownerType, owner_id: row.ownerId, owner_name: row.ownerName, affected_clocks_json: JSON.stringify(row.affectedClocks), expected_resume_at: row.expectedResumeAt, paused_by_actor_type: row.pausedByActorType, paused_by_actor_id: row.pausedByActorId, paused_by_actor_name: row.pausedByActorName, paused_at: row.pausedAt })));
  push("ops_workflow_task_sla_resumes", fixture.workflowTaskSlaResumes.map((row) => ({ id: row.id, organization_id: row.organizationId, workflow_task_id: row.workflowTaskId, work_order_id: row.workOrderId, pause_id: row.pauseId, resumed_by_actor_type: row.resumedByActorType, resumed_by_actor_id: row.resumedByActorId, resumed_by_actor_name: row.resumedByActorName, resumed_at: row.resumedAt, note: row.note })));
  push("ops_exceptions", fixture.exceptions.map((row) => ({ id: row.id, organization_id: row.organizationId, kind: row.kind, store_id: row.storeId, work_order_id: row.workOrderId, visit_id: row.visitId, vendor_id: row.vendorId, severity: row.severity, status: row.status, summary: row.summary, detected_at: row.detectedAt })));
  push("ops_replacement_profiles", fixture.replacementProfiles.map((row) => ({ id: row.id, organization_id: row.organizationId, code: row.code, name: row.name, description: row.description, category_key: row.categoryKey, taxonomy_node_id: row.taxonomyNodeId, match_keys_json: JSON.stringify(row.matchKeys), attributes_json: JSON.stringify(row.attributes), expected_life_years: row.expectedLifeYears, annual_escalation_bps: row.annualEscalationBps, low_variance_bps: row.lowVarianceBps, high_variance_bps: row.highVarianceBps, active: row.active ? 1 : 0, created_at: row.createdAt })));
  push("ops_assets", fixture.assets.map((row) => ({ id: row.id, organization_id: row.organizationId, store_id: row.storeId, category_key: row.categoryKey, taxonomy_node_id: row.taxonomyNodeId, equipment_template_id: row.equipmentTemplateId, group_path_json: JSON.stringify(row.groupPath), asset_tag: row.assetTag, name: row.name, manufacturer: row.manufacturer, model: row.model, serial_number: row.serialNumber, supplier: row.supplier, installed_at: row.installedAt, expected_life_years: row.expectedLifeYears, warranty_ends_at: row.warrantyEndsAt, replacement_profile_id: row.replacementProfileId, replacement_attributes_json: JSON.stringify(row.replacementAttributes), replacement_adjustment_bps: row.replacementAdjustmentBps, replacement_planning_excluded_at: row.replacementPlanningExcludedAt, replacement_planning_exclusion_reason: row.replacementPlanningExclusionReason, replacement_estimate_minor: row.replacementEstimate?.amountMinor, replacement_currency: row.replacementEstimate?.currency, status: row.status, retired_at: row.retiredAt, replaced_by_asset_id: row.replacedByAssetId, created_at: row.createdAt })));
  push("ops_replacement_benchmarks", fixture.replacementBenchmarks.map((row) => ({ id: row.id, organization_id: row.organizationId, profile_id: row.profileId, source_type: row.sourceType, source_work_order_id: row.sourceWorkOrderId, source_estimate_proposal_id: row.sourceEstimateProposalId, source_asset_id: row.sourceAssetId, source_vendor_id: row.sourceVendorId, equipment_amount_minor: row.equipmentAmount.amountMinor, installation_amount_minor: row.installationAmount.amountMinor, other_amount_minor: row.otherAmount.amountMinor, total_amount_minor: row.totalAmount.amountMinor, currency: row.totalAmount.currency, effective_at: row.effectiveAt, status: row.status, superseded_at: row.supersededAt, notes: row.notes, created_at: row.createdAt })));
  push("ops_asset_replacement_overrides", fixture.assetReplacementOverrides.map((row) => ({ id: row.id, organization_id: row.organizationId, asset_id: row.assetId, source_benchmark_id: row.sourceBenchmarkId, amount_minor: row.amount.amountMinor, currency: row.amount.currency, effective_at: row.effectiveAt, reason: row.reason, status: row.status, superseded_at: row.supersededAt, created_at: row.createdAt })));
  push("ops_replacement_events", fixture.replacementEvents.map((row) => ({ id: row.id, organization_id: row.organizationId, asset_id: row.assetId, work_order_id: row.workOrderId, profile_id: row.profileId, source_estimate_proposal_id: row.sourceEstimateProposalId, status: row.status, approved_amount_minor: row.approvedAmount.amountMinor, currency: row.approvedAmount.currency, approved_at: row.approvedAt, completed_at: row.completedAt, final_amount_minor: row.finalAmount?.amountMinor, replacement_asset_id: row.replacementAssetId, created_at: row.createdAt })));
  push("ops_lifecycle_recommendations", fixture.lifecycleRecommendations.map((row) => ({ id: row.id, organization_id: row.organizationId, asset_id: row.assetId, work_order_id: row.workOrderId, version: row.version, model_version: row.modelVersion, recommendation: row.recommendation, confidence: row.confidence, inputs_json: row.inputsJson, explanation: row.explanation, missing_data_json: JSON.stringify(row.missingData), user_decision: row.userDecision, user_reason: row.userReason, planned_for_year: row.plannedForYear, decided_by_membership_id: row.decidedByMembershipId, decided_at: row.decidedAt, actual_outcome: row.actualOutcome, actual_outcome_at: row.actualOutcomeAt, replacement_event_id: row.replacementEventId, created_at: row.createdAt })));
  push("ops_asset_components", fixture.components.map((row) => ({ id: row.id, organization_id: row.organizationId, asset_id: row.assetId, parent_component_id: row.parentComponentId, name: row.name, part_number: row.partNumber, serial_number: row.serialNumber, installed_at: row.installedAt, warranty_ends_at: row.warrantyEndsAt, removed_at: row.removedAt, replaced_by_component_id: row.replacedByComponentId, created_at: row.createdAt })));
  push("ops_maintenance_programs", fixture.maintenancePrograms.map((row) => ({ id: row.id, organization_id: row.organizationId, program_key: row.programKey, version: row.version, name: row.name, trade_key: row.tradeKey, work_type: row.workType, applicable_asset_types_json: JSON.stringify(row.applicableAssetTypes), frequency_days: row.frequencyDays, recurrence_kind: row.recurrenceKind, due_window_days: row.dueWindowDays, schedule_anchor_at: row.scheduleAnchorAt, seasonal_start_month: row.seasonalStartMonth, seasonal_end_month: row.seasonalEndMonth, checklist_template_id: row.checklistTemplateId, required_evidence_kinds_json: JSON.stringify(row.requiredEvidenceKinds), expected_duration_minutes: row.expectedDurationMinutes, completion_criteria: row.completionCriteria, corrective_work_authority_minor: row.correctiveWorkAuthorityMinor, currency: row.currency, deficiency_handling: row.deficiencyHandling, status: row.status, supersedes_program_id: row.supersedesProgramId, created_at: row.createdAt })));
  push("ops_checklist_templates", fixture.checklistTemplates.map((row) => ({ id: row.id, organization_id: row.organizationId, name: row.name, version: row.version, items_json: JSON.stringify(row.items), status: row.status, created_at: row.createdAt })));
  push("ops_pm_plans", fixture.pmPlans.map((row) => ({ id: row.id, organization_id: row.organizationId, name: row.name, program_id: row.programId, program_version: row.programVersion, store_id: row.storeId, asset_id: row.assetId, asset_selection_rule: row.assetSelectionRule, category_key: row.categoryKey, cadence_days: row.cadenceDays, completion_window_days: row.completionWindowDays, preferred_vendor_id: row.preferredVendorId, backup_vendor_id: row.backupVendorId, contract_version_id: row.contractVersionId, effective_starts_at: row.effectiveStartsAt, effective_ends_at: row.effectiveEndsAt, access_requirements: row.accessRequirements, program_authorization_minor: row.programAuthorizationMinor, budget_minor: row.budgetMinor, currency: row.currency, service_level_policy_id: row.serviceLevelPolicyId, scheduling_mode: row.schedulingMode, escalation_rules: row.escalationRules, cadence_override_reason: row.cadenceOverrideReason, cadence_overridden_at: row.cadenceOverriddenAt, cadence_overridden_by_membership_id: row.cadenceOverriddenByMembershipId, active: row.active ? 1 : 0, created_at: row.createdAt })));
  push("ops_pm_occurrences", fixture.pmOccurrences.map((row) => ({ id: row.id, organization_id: row.organizationId, plan_id: row.planId, store_id: row.storeId, asset_id: row.assetId, work_order_id: row.workOrderId, program_id: row.programId, program_version: row.programVersion, plan_version: row.planVersion, due_at: row.dueAt, window_starts_at: row.windowStartsAt, window_ends_at: row.windowEndsAt, proposed_at: row.proposedAt, committed_at: row.committedAt, status: row.status, completed_at: row.completedAt, result: row.result, exception_reason: row.exceptionReason, recurrence_key: row.recurrenceKey, created_at: row.createdAt })));
  push("ops_pm_work_items", fixture.pmWorkItems.map((row) => ({ id: row.id, organization_id: row.organizationId, occurrence_id: row.occurrenceId, work_order_id: row.workOrderId, asset_id: row.assetId, component_id: row.componentId, required_task: row.requiredTask, checklist_template_id: row.checklistTemplateId, status: row.status, result: row.result, deficiency: row.deficiency, follow_up_id: row.followUpId, corrective_work_order_id: row.correctiveWorkOrderId, cost_allocation_minor: row.costAllocationMinor, currency: row.currency, created_at: row.createdAt, completed_at: row.completedAt })));
  push("ops_checklist_responses", fixture.checklistResponses.map((row) => ({ id: row.id, organization_id: row.organizationId, work_item_id: row.workItemId, checklist_template_id: row.checklistTemplateId, item_key: row.itemKey, response_kind: row.responseKind, passed: row.passed, numeric_value: row.numericValue, text_value: row.textValue, measurement_unit: row.measurementUnit, evidence_file_ids_json: JSON.stringify(row.evidenceFileIds), recorded_by_actor_type: row.recordedByActorType, recorded_by_actor_id: row.recordedByActorId, recorded_by_actor_name: row.recordedByActorName, recorded_at: row.recordedAt })));
  push("ops_service_runs", fixture.serviceRuns.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, contract_version_id: row.contractVersionId, scheduling_mode: row.schedulingMode, status: row.status, proposed_starts_at: row.proposedStartsAt, proposed_ends_at: row.proposedEndsAt, response_due_at: row.responseDueAt, committed_starts_at: row.committedStartsAt, committed_ends_at: row.committedEndsAt, estimated_drive_minutes: row.estimatedDriveMinutes, estimated_service_minutes: row.estimatedServiceMinutes, capacity_used_minutes: row.capacityUsedMinutes, expected_work_value_minor: row.expectedWorkValue.amountMinor, currency: row.expectedWorkValue.currency, estimated_trip_reduction: row.estimatedTripReduction, estimated_opportunity_minor: row.estimatedOpportunity.amountMinor, recommendation_explanation: row.recommendationExplanation, required_qualifications_json: JSON.stringify(row.requiredQualifications), constraints_json: row.constraintsJson, confidence: row.confidence, scheduler_version: row.schedulerVersion, original_recommendation_json: row.originalRecommendationJson, created_by_actor_type: row.createdByActorType, created_by_actor_id: row.createdByActorId, created_by_actor_name: row.createdByActorName, created_at: row.createdAt, accepted_at: row.acceptedAt, completed_at: row.completedAt })));
  push("ops_route_stops", fixture.routeStops.map((row) => ({ id: row.id, organization_id: row.organizationId, service_run_id: row.serviceRunId, store_id: row.storeId, sequence: row.sequence, proposed_arrival_at: row.proposedArrivalAt, committed_arrival_at: row.committedArrivalAt, estimated_drive_minutes: row.estimatedDriveMinutes, estimated_service_minutes: row.estimatedServiceMinutes, access_requirements: row.accessRequirements, status: row.status, site_visit_id: row.siteVisitId })));
  push("ops_service_run_work_orders", fixture.serviceRunWorkOrders.map((row) => ({ id: row.id, organization_id: row.organizationId, service_run_id: row.serviceRunId, route_stop_id: row.routeStopId, work_order_id: row.workOrderId, occurrence_id: row.occurrenceId, planned: row.planned ? 1 : 0, estimated_duration_minutes: row.estimatedDurationMinutes, addressed: row.addressed ? 1 : 0, removal_reason: row.removalReason })));
  push("ops_service_run_responses", fixture.serviceRunResponses.map((row) => ({ id: row.id, organization_id: row.organizationId, service_run_id: row.serviceRunId, response: row.response, requested_starts_at: row.requestedStartsAt, requested_stop_changes_json: row.requestedStopChangesJson, requested_work_order_changes_json: row.requestedWorkOrderChangesJson, reason_code: row.reasonCode, reason_detail: row.reasonDetail, travel_impact_minutes: row.travelImpactMinutes, due_window_impact_count: row.dueWindowImpactCount, economic_impact_minor: row.economicImpact.amountMinor, currency: row.economicImpact.currency, responder_name: row.responderName, responded_at: row.respondedAt, resulting_plan_json: row.resultingPlanJson })));
  push("ops_vendor_warranty_profiles", fixture.vendorWarrantyProfiles.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, base_labor_days: row.baseLaborDays, base_parts_days: row.basePartsDays, base_travel_days: row.baseTravelDays, base_diagnostic_days: row.baseDiagnosticDays, effective_starts_at: row.effectiveStartsAt, effective_ends_at: row.effectiveEndsAt, status: row.status, created_at: row.createdAt })));
  push("ops_warranty_rules", fixture.warrantyRules.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_warranty_profile_id: row.vendorWarrantyProfileId, vendor_id: row.vendorId, contract_version_id: row.contractVersionId, quote_id: row.quoteId, authorization_id: row.authorizationId, trade_key: row.tradeKey, work_type: row.workType, service_type: row.serviceType, asset_type: row.assetType, component_type: row.componentType, manufacturer: row.manufacturer, model: row.model, vendor_supplied_part: row.vendorSuppliedPart, customer_supplied_part: row.customerSuppliedPart, region_id: row.regionId, store_id: row.storeId, priority: row.priority, effective_starts_at: row.effectiveStartsAt, effective_ends_at: row.effectiveEndsAt, status: row.status, created_at: row.createdAt })));
  push("ops_warranty_coverage_lines", fixture.warrantyCoverageLines.map((row) => ({ id: row.id, organization_id: row.organizationId, warranty_rule_id: row.warrantyRuleId, vendor_warranty_profile_id: row.vendorWarrantyProfileId, coverage_type: row.coverageType, duration: row.duration, duration_unit: row.durationUnit, start_event: row.startEvent, start_date: row.startDate, end_date: row.endDate, provider: row.provider, obligated_vendor_id: row.obligatedVendorId, routing_rule: row.routingRule, deductible_minor: row.deductible.amountMinor, maximum_coverage_minor: row.maximumCoverage?.amountMinor, currency: row.deductible.currency, conditions: row.conditions, exclusions: row.exclusions })));
  push("ops_repair_items", fixture.repairItems.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, site_visit_work_order_id: row.siteVisitWorkOrderId, vendor_id: row.vendorId, contract_version_id: row.contractVersionId, asset_id: row.assetId, component_id: row.componentId, failure_code: row.failureCode, repair_action: row.repairAction, repair_severity: row.repairSeverity, removed_component_id: row.removedComponentId, installed_component_id: row.installedComponentId, part_manufacturer: row.partManufacturer, part_model: row.partModel, serial_number: row.serialNumber, vendor_supplied: row.vendorSupplied, completion_date: row.completionDate, verification_date: row.verificationDate, labor_cost_minor: row.laborCost.amountMinor, part_cost_minor: row.partCost.amountMinor, currency: row.laborCost.currency, root_cause: row.rootCause, created_at: row.createdAt })));
  push("ops_component_lifecycle_events", fixture.componentLifecycleEvents.map((row) => ({ id: row.id, organization_id: row.organizationId, asset_id: row.assetId, removed_component_id: row.removedComponentId, installed_component_id: row.installedComponentId, repair_item_id: row.repairItemId, work_order_id: row.workOrderId, vendor_id: row.vendorId, part_manufacturer: row.partManufacturer, part_model: row.partModel, serial_number: row.serialNumber, removed_at: row.removedAt, installed_at: row.installedAt, failure_mode: row.failureMode, root_cause: row.rootCause, labor_cost_minor: row.laborCost.amountMinor, part_cost_minor: row.partCost.amountMinor, currency: row.laborCost.currency, replacement_kind: row.replacementKind, expected_life_months: row.expectedLifeMonths, warranty_ends_at: row.warrantyEndsAt, created_at: row.createdAt })));
  push("ops_applied_warranties", fixture.appliedWarranties.map((row) => ({ id: row.id, organization_id: row.organizationId, repair_item_id: row.repairItemId, coverage_type: row.coverageType, provider: row.provider, obligated_vendor_id: row.obligatedVendorId, start_date: row.startDate, end_date: row.endDate, covered_charges_json: JSON.stringify(row.coveredCharges), routing_rule: row.routingRule, contract_version_id: row.contractVersionId, policy_source: row.policySource, rule_source: row.ruleSource, original_calculated_terms_json: row.originalCalculatedTermsJson, created_at: row.createdAt })));
  push("ops_warranty_amendments", fixture.warrantyAmendments.map((row) => ({ id: row.id, organization_id: row.organizationId, applied_warranty_id: row.appliedWarrantyId, amendment_kind: row.amendmentKind, applies_to_repair_only: row.appliesToRepairOnly, amended_terms_json: row.amendedTermsJson, reason: row.reason, decided_by_membership_id: row.decidedByMembershipId, decided_by_name: row.decidedByName, decided_at: row.decidedAt })));
  push("ops_manufacturer_warranties", fixture.manufacturerWarranties.map((row) => ({ id: row.id, organization_id: row.organizationId, asset_id: row.assetId, component_id: row.componentId, manufacturer: row.manufacturer, model: row.model, serial_number: row.serialNumber, parts_coverage: row.partsCoverage, labor_coverage: row.laborCoverage, start_date: row.startDate, expiration_date: row.expirationDate, authorized_provider_rule: row.authorizedProviderRule, claim_requirements: row.claimRequirements, installing_vendor_id: row.installingVendorId, administrator: row.administrator, supporting_file_id: row.supportingFileId, created_at: row.createdAt })));
  push("ops_warranty_cases", fixture.warrantyCases.map((row) => ({ id: row.id, organization_id: row.organizationId, request_id: row.requestId, work_order_id: row.workOrderId, asset_id: row.assetId, component_id: row.componentId, prior_repair_item_id: row.priorRepairItemId, applied_warranty_id: row.appliedWarrantyId, manufacturer_warranty_id: row.manufacturerWarrantyId, status: row.status, confidence: row.confidence, detection_explanation: row.detectionExplanation, diagnosis_required: row.diagnosisRequired, coverage_decision: row.coverageDecision, customer_charge_status: row.customerChargeStatus, invoice_hold: row.invoiceHold, routing_rule: row.routingRule, obligated_vendor_id: row.obligatedVendorId, vendor_response_due_at: row.vendorResponseDueAt, created_at: row.createdAt, closed_at: row.closedAt })));
  push("ops_quotes", fixture.quotes.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, vendor_id: row.vendorId, contract_version_id: row.contractVersionId, quote_number: row.quoteNumber, version: row.version, scope: row.scope, subtotal_minor: row.subtotal.amountMinor, tax_minor: row.tax.amountMinor, fees_minor: row.fees.amountMinor, total_minor: row.total.amountMinor, currency: row.total.currency, submitted_at: row.submittedAt, expires_at: row.expiresAt, supersedes_quote_id: row.supersedesQuoteId })));
  push("ops_authorizations", fixture.authorizations.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, authorization_type: row.authorizationType, authorized_amount_minor: row.authorizedAmount.amountMinor, currency: row.authorizedAmount.currency, authorized_scope: row.authorizedScope, approver_membership_id: row.approverMembershipId, approver_name: row.approverName, approval_authority: row.approvalAuthority, authorized_at: row.authorizedAt, reason: row.reason, contract_version_id: row.contractVersionId, supersedes_authorization_id: row.supersedesAuthorizationId })));
  push("ops_invoices", fixture.invoices.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, contract_version_id: row.contractVersionId, vendor_invoice_number: row.vendorInvoiceNumber, invoice_date: row.invoiceDate, subtotal_minor: row.subtotal.amountMinor, tax_minor: row.tax.amountMinor, fees_minor: row.fees.amountMinor, total_minor: row.total.amountMinor, approved_for_payment_minor: row.approvedForPayment.amountMinor, paid_amount_minor: row.paidAmount.amountMinor, currency: row.total.currency, status: row.status, exception_reason: row.exceptionReason, supporting_file_id: row.supportingFileId, submitted_by_membership_id: row.submittedByMembershipId, created_at: row.createdAt })));
  push("ops_invoice_lines", fixture.invoiceLines.map((row) => ({ id: row.id, organization_id: row.organizationId, invoice_id: row.invoiceId, line_number: row.lineNumber, category: row.category, description: row.description, quantity_thousandths: row.quantityThousandths, unit_amount_minor: row.unitAmount.amountMinor, line_amount_minor: row.lineAmount.amountMinor, currency: row.lineAmount.currency, contract_rate_card_line_id: row.contractRateCardLineId, created_at: row.createdAt })));
  push("ops_invoice_line_allocations", fixture.invoiceLineAllocations.map((row) => ({ id: row.id, organization_id: row.organizationId, invoice_line_id: row.invoiceLineId, work_order_id: row.workOrderId, work_item_id: row.workItemId, repair_item_id: row.repairItemId, site_visit_work_order_id: row.siteVisitWorkOrderId, asset_id: row.assetId, component_id: row.componentId, store_id: row.storeId, trade_key: row.tradeKey, amount_minor: row.amount.amountMinor, currency: row.amount.currency, method: row.method, confirmed_by_membership_id: row.confirmedByMembershipId, confirmed_at: row.confirmedAt })));
  push("ops_invoice_exceptions", fixture.invoiceExceptions.map((row) => ({ id: row.id, organization_id: row.organizationId, invoice_id: row.invoiceId, invoice_line_id: row.invoiceLineId, kind: row.kind, status: row.status, summary: row.summary, amount_minor: row.amount.amountMinor, currency: row.amount.currency, detected_at: row.detectedAt, resolved_at: row.resolvedAt, resolution_reason: row.resolutionReason })));
  push("ops_invoice_adjustments", fixture.invoiceAdjustments.map((row) => ({ id: row.id, organization_id: row.organizationId, invoice_id: row.invoiceId, kind: row.kind, amount_minor: row.amount.amountMinor, currency: row.amount.currency, reason: row.reason, created_by_membership_id: row.createdByMembershipId, created_at: row.createdAt })));
  push("ops_service_discrepancies", fixture.serviceDiscrepancies.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, invoice_id: row.invoiceId, site_visit_work_order_id: row.siteVisitWorkOrderId, discrepancy_type: row.discrepancyType, status: row.status, facts_json: row.factsJson, vendor_response: row.vendorResponse, resolution: row.resolution, created_at: row.createdAt, resolved_at: row.resolvedAt })));
  push("ops_value_events", fixture.valueEvents.map((row) => ({ id: row.id, organization_id: row.organizationId, category: row.category, event_type: row.eventType, amount_minor: row.amount.amountMinor, currency: row.amount.currency, work_order_id: row.workOrderId, invoice_line_id: row.invoiceLineId, service_run_id: row.serviceRunId, contract_version_id: row.contractVersionId, warranty_case_id: row.warrantyCaseId, asset_id: row.assetId, approval_decision_id: row.approvalDecisionId, source_decision: row.sourceDecision, deduplication_key: row.deduplicationKey, occurred_at: row.occurredAt })));
  push("ops_cost_lines", fixture.costLines.map((row) => ({ id: row.id, organization_id: row.organizationId, work_order_id: row.workOrderId, kind: row.kind, description: row.description, amount_minor: row.amount.amountMinor, currency: row.amount.currency, service_date: row.serviceDate, recorded_at: row.recordedAt })));
  push("ops_invoice_references", fixture.invoiceReferences.map((row) => ({ id: row.id, organization_id: row.organizationId, vendor_id: row.vendorId, invoice_number: row.invoiceNumber, invoice_date: row.invoiceDate, gross_amount_minor: row.grossAmount.amountMinor, currency: row.grossAmount.currency, operator_work_order_number: row.operatorWorkOrderNumber, match_status: row.matchStatus, created_at: row.createdAt })));
  push("ops_invoice_allocations", fixture.invoiceAllocations.map((row) => ({ id: row.id, organization_id: row.organizationId, invoice_reference_id: row.invoiceReferenceId, work_order_id: row.workOrderId, amount_minor: row.amount.amountMinor, currency: row.amount.currency, confirmed_by_membership_id: row.confirmedByMembershipId, confirmed_at: row.confirmedAt })));
  push("ops_audit_events", fixture.auditEvents.map((row) => ({ id: row.id, organization_id: row.organizationId, aggregate_type: row.aggregateType, aggregate_id: row.aggregateId, event_type: row.eventType, actor_type: row.actorType, actor_id: row.actorId, actor_name: row.actorName, occurred_at: row.occurredAt, payload_json: row.payloadJson })));
  push("ops_outbox_messages", fixture.outboxMessages.map((row) => ({ id: row.id, organization_id: row.organizationId, topic: row.topic, aggregate_type: row.aggregateType, aggregate_id: row.aggregateId, payload_json: row.payloadJson, status: row.status, available_at: row.availableAt, created_at: row.createdAt })));
  push("ops_notification_rules", (fixture.notificationRules ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, event_key: row.eventKey, email_enabled: row.emailEnabled ? 1 : 0, recipient_role: row.recipientRole, updated_by_membership_id: row.updatedByMembershipId, created_at: row.createdAt, updated_at: row.updatedAt })));
  push("ops_role_capability_overrides", (fixture.roleCapabilityOverrides ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, role: row.role, capability: row.capability, enabled: row.enabled ? 1 : 0, updated_by_membership_id: row.updatedByMembershipId, updated_by_name: row.updatedByName, created_at: row.createdAt, updated_at: row.updatedAt })));
  push("ops_workflow_policies", (fixture.workflowPolicies ?? []).map((row) => ({ id: row.id, organization_id: row.organizationId, version: row.version, status: row.status, auto_close_routine_after_verification: row.autoCloseRoutineAfterVerification ? 1 : 0, applies_to_active_work: row.appliesToActiveWork ? 1 : 0, created_by_membership_id: row.createdByMembershipId, created_by_name: row.createdByName, created_at: row.createdAt })));
  push("ops_public_tokens", fixture.publicTokens.map((row) => ({ id: row.id, organization_id: row.organizationId, purpose: row.purpose, subject_type: row.subjectType, subject_id: row.subjectId, token_hash: row.tokenHash, expires_at: row.expiresAt, created_at: row.createdAt, used_at: row.usedAt, revoked_at: row.revokedAt })));
  for (const organization of fixture.organizations) {
    const counters = new Map<number, number>();
    for (const workOrder of fixture.workOrders.filter((row) => row.organizationId === organization.id)) {
      const match = workOrder.number.match(new RegExp(`^${organization.workOrderPrefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}-(\\d{4})-(\\d+)$`));
      if (!match) continue;
      const year = Number(match[1]);
      const sequence = Number(match[2]);
      if (Number.isInteger(year) && Number.isInteger(sequence)) counters.set(year, Math.max(counters.get(year) ?? 0, sequence));
    }
    for (const [year, highest] of counters) {
      statements.push({
        sql: `INSERT INTO ops_work_order_counters (organization_id, counter_year, next_value)
          VALUES (?, ?, ?)
          ON CONFLICT(organization_id, counter_year) DO UPDATE SET next_value =
            CASE WHEN excluded.next_value > ops_work_order_counters.next_value
              THEN excluded.next_value ELSE ops_work_order_counters.next_value END`,
        params: [organization.id, year, highest + 1],
      });
    }
  }
  return statements;
}

export async function seedOpsRepository(
  repository: OpsRepository,
  fixture: OpsFixture,
  finalStatements: readonly OpsStatement[] = [],
) {
  const statements = [...buildOpsSeedStatements(fixture), ...finalStatements];
  const chunkSize = repository.kind === "d1" ? 75 : statements.length;
  for (let index = 0; index < statements.length; index += chunkSize) await repository.atomicWrite(statements.slice(index, index + chunkSize));
  return { statements: statements.length, organizations: fixture.organizations.length, stores: fixture.stores.length, vendors: fixture.vendors.length };
}
