import type { OrganizationScope } from "./repository";
import type { OpsSqlDriver } from "./sql-driver";
import { scopeWhere } from "./sql-scope";
import { dashboardPageBounds } from "./dashboard-query";
import { coverageViews, coverageEndWindow, warrantyStatus, type WarrantyDirectoryQuery, type WarrantyDirectoryPage, type WarrantyDirectoryRow } from "./warranty-directory";
export async function queryWarrantyDirectory(driver:OpsSqlDriver,scope:OrganizationScope,q:WarrantyDirectoryQuery):Promise<WarrantyDirectoryPage> {
 const params:unknown[]=[],bind=(v:unknown)=>{params.push(v);return "?";},scoped=scopeWhere(scope,"s",params);
 const search=q.search?` AND LOWER(title||' '||provider||' '||asset_name||' '||asset_tag||' '||store_number||' '||store_name||' '||address||' '||aliases||' '||COALESCE(component,'')) LIKE ${bind('%'+q.search.toLowerCase().replace(/[\\%_]/g,c=>'\\'+c)+'%')} ESCAPE '\\'`:"";
 const filters=search+(q.id?` AND id=${bind(q.id)}`:"")+(q.assetId?` AND asset_id=${bind(q.assetId)}`:"")+(q.vendorId?` AND vendor_id=${bind(q.vendorId)}`:"");
 const today=bind(q.today),endWindow=bind(coverageEndWindow(q.today)),{limit,offset}=dashboardPageBounds(q);
 const predicates={all:"1=1",active:"state='Active'",expiring:"state='Active' AND end_date<=window_end",expired:"state='Expired'",review:"state='Review terms'"};
 const sql=`WITH scoped_stores AS (SELECT s.* FROM ops_stores s WHERE ${scoped}),
 raw AS (
 SELECT m.id,'registered' AS kind,a.id AS asset_id,a.name AS asset_name,a.asset_tag,s.id AS store_id,s.store_number,s.name AS store_name,s.address_1||' '||s.city||' '||s.state||' '||s.postal_code AS address,COALESCE(CAST(s.aliases_json AS TEXT),'') AS aliases,c.name AS component,COALESCE(m.title,'Manufacturer warranty') AS title,m.manufacturer AS provider,m.vendor_id,SUBSTR(CAST(m.start_date AS TEXT),1,10) AS start_date,SUBSTR(CAST(m.expiration_date AS TEXT),1,10) AS end_date,m.parts_coverage AS parts,m.labor_coverage AS labor,COALESCE(m.travel_coverage,'Not recorded') AS travel,m.claim_requirements AS instructions,m.authorized_provider_rule AS provider_rule,m.administrator AS contact,m.work_order_id AS work_id,0 AS amended
 FROM ops_manufacturer_warranties m JOIN ops_assets a ON a.organization_id=m.organization_id AND a.id=m.asset_id JOIN scoped_stores s ON s.organization_id=a.organization_id AND s.id=a.store_id LEFT JOIN ops_asset_components c ON c.organization_id=a.organization_id AND c.asset_id=a.id AND c.id=m.component_id
 UNION ALL
 SELECT w.id,'repair',a.id,a.name,a.asset_tag,s.id,s.store_number,s.name,s.address_1||' '||s.city||' '||s.state||' '||s.postal_code,COALESCE(CAST(s.aliases_json AS TEXT),''),c.name,REPLACE(w.coverage_type,'_',' ')||' repair warranty',COALESCE(v.name,w.provider),w.obligated_vendor_id,SUBSTR(CAST(w.start_date AS TEXT),1,10),SUBSTR(CAST(w.end_date AS TEXT),1,10),CASE WHEN w.coverage_type='part' OR CAST(w.covered_charges_json AS TEXT) LIKE '%"part"%' THEN 'Covered by this term' ELSE 'Not included in this term' END,CASE WHEN w.coverage_type='labor' OR CAST(w.covered_charges_json AS TEXT) LIKE '%"labor"%' THEN 'Covered by this term' ELSE 'Not included in this term' END,CASE WHEN w.coverage_type='travel' OR CAST(w.covered_charges_json AS TEXT) LIKE '%"travel"%' THEN 'Covered by this term' ELSE 'Not included in this term' END,w.policy_source,w.routing_rule,NULL,r.work_order_id,CASE WHEN EXISTS (SELECT 1 FROM ops_warranty_amendments x WHERE x.organization_id=w.organization_id AND x.applied_warranty_id=w.id AND x.amendment_kind<>'accept_calculated') THEN 1 ELSE 0 END
 FROM ops_applied_warranties w JOIN ops_repair_items r ON r.organization_id=w.organization_id AND r.id=w.repair_item_id JOIN ops_assets a ON a.organization_id=r.organization_id AND a.id=r.asset_id JOIN scoped_stores s ON s.organization_id=a.organization_id AND s.id=a.store_id LEFT JOIN ops_vendors v ON v.organization_id=w.organization_id AND v.id=w.obligated_vendor_id LEFT JOIN ops_asset_components c ON c.organization_id=a.organization_id AND c.asset_id=a.id AND c.id=r.component_id
 ),filtered AS (SELECT * FROM raw WHERE 1=1${filters}), dates AS (SELECT ${today} AS today,${endWindow} AS window_end), states AS (SELECT f.*,d.window_end,CASE WHEN amended=1 THEN 'Review terms' WHEN start_date>d.today THEN 'Starts later' WHEN end_date<d.today THEN 'Expired' ELSE 'Active' END AS state FROM filtered f CROSS JOIN dates d), counts AS (SELECT ${coverageViews.map(v=>`SUM(CASE WHEN ${predicates[v]} THEN 1 ELSE 0 END) AS ${v}_count`).join(',')} FROM states),selected AS (SELECT * FROM states WHERE ${predicates[q.view]}),total AS (SELECT COUNT(*) AS total_count FROM selected),visible AS (SELECT * FROM selected ORDER BY end_date,id LIMIT ${bind(limit)} OFFSET ${bind(offset)}) SELECT v.*,c.*,t.total_count FROM counts c CROSS JOIN total t LEFT JOIN visible v ON 1=1 ORDER BY v.end_date,v.id`;
 const result=await driver.query({sql,params}),first=result.rows[0]??{},totalCount=Number(first.total_count??0);
 return {totalCount,nextOffset:offset+limit<totalCount?offset+limit:undefined,counts:Object.fromEntries(coverageViews.map(v=>[v,Number(first[v+'_count']??0)])) as WarrantyDirectoryPage['counts'],items:result.rows.filter(r=>r.id!=null).map(r=>{const optional=(key:string)=>r[key]==null?undefined:String(r[key]);return {id:String(r.id),kind:r.kind as WarrantyDirectoryRow['kind'],assetId:String(r.asset_id),assetName:String(r.asset_name),assetTag:String(r.asset_tag),storeId:String(r.store_id),storeNumber:String(r.store_number),storeName:String(r.store_name),address:String(r.address),component:optional('component'),title:String(r.title),provider:String(r.provider),vendorId:optional('vendor_id'),start:String(r.start_date),end:String(r.end_date),parts:String(r.parts),labor:String(r.labor),travel:String(r.travel),instructions:optional('instructions'),providerRule:optional('provider_rule'),contact:optional('contact'),workId:optional('work_id'),amended:Number(r.amended)===1,status:warrantyStatus(String(r.start_date),String(r.end_date),Number(r.amended)===1,q.today)};})};
}
