import { warrantyQueueViews } from "./warranty-queue-query";
import type { OrganizationScope } from "./repository";
import type { OpsSqlDriver } from "./sql-driver";
import { scopeWhere } from "./sql-scope";
import { dashboardPageBounds } from "./dashboard-query";
import type { WarrantyQueueQuery, WarrantyQueuePage } from "./warranty-queue-query";
export async function queryWarrantyQueue(driver: OpsSqlDriver, scope: OrganizationScope, q: WarrantyQueueQuery): Promise<WarrantyQueuePage> {
    if (!warrantyQueueViews.includes(q.view))
        throw new RangeError("Choose a warranty view.");
    const pg = driver.dialect === "postgres", params: unknown[] = [], scoped = scopeWhere(scope, "s", params), bind = (v: unknown) => { params.push(v); return "?"; }, yes = pg ? "true" : "1", binary = pg ? 'COLLATE "C"' : "COLLATE BINARY", instant = (s: string) => pg ? s : `julianday(${s})`;
    const search = q.search ? ` AND LOWER(w.number||' '||w.problem||' '||s.store_number||' '||s.name) LIKE ${bind('%' + q.search.toLowerCase().replace(/[\\%_]/g, c => '\\' + c) + '%')} ESCAPE '\\'` : "";
    const currency = bind(q.currency), { limit, offset } = dashboardPageBounds(q);
    const selected = q.view === "exposure" ? "SELECT e.id,c.id AS case_id,c.work_order_id,c.work_number,c.store_number,c.store_name,c.status,c.coverage_decision,c.diagnosis_required,c.invoice_hold,e.occurred_at AS date,e.amount_minor,e.source_decision AS detail FROM events e JOIN cases c ON c.id=e.warranty_case_id" : `SELECT c.id,c.id AS case_id,c.work_order_id,c.work_number,c.store_number,c.store_name,c.status,c.coverage_decision,c.diagnosis_required,c.invoice_hold,c.created_at AS date,NULL AS amount_minor,NULL AS detail FROM cases c${q.view === "open" ? " WHERE c.closed_at IS NULL" : q.view === "diagnosis" ? ` WHERE c.diagnosis_required=${yes}` : q.view === "held" ? ` WHERE c.invoice_hold=${yes}` : ""}`;
    const result = await driver.query({ sql: `WITH scoped_stores AS (SELECT s.* FROM ops_stores s WHERE ${scoped}),cases AS MATERIALIZED (SELECT c.*,w.number AS work_number,s.store_number,s.name AS store_name FROM ops_warranty_cases c JOIN ops_work_orders w ON w.organization_id=c.organization_id AND w.id=c.work_order_id JOIN scoped_stores s ON s.organization_id=w.organization_id AND s.id=w.store_id WHERE 1=1${search}),events AS MATERIALIZED (SELECT e.* FROM ops_value_events e JOIN cases c ON c.organization_id=e.organization_id AND c.id=e.warranty_case_id WHERE e.category='identified_exposure' AND e.currency=${currency}),counts AS (SELECT (SELECT COUNT(*) FROM cases) AS all_count,(SELECT COUNT(*) FROM cases WHERE closed_at IS NULL) AS open_count,(SELECT COUNT(*) FROM cases WHERE diagnosis_required=${yes}) AS diagnosis_count,(SELECT COUNT(*) FROM cases WHERE invoice_hold=${yes}) AS held_count,(SELECT COUNT(*) FROM events) AS exposure_count,COALESCE((SELECT SUM(amount_minor) FROM events),0) AS exposure_minor),selected AS (${selected}),total AS (SELECT COUNT(*) AS total_count FROM selected),visible AS (SELECT * FROM selected ORDER BY ${instant("date")} DESC,id ${binary} LIMIT ${bind(limit)} OFFSET ${bind(offset)}) SELECT v.*,c.*,t.total_count FROM counts c CROSS JOIN total t LEFT JOIN visible v ON 1=1 ORDER BY ${instant("v.date")} DESC,v.id ${binary}`, params });
    const first = result.rows[0] ?? {}, totalCount = Number(first.total_count ?? 0);
    return { totalCount, nextOffset: offset + limit < totalCount ? offset + limit : undefined, exposureMinor: Number(first.exposure_minor ?? 0), counts: { all: Number(first.all_count ?? 0), open: Number(first.open_count ?? 0), diagnosis: Number(first.diagnosis_count ?? 0), held: Number(first.held_count ?? 0), exposure: Number(first.exposure_count ?? 0) }, rows: result.rows.filter(r => r.id != null).map(r => ({ id: String(r.id), caseId: String(r.case_id), workId: String(r.work_order_id), workNumber: String(r.work_number), storeNumber: String(r.store_number), storeName: String(r.store_name), status: String(r.status), coverage: String(r.coverage_decision), diagnosis: r.diagnosis_required === true || Number(r.diagnosis_required) === 1, held: r.invoice_hold === true || Number(r.invoice_hold) === 1, date: new Date(String(r.date)).toISOString(), amountMinor: r.amount_minor == null ? undefined : Number(r.amount_minor), detail: r.detail == null ? undefined : String(r.detail) })) };
}
