"use client";

import { useState } from "react";
import { CalendarClock, CheckCircle2, Clock3, MapPin, Package, Play, UserRound, Wrench } from "lucide-react";
import Link from "@/components/site-link";
import { AppShell } from "@/components/app-shell";
import { Breadcrumbs, MetricCard, PageHeader, PanelTitle, StatusBadge } from "@/components/ui";
import { formatDate } from "@/lib/domain/analytics";
import { demoData, DEMO_NOW } from "@/lib/demo/data";
import { statusTone, workOrderStatusLabel } from "@/lib/presentation";

export function MaintenanceWorkspace() {
  const [technicianId, setTechnicianId] = useState(demoData.technicians[0].id);
  const technician = demoData.technicians.find((item) => item.id === technicianId)!;
  const work = demoData.workOrders.filter((item) => item.assignmentType === "internal" && item.assignedToId === technicianId && !["closed", "cancelled"].includes(item.status)).sort((a, b) => (a.dueAt ?? "").localeCompare(b.dueAt ?? ""));
  const overdue = work.filter((item) => item.dueAt && item.dueAt < DEMO_NOW).length;
  const active = work.filter((item) => item.status === "visit_active").length;
  const hours = work.reduce((sum, item) => sum + (item.estimatedHours ?? 0), 0);
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "My Maintenance Work" }]} /><PageHeader eyebrow="Internal maintenance mobile desk" title="My work" description="A field-ready queue for company maintenance technicians: assignment scope, travel context, hazards, work plan, time, parts, notes and closeout."><label className="technician-picker"><UserRound /><span>Working as</span><select value={technicianId} onChange={(event) => setTechnicianId(event.target.value)}>{demoData.technicians.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.title}</option>)}</select></label></PageHeader>
    <div className="metric-grid"><MetricCard label="Assigned work" value={String(work.length)} note={`${technician.weeklyCapacityHours}h weekly capacity`} icon={Wrench} /><MetricCard label="Active onsite" value={String(active)} note="Clocked or in progress" icon={Play} tone={active ? "warning" : "good"} /><MetricCard label="Overdue" value={String(overdue)} note="Target completion exceeded" icon={CalendarClock} tone={overdue ? "critical" : "good"} /><MetricCard label="Planned hours" value={`${hours.toFixed(1)}h`} note="Open assigned workload" icon={Clock3} /></div>
    <div className="maintenance-layout"><section className="panel panel-pad"><PanelTitle title="Assigned route and work queue" description={`${technician.trades.join(" · ")} · ${technician.certifications.join(" · ")}`} />{work.length ? <div className="assignment-list">{work.map((item, index) => { const store = demoData.stores.find((candidate) => candidate.id === item.storeId)!; const asset = demoData.assets.find((candidate) => candidate.id === item.assetId); const checks = demoData.checklistItems.filter((candidate) => candidate.workOrderId === item.id); const complete = checks.filter((candidate) => candidate.completed).length; return <article className="assignment-card" key={item.id}><div className="assignment-sequence">{index + 1}</div><div className="assignment-main"><div className="record-line"><Link className="row-link mono" href={`/work-orders/${item.id}`}>{item.number}</Link><StatusBadge tone={statusTone(item.status)}>{workOrderStatusLabel[item.status]}</StatusBadge><StatusBadge tone={item.safetyRisk === "high" ? "critical" : "warning"}>{item.safetyRisk} safety risk</StatusBadge></div><h3>{item.title}</h3><p>{item.description}</p><div className="assignment-meta"><span><MapPin />Store {store.code} · {store.address1}, {store.city}</span><span><Wrench />{asset?.assetTag} · {asset?.name}</span><span><CalendarClock />Due {item.dueAt ? formatDate(item.dueAt, true) : "not set"}</span><span><Clock3 />{item.estimatedHours}h planned · {item.actualHours}h recorded</span><span><CheckCircle2 />{complete}/{checks.length} checklist items</span><span><Package />{demoData.partsUsed.filter((candidate) => candidate.workOrderId === item.id).length} parts recorded</span></div></div><Link className="button primary" href={`/work-orders/${item.id}`}>{item.status === "visit_active" ? "Continue work" : "Open assignment"}</Link></article>; })}</div> : <div className="empty-state">No open assignments for this technician.</div>}</section>
      <aside className="stack"><section className="panel panel-pad"><PanelTitle title="Technician profile" description="Regional scope and current readiness" /><div className="technician-profile"><div className="avatar-large">{technician.name.split(" ").map((item) => item[0]).join("")}</div><div><h3>{technician.name}</h3><p>{technician.title}</p><StatusBadge tone={technician.status === "available" ? "good" : "active"}>{technician.status}</StatusBadge></div></div><div className="detail-pairs"><div><span>Regions</span><strong>{technician.regionIds.map((id) => demoData.regions.find((item) => item.id === id)?.name).join(", ")}</strong></div><div><span>Trades</span><strong>{technician.trades.join(", ")}</strong></div><div><span>Certifications</span><strong>{technician.certifications.join(", ")}</strong></div><div><span>Contact</span><strong>{technician.phone}</strong></div></div></section><div className="callout warning"><strong>Mobile execution standard</strong><p>Technicians can start work, complete required safety and verification steps, capture labor and materials, add notes and proof, then submit for store verification from the same work order.</p></div></aside></div>
  </div></AppShell>;
}
