"use client";

import { Check, CircleDollarSign, FileText, Inbox, ShieldCheck, UploadCloud, Wrench } from "lucide-react";
import Link from "next/link";
import { type DragEvent, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Breadcrumbs, MetricCard, PageHeader, PanelTitle, StatusBadge } from "@/components/ui";
import { formatCurrency, formatDate, formatPercent, pmCompliance } from "@/lib/domain/analytics";
import { demoData, DEMO_NOW } from "@/lib/demo/data";
import { statusTone, workOrderStatusLabel } from "@/lib/presentation";

export function PmPage() {
  const compliance = pmCompliance(demoData, {}, DEMO_NOW);
  const missed = demoData.pmOccurrences.filter((item) => item.status === "missed");
  const documentation = demoData.pmOccurrences.filter((item) => item.status === "documentation_pending");
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Preventive Maintenance" }]} /><PageHeader eyebrow="Planned work" title="Preventive maintenance" description="Recurring plans create dated occurrences with explicit windows, proof requirements and vendor acceptance—separate from reactive work." />
    <div className="metric-grid"><MetricCard label="On-time compliance" value={formatPercent(compliance.value)} note={`${compliance.numerator} of ${compliance.denominator} verified eligible occurrences`} icon={ShieldCheck} tone={compliance.value >= .9 ? "good" : "warning"} /><MetricCard label="Active plans" value={String(demoData.pmPlans.filter((item) => item.active).length)} note="Across stores, systems and assets" icon={Wrench} /><MetricCard label="Missed occurrences" value={String(missed.length)} note="Recovery work required" icon={Inbox} tone="critical" /><MetricCard label="Documentation pending" value={String(documentation.length)} note="Not counted as compliant" icon={FileText} tone="warning" /></div>
    <div className="callout warning" style={{ marginBottom: 14 }}><strong>Store 45 · April Beer Cave PM was missed</strong><p>Recovery work order CWO-0264 is open. The occurrence remains missed; rescheduling does not rewrite the original result.</p></div>
    <div className="split-grid"><section className="panel panel-pad"><PanelTitle title="Upcoming and exception occurrences" description="Occurrence status is evaluated against the plan’s early and late windows." /><div className="exception-list">{demoData.pmOccurrences.sort((a, b) => b.dueAt.localeCompare(a.dueAt)).slice(0, 18).map((occurrence) => { const plan = demoData.pmPlans.find((item) => item.id === occurrence.planId)!; const store = demoData.stores.find((item) => item.id === occurrence.storeId)!; return <div className="exception-row" key={occurrence.id}><span className={`exception-bar ${occurrence.status === "missed" ? "red" : ""}`} /><span className="exception-copy"><strong>{store.name} · {plan.name}</strong><span>Due {formatDate(occurrence.dueAt)} · window {formatDate(occurrence.windowStart)}–{formatDate(occurrence.windowEnd)}</span></span><StatusBadge tone={occurrence.status === "missed" ? "missed" : occurrence.verified ? "good" : "pending"}>{occurrence.status.replaceAll("_", " ")}</StatusBadge></div>;})}</div></section>
      <section className="panel panel-pad"><PanelTitle title="Plan library" description="Requirements stay consistent while scope remains flexible." />{demoData.pmPlans.map((plan) => <div className="record-card" style={{ padding: 13, borderRadius: 10, marginBottom: 8 }} key={plan.id}><div className="record-line"><strong>{plan.name}</strong><StatusBadge tone={plan.active ? "good" : "neutral"}>{plan.frequency}</StatusBadge></div><span className="subtext">{plan.scopeLabel} · {demoData.vendors.find((vendor) => vendor.id === plan.vendorId)?.shortName}</span><span className="subtext">Proof: {plan.requiredDocument} · ± {plan.earlyWindowDays}/{plan.lateWindowDays} day window</span></div>)}</section></div>
  </div></AppShell>;
}

export function VendorsPage() {
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Vendors" }]} /><PageHeader eyebrow="Lightweight collaboration" title="Vendors" description="Clark’s requests acceptance, decline or clarification. The vendor keeps its own dispatch board, technician assignment and route logic." />
    <div className="callout" style={{ marginBottom: 14 }}><strong>Boundary by design</strong><p>No duplicate technician roster, dispatch queue, inventory or vendor scheduling system lives here. Clark’s retains customer-side accountability and proof.</p></div>
    <div className="triple-grid">{demoData.vendors.map((vendor) => { const work = demoData.workOrders.filter((item) => item.vendorId === vendor.id); const open = work.filter((item) => !["closed", "cancelled"].includes(item.status)); const pending = work.filter((item) => item.vendorAcceptance === "pending"); const spend = demoData.invoices.filter((invoice) => invoice.vendorId === vendor.id && invoice.status === "paid").reduce((sum, invoice) => sum + invoice.totalCents, 0); return <section className="panel panel-pad" key={vendor.id}><PanelTitle title={vendor.name} description={vendor.trade} /><div className="coverage-grid"><div className="coverage-item"><strong>{open.length}</strong><span>open work orders</span></div><div className="coverage-item"><strong>{pending.length}</strong><span>awaiting response</span></div><div className="coverage-item"><strong>{formatCurrency(spend, true)}</strong><span>recorded paid invoices</span></div><div className="coverage-item"><strong>{demoData.visits.filter((visit) => visit.vendorId === vendor.id).length}</strong><span>verified visits</span></div></div><p className="subtext" style={{ marginTop: 12 }}>{vendor.dispatchEmail}</p></section>;})}</div>
    <section className="panel table-wrap"><PanelTitle title="Vendor response queue" description="Opaque-link responses update Clark’s work order only." /><table className="data-table"><thead><tr><th>Work order</th><th>Vendor</th><th>Status</th><th>Response</th><th>Customer control</th></tr></thead><tbody>{demoData.workOrders.filter((item) => item.vendorId && !["closed", "cancelled"].includes(item.status)).slice(0, 15).map((item) => <tr key={item.id}><td><Link className="row-link mono" href={`/work-orders/${item.id}`}>{item.number}</Link><span className="subtext">{item.title}</span></td><td>{demoData.vendors.find((vendor) => vendor.id === item.vendorId)?.name}</td><td><StatusBadge tone={statusTone(item.status)}>{workOrderStatusLabel[item.status]}</StatusBadge></td><td><StatusBadge tone={item.vendorAcceptance === "accepted" ? "accepted" : "pending"}>{item.vendorAcceptance.replaceAll("_", " ")}</StatusBadge></td><td>{item.accountableParty}<span className="subtext">{item.nextAction}</span></td></tr>)}</tbody></table></section>
  </div></AppShell>;
}

export function FilesPage() {
  const [uploaded, setUploaded] = useState<string[]>([]);
  const [dragging, setDragging] = useState(false);
  const [message, setMessage] = useState("");
  async function acceptFiles(files: FileList | null) {
    if (!files?.length) return;
    const selected = Array.from(files);
    const names = selected.map((file) => file.name);
    await Promise.all(selected.map(async (file) => {
      const body = new FormData();
      body.append("file", file);
      await fetch("/api/uploads", { method: "POST", body });
    }));
    setUploaded((current) => [...names, ...current]);
    setMessage(`${names.length} file${names.length === 1 ? "" : "s"} classified in this demo session.`);
  }
  function drop(event: DragEvent<HTMLDivElement>) { event.preventDefault(); setDragging(false); void acceptFiles(event.dataTransfer.files); }
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Files & Invoices" }]} /><PageHeader eyebrow="Operational records" title="Files & invoices" description="Documents are classified, linked to work and stored once. Invoice value rolls up from component to asset, system, category, store and company." />
    <div className="metric-grid"><MetricCard label="Documents" value={String(demoData.documents.length + uploaded.length)} note="Classified source files" icon={FileText} /><MetricCard label="Invoices in review" value={String(demoData.invoices.filter((item) => ["submitted", "review"].includes(item.status)).length)} note="Require financial control" icon={Inbox} tone="warning" /><MetricCard label="Paid invoice value" value={formatCurrency(demoData.invoices.filter((item) => item.status === "paid").reduce((sum, item) => sum + item.totalCents, 0), true)} note="Before posted credits" icon={CircleDollarSign} /><MetricCard label="Potential credits" value={formatCurrency(demoData.credits.filter((item) => item.status === "potential").reduce((sum, item) => sum + item.amountCents, 0))} note="Not deducted until posted" icon={Check} /></div>
    <div className="split-grid"><section className="panel panel-pad"><PanelTitle title="Document library" description="Filterable in production by classification, link, uploader and date." /><div className="document-grid">{uploaded.map((name) => <div className="document-card" key={name}><span className="document-icon"><FileText /></span><span><strong>{name}</strong><span>new upload · needs classification</span></span><StatusBadge tone="pending">session</StatusBadge></div>)}{demoData.documents.map((document) => <Link className="document-card" href={document.href} key={document.id}><span className="document-icon"><FileText /></span><span><strong>{document.name}</strong><span>{document.classification.replaceAll("_", " ")} · {document.uploadedBy}</span></span><StatusBadge tone={document.visibility === "internal" ? "neutral" : "info"}>{document.visibility.replaceAll("_", " ")}</StatusBadge></Link>)}</div></section>
      <section className="stack"><div className="panel panel-pad"><PanelTitle title="Upload and classify" description="R2-backed in the hosted environment; session preview works locally." /><div onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={drop} style={{ border: `2px dashed ${dragging ? "#0e6255" : "#c8d1cc"}`, borderRadius: 12, padding: 25, textAlign: "center", background: dragging ? "#e5f1ee" : "#f8f8f5" }}><UploadCloud size={26} color="#0e6255" /><p style={{ fontSize: 11, color: "#536465" }}>Drop service tickets, quotes, proof, invoices or equipment records</p><label className="button small">Choose files<input className="sr-only" multiple type="file" onChange={(event) => void acceptFiles(event.target.files)} /></label></div>{message && <div className="result-state"><strong>{message}</strong></div>}</div>
        <div className="callout warning"><strong>Invoice allocation control</strong><p>An invoice cannot be approved when allocation lines do not equal its total. Potential credits remain separate until posted.</p></div></section></div>
    <section className="panel table-wrap"><PanelTitle title="Invoice register" description="Financial state and operational classification remain distinct." /><table className="data-table"><thead><tr><th>Invoice</th><th>Work order</th><th>Vendor</th><th>Issued</th><th>Status</th><th className="numeric">Total</th></tr></thead><tbody>{demoData.invoices.sort((a, b) => b.issuedAt.localeCompare(a.issuedAt)).slice(0, 20).map((invoice) => <tr key={invoice.id}><td className="mono"><strong>{invoice.number}</strong></td><td><Link className="row-link mono" href={`/work-orders/${invoice.workOrderId}`}>{demoData.workOrders.find((item) => item.id === invoice.workOrderId)?.number}</Link></td><td>{demoData.vendors.find((vendor) => vendor.id === invoice.vendorId)?.shortName}</td><td>{formatDate(invoice.issuedAt)}</td><td><StatusBadge tone={invoice.status === "paid" ? "good" : "pending"}>{invoice.status}</StatusBadge></td><td className="numeric"><strong>{formatCurrency(invoice.totalCents)}</strong></td></tr>)}</tbody></table></section>
  </div></AppShell>;
}
