import { ArrowRight, Check, CircleDollarSign, Factory, MapPin, ShieldAlert, Store as StoreIcon, Wrench } from "lucide-react";
import Link from "@/components/site-link";
import { AppShell } from "@/components/app-shell";
import { Breadcrumbs, MetricCard, PageHeader, PanelTitle, StatusBadge } from "@/components/ui";
import { formatCurrency, formatDate, formatPercent, pmCompliance, replacementAnalysis, replacementWatchlist, spendForPeriod, storeComparison, trailingPeriods } from "@/lib/domain/analytics";
import type { Asset, Component, Store, StoreSystem } from "@/lib/domain/types";
import { demoData, DEMO_NOW } from "@/lib/demo/data";
import { statusTone, workOrderStatusLabel } from "@/lib/presentation";
import { StoreDirectory } from "@/components/store-directory";

export function StoresPageLegacy() {
  const rows = storeComparison(demoData, DEMO_NOW).sort((a, b) => b.spend - a.spend);
  const candidates = replacementWatchlist(demoData, DEMO_NOW).length;
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Stores" }]} /><PageHeader eyebrow="Portfolio comparison" title="Stores" description="Compare operating burden across the company, then drill into a store, system, asset and component without changing the cost logic." />
    <div className="metric-grid"><MetricCard label="Stores in demo scope" value={String(rows.length)} note="Pilot architecture sized beyond 65" icon={StoreIcon} /><MetricCard label="Outlier stores" value={String(rows.filter((row) => row.isOutlier).length)} note="Rule-based refrigeration signal" icon={ShieldAlert} tone="critical" /><MetricCard label="Replacement reviews" value={String(candidates)} note="Explainable capital candidates" icon={Factory} tone="warning" /><MetricCard label="Regions" value={String(demoData.regions.length)} note="Optional for single-store operators" icon={MapPin} /></div>
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Store</th><th>Region</th><th className="numeric">Open / critical</th><th className="numeric">TTM spend</th><th>PM compliance</th><th className="numeric">Reactive : planned</th><th className="numeric">Repeat visits</th><th>Portfolio signal</th></tr></thead><tbody>{rows.map((row) => <tr key={row.store.id}><td><Link className="row-link" href={`/stores/${row.store.id}`}>{row.store.name}</Link><span className="subtext">{row.store.city}, {row.store.state}</span></td><td>{demoData.regions.find((region) => region.id === row.store.regionId)?.name ?? "No region"}</td><td className="numeric"><strong>{row.openCount}</strong> / {row.criticalCount}</td><td className="numeric"><strong>{formatCurrency(row.spend)}</strong><span className="subtext">{row.change >= 0 ? "+" : ""}{formatPercent(row.change)} vs prior TTM</span></td><td><div className="progress-row" style={{ gridTemplateColumns: "1fr 38px", margin: 0 }}><div className="progress-track"><div className="progress-fill" style={{ width: formatPercent(row.pm.value) }} /></div><strong>{formatPercent(row.pm.value)}</strong></div></td><td className="numeric">{Number.isFinite(row.reactivePlannedRatio) ? `${row.reactivePlannedRatio.toFixed(1)}×` : "No planned spend"}</td><td className="numeric">{row.repeatVisits}</td><td>{row.isOutlier ? <StatusBadge tone="critical">{row.outlierRatio.toFixed(1)}× median</StatusBadge> : <StatusBadge tone="good">Within range</StatusBadge>}</td></tr>)}</tbody></table></div>
  </div></AppShell>;
}

export function StoresPage() { return <StoreDirectory />; }

export function StoreDetail({ store }: { store: Store }) {
  const comparison = storeComparison(demoData, DEMO_NOW).find((row) => row.store.id === store.id)!;
  const systems = demoData.systems.filter((item) => item.storeId === store.id);
  const workOrders = demoData.workOrders.filter((item) => item.storeId === store.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const candidates = replacementWatchlist(demoData, DEMO_NOW).filter(({ asset }) => systems.some((system) => system.id === asset.storeSystemId));
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Stores", href: "/stores" }, { label: store.name }]} /><PageHeader eyebrow={`${store.code} · ${demoData.regions.find((region) => region.id === store.regionId)?.name ?? "Independent"}`} title={store.name} description={`${store.address1}, ${store.city}, ${store.state} ${store.postalCode} · ${store.managerName} · ${store.geofenceRadiusM}m verification radius`}><Link className="button primary" href="/work-orders/new">Create work order</Link><Link className="button" href="/cost-centers/new">Add cost center</Link></PageHeader>
    <div className="metric-grid"><MetricCard label="TTM spend" value={formatCurrency(comparison.spend)} note={`${comparison.change >= 0 ? "+" : ""}${formatPercent(comparison.change)} vs prior TTM`} icon={CircleDollarSign} tone={comparison.isOutlier ? "critical" : ""} /><MetricCard label="Open work" value={String(comparison.openCount)} note={`${comparison.criticalCount} critical`} icon={Wrench} /><MetricCard label="PM compliance" value={formatPercent(comparison.pm.value)} note={`${comparison.pm.numerator} of ${comparison.pm.denominator} verified on time`} icon={Check} /><MetricCard label="Replacement reviews" value={String(candidates.length)} note="Rules met for capital review" icon={Factory} tone={candidates.length ? "warning" : "good"} /></div>
    {comparison.isOutlier && <div className="callout danger" style={{ marginBottom: 14 }}><strong>Explainable outlier: refrigeration spend is {comparison.outlierRatio.toFixed(1)}× the company median</strong><p>This is a review signal, not a causal claim. Drill into Beer Cave Refrigeration to see classified cost, visits, failures and PM records.</p></div>}
    <div className="split-grid"><section className="panel panel-pad"><PanelTitle title="Systems" description="Store-level classification starts here; assets are added only when known." /><div className="exception-list">{systems.map((system) => { const systemAssets = demoData.assets.filter((asset) => asset.storeSystemId === system.id); const { now, ttmStart } = trailingPeriods(DEMO_NOW); const spend = spendForPeriod(demoData, ttmStart, now, { systemId: system.id }); return <Link className="exception-row" key={system.id} href={`/stores/${store.id}/systems/${system.id}`}><span className={`exception-bar ${system.state === "exception" ? "red" : ""}`} /><span className="exception-copy"><strong>{system.name}</strong><span>{system.type} · {systemAssets.length} assets · {formatCurrency(spend)} TTM</span></span><StatusBadge tone={system.state === "exception" ? "critical" : system.state === "watch" ? "warning" : "good"}>{system.state}</StatusBadge></Link>;})}</div></section>
      <section className="panel panel-pad"><PanelTitle title="Open control actions" description="Accountability stays explicit at store level." />{workOrders.filter((item) => !["closed", "cancelled"].includes(item.status)).slice(0, 6).map((item) => <Link className="exception-row" href={`/work-orders/${item.id}`} key={item.id}><span className="exception-bar red" /><span className="exception-copy"><strong>{item.number} · {item.title}</strong><span>{item.accountableParty} · {item.nextAction}</span></span><StatusBadge tone={statusTone(item.status)}>{workOrderStatusLabel[item.status]}</StatusBadge></Link>)}</section></div>
    <section className="panel table-wrap"><PanelTitle title="Recent work history" description="All statuses remain visible for audit and trend analysis." /><table className="data-table"><thead><tr><th>Work order</th><th>Classification</th><th>Status</th><th>Created</th><th className="numeric">Exposure</th></tr></thead><tbody>{workOrders.slice(0, 12).map((item) => <tr key={item.id}><td><Link className="row-link mono" href={`/work-orders/${item.id}`}>{item.number}</Link><span className="subtext">{item.title}</span></td><td>{demoData.categories.find((category) => category.id === item.categoryId)?.name}<span className="subtext">{demoData.systems.find((system) => system.id === item.systemId)?.name ?? "Store + category"}</span></td><td><StatusBadge tone={statusTone(item.status)}>{workOrderStatusLabel[item.status]}</StatusBadge></td><td>{formatDate(item.createdAt)}</td><td className="numeric">{formatCurrency(item.costExposureCents)}</td></tr>)}</tbody></table></section>
  </div></AppShell>;
}

export function CategoryExplorer({ categoryId }: { categoryId: string }) {
  const category = demoData.categories.find((item) => item.id === categoryId) ?? demoData.categories[0];
  const systems = demoData.systems.filter((item) => item.categoryId === category.id);
  const { now, ttmStart } = trailingPeriods(DEMO_NOW);
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Systems & Assets" }, { label: category.name }]} /><PageHeader eyebrow="Company category explorer" title={category.name} description="Compare the same service system across stores, then follow a cost signal down to the physical equipment." />
    <div className="filter-bar"><span className="period-chip">Trailing 12 months through Aug 5, 2026</span><span className="filter-summary">{systems.length} store systems · {demoData.assets.filter((asset) => systems.some((system) => system.id === asset.storeSystemId)).length} assets</span></div>
    <div className="panel table-wrap"><table className="data-table"><thead><tr><th>Store / system</th><th>State</th><th className="numeric">TTM spend</th><th className="numeric">Open work</th><th>PM compliance</th><th className="numeric">Assets on watch</th><th></th></tr></thead><tbody>{systems.sort((a, b) => spendForPeriod(demoData, ttmStart, now, { systemId: b.id }) - spendForPeriod(demoData, ttmStart, now, { systemId: a.id })).map((system) => { const store = demoData.stores.find((item) => item.id === system.storeId)!; const compliance = pmCompliance(demoData, { systemId: system.id }, DEMO_NOW); const assets = demoData.assets.filter((asset) => asset.storeSystemId === system.id); return <tr key={system.id}><td><Link className="row-link" href={`/stores/${store.id}/systems/${system.id}`}>{store.name} · {system.name}</Link><span className="subtext">{store.city}, {store.state}</span></td><td><StatusBadge tone={system.state === "exception" ? "critical" : system.state === "watch" ? "warning" : "good"}>{system.state}</StatusBadge></td><td className="numeric"><strong>{formatCurrency(spendForPeriod(demoData, ttmStart, now, { systemId: system.id }))}</strong></td><td className="numeric">{demoData.workOrders.filter((item) => item.systemId === system.id && !["closed", "cancelled"].includes(item.status)).length}</td><td>{formatPercent(compliance.value)}</td><td className="numeric">{assets.filter((asset) => asset.state !== "operational").length}</td><td><Link className="button small" href={`/stores/${store.id}/systems/${system.id}`}>Open <ArrowRight /></Link></td></tr>;})}</tbody></table></div>
  </div></AppShell>;
}

export function SystemDetail({ system }: { system: StoreSystem }) {
  const store = demoData.stores.find((item) => item.id === system.storeId)!;
  const category = demoData.categories.find((item) => item.id === system.categoryId)!;
  const assets = demoData.assets.filter((item) => item.storeSystemId === system.id);
  const { now, ttmStart, priorStart } = trailingPeriods(DEMO_NOW);
  const current = spendForPeriod(demoData, ttmStart, now, { systemId: system.id });
  const prior = spendForPeriod(demoData, priorStart, ttmStart, { systemId: system.id });
  const pm = pmCompliance(demoData, { systemId: system.id }, DEMO_NOW);
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Stores", href: "/stores" }, { label: store.name, href: `/stores/${store.id}` }, { label: system.name }]} /><PageHeader eyebrow={`${category.name} cost center · ${system.code}`} title={system.name} description={`${store.name} · ${system.type} · ${system.location} · GL ${system.glCode}.`}><Link className="button primary" href="/assets/new">Add asset</Link><Link className="button" href="/work-orders/new">Create work order</Link></PageHeader>
    <div className="metric-grid"><MetricCard label="TTM classified spend" value={formatCurrency(current)} note={`${prior ? `${formatPercent((current - prior) / prior)} vs prior TTM` : "No prior period"}`} icon={CircleDollarSign} tone={system.state === "exception" ? "critical" : ""} /><MetricCard label="Assets" value={String(assets.length)} note={`${assets.filter((item) => item.state !== "operational").length} require attention`} icon={Factory} /><MetricCard label="PM compliance" value={formatPercent(pm.value)} note={`${pm.numerator} of ${pm.denominator} verified on time`} icon={Check} /><MetricCard label="Open work" value={String(demoData.workOrders.filter((item) => item.systemId === system.id && !["closed", "cancelled"].includes(item.status)).length)} note="Across all mapped assets" icon={Wrench} /></div>
    <div className="split-grid"><section className="panel panel-pad"><PanelTitle title="Asset registry" description="Cost and service history accumulate at known equipment." /><div className="exception-list">{assets.map((asset) => { const analysis = replacementAnalysis(demoData, asset, DEMO_NOW); return <Link className="exception-row" href={`/assets/${asset.id}`} key={asset.id}><span className={`exception-bar ${analysis.recommended ? "red" : ""}`} /><span className="exception-copy"><strong>{asset.name} · {asset.assetClass}</strong><span>{asset.manufacturer} {asset.model} · installed {formatDate(asset.installedAt)} · {formatCurrency(analysis.currentReactive)} reactive TTM</span></span><StatusBadge tone={analysis.recommended ? "critical" : asset.state === "operational" ? "good" : "warning"}>{analysis.recommended ? "capital review" : asset.state}</StatusBadge></Link>;})}</div></section>
      <section className="panel panel-pad"><PanelTitle title="Preventive maintenance" description="Occurrences measured against explicit service windows." />{demoData.pmOccurrences.filter((item) => item.systemId === system.id).sort((a, b) => b.dueAt.localeCompare(a.dueAt)).slice(0, 8).map((item) => <div className="record-line" style={{ justifyContent: "space-between" }} key={item.id}><span><strong>{formatDate(item.dueAt)}</strong><span className="subtext">{formatDate(item.windowStart)} – {formatDate(item.windowEnd)}</span></span><StatusBadge tone={item.status === "missed" ? "missed" : item.verified ? "good" : "pending"}>{item.status.replaceAll("_", " ")}</StatusBadge></div>)}</section></div>
  </div></AppShell>;
}

export function AssetDetail({ asset }: { asset: Asset }) {
  const system = demoData.systems.find((item) => item.id === asset.storeSystemId)!;
  const store = demoData.stores.find((item) => item.id === system.storeId)!;
  const analysis = replacementAnalysis(demoData, asset, DEMO_NOW);
  const components = demoData.components.filter((item) => item.assetId === asset.id);
  const workOrders = demoData.workOrders.filter((item) => item.assetId === asset.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Stores", href: "/stores" }, { label: store.name, href: `/stores/${store.id}` }, { label: system.name, href: `/stores/${store.id}/systems/${system.id}` }, { label: asset.name }]} />
    <div className="detail-hero"><section className="record-card"><div className="record-line"><span className="mono">{asset.assetTag} · {asset.serial}</span><StatusBadge tone={asset.state === "operational" ? "good" : "warning"}>{asset.state}</StatusBadge>{analysis.recommended && <StatusBadge tone="critical">Capital review recommended</StatusBadge>}<Link className="button small" href="/components/new">Add component</Link><Link className="button primary small" href="/work-orders/new">Create work order</Link></div><h1>{asset.name}</h1><p className="description">{asset.manufacturer} {asset.model} · {asset.assetClass} · {asset.location} · condition {asset.condition}.</p><div className="record-meta"><div className="meta-item"><span>Installed</span><strong>{formatDate(asset.installedAt)}</strong></div><div className="meta-item"><span>Expected life</span><strong>{asset.expectedLifeYears} years</strong></div><div className="meta-item"><span>Replacement estimate</span><strong>{formatCurrency(asset.replacementCostCents)}</strong></div><div className="meta-item"><span>Warranty through</span><strong>{formatDate(asset.warrantyEndsAt)}</strong></div></div></section><aside className="control-card"><span className="label">Decision posture</span><h3>{analysis.recommended ? "Prepare capital review" : "Continue operating"}</h3><p>{analysis.reasons.length} rule conditions currently apply. Facilities must still validate operational context, lead time and funding.</p><div className="due"><strong>Reactive burden:</strong> {formatPercent(analysis.burden)} of replacement estimate<br /><strong>TTM repairs:</strong> {formatCurrency(analysis.currentReactive)}</div></aside></div>
    <div className="split-grid"><section className="panel panel-pad"><PanelTitle title="Why this asset is flagged" description="Each condition exposes its measured value and threshold." /><div className="reason-list">{analysis.reasons.map((reason) => <div className="reason" key={reason.key}><span className="reason-check"><Check /></span><span><strong>{reason.label}</strong><span>{reason.threshold}</span></span><b>{reason.value}</b></div>)}</div></section><section className="panel panel-pad"><PanelTitle title="Component registry" description="Optional depth when a repair identifies a replaceable part." />{components.length ? components.map((component) => <Link className="exception-row" href={`/components/${component.id}`} key={component.id}><span className="exception-bar" /><span className="exception-copy"><strong>{component.name}</strong><span>{component.type} · {component.partNumber}</span></span><ArrowRight /></Link>) : <div className="empty-state">No components registered. Asset-level classification remains valid.</div>}</section></div>
    <section className="panel table-wrap"><PanelTitle title="Repair and failure history" description={`${analysis.visitCount} verified visits · ${analysis.failureCount} reactive failures in the trailing 12 months`} /><table className="data-table"><thead><tr><th>Work order</th><th>Type</th><th>Status</th><th>Opened</th><th>Vendor</th><th className="numeric">Recorded cost</th></tr></thead><tbody>{workOrders.map((item) => <tr key={item.id}><td><Link className="row-link mono" href={`/work-orders/${item.id}`}>{item.number}</Link><span className="subtext">{item.title}</span></td><td>{item.workType}</td><td><StatusBadge tone={statusTone(item.status)}>{workOrderStatusLabel[item.status]}</StatusBadge></td><td>{formatDate(item.createdAt)}</td><td>{demoData.vendors.find((vendor) => vendor.id === item.vendorId)?.shortName}</td><td className="numeric">{formatCurrency(demoData.allocations.filter((allocation) => allocation.workOrderId === item.id).reduce((sum, allocation) => sum + allocation.amountCents, 0))}</td></tr>)}</tbody></table></section>
  </div></AppShell>;
}

export function ComponentDetail({ component }: { component: Component }) {
  const asset = demoData.assets.find((item) => item.id === component.assetId)!;
  const system = demoData.systems.find((item) => item.id === asset.storeSystemId)!;
  const store = demoData.stores.find((item) => item.id === system.storeId)!;
  const allocations = demoData.allocations.filter((item) => item.componentId === component.id);
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: store.name, href: `/stores/${store.id}` }, { label: system.name, href: `/stores/${store.id}/systems/${system.id}` }, { label: asset.name, href: `/assets/${asset.id}` }, { label: component.name }]} /><PageHeader eyebrow="Replaceable component" title={component.name} description={`${component.type} · part ${component.partNumber} · installed on ${asset.name}`}><Link className="button primary" href="/work-orders/new">Create work order</Link></PageHeader>
    <div className="metric-grid"><MetricCard label="Lifetime classified cost" value={formatCurrency(allocations.reduce((sum, item) => sum + item.amountCents, 0))} note={`${allocations.length} allocation lines`} icon={CircleDollarSign} /><MetricCard label="Installed" value={formatDate(component.installedAt)} note={`Warranty to ${formatDate(component.warrantyEndsAt)}`} icon={Check} /><MetricCard label="Vendor" value={demoData.vendors.find((item) => item.id === component.vendorId)?.shortName ?? "Unknown"} note="Supplying / servicing vendor" icon={Wrench} /><MetricCard label="Parent asset" value={asset.name} note={system.name} icon={Factory} /></div>
    <section className="panel table-wrap"><PanelTitle title="Component-linked costs" description="Only costs explicitly attributed to this component appear here." /><table className="data-table"><thead><tr><th>Work order</th><th>Invoice</th><th>Work class</th><th>Cost category</th><th className="numeric">Amount</th></tr></thead><tbody>{allocations.map((item) => <tr key={item.id}><td><Link className="row-link mono" href={`/work-orders/${item.workOrderId}`}>{demoData.workOrders.find((workOrder) => workOrder.id === item.workOrderId)?.number}</Link></td><td>{demoData.invoices.find((invoice) => invoice.id === item.invoiceId)?.number}</td><td>{item.workClass}</td><td>{item.costCategory}</td><td className="numeric"><strong>{formatCurrency(item.amountCents)}</strong></td></tr>)}</tbody></table></section>
  </div></AppShell>;
}
