"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Boxes, Building2, ClipboardPlus, Cpu, Save, Store, Wrench } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Breadcrumbs, PageHeader, PanelTitle, StatusBadge } from "@/components/ui";
import { demoData } from "@/lib/demo/data";

type Entity = "stores" | "cost-centers" | "assets" | "components" | "work-orders";
type ApiRecord = Record<string, string | number | boolean | null>;

const entityMeta: Record<Entity, { label: string; singular: string; icon: typeof Store; description: string }> = {
  stores: { label: "Stores", singular: "store", icon: Store, description: "Create a location with its operating identity, address, region, manager and verification settings." },
  "cost-centers": { label: "Cost centers", singular: "cost center", icon: Building2, description: "Define a maintainable operating system such as Hot Food & Bakery, Beer Cave, HVAC or Fuel & Forecourt." },
  assets: { label: "Assets", singular: "asset", icon: Wrench, description: "Register the physical equipment owned by a cost center, including tag, class, condition and replacement value." },
  components: { label: "Components", singular: "component", icon: Cpu, description: "Add serviceable parts beneath an asset for failure history, warranty tracking and part-level cost." },
  "work-orders": { label: "Work orders", singular: "work order", icon: ClipboardPlus, description: "Issue a complete assignment to internal maintenance, a vendor, or both—with scope, SLA, safety and cost controls." },
};

function field(form: FormData, name: string) { return String(form.get(name) ?? "").trim(); }
function cents(form: FormData, name: string) { return Math.round(Number(field(form, name) || 0) * 100); }

export function RegistryConsole({ initialEntity = "stores", initialStoreId = "", initialSystemId = "", initialAssetId = "" }: { initialEntity?: Entity; initialStoreId?: string; initialSystemId?: string; initialAssetId?: string }) {
  const initialSystem = demoData.systems.find((item) => item.id === initialSystemId);
  const initialAsset = demoData.assets.find((item) => item.id === initialAssetId);
  const resolvedSystem = initialSystem ?? demoData.systems.find((item) => item.id === initialAsset?.storeSystemId);
  const [entity, setEntity] = useState<Entity>(initialEntity);
  const [records, setRecords] = useState<ApiRecord[]>([]);
  const [selectedStore, setSelectedStore] = useState(initialStoreId || resolvedSystem?.storeId || demoData.stores[0].id);
  const [selectedCategory, setSelectedCategory] = useState(resolvedSystem?.categoryId || demoData.categories[0].id);
  const [selectedSystem, setSelectedSystem] = useState(resolvedSystem?.id || demoData.systems[0].id);
  const [selectedAsset, setSelectedAsset] = useState(initialAsset?.id || demoData.assets[0].id);
  const [assignmentType, setAssignmentType] = useState("internal");
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const formRef = useRef<HTMLFormElement>(null);

  const availableSystems = useMemo(() => demoData.systems.filter((item) => item.storeId === selectedStore && (!selectedCategory || item.categoryId === selectedCategory)), [selectedStore, selectedCategory]);
  const availableAssets = useMemo(() => demoData.assets.filter((item) => item.storeSystemId === selectedSystem), [selectedSystem]);
  useEffect(() => { const timer = window.setTimeout(() => { const next = availableSystems[0]; if (next && !availableSystems.some((item) => item.id === selectedSystem)) setSelectedSystem(next.id); }, 0); return () => window.clearTimeout(timer); }, [availableSystems, selectedSystem]);
  useEffect(() => { const timer = window.setTimeout(() => { if (entity === "work-orders" && selectedAsset === "") return; const next = availableAssets[0]; if (next && !availableAssets.some((item) => item.id === selectedAsset)) setSelectedAsset(next.id); }, 0); return () => window.clearTimeout(timer); }, [availableAssets, selectedAsset, entity]);
  useEffect(() => {
    let cancelled = false;
    fetch(`/api/registry?entity=${entity}`).then((response) => response.json()).then((raw) => { const result = raw as { ok: boolean; records?: ApiRecord[] }; if (!cancelled && result.ok) setRecords(result.records ?? []); }).catch(() => undefined);
    return () => { cancelled = true; };
  }, [entity, message]);

  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setMessage("");
    const form = new FormData(event.currentTarget);
    let data: Record<string, unknown>;
    if (entity === "stores") data = { code: field(form, "code"), name: field(form, "name"), regionId: field(form, "regionId"), address1: field(form, "address1"), city: field(form, "city"), state: field(form, "state"), postalCode: field(form, "postalCode"), phone: field(form, "phone"), managerName: field(form, "managerName"), district: field(form, "district"), squareFeet: Number(field(form, "squareFeet") || 0) };
    else if (entity === "cost-centers") data = { storeId: field(form, "storeId"), categoryId: field(form, "categoryId"), code: field(form, "code"), name: field(form, "name"), type: field(form, "type"), description: field(form, "description"), location: field(form, "location"), glCode: field(form, "glCode"), annualBudgetCents: cents(form, "annualBudget"), ownerName: field(form, "ownerName"), maintenanceStrategy: field(form, "maintenanceStrategy") };
    else if (entity === "assets") data = { storeSystemId: field(form, "storeSystemId"), assetClass: field(form, "assetClass"), assetTag: field(form, "assetTag"), name: field(form, "name"), manufacturer: field(form, "manufacturer"), model: field(form, "model"), serial: field(form, "serial"), location: field(form, "location"), installedAt: field(form, "installedAt"), replacementCostCents: cents(form, "replacementCost"), criticality: field(form, "criticality") };
    else if (entity === "components") data = { assetId: field(form, "assetId"), type: field(form, "type"), name: field(form, "name"), partNumber: field(form, "partNumber"), serial: field(form, "serial"), quantity: Number(field(form, "quantity") || 1), unitCostCents: cents(form, "unitCost"), criticalSpare: form.get("criticalSpare") === "on", installedAt: field(form, "installedAt"), warrantyEndsAt: field(form, "warrantyEndsAt") };
    else {
      const assigneeId = field(form, "assigneeId");
      const technician = demoData.technicians.find((item) => item.id === assigneeId);
      const vendor = demoData.vendors.find((item) => item.id === assigneeId);
      data = { storeId: field(form, "storeId"), categoryId: field(form, "categoryId"), systemId: field(form, "systemId") || undefined, assetId: field(form, "assetId") || undefined, componentId: field(form, "componentId") || undefined, title: field(form, "title"), description: field(form, "description"), location: field(form, "location"), requestedBy: field(form, "requestedBy"), priority: field(form, "priority"), workType: field(form, "workType"), assignmentType, assignedToId: technician?.id, assignedToName: technician?.name ?? vendor?.name, vendorId: vendor?.id, dueAt: field(form, "dueAt") || undefined, estimatedHours: Number(field(form, "estimatedHours") || 0), safetyRisk: field(form, "safetyRisk"), accessInstructions: field(form, "accessInstructions"), nteCents: cents(form, "nte") };
    }
    try {
      const response = await fetch("/api/registry", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entity, data }) });
      const result = await response.json() as { ok: boolean; error?: string; number?: string };
      if (!response.ok || !result.ok) throw new Error(result.error ?? "Unable to save record");
      setMessage(`${result.number ? `${result.number} · ` : ""}${entityMeta[entity].singular} created and saved to the hosted operations database.`);
      formRef.current?.reset();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save record"); }
    finally { setSaving(false); }
  }

  const meta = entityMeta[entity];
  return <AppShell><div className="page registry-page">
    <Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Setup & creation" }]} />
    <PageHeader eyebrow="Portfolio administration" title="Create and manage operational records" description="A guided hierarchy for a single independent store or a 65-location regional operator. Every created record is tenant-scoped and durable."><StatusBadge tone="good">D1-backed registry</StatusBadge></PageHeader>
    <div className="registry-tabs" role="tablist">{(Object.keys(entityMeta) as Entity[]).map((item) => { const Icon = entityMeta[item].icon; return <button key={item} type="button" role="tab" aria-selected={entity === item} className={entity === item ? "active" : ""} onClick={() => { setEntity(item); setMessage(""); }}><Icon />{entityMeta[item].label}</button>; })}</div>
    <div className="registry-grid">
      <section className="panel panel-pad"><PanelTitle title={`Create ${meta.singular}`} description={meta.description} />
        <form ref={formRef} className="admin-form" onSubmit={submit}>
          {entity === "stores" && <><FormField label="Store number" name="code" required placeholder="156" /><FormField label="Store name" name="name" required placeholder="Store 156 - New Market" /><SelectField label="Region" name="regionId" options={demoData.regions.map((item) => [item.id, item.name])} /><FormField label="Street address" name="address1" required placeholder="410 Market Street" wide /><FormField label="City" name="city" required /><FormField label="State" name="state" required defaultValue="PA" /><FormField label="ZIP code" name="postalCode" required /><FormField label="Phone" name="phone" /><FormField label="Store manager" name="managerName" /><FormField label="District" name="district" placeholder="District 9" /><FormField label="Square feet" name="squareFeet" type="number" /></>}
          {entity === "cost-centers" && <><SelectField label="Store" name="storeId" value={selectedStore} onChange={setSelectedStore} options={demoData.stores.map((item) => [item.id, `${item.code} · ${item.city} · ${item.address1}`])} wide /><SelectField label="Service category" name="categoryId" options={demoData.categories.map((item) => [item.id, item.name])} /><FormField label="Cost center code" name="code" required placeholder="156-FOOD" /><FormField label="Name" name="name" required placeholder="Hot Food & Bakery" /><FormField label="System type" name="type" required placeholder="Ovens, fryers & holding" /><FormField label="Physical location" name="location" placeholder="Foodservice line" /><FormField label="GL code" name="glCode" /><FormField label="Annual budget ($)" name="annualBudget" type="number" /><FormField label="Responsible owner" name="ownerName" /><SelectField label="Strategy" name="maintenanceStrategy" options={[["preventive", "Preventive"], ["condition_based", "Condition based"], ["run_to_failure", "Run to failure"], ["statutory", "Statutory"]]} /><TextField label="Description" name="description" wide /></>}
          {entity === "assets" && <><SelectField label="Store" name="storePicker" value={selectedStore} onChange={setSelectedStore} options={demoData.stores.map((item) => [item.id, `${item.code} · ${item.city}`])} /><SelectField label="Category" name="categoryPicker" value={selectedCategory} onChange={setSelectedCategory} options={demoData.categories.map((item) => [item.id, item.name])} /><SelectField label="Cost center" name="storeSystemId" value={selectedSystem} onChange={setSelectedSystem} options={availableSystems.map((item) => [item.id, `${item.code} · ${item.name}`])} wide /><FormField label="Asset tag" name="assetTag" required placeholder="156-OVEN1" /><FormField label="Asset name" name="name" required placeholder="Combi Oven OVEN-1" /><FormField label="Asset class" name="assetClass" required placeholder="Combi Oven" /><FormField label="Manufacturer" name="manufacturer" /><FormField label="Model" name="model" /><FormField label="Serial number" name="serial" /><FormField label="Location" name="location" /><FormField label="Installed date" name="installedAt" type="date" /><FormField label="Replacement value ($)" name="replacementCost" type="number" /><SelectField label="Criticality" name="criticality" options={[["critical", "Critical"], ["high", "High"], ["standard", "Standard"]]} /></>}
          {entity === "components" && <><SelectField label="Store" name="storePicker" value={selectedStore} onChange={setSelectedStore} options={demoData.stores.map((item) => [item.id, `${item.code} · ${item.city}`])} /><SelectField label="Category" name="categoryPicker" value={selectedCategory} onChange={setSelectedCategory} options={demoData.categories.map((item) => [item.id, item.name])} /><SelectField label="Cost center" name="systemPicker" value={selectedSystem} onChange={setSelectedSystem} options={availableSystems.map((item) => [item.id, item.name])} /><SelectField label="Parent asset" name="assetId" value={selectedAsset} onChange={setSelectedAsset} options={availableAssets.map((item) => [item.id, `${item.assetTag} · ${item.name}`])} wide /><FormField label="Component name" name="name" required placeholder="Oven control board" /><FormField label="Component type" name="type" required placeholder="Control Board" /><FormField label="Part number" name="partNumber" /><FormField label="Serial number" name="serial" /><FormField label="Quantity" name="quantity" type="number" defaultValue="1" /><FormField label="Unit cost ($)" name="unitCost" type="number" /><FormField label="Installed date" name="installedAt" type="date" /><FormField label="Warranty end" name="warrantyEndsAt" type="date" /><label className="checkbox-field"><input type="checkbox" name="criticalSpare" />Critical spare should be stocked</label></>}
          {entity === "work-orders" && <><SelectField label="Store" name="storeId" value={selectedStore} onChange={setSelectedStore} options={demoData.stores.map((item) => [item.id, `${item.code} · ${item.city} · ${item.address1}`])} wide /><SelectField label="Category" name="categoryId" value={selectedCategory} onChange={setSelectedCategory} options={demoData.categories.map((item) => [item.id, item.name])} /><SelectField label="Cost center" name="systemId" value={selectedSystem} onChange={setSelectedSystem} options={availableSystems.map((item) => [item.id, `${item.code} · ${item.name}`])} /><SelectField label="Asset (optional)" name="assetId" value={selectedAsset} onChange={setSelectedAsset} options={[["", "Identify during diagnosis"], ...availableAssets.map((item) => [item.id, `${item.assetTag} · ${item.name}`])]} wide /><SelectField label="Component (optional)" name="componentId" options={[["", "Identify during diagnosis"], ...demoData.components.filter((item) => item.assetId === selectedAsset).map((item) => [item.id, `${item.partNumber} · ${item.name}`])]} wide /><FormField label="Work order title" name="title" required placeholder="Combi oven will not heat above 280°F" wide /><TextField label="Problem description / requested scope" name="description" required wide /><FormField label="Exact location" name="location" placeholder="Foodservice line · Oven 1" /><FormField label="Requested by" name="requestedBy" required defaultValue="Facilities Service Desk" /><SelectField label="Priority" name="priority" options={[["critical", "Critical"], ["high", "High"], ["routine", "Routine"], ["low", "Low"]]} /><SelectField label="Work type" name="workType" options={[["reactive", "Reactive"], ["internal", "Internal maintenance"], ["preventive", "Preventive"], ["inspection", "Inspection"], ["emergency", "Emergency"], ["warranty", "Warranty"], ["capital", "Capital"]]} /><SelectField label="Assignment model" name="assignmentType" value={assignmentType} onChange={setAssignmentType} options={[["internal", "Internal maintenance"], ["vendor", "Service vendor"], ["blended", "Blended handoff"], ["unassigned", "Unassigned queue"]]} /><SelectField label="Assignee" name="assigneeId" options={assignmentType === "vendor" ? demoData.vendors.map((item) => [item.id, `${item.shortName} · ${item.trade}`]) : demoData.technicians.map((item) => [item.id, `${item.name} · ${item.trades.join(", ")}`])} wide /><FormField label="Target completion" name="dueAt" type="datetime-local" /><FormField label="Estimated hours" name="estimatedHours" type="number" defaultValue="2" /><SelectField label="Safety risk" name="safetyRisk" options={[["none", "None"], ["low", "Low"], ["moderate", "Moderate"], ["high", "High"]]} /><FormField label="Not-to-exceed ($)" name="nte" type="number" /><TextField label="Access and safety instructions" name="accessInstructions" wide /></>}
          <div className="form-actions"><button className="button primary" disabled={saving}><Save />{saving ? "Saving…" : `Create ${meta.singular}`}</button><span>Required fields are validated before the record is issued.</span></div>
        </form>{message && <div className={`result-state ${message.includes("Unable") || message.includes("Invalid") ? "danger" : ""}`}><strong>{message}</strong></div>}
      </section>
      <aside className="stack"><section className="panel panel-pad"><PanelTitle title="Operating hierarchy" description="Stable for one store, 65 stores or multiple future operators." /><div className="hierarchy-list"><div><Store /><strong>Store</strong><span>Number, address, manager and region</span></div><div><Building2 /><strong>Cost center</strong><span>Budget-owning maintainable system</span></div><div><Wrench /><strong>Asset</strong><span>Tagged physical equipment</span></div><div><Cpu /><strong>Component</strong><span>Serviceable part and warranty</span></div><div><ClipboardPlus /><strong>Work order</strong><span>Execution, labor, parts, proof and cost</span></div></div></section>
        <section className="panel panel-pad"><PanelTitle title="Created in this environment" description="Records entered through these forms are stored in the hosted tenant database." /><div className="coverage-grid"><div className="coverage-item"><strong>{records.length}</strong><span>created {meta.label.toLowerCase()}</span></div><div className="coverage-item"><strong>{entity === "stores" ? demoData.stores.length : entity === "cost-centers" ? demoData.systems.length : entity === "assets" ? demoData.assets.length : entity === "components" ? demoData.components.length : demoData.workOrders.length}</strong><span>operational seed records</span></div></div>{records.slice(0, 6).map((record) => <div className="registry-record" key={String(record.id)}><Boxes /><span><strong>{String(record.name ?? record.number ?? record.title ?? record.id)}</strong><small>{String(record.code ?? record.status ?? record.createdAt ?? "Saved record")}</small></span></div>)}</section></aside>
    </div>
  </div></AppShell>;
}

function FormField({ label, name, required, placeholder, type = "text", defaultValue, wide = false }: { label: string; name: string; required?: boolean; placeholder?: string; type?: string; defaultValue?: string; wide?: boolean }) { return <label className={`form-field ${wide ? "wide" : ""}`}><span>{label}{required && " *"}</span><input name={name} required={required} placeholder={placeholder} type={type} defaultValue={defaultValue} step={type === "number" ? "0.01" : undefined} /></label>; }
function TextField({ label, name, required, wide = false }: { label: string; name: string; required?: boolean; wide?: boolean }) { return <label className={`form-field ${wide ? "wide" : ""}`}><span>{label}{required && " *"}</span><textarea name={name} required={required} /></label>; }
function SelectField({ label, name, options, value, onChange, wide = false }: { label: string; name: string; options: ReadonlyArray<ReadonlyArray<string>>; value?: string; onChange?: (value: string) => void; wide?: boolean }) { return <label className={`form-field ${wide ? "wide" : ""}`}><span>{label}</span><select name={name} value={value} onChange={onChange ? (event) => onChange(event.target.value) : undefined} defaultValue={value === undefined ? options[0]?.[0] : undefined}>{options.map(([optionValue, text]) => <option key={optionValue} value={optionValue}>{text}</option>)}</select></label>; }
