"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, CircleDollarSign, ClipboardCheck, Download, Factory, Gauge, ShieldAlert, Store, Users, Wrench } from "lucide-react";
import Link from "@/components/site-link";
import { AppShell } from "@/components/app-shell";
import { Breadcrumbs, MetricCard, PageHeader, PanelTitle, StatusBadge } from "@/components/ui";
import { classificationCoverage, formatCurrency, formatDate, formatPercent, isOpenWorkOrder, pmCompliance, storeComparison } from "@/lib/domain/analytics";
import { demoData, DEMO_NOW } from "@/lib/demo/data";
import { statusTone, workOrderStatusLabel } from "@/lib/presentation";
import type { WorkOrder } from "@/lib/domain/types";

type ReportTab = "executive" | "backlog" | "spend" | "pm" | "reliability" | "workforce" | "vendors" | "data-quality";
const tabs: Array<[ReportTab, string]> = [["executive", "Executive"], ["backlog", "Backlog & SLA"], ["spend", "Spend & budget"], ["pm", "PM compliance"], ["reliability", "Asset reliability"], ["workforce", "Internal workforce"], ["vendors", "Vendor performance"], ["data-quality", "Data quality"]];

export function ReportingCenter() {
  const [tab, setTab] = useState<ReportTab>("executive"); const [region, setRegion] = useState(""); const [storeId, setStoreId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [assignment, setAssignment] = useState("");
  const filtered = useMemo(() => demoData.workOrders.filter((workOrder) => { const store = demoData.stores.find((item) => item.id === workOrder.storeId); return (!region || store?.regionId === region) && (!storeId || workOrder.storeId === storeId) && (!categoryId || workOrder.categoryId === categoryId) && (!assignment || workOrder.assignmentType === assignment); }), [region, storeId, categoryId, assignment]);
  const filteredIds = useMemo(() => new Set(filtered.map((item) => item.id)), [filtered]);
  const open = filtered.filter(isOpenWorkOrder); const overdue = open.filter((item) => item.dueAt && item.dueAt < DEMO_NOW); const critical = open.filter((item) => item.priority === "critical");
  const invoiceIds = new Set(demoData.invoices.filter((item) => item.status === "paid" && filteredIds.has(item.workOrderId)).map((item) => item.id));
  const spend = demoData.allocations.filter((item) => invoiceIds.has(item.invoiceId)).reduce((sum, item) => sum + item.amountCents, 0);
  const compliance = pmCompliance({ ...demoData, workOrders: filtered }, { storeId: storeId || undefined, categoryId: categoryId || undefined }, DEMO_NOW);
  function exportCsv() { const rows = [["Work order", "Store", "Address", "Title", "Category", "Priority", "Status", "Assignment", "Assignee", "Due", "Exposure"], ...filtered.map((item) => { const store = demoData.stores.find((candidate) => candidate.id === item.storeId)!; return [item.number, store.code, `${store.address1}, ${store.city}, ${store.state} ${store.postalCode}`, item.title, item.categoryId, item.priority, item.status, item.assignmentType ?? "", item.assignedToName ?? item.accountableParty, item.dueAt ?? "", String(item.costExposureCents)]; })]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `clarks-operations-${tab}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  return <AppShell><div className="page reporting-page"><Breadcrumbs items={[{ label: "Operations", href: "/" }, { label: "Reporting Center" }]} /><PageHeader eyebrow="Operational intelligence" title="Reporting center" description="Drillable operating, financial, preventive-maintenance, asset, workforce, vendor and data-quality reporting across one store or the full regional portfolio."><button className="button" onClick={exportCsv}><Download />Export filtered data</button></PageHeader>
    <div className="report-filter-bar"><label><span>Region</span><select value={region} onChange={(event) => { setRegion(event.target.value); setStoreId(""); }}><option value="">All regions</option>{demoData.regions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Store</span><select value={storeId} onChange={(event) => setStoreId(event.target.value)}><option value="">All stores</option>{demoData.stores.filter((item) => !region || item.regionId === region).map((item) => <option key={item.id} value={item.id}>{item.code} · {item.city}</option>)}</select></label><label><span>Category</span><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">All categories</option>{demoData.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label><span>Assignment</span><select value={assignment} onChange={(event) => setAssignment(event.target.value)}><option value="">Internal + vendor</option><option value="internal">Internal maintenance</option><option value="vendor">Vendor</option><option value="blended">Blended</option><option value="unassigned">Unassigned</option></select></label><div><span>As of</span><strong>Aug 5, 2026 · 10:00 AM ET</strong></div></div>
    <div className="report-tabs" role="tablist">{tabs.map(([id, label]) => <button role="tab" aria-selected={tab === id} className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id)}>{label}</button>)}</div>
    <div className="metric-grid"><MetricCard label="Open work" value={String(open.length)} note={`${critical.length} critical`} icon={Wrench} tone={critical.length ? "critical" : ""} /><MetricCard label="Overdue control" value={String(overdue.length)} note={`${open.length ? Math.round(overdue.length / open.length * 100) : 0}% of open backlog`} icon={ShieldAlert} tone={overdue.length ? "warning" : "good"} /><MetricCard label="Recorded spend" value={formatCurrency(spend, true)} note="Paid, allocated invoice value" icon={CircleDollarSign} /><MetricCard label="PM compliance" value={formatPercent(compliance.value)} note={`${compliance.numerator} / ${compliance.denominator} eligible`} icon={ClipboardCheck} tone={compliance.value >= .9 ? "good" : "warning"} /></div>
    {tab === "executive" && <ExecutiveReport filtered={filtered} />}{tab === "backlog" && <BacklogReport work={open} />}{tab === "spend" && <SpendReport workIds={filteredIds} />}{tab === "pm" && <PmReport storeId={storeId} categoryId={categoryId} />}{tab === "reliability" && <ReliabilityReport work={filtered} />}{tab === "workforce" && <WorkforceReport work={filtered} />}{tab === "vendors" && <VendorReport work={filtered} />}{tab === "data-quality" && <DataQualityReport work={filtered} />}
  </div></AppShell>;
}

function ExecutiveReport({ filtered }: { filtered: WorkOrder[] }) {
  const ids = new Set(filtered.map((item) => item.id)); const stores = storeComparison(demoData, DEMO_NOW).filter((item) => filtered.some((work) => work.storeId === item.store.id)).sort((a, b) => b.spend - a.spend).slice(0, 10); const categoryValues = demoData.categories.map((category) => ({ label: category.name, value: demoData.allocations.filter((item) => item.categoryId === category.id && ids.has(item.workOrderId)).reduce((sum, item) => sum + item.amountCents, 0) })).sort((a, b) => b.value - a.value); const max = Math.max(...categoryValues.map((item) => item.value), 1);
  return <div className="report-grid"><section className="panel panel-pad"><PanelTitle title="Maintenance spend by category" description="Allocated invoice value; click a category in the filter to isolate work." /><div className="bar-report">{categoryValues.map((item) => <div key={item.label}><span>{item.label}</span><div><i style={{ width: `${item.value / max * 100}%` }} /></div><strong>{formatCurrency(item.value, true)}</strong></div>)}</div></section><section className="panel table-wrap"><PanelTitle title="Highest-burden locations" description="Portfolio ranking with operational context." /><table className="data-table"><thead><tr><th>Store</th><th className="numeric">TTM spend</th><th className="numeric">Open</th><th>PM</th><th>Signal</th></tr></thead><tbody>{stores.map((item) => <tr key={item.store.id}><td><Link className="row-link" href={`/stores/${item.store.id}`}>{item.store.code} · {item.store.city}</Link><span className="subtext">{item.store.address1}</span></td><td className="numeric">{formatCurrency(item.spend)}</td><td className="numeric">{item.openCount}</td><td>{formatPercent(item.pm.value)}</td><td><StatusBadge tone={item.isOutlier ? "critical" : "good"}>{item.isOutlier ? "outlier" : "within range"}</StatusBadge></td></tr>)}</tbody></table></section></div>;
}

function BacklogReport({ work }: { work: WorkOrder[] }) {
  const now = new Date(DEMO_NOW).getTime(); const buckets = [["0–2 days", 0, 2], ["3–7 days", 3, 7], ["8–14 days", 8, 14], ["15–30 days", 15, 30], ["31+ days", 31, 9999]] as const; const ages = buckets.map(([label, min, max]) => ({ label, value: work.filter((item) => { const age = (now - new Date(item.createdAt).getTime()) / 86_400_000; return age >= min && age <= max; }).length })); const maximum = Math.max(...ages.map((item) => item.value), 1); const due = [...work].sort((a, b) => (a.dueAt ?? "9999").localeCompare(b.dueAt ?? "9999")).slice(0, 18);
  return <div className="report-grid"><section className="panel panel-pad"><PanelTitle title="Backlog aging" description="Open work by elapsed calendar days." /><div className="bar-report count-bars">{ages.map((item) => <div key={item.label}><span>{item.label}</span><div><i style={{ width: `${item.value / maximum * 100}%` }} /></div><strong>{item.value}</strong></div>)}</div><div className="callout warning"><strong>Escalation logic</strong><p>Critical overdue work escalates to the regional manager; all other overdue items remain owned by the named accountable party until a dated recovery action is recorded.</p></div></section><section className="panel table-wrap"><PanelTitle title="SLA exception queue" description="The work that needs an owner decision first." /><table className="data-table"><thead><tr><th>Work order</th><th>Store / address</th><th>Status</th><th>Owner</th><th>Due</th></tr></thead><tbody>{due.map((item) => { const store = demoData.stores.find((candidate) => candidate.id === item.storeId)!; return <tr key={item.id}><td><Link className="row-link mono" href={`/work-orders/${item.id}`}>{item.number}</Link><span className="subtext">{item.title}</span></td><td>Store {store.code} · {store.city}<span className="subtext">{store.address1}</span></td><td><StatusBadge tone={statusTone(item.status)}>{workOrderStatusLabel[item.status]}</StatusBadge></td><td>{item.assignedToName ?? item.accountableParty}<span className="subtext">{item.nextAction}</span></td><td>{item.dueAt ? formatDate(item.dueAt, true) : "Not set"}</td></tr>; })}</tbody></table></section></div>;
}

function SpendReport({ workIds }: { workIds: Set<string> }) {
  const paid = new Set(demoData.invoices.filter((item) => item.status === "paid").map((item) => item.id)); const byCategory = demoData.categories.map((category) => { const systems = demoData.systems.filter((item) => item.categoryId === category.id); const budget = systems.reduce((sum, item) => sum + item.annualBudgetCents, 0); const actual = demoData.allocations.filter((item) => item.categoryId === category.id && paid.has(item.invoiceId) && workIds.has(item.workOrderId)).reduce((sum, item) => sum + item.amountCents, 0); return { category, budget, actual }; }).sort((a, b) => b.actual - a.actual); const costTypes = ["labor", "parts", "travel", "emergency_surcharge", "rental", "tax", "other"].map((label) => ({ label, value: demoData.allocations.filter((item) => item.costCategory === label && workIds.has(item.workOrderId)).reduce((sum, item) => sum + item.amountCents, 0) })); const max = Math.max(...costTypes.map((item) => item.value), 1);
  return <div className="report-grid"><section className="panel table-wrap"><PanelTitle title="Category budget posture" description="Actual paid allocation compared with configured annual maintenance budget." /><table className="data-table"><thead><tr><th>Category</th><th className="numeric">Budget</th><th className="numeric">Actual</th><th className="numeric">Remaining</th><th>Utilization</th></tr></thead><tbody>{byCategory.map(({ category, budget, actual }) => <tr key={category.id}><td><strong>{category.name}</strong></td><td className="numeric">{formatCurrency(budget, true)}</td><td className="numeric">{formatCurrency(actual, true)}</td><td className="numeric">{formatCurrency(budget - actual, true)}</td><td><div className="progress-row" style={{ gridTemplateColumns: "1fr 44px", margin: 0 }}><div className="progress-track"><div className="progress-fill" style={{ width: `${Math.min(actual / Math.max(budget, 1) * 100, 100)}%` }} /></div><strong>{formatPercent(actual / Math.max(budget, 1))}</strong></div></td></tr>)}</tbody></table></section><section className="panel panel-pad"><PanelTitle title="Spend composition" description="Allocated cost categories." /><div className="bar-report">{costTypes.map((item) => <div key={item.label}><span>{item.label.replaceAll("_", " ")}</span><div><i style={{ width: `${item.value / max * 100}%` }} /></div><strong>{formatCurrency(item.value, true)}</strong></div>)}</div></section></div>;
}

function PmReport({ storeId, categoryId }: { storeId: string; categoryId: string }) {
  const rows = demoData.pmPlans.filter((plan) => !categoryId || plan.categoryId === categoryId).map((plan) => { const occurrences = demoData.pmOccurrences.filter((item) => item.planId === plan.id && (!storeId || item.storeId === storeId) && item.dueAt <= DEMO_NOW); const completed = occurrences.filter((item) => ["completed_on_time", "completed_early"].includes(item.status) && item.verified).length; return { plan, occurrences, completed, missed: occurrences.filter((item) => item.status === "missed").length, value: occurrences.length ? completed / occurrences.length : 0 }; });
  return <section className="panel table-wrap"><PanelTitle title="Preventive-maintenance scorecard" description="Occurrence-level denominator, on-time evidence and recovery status." /><table className="data-table"><thead><tr><th>Plan</th><th>Scope</th><th>Frequency</th><th className="numeric">Eligible</th><th className="numeric">On time</th><th className="numeric">Missed</th><th>Compliance</th><th>Proof</th></tr></thead><tbody>{rows.map(({ plan, occurrences, completed, missed, value }) => <tr key={plan.id}><td><strong>{plan.name}</strong></td><td>{plan.scopeLabel}</td><td>{plan.frequency}</td><td className="numeric">{occurrences.length}</td><td className="numeric">{completed}</td><td className="numeric">{missed}</td><td><StatusBadge tone={value >= .9 ? "good" : value >= .75 ? "warning" : "critical"}>{formatPercent(value)}</StatusBadge></td><td>{plan.requiredDocument}</td></tr>)}</tbody></table></section>;
}

function ReliabilityReport({ work }: { work: WorkOrder[] }) {
  const workIds = new Set(work.map((item) => item.id)); const assetRows = demoData.assets.map((asset) => { const orders = work.filter((item) => item.assetId === asset.id); const visits = demoData.visits.filter((item) => orders.some((order) => order.id === item.workOrderId)); const cost = demoData.allocations.filter((item) => item.assetId === asset.id && workIds.has(item.workOrderId)).reduce((sum, item) => sum + item.amountCents, 0); return { asset, orders, visits, cost }; }).filter((item) => item.orders.length).sort((a, b) => b.cost - a.cost || b.orders.length - a.orders.length).slice(0, 25);
  return <section className="panel table-wrap"><PanelTitle title="Asset reliability and service burden" description="Failure demand, repeat visits, age, condition and recorded maintenance cost." /><table className="data-table"><thead><tr><th>Asset</th><th>Store / cost center</th><th>Age / condition</th><th className="numeric">Work orders</th><th className="numeric">Visits</th><th className="numeric">Service cost</th><th>Reliability signal</th></tr></thead><tbody>{assetRows.map(({ asset, orders, visits, cost }) => { const system = demoData.systems.find((item) => item.id === asset.storeSystemId)!; const store = demoData.stores.find((item) => item.id === system.storeId)!; const age = 2026 - Number(asset.installedAt.slice(0, 4)); const signal = orders.length >= 3 || visits.length > orders.length || asset.condition === "poor"; return <tr key={asset.id}><td><Link className="row-link" href={`/assets/${asset.id}`}>{asset.assetTag} · {asset.name}</Link><span className="subtext">{asset.manufacturer} {asset.model} · {asset.serial}</span></td><td>Store {store.code} · {store.city}<span className="subtext">{system.name}</span></td><td>{age} years<span className="subtext">{asset.condition} · {asset.state}</span></td><td className="numeric">{orders.length}</td><td className="numeric">{visits.length}</td><td className="numeric">{formatCurrency(cost)}</td><td><StatusBadge tone={signal ? "warning" : "good"}>{signal ? "review" : "stable"}</StatusBadge></td></tr>; })}</tbody></table></section>;
}

function WorkforceReport({ work }: { work: WorkOrder[] }) {
  const rows = demoData.technicians.map((technician) => { const assigned = work.filter((item) => item.assignedToId === technician.id); const labor = demoData.laborEntries.filter((item) => item.technicianId === technician.id); const hours = labor.reduce((sum, item) => sum + item.regularHours + item.overtimeHours, 0); const planned = assigned.reduce((sum, item) => sum + (item.estimatedHours ?? 0), 0); const cost = labor.reduce((sum, item) => sum + (item.regularHours + item.overtimeHours) * item.hourlyRateCents, 0); return { technician, assigned, hours, planned, cost }; });
  return <section className="panel table-wrap"><PanelTitle title="Internal maintenance capacity and productivity" description="Open workload, recorded time, labor cost, trade coverage and due-date risk." /><table className="data-table"><thead><tr><th>Technician</th><th>Region / trades</th><th>Status</th><th className="numeric">Open assignments</th><th className="numeric">Planned h</th><th className="numeric">Recorded h</th><th className="numeric">Labor cost</th><th>Capacity</th></tr></thead><tbody>{rows.map(({ technician, assigned, hours, planned, cost }) => <tr key={technician.id}><td><strong>{technician.name}</strong><span className="subtext">{technician.title}</span></td><td>{technician.regionIds.map((id) => demoData.regions.find((item) => item.id === id)?.name).join(", ")}<span className="subtext">{technician.trades.join(" · ")}</span></td><td><StatusBadge tone={technician.status === "available" ? "good" : "active"}>{technician.status}</StatusBadge></td><td className="numeric">{assigned.length}</td><td className="numeric">{planned.toFixed(1)}</td><td className="numeric">{hours.toFixed(1)}</td><td className="numeric">{formatCurrency(cost)}</td><td><div className="progress-row" style={{ gridTemplateColumns: "1fr 42px", margin: 0 }}><div className="progress-track"><div className="progress-fill" style={{ width: `${Math.min(planned / technician.weeklyCapacityHours * 100, 100)}%` }} /></div><strong>{formatPercent(planned / technician.weeklyCapacityHours)}</strong></div></td></tr>)}</tbody></table></section>;
}

function VendorReport({ work }: { work: WorkOrder[] }) {
  const rows = demoData.vendors.map((vendor) => { const orders = work.filter((item) => item.vendorId === vendor.id); const open = orders.filter(isOpenWorkOrder); const invoices = demoData.invoices.filter((item) => item.vendorId === vendor.id && orders.some((order) => order.id === item.workOrderId)); const spend = invoices.reduce((sum, item) => sum + item.totalCents, 0); const responses = demoData.vendorResponses.filter((item) => item.vendorId === vendor.id && orders.some((order) => order.id === item.workOrderId)); const responseHours = responses.length ? responses.reduce((sum, item) => sum + (new Date(item.respondedAt).getTime() - new Date(item.issuedAt).getTime()) / 3_600_000, 0) / responses.length : 0; const visits = demoData.visits.filter((item) => item.vendorId === vendor.id && orders.some((order) => order.id === item.workOrderId)); const callbacks = visits.length - new Set(visits.map((item) => item.workOrderId)).size; return { vendor, orders, open, spend, responseHours, visits, callbacks }; }).filter((item) => item.orders.length).sort((a, b) => b.spend - a.spend);
  return <section className="panel table-wrap"><PanelTitle title="Vendor performance scorecard" description="Customer-side demand, response, repeat visits, financial volume and open control." /><table className="data-table"><thead><tr><th>Vendor</th><th>Trade</th><th className="numeric">Work / open</th><th className="numeric">Avg response</th><th className="numeric">Visits / callbacks</th><th className="numeric">Invoice value</th><th>Control signal</th></tr></thead><tbody>{rows.map(({ vendor, orders, open, spend, responseHours, visits, callbacks }) => <tr key={vendor.id}><td><strong>{vendor.name}</strong><span className="subtext">{vendor.dispatchEmail}</span></td><td>{vendor.trade}</td><td className="numeric">{orders.length} / <strong>{open.length}</strong></td><td className="numeric">{responseHours.toFixed(1)}h</td><td className="numeric">{visits.length} / {callbacks}</td><td className="numeric">{formatCurrency(spend, true)}</td><td><StatusBadge tone={callbacks > orders.length * .15 ? "warning" : "good"}>{callbacks > orders.length * .15 ? "callback review" : "within range"}</StatusBadge></td></tr>)}</tbody></table></section>;
}

function DataQualityReport({ work }: { work: WorkOrder[] }) {
  const scoped = { ...demoData, workOrders: work }; const coverage = classificationCoverage(scoped); const checks = [{ label: "Category classified", value: coverage.categorized, icon: CheckCircle2 }, { label: "Cost center identified", value: coverage.systemMapped, icon: BuildingIcon }, { label: "Asset identified", value: work.length ? work.filter((item) => item.assetId).length / work.length : 0, icon: Factory }, { label: "Component identified", value: work.length ? work.filter((item) => item.componentId).length / work.length : 0, icon: Gauge }, { label: "Named assignment", value: work.length ? work.filter((item) => item.assignedToName).length / work.length : 0, icon: Users }, { label: "Target completion set", value: work.length ? work.filter((item) => item.targetCompletionAt || item.dueAt).length / work.length : 0, icon: ClipboardCheck }]; const exceptions = work.filter((item) => !item.systemId || !item.assignedToName || !(item.targetCompletionAt || item.dueAt)).slice(0, 25);
  return <div><div className="quality-grid">{checks.map(({ label, value, icon: Icon }) => <div className="quality-card" key={label}><Icon /><span>{label}</span><strong>{formatPercent(value)}</strong><div className="progress-track"><div className="progress-fill" style={{ width: formatPercent(value) }} /></div></div>)}</div><section className="panel table-wrap"><PanelTitle title="Records requiring enrichment" description="Incomplete operational fields that limit dispatch, analysis or cost rollup." /><table className="data-table"><thead><tr><th>Work order</th><th>Store</th><th>Missing cost center</th><th>Missing assignment</th><th>Missing target</th><th>Recommended action</th></tr></thead><tbody>{exceptions.map((item) => { const store = demoData.stores.find((candidate) => candidate.id === item.storeId)!; return <tr key={item.id}><td><Link className="row-link mono" href={`/work-orders/${item.id}`}>{item.number}</Link><span className="subtext">{item.title}</span></td><td>{store.code} · {store.city}</td><td>{item.systemId ? "No" : "Yes"}</td><td>{item.assignedToName ? "No" : "Yes"}</td><td>{item.targetCompletionAt || item.dueAt ? "No" : "Yes"}</td><td>Open work order and refine classification</td></tr>; })}</tbody></table></section></div>;
}

function BuildingIcon(props: React.ComponentProps<typeof Store>) { return <Store {...props} />; }
