"use client";

import { useEffect, useMemo, useState } from "react";
import { Building2, Download, MapPin, Plus, Search, Store as StoreIcon } from "lucide-react";
import Link from "@/components/site-link";
import { AppShell } from "@/components/app-shell";
import { Breadcrumbs, MetricCard, PageHeader, StatusBadge } from "@/components/ui";
import { formatCurrency, storeComparison } from "@/lib/domain/analytics";
import { demoData, DEMO_NOW } from "@/lib/demo/data";

const PAGE_SIZE = 20;
type CustomStore = { id: string; code: string; name: string; address1: string; city: string; state: string; postalCode: string; managerName?: string; district?: string; regionId?: string; status?: string };

export function StoreDirectory() {
  const [query, setQuery] = useState(""); const [region, setRegion] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [custom, setCustom] = useState<CustomStore[]>([]);
  useEffect(() => { fetch("/api/registry?entity=stores").then((response) => response.json()).then((raw) => { const result = raw as { ok: boolean; records?: CustomStore[] }; if (result.ok) setCustom(result.records ?? []); }).catch(() => undefined); }, []);
  const comparison = useMemo(() => new Map(storeComparison(demoData, DEMO_NOW).map((row) => [row.store.id, row])), []);
  const stores = useMemo(() => [...demoData.stores, ...custom].filter((store) => {
    const haystack = `${store.code} ${store.name} ${store.address1} ${store.city} ${store.state} ${store.postalCode} ${store.managerName ?? ""} ${store.district ?? ""}`.toLowerCase();
    return (!query || haystack.includes(query.toLowerCase())) && (!region || store.regionId === region) && (!status || (store.status ?? "active") === status);
  }).sort((a, b) => Number(a.code) - Number(b.code)), [custom, query, region, status]);
  const pageCount = Math.max(1, Math.ceil(stores.length / PAGE_SIZE)); const visible = stores.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  function reset(action: () => void) { action(); setPage(1); }
  const active = [...demoData.stores, ...custom].filter((store) => (store.status ?? "active") === "active").length;
  return <AppShell><div className="page"><Breadcrumbs items={[{ label: "Portfolio", href: "/" }, { label: "Stores" }]} /><PageHeader eyebrow="Searchable portfolio registry" title="Stores" description="Find any location by store number, name, street address, city, ZIP code, manager or district. Open a store to see its cost centers, assets, work and financial history."><Link className="button primary" href="/stores/new"><Plus />New store</Link><button className="button" onClick={() => window.print()}><Download />Export</button></PageHeader>
    <div className="metric-grid"><MetricCard label="Portfolio locations" value={String(demoData.stores.length + custom.length)} note="65-store pilot plus created records" icon={StoreIcon} /><MetricCard label="Active stores" value={String(active)} note="Opening and inactive tracked separately" icon={MapPin} tone="good" /><MetricCard label="Cost centers" value={String(demoData.systems.length)} note="Eight operating systems per store" icon={Building2} /><MetricCard label="Registered assets" value={String(demoData.assets.length)} note="Tagged equipment with components" icon={StoreIcon} /></div>
    <div className="filter-bar"><label className="filter-field directory-search"><span>Search by number or address</span><div style={{ position: "relative" }}><Search size={14} style={{ position: "absolute", left: 10, top: 11, color: "#71807d" }} /><input value={query} onChange={(event) => reset(() => setQuery(event.target.value))} placeholder="Try 45, Market Street, 15001…" style={{ paddingLeft: 31 }} /></div></label><label className="filter-field"><span>Region</span><select value={region} onChange={(event) => reset(() => setRegion(event.target.value))}><option value="">All regions</option>{demoData.regions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="filter-field"><span>Store status</span><select value={status} onChange={(event) => reset(() => setStatus(event.target.value))}><option value="">All statuses</option><option value="active">Active</option><option value="opening">Opening</option><option value="temporarily_closed">Temporarily closed</option><option value="inactive">Inactive</option></select></label><span className="filter-summary">{stores.length} locations · page {page} of {pageCount}</span></div>
    <section className="panel table-wrap"><table className="data-table store-table"><thead><tr><th>Store</th><th>Address</th><th>Region / district</th><th>Manager</th><th className="numeric">Cost centers / assets</th><th className="numeric">Open / critical</th><th className="numeric">TTM spend</th><th>Status</th></tr></thead><tbody>{visible.map((store) => { const metrics = comparison.get(store.id); const systemIds = demoData.systems.filter((item) => item.storeId === store.id).map((item) => item.id); const assetCount = demoData.assets.filter((item) => systemIds.includes(item.storeSystemId)).length; const seeded = demoData.stores.some((item) => item.id === store.id); return <tr key={store.id}><td>{seeded ? <Link className="row-link" href={`/stores/${store.id}`}>Store {store.code}</Link> : <strong>Store {store.code}</strong>}<span className="subtext">{store.name.replace(`Store ${store.code} - `, "")}</span></td><td><strong>{store.address1}</strong><span className="subtext">{store.city}, {store.state} {store.postalCode}</span></td><td>{demoData.regions.find((item) => item.id === store.regionId)?.name ?? "Independent"}<span className="subtext">{store.district ?? "No district"}</span></td><td>{store.managerName || "Unassigned"}</td><td className="numeric"><strong>{systemIds.length}</strong> / {assetCount}</td><td className="numeric"><strong>{metrics?.openCount ?? 0}</strong> / {metrics?.criticalCount ?? 0}</td><td className="numeric"><strong>{formatCurrency(metrics?.spend ?? 0)}</strong></td><td><StatusBadge tone={(store.status ?? "active") === "active" ? "good" : "warning"}>{store.status ?? "active"}</StatusBadge></td></tr>; })}</tbody></table>{!visible.length && <div className="empty-state">No stores match this search.</div>}</section>
    <div className="pagination"><button className="button small" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><span>Showing {(page - 1) * PAGE_SIZE + (visible.length ? 1 : 0)}–{(page - 1) * PAGE_SIZE + visible.length} of {stores.length}</span><button className="button small" disabled={page === pageCount} onClick={() => setPage((value) => value + 1)}>Next</button></div>
  </div></AppShell>;
}
