"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ClipboardCheck, Clock3, MessageSquare, Package, Play, ShieldAlert, Users } from "lucide-react";
import { PanelTitle, StatusBadge } from "@/components/ui";
import { formatCurrency, formatDate } from "@/lib/domain/analytics";
import { demoData } from "@/lib/demo/data";
import type { LaborEntry, PartUsage, WorkOrder, WorkOrderChecklistItem, WorkOrderNote } from "@/lib/domain/types";

type Tab = "overview" | "plan" | "time-parts" | "activity";
type ActivityResponse = { ok: boolean; error?: string; notes?: WorkOrderNote[]; labor?: Array<Record<string, unknown>>; parts?: Array<Record<string, unknown>>; checklist?: WorkOrderChecklistItem[] };

export function WorkOrderExecution({ workOrder }: { workOrder: WorkOrder }) {
  const [tab, setTab] = useState<Tab>("overview");
  const [checklist, setChecklist] = useState<WorkOrderChecklistItem[]>(demoData.checklistItems.filter((item) => item.workOrderId === workOrder.id));
  const [notes, setNotes] = useState<WorkOrderNote[]>(demoData.workOrderNotes.filter((item) => item.workOrderId === workOrder.id));
  const [labor, setLabor] = useState<LaborEntry[]>(demoData.laborEntries.filter((item) => item.workOrderId === workOrder.id));
  const [parts, setParts] = useState<PartUsage[]>(demoData.partsUsed.filter((item) => item.workOrderId === workOrder.id));
  const [status, setStatus] = useState(workOrder.status);
  const [saving, setSaving] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => { fetch(`/api/work-orders/${workOrder.id}/activity`).then((response) => response.json()).then((raw) => { const result = raw as ActivityResponse; if (!result.ok) return; if (result.notes?.length) setNotes((current) => [...result.notes!, ...current]); if (result.labor?.length) setLabor((current) => [...result.labor!.map((item) => ({ ...item, regularHours: Number(item.regularMinutes) / 60, overtimeHours: Number(item.overtimeMinutes) / 60 })), ...current] as LaborEntry[]); if (result.parts?.length) setParts((current) => [...result.parts!.map((item) => ({ ...item, quantity: Number(item.quantityMilli) / 1000 })), ...current] as PartUsage[]); if (result.checklist?.length) setChecklist(result.checklist); }).catch(() => undefined); }, [workOrder.id]);
  const completed = checklist.filter((item) => item.completed).length;
  const laborHours = useMemo(() => labor.reduce((sum, item) => sum + item.regularHours + item.overtimeHours, 0), [labor]);
  const laborCost = labor.reduce((sum, item) => sum + (item.regularHours + item.overtimeHours) * item.hourlyRateCents, 0);
  const partCost = parts.reduce((sum, item) => sum + item.quantity * item.unitCostCents, 0);

  async function record(payload: Record<string, unknown>) {
    setSaving(String(payload.type)); setMessage("");
    try { const response = await fetch(`/api/work-orders/${workOrder.id}/activity`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as ActivityResponse; if (!response.ok || !result.ok) throw new Error(result.error ?? "Unable to record update"); setMessage("Update saved to the work-order record."); return true; }
    catch (error) { setMessage(error instanceof Error ? error.message : "Unable to record update"); return false; }
    finally { setSaving(""); }
  }
  async function changeStatus(next: string, reason: string) { if (await record({ type: "status", priorStatus: status, newStatus: next, reason, actorName: workOrder.assignedToName ?? "Maintenance team" })) setStatus(next as WorkOrder["status"]); }
  async function toggle(item: WorkOrderChecklistItem) { const next = !item.completed; setChecklist((current) => current.map((candidate) => candidate.id === item.id ? { ...candidate, completed: next, completedBy: workOrder.assignedToName } : candidate)); await record({ type: "checklist", itemId: item.id, completed: next, completedBy: workOrder.assignedToName ?? "Maintenance team" }); }
  async function addNote(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = String(form.get("body") ?? ""); const visibility = String(form.get("visibility") ?? "internal"); const author = workOrder.assignedToName ?? "Maintenance team"; if (await record({ type: "note", author, authorRole: workOrder.assignmentType === "internal" ? "Internal maintenance" : "Service provider", body, visibility })) { setNotes((current) => [{ id: `session-${Date.now()}`, workOrderId: workOrder.id, author, authorRole: "Maintenance", body, visibility: visibility as WorkOrderNote["visibility"], createdAt: new Date().toISOString() }, ...current]); event.currentTarget.reset(); } }
  async function addLabor(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const hours = Number(form.get("hours") ?? 0); const now = new Date(); const startedAt = new Date(now.getTime() - hours * 3_600_000).toISOString(); const technicianName = workOrder.assignedToName ?? "Maintenance team"; if (await record({ type: "labor", technicianId: workOrder.assignedToId ?? "unassigned", technicianName, startedAt, endedAt: now.toISOString(), regularHours: hours, overtimeHours: Number(form.get("overtime") ?? 0), hourlyRateCents: Number(form.get("rate") ?? 0) * 100, notes: String(form.get("notes") ?? "") })) event.currentTarget.reset(); }
  async function addPart(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); if (await record({ type: "part", partNumber: String(form.get("partNumber") ?? ""), description: String(form.get("description") ?? ""), quantity: Number(form.get("quantity") ?? 1), unitCostCents: Number(form.get("unitCost") ?? 0) * 100, source: String(form.get("source") ?? "truck_stock"), recordedBy: workOrder.assignedToName ?? "Maintenance team" })) event.currentTarget.reset(); }

  return <section className="panel execution-workspace"><div className="execution-head"><div><span className="eyebrow">Maintenance execution workspace</span><h2>{workOrder.assignmentType === "internal" ? "Internal technician assignment" : "Controlled service assignment"}</h2><p>The field-ready work package: scope, hazards, checklist, time, materials, notes, status and closeout evidence.</p></div><div className="execution-status"><StatusBadge tone={status === "visit_active" ? "active" : status === "closed" ? "good" : "warning"}>{status.replaceAll("_", " ")}</StatusBadge><strong>{workOrder.assignedToName ?? workOrder.accountableParty}</strong><span>{workOrder.assignmentType?.replaceAll("_", " ")}</span></div></div>
    <div className="execution-actions"><button onClick={() => void changeStatus("visit_active", "Technician started onsite work")}><Play />Start work</button><button onClick={() => void changeStatus("waiting_on_parts", "Required material is not yet available")}><Package />Waiting on parts</button><button onClick={() => void changeStatus("completed_pending_verification", "Work completed; store verification requested")}><CheckCircle2 />Complete work</button></div>
    <div className="execution-tabs" role="tablist">{(["overview", "plan", "time-parts", "activity"] as Tab[]).map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item === "time-parts" ? "Time & parts" : item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    <div className="execution-body">
      {tab === "overview" && <div className="execution-overview"><div className="scope-card"><PanelTitle title="Requested scope" description={`Requested by ${workOrder.requestedBy ?? "Operations"}`} /><p>{workOrder.description}</p><div className="detail-pairs"><div><span>Exact location</span><strong>{workOrder.location}</strong></div><div><span>Problem code</span><strong>{workOrder.problemCode}</strong></div><div><span>Target response</span><strong>{workOrder.targetResponseAt ? formatDate(workOrder.targetResponseAt, true) : "Not set"}</strong></div><div><span>Target completion</span><strong>{workOrder.targetCompletionAt ? formatDate(workOrder.targetCompletionAt, true) : "Not set"}</strong></div><div><span>Estimated effort</span><strong>{workOrder.estimatedHours ?? 0} hours</strong></div><div><span>Downtime</span><strong>{workOrder.downtimeMinutes ?? 0} minutes</strong></div></div></div><aside className={`safety-card ${workOrder.safetyRisk === "high" ? "high" : ""}`}><ShieldAlert /><span>Safety and access</span><strong>{workOrder.safetyRisk ?? "low"} risk</strong><p>{workOrder.accessInstructions}</p></aside></div>}
      {tab === "plan" && <div className="checklist-panel"><div className="checklist-summary"><ClipboardCheck /><div><strong>{completed} of {checklist.length} complete</strong><span>All required items must be complete before closeout.</span></div><b>{checklist.length ? Math.round(completed / checklist.length * 100) : 0}%</b></div>{checklist.map((item) => <label className={`checklist-row ${item.completed ? "done" : ""}`} key={item.id}><input aria-label={item.label} type="checkbox" checked={item.completed} onChange={() => void toggle(item)} /><span><strong>{item.sequence}. {item.label}</strong><small>{item.required ? "Required" : "Recommended"}{item.completedBy ? ` · ${item.completedBy}` : ""}</small></span></label>)}</div>}
      {tab === "time-parts" && <div className="time-parts-grid"><div><PanelTitle title="Labor entries" description={`${laborHours.toFixed(2)} recorded hours · ${formatCurrency(laborCost)}`} />{labor.map((item) => <div className="ledger-row" key={item.id}><Clock3 /><span><strong>{item.technicianName}</strong><small>{item.regularHours.toFixed(2)} regular · {item.overtimeHours.toFixed(2)} OT · {item.notes}</small></span><b>{formatCurrency((item.regularHours + item.overtimeHours) * item.hourlyRateCents)}</b></div>)}<form className="mini-form" onSubmit={addLabor}><input name="hours" type="number" step=".25" min=".25" placeholder="Regular hours" required /><input name="overtime" type="number" step=".25" min="0" placeholder="OT hours" /><input name="rate" type="number" step=".01" min="0" placeholder="Hourly rate $" /><input name="notes" placeholder="Work performed" required /><button className="button small" disabled={saving === "labor"}>Add time</button></form></div><div><PanelTitle title="Parts and materials" description={`${parts.length} line items · ${formatCurrency(partCost)}`} />{parts.map((item) => <div className="ledger-row" key={item.id}><Package /><span><strong>{item.partNumber || "No part #"} · {item.description}</strong><small>{item.quantity} × {formatCurrency(item.unitCostCents)} · {item.source.replaceAll("_", " ")}</small></span><b>{formatCurrency(item.quantity * item.unitCostCents)}</b></div>)}<form className="mini-form" onSubmit={addPart}><input name="partNumber" placeholder="Part number" /><input name="description" placeholder="Description" required /><input name="quantity" type="number" min=".01" step=".01" defaultValue="1" required /><input name="unitCost" type="number" min="0" step=".01" placeholder="Unit cost $" /><select name="source"><option value="truck_stock">Truck stock</option><option value="storeroom">Storeroom</option><option value="purchased">Purchased</option><option value="vendor_supplied">Vendor supplied</option></select><button className="button small" disabled={saving === "part"}>Add part</button></form></div></div>}
      {tab === "activity" && <div className="activity-grid"><div><PanelTitle title="Work log" description="Timestamped updates with audience controls." />{notes.sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map((note) => <div className="activity-note" key={note.id}><MessageSquare /><div><strong>{note.author}</strong><span>{note.authorRole} · {formatDate(note.createdAt, true)} · {note.visibility}</span><p>{note.body}</p></div></div>)}</div><form className="note-form" onSubmit={addNote}><label><span>New work note</span><textarea name="body" placeholder="What did you find, do, test, or communicate?" required /></label><label><span>Visible to</span><select name="visibility"><option value="internal">Internal team</option><option value="store">Store team</option><option value="vendor">Vendor</option></select></label><button className="button primary" disabled={saving === "note"}><MessageSquare />Add note</button><div className="closeout-rules"><Users /><strong>Closeout requirements</strong><p>Required checklist complete, outcome recorded, time and parts entered, proof attached, store notified, and invoice allocation reconciled when applicable.</p></div></form></div>}
    </div>{message && <div className="execution-message">{message}</div>}
  </section>;
}
