import type { OperatorSession,ProgramPageViewModel,PaginationViewModel,TableRowViewModel } from "@/components/ops/data-contract";
import type { PmProgramManagementModel } from "@/components/workspace/pm-program-management";
import type { OpsRepository } from "@/lib/ops/repository";
import type { PmReviewQuery,PmReviewRow } from "@/lib/ops/pm-review-query";
import { compactStoreLabel } from "@/lib/product/store-label";
import { formatOperationsDate } from "@/lib/ops/local-time";
import { pmScheduleScope } from "@/lib/ops/pm-schedule-query";
import { pmHref } from "./pm-schedule-presenter";

type Query=Record<string,string|string[]|undefined>;
const first=(v:string|string[]|undefined)=>Array.isArray(v)?v[0]:v;
const base=(q:Query)=>({store:first(q.store),region:first(q.region),program:first(q.program)});
const money=(minor:number|undefined,currency:string|undefined)=>minor===undefined||!currency?"See currency details":new Intl.NumberFormat("en-US",{style:"currency",currency}).format(minor/100);
const store=(r:PmReviewRow,s:OperatorSession)=>compactStoreLabel(`Store ${r.storeNumber} · ${r.storeName}`,s.organizationName);
export function pmReviewHref(q:Query,kind:PmReviewQuery["kind"]="reviews",review?:string,missing=false){return pmHref(q,{reviewSource:kind,pmReview:review,reviewMissing:missing?"yes":undefined,reviewPage:undefined,setup:undefined,setupFilter:undefined,setupPage:undefined,evidence:undefined,asset:undefined});}
function previewRow(r:PmReviewRow,session:OperatorSession,q:Query):PmProgramManagementModel["reconciliations"][number]{return {id:r.id,programName:r.programName,storeLabel:store(r,session),periodLabel:r.periodLabel,invoiceCount:r.invoiceCount,visitCount:r.visitCount,missingCount:r.missingCount,amountLabel:money(r.amountMinor,r.currency),missingAmountLabel:money(r.missingAmountMinor,r.currency),unavailableLinks:r.unavailableLinks,
  href:pmReviewHref(q,"invoices",r.id),invoicesHref:pmReviewHref(q,"invoices",r.id),visitsHref:pmReviewHref(q,"visits",r.id),missingHref:pmReviewHref(q,"occurrences",r.id,true),missingAmountHref:pmReviewHref(q,"invoices",r.id,true)};}
export async function buildPmReviewPreview(repository:OpsRepository,session:OperatorSession,q:Query){const result=await repository.listPmReview(session,{...base(q),kind:"reviews",limit:5});return {rows:result.reviews.map(r=>previewRow(r,session,q)),total:result.totalCount,href:pmReviewHref(q)};}
export async function buildPmReviewSources(repository:OpsRepository,session:OperatorSession,q:Query):Promise<ProgramPageViewModel>{
  const requested=Number(first(q.reviewPage)??1),page=Number.isSafeInteger(requested)&&requested>0&&requested<=1_000_000?requested:1,size=25;
  const kind=(first(q.reviewSource)??"invoices") as PmReviewQuery["kind"],review=first(q.pmReview),missing=first(q.reviewMissing)==="yes";
  const result=await repository.listPmReview(session,{...base(q),kind,review,missing,limit:size,offset:(page-1)*size}),parent=result.parent;
  const count=result.totalCount,pages=Math.max(1,Math.ceil(count/size));
  const pagination:PaginationViewModel|undefined=pages===1&&page===1?undefined:{summary:`Page ${page} of ${pages}`,currentPage:page,totalPages:pages,pageLinks:[],previousHref:page>1?pmHref(q,{reviewPage:String(Math.min(page-1,pages))}):undefined,nextHref:page<pages?pmHref(q,{reviewPage:String(page+1)}):undefined};
  const title=kind==="reviews"?"PM invoice reviews":kind==="invoices"?"Invoices in this review":kind==="visits"?"Visits in this review":"PM windows in this review";
  const selection=base(q),selectedStore=selection.store||selection.region?await repository.searchStores(pmScheduleScope(session,selection),"",{limit:1}):undefined;
  const scope=parent?`${store(parent,session)} · ${parent.programName}`:selection.store?selectedStore?.items[0]?compactStoreLabel(`Store ${selectedStore.items[0].storeNumber} · ${selectedStore.items[0].name}`,session.organizationName):"Store unavailable":selection.region?`${selectedStore?.items[0]?.regionName??"Region unavailable"} · ${selectedStore?.totalCount??0} stores`:session.scopeLabel;
  const rows:TableRowViewModel[]=kind==="reviews"?result.reviews.map(r=>({id:r.id,label:r.programName,href:pmReviewHref(q,"invoices",r.id),cells:[{key:"record",value:store(r,session),secondary:r.programName},{key:"period",value:r.periodLabel},{key:"amount",value:money(r.amountMinor,r.currency),secondary:`${r.invoiceCount} invoices`,link:{href:pmReviewHref(q,"invoices",r.id),label:"Open all invoices"}},{key:"missing",value:`${r.missingCount} PM windows`,secondary:r.unavailableLinks?`${r.unavailableLinks} links unavailable`:"No visit recorded",link:{href:pmReviewHref(q,"occurrences",r.id,true),label:"Review windows without visits"}}]})):
    result.sources.map(r=>{const href=kind==="invoices"?`/app/invoices/${encodeURIComponent(r.id)}`:kind==="visits"?`/app/visits/${encodeURIComponent(r.id)}`:`/app/pm/occurrences/${encodeURIComponent(r.id)}?${new URLSearchParams({returnTo:pmHref(q)})}`;return {id:r.id,label:r.label,href,cells:[{key:"record",value:r.label,secondary:r.detail},{key:"date",value:kind==="invoices"?r.date:formatOperationsDate(r.date)},{key:"status",value:r.status.replaceAll("_"," ")},...(kind==="invoices"?[{key:"amount",value:money(r.amountMinor,r.currency)}]:[])]};});
  const metrics=parent?[{id:"invoices",label:"Invoices",value:String(parent.invoiceCount),href:pmReviewHref(q,"invoices",parent.id)},{id:"visits",label:"Recorded visits",value:String(parent.visitCount),href:pmReviewHref(q,"visits",parent.id)},{id:"windows",label:"PM windows",value:String(parent.occurrenceCount),href:pmReviewHref(q,"occurrences",parent.id)},{id:"missing",label:"Without visits",value:String(parent.missingCount),href:pmReviewHref(q,"occurrences",parent.id,true)}].map(m=>({id:m.id,label:m.label,value:m.value,supportingText:"",link:{href:m.href,label:`Review ${m.label.toLowerCase()}`}})):[];
  return {state:kind!=="reviews"&&!parent?{kind:"empty",title:"Review unavailable",message:"This review is outside your scope or is no longer open."}:{kind:"ready"},page:{title,description:"Missing visit evidence is a reason to check the records.",scopeLabel:scope,periodLabel:parent?.periodLabel??"Open reviews",secondaryAction:{label:parent?"Back to PM reviews":"Back to PM schedule",href:parent?pmReviewHref(q):pmHref(q,{pmReview:undefined,reviewSource:undefined,reviewMissing:undefined,reviewPage:undefined})}},metrics,priorityActions:[],breakdowns:[],trends:[],
    sourceDescription:parent?`${kind==="invoices"?`${money(missing?parent.missingAmountMinor:parent.amountMinor,parent.currency)} linked invoice amount. `:""}${parent.unavailableLinks?`${parent.unavailableLinks} source links are unavailable. `:""}Current source evidence.`:"",
    sourceMethodology:parent?"Amounts use the invoice allocations linked to this store and PM program. Currencies stay separate. Visits come from the linked work records, across all recorded channels. Missing visits do not show that service was not performed. Counts reflect current evidence; the original review remains recorded.":undefined,
    filters:parent&&kind!=="visits"?[{id:"evidence",label:"Evidence",options:[{value:"all",label:"All records",selected:!missing,href:pmReviewHref(q,kind,parent.id)},{value:"missing",label:"Without visit evidence",selected:missing,href:pmReviewHref(q,kind,parent.id,true)}]}]:undefined,
    table:{id:"pm-review-evidence",caption:title,rows,columns:kind==="reviews"?[{key:"record",label:"Store / schedule"},{key:"period",label:"Review period"},{key:"amount",label:"Linked invoice amount"},{key:"missing",label:"Without visit evidence"}]:[{key:"record",label:kind==="invoices"?"Invoice":kind==="visits"?"Technician / provider":"Work order / schedule"},{key:"date",label:kind==="invoices"?"Invoice date":kind==="visits"?"Check-in":"Due date"},{key:"status",label:"Status"},...(kind==="invoices"?[{key:"amount",label:"Linked invoice amount"}]:[])]},resultSummary:`${rows.length?(page-1)*size+1:0}–${rows.length?(page-1)*size+rows.length:0} of ${count}`,pagination};
}
