import "server-only";
import { getRequestOpsFixtureSnapshot } from "@/app/app/_data/request-data";
import type { ValueEventCategory } from "@/lib/ops/types";
import { loadOperatorSession } from "./operator-loader";

export async function loadValueLedgerWorkspace(category?:ValueEventCategory){
  const[fixture,session]=await Promise.all([getRequestOpsFixtureSnapshot(),loadOperatorSession()]);const organizationId=session.organizationId;
  const allowedStore=(storeId:string)=>{const store=fixture.stores.find((item)=>item.organizationId===organizationId&&item.id===storeId);if(!store)return false;if(session.storeIds?.length&&!session.storeIds.includes(store.id))return false;if(session.regionIds?.length&&(!store.regionId||!session.regionIds.includes(store.regionId)))return false;return true};
  const allowedEvent=(event:(typeof fixture.valueEvents)[number])=>{if(event.organizationId!==organizationId)return false;if(event.workOrderId){const work=fixture.workOrders.find((item)=>item.organizationId===organizationId&&item.id===event.workOrderId);return Boolean(work&&allowedStore(work.storeId))}if(event.assetId){const asset=fixture.assets.find((item)=>item.organizationId===organizationId&&item.id===event.assetId);return Boolean(asset&&allowedStore(asset.storeId))}if(event.invoiceLineId){const allocations=fixture.invoiceLineAllocations.filter((item)=>item.organizationId===organizationId&&item.invoiceLineId===event.invoiceLineId);return allocations.length>0&&allocations.every((item)=>allowedStore(item.storeId))}if(event.warrantyCaseId){const item=fixture.warrantyCases.find((candidate)=>candidate.organizationId===organizationId&&candidate.id===event.warrantyCaseId);const work=item&&fixture.workOrders.find((candidate)=>candidate.id===item.workOrderId);return Boolean(work&&allowedStore(work.storeId))}if(event.serviceRunId){const stops=fixture.routeStops.filter((item)=>item.organizationId===organizationId&&item.serviceRunId===event.serviceRunId);return stops.length>0&&stops.every((item)=>allowedStore(item.storeId))}return !session.storeIds?.length&&!session.regionIds?.length};
  const allEvents=fixture.valueEvents.filter(allowedEvent).sort((left,right)=>right.occurredAt.localeCompare(left.occurredAt));return{fixture,session,allEvents,events:category?allEvents.filter((event)=>event.category===category):allEvents,category};
}
