import Link from "next/link";
import type { Asset, AssetComponent, OpsFixture } from "@/lib/ops/types";
import styles from "./component-lifecycle-panel.module.css";

const money = (minor: number, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(minor / 100);
const date = (value?: string) => value ? new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(value)) : "Not recorded";
const monthsBetween = (start?: string, end?: string) => start && end ? Math.max(0, Math.round((Date.parse(end) - Date.parse(start)) / 2_629_746_000)) : undefined;
const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b); return sorted.length ? sorted.length % 2 ? sorted[(sorted.length - 1) / 2] : Math.round((sorted[sorted.length / 2 - 1] + sorted[sorted.length / 2]) / 2) : undefined; };

export function ComponentLifecyclePanel({ fixture, asset, component, canManage }: { fixture: OpsFixture; asset: Asset; component: AssetComponent; canManage: boolean }) {
  const organizationEvents = fixture.componentLifecycleEvents.filter((event) => event.organizationId === asset.organizationId);
  const events = organizationEvents.filter((event) => event.removedComponentId === component.id || event.installedComponentId === component.id).sort((a, b) => b.removedAt.localeCompare(a.removedAt));
  const eventStats = organizationEvents.map((event) => {
    const removed = fixture.components.find((item) => item.id === event.removedComponentId);
    return { event, actualMonths: monthsBetween(removed?.installedAt, event.removedAt) };
  });
  const currentEvent = events[0];
  const currentRemoved = currentEvent ? fixture.components.find((item) => item.id === currentEvent.removedComponentId) : undefined;
  const actualMonths = currentEvent ? monthsBetween(currentRemoved?.installedAt, currentEvent.removedAt) : undefined;
  const lifeRatio = actualMonths && currentEvent?.expectedLifeMonths ? actualMonths / currentEvent.expectedLifeMonths : undefined;
  const modelCohort = currentEvent ? eventStats.filter(({ event }) => event.partManufacturer === currentEvent.partManufacturer && event.partModel === currentEvent.partModel && event.expectedLifeMonths && monthsBetween(fixture.components.find((item) => item.id === event.removedComponentId)?.installedAt, event.removedAt) !== undefined) : [];
  const prematureRate = modelCohort.length ? modelCohort.filter(({ event, actualMonths: life }) => life! < event.expectedLifeMonths! * .75).length / modelCohort.length : undefined;
  const assetWork = fixture.workOrders.filter((work) => work.assetId === asset.id);
  const eligible = fixture.siteVisitWorkOrders.flatMap((visitWork) => {
    const work = assetWork.find((item) => item.id === visitWork.workOrderId);
    const visit = fixture.visits.find((item) => item.id === visitWork.visitId);
    const verified = fixture.workOrderVerifications.find((item) => item.siteVisitWorkOrderId === visitWork.id && item.decision === "verified");
    const recorded = fixture.repairItems.some((item) => item.siteVisitWorkOrderId === visitWork.id);
    return work && visit?.vendorId && verified && !recorded && ["completed", "no_issue_found"].includes(visitWork.outcome ?? "") && (!work.componentId || work.componentId === component.id) ? [{ visitWork, work, visit }] : [];
  });
  const warrantyCases = currentEvent ? fixture.warrantyCases.filter((item) => item.priorRepairItemId === currentEvent.repairItemId) : [];
  const repeatWork = currentEvent ? fixture.workOrders.filter((work) => work.componentId === currentEvent.installedComponentId && Date.parse(work.createdAt) > Date.parse(currentEvent.installedAt)) : [];

  return <div className={styles.stack}>
    <section className={styles.panel} id="component-life"><div className={styles.heading}><div><h2>Component replacement intelligence</h2><p>Structured removed/installed identity, verified repair evidence, cost, Vendor, warranty, and service life. Cohorts remain visibly sample-limited; no opaque health score is used.</p></div></div>
      <div className={styles.metrics}><div className={styles.metric}><small>Actual life</small><strong>{actualMonths === undefined ? "Insufficient data" : `${actualMonths} months`}</strong></div><div className={styles.metric}><small>Expected life</small><strong>{currentEvent?.expectedLifeMonths ? `${currentEvent.expectedLifeMonths} months` : "Not recorded"}</strong></div><div className={styles.metric}><small>Life ratio</small><strong className={lifeRatio !== undefined && lifeRatio < .75 ? styles.risk : styles.good}>{lifeRatio === undefined ? "Insufficient data" : `${Math.round(lifeRatio * 100)}%`}</strong></div><div className={styles.metric}><small>Warranty opportunity</small><strong>{warrantyCases.length ? `${warrantyCases.length} matched case` : "None detected"}</strong></div></div>
      <div className={styles.body}><p className={styles.notice}><strong>Model cohort:</strong> {modelCohort.length ? `${modelCohort.length} replacement${modelCohort.length === 1 ? "" : "s"}; median ${median(modelCohort.flatMap((row) => row.actualMonths ?? []))} months; premature-failure rate ${Math.round((prematureRate ?? 0) * 100)}%.` : "No comparable model replacements yet."} {modelCohort.length < 5 ? "Small sample—use as review evidence, not a causal or replacement decision." : "Open source records before making a capital decision."} Repeat work after the installed replacement: {repeatWork.length}.</p></div>
      <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Removed / installed</th><th>Failure and root cause</th><th>Vendor / work</th><th>Cost</th><th>Life / warranty</th></tr></thead><tbody>{events.length ? events.map((event) => { const vendor = fixture.vendors.find((item) => item.id === event.vendorId); const work = fixture.workOrders.find((item) => item.id === event.workOrderId); const removed = fixture.components.find((item) => item.id === event.removedComponentId); const life = monthsBetween(removed?.installedAt, event.removedAt); return <tr key={event.id}><td>{date(event.removedAt)} → {date(event.installedAt)}<span className={styles.meta}>{event.partManufacturer} {event.partModel} · S/N {event.serialNumber ?? "not entered"} · {event.replacementKind}</span></td><td>{event.failureMode}<span className={styles.meta}>{event.rootCause ?? "Root cause not established"}</span></td><td>{vendor?.name ?? event.vendorId}<span className={styles.meta}><Link href={`/app/work-orders/${event.workOrderId}`}>{work?.number ?? event.workOrderId}</Link> · Repair Item {event.repairItemId}</span></td><td>{money(event.laborCost.amountMinor + event.partCost.amountMinor, event.laborCost.currency)}<span className={styles.meta}>Labor {money(event.laborCost.amountMinor, event.laborCost.currency)} · part {money(event.partCost.amountMinor, event.partCost.currency)}</span></td><td>{life === undefined ? "Actual life unavailable" : `${life} months actual`}<span className={styles.meta}>{event.expectedLifeMonths ? `${event.expectedLifeMonths} expected` : "Expected life not entered"} · warranty {date(event.warrantyEndsAt)}</span></td></tr>; }) : <tr><td colSpan={5}>No structured replacement event has been recorded for this Component.</td></tr>}</tbody></table></div>
    </section>
    {canManage && !component.removedAt ? <section className={styles.panel}><div className={styles.heading}><div><h2>Record a verified Component replacement</h2><p>This action requires an accepted outside-Vendor Site Visit outcome. It creates the Repair Item, installed Component, calculated warranty records, lifecycle history, Audit Event, and Outbox Message together.</p></div></div><div className={styles.body}>{eligible.length ? <form className={styles.form} action={`/api/ops/equipment/${asset.id}/components/${component.id}/replacement`} method="post"><div className={styles.grid}><label>Verified service outcome<select name="siteVisitWorkOrderId" required defaultValue=""><option value="" disabled>Select outcome</option>{eligible.map(({ visitWork, work, visit }) => <option key={visitWork.id} value={visitWork.id}>{work.number} · {visit.providerName} · {date(visitWork.outcomeRecordedAt)}</option>)}</select></label><label>Replacement type<select name="replacementKind" defaultValue="reactive"><option value="reactive">Reactive</option><option value="planned">Planned</option></select></label><label>Severity<select name="repairSeverity" defaultValue="major"><option value="minor">Minor</option><option value="moderate">Moderate</option><option value="major">Major</option><option value="critical">Critical</option></select></label><label>Removal date<input name="removedAt" type="date" required /></label><label>Installation date<input name="installedAt" type="date" required /></label><label>Warranty end<input name="warrantyEndsAt" type="date" /></label><label>Installed component name<input name="installedComponentName" defaultValue={component.name} /></label><label>Manufacturer<input name="partManufacturer" required /></label><label>Model<input name="partModel" required /></label><label>Part number<input name="partNumber" /></label><label>Serial number<input name="serialNumber" /></label><label>Expected life (months)<input name="expectedLifeMonths" type="number" min="1" /></label><label>Labor cost (dollars)<input name="laborCost" inputMode="decimal" required /></label><label>Part cost (dollars)<input name="partCost" inputMode="decimal" required /></label><label>Currency<input name="currency" defaultValue="USD" maxLength={3} required /></label></div><input type="hidden" name="vendorSupplied" value="yes" /><label>Failure mode<input name="failureMode" required /></label><label>Root cause<textarea name="rootCause" /></label><label>Repair action<textarea name="repairAction" required /></label><button className={styles.button} type="submit">Record replacement and warranties</button></form> : <p className={styles.empty}>No unrecorded verified outside-Vendor outcome is available for this Component. Complete and internally verify its Work Order first; the action will then appear here.</p>}</div></section> : null}
  </div>;
}
