import Link from "next/link";
import type { OpsFixture, ServiceRun } from "@/lib/ops/types";
import styles from "./service-run-workspace.module.css";

function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value)); }
function money(amountMinor: number, currency: string) { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(amountMinor / 100); }

export function ServiceRunListWorkspace({ fixture, runs }: { fixture: OpsFixture; runs: ServiceRun[] }) {
  const proposed = runs.filter((run) => ["recommended", "proposed", "countered"].includes(run.status)).length;
  const committed = runs.filter((run) => ["accepted", "committed", "in_progress"].includes(run.status)).length;
  return <div className={styles.page}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Maintenance orchestration</p><h1>Service Run planner</h1><p>Bundle independent Work Orders only after qualifications, contract scope, compliance, due windows, access, authorization, equipment, and protected Vendor capacity pass.</p></div></header>
    <section className={styles.metrics} aria-label="Service Run measures"><div className={styles.metric}><span>Awaiting response</span><strong>{proposed}</strong></div><div className={styles.metric}><span>Committed runs</span><strong>{committed}</strong></div><div className={styles.metric}><span>Planned truck-roll reduction</span><strong>{runs.reduce((sum, run) => sum + run.estimatedTripReduction, 0)}</strong></div><div className={styles.metric}><span>Estimated opportunity</span><strong>{money(runs.reduce((sum, run) => sum + run.estimatedOpportunity.amountMinor, 0), "USD")}</strong></div></section>
    <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Recommended and committed runs</h2><p>Estimated opportunity remains separate from realized and verified value.</p></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Service Run</th><th>Vendor</th><th>Window</th><th>Stops / work</th><th>Capacity</th><th>Status</th></tr></thead><tbody>{runs.map((run) => { const vendor = fixture.vendors.find((row) => row.id === run.vendorId); const stops = fixture.routeStops.filter((row) => row.serviceRunId === run.id); const work = fixture.serviceRunWorkOrders.filter((row) => row.serviceRunId === run.id && row.planned); return <tr key={run.id}><td><Link href={`/app/service-runs/${run.id}`}>{run.id.replace("service-run-", "")}</Link><div className={styles.muted}>{run.estimatedTripReduction} potential truck roll avoided</div></td><td>{vendor?.name}</td><td>{formatDate(run.committedStartsAt ?? run.proposedStartsAt)}</td><td>{stops.length} Stores · {work.length} Work Orders</td><td>{run.capacityUsedMinutes} min</td><td><span className={styles.pill}>{run.status.replaceAll("_", " ")}</span></td></tr>; })}</tbody></table></div></section>
  </div>;
}

export function ServiceRunDetailWorkspace({ fixture, run, publicResponseHref }: { fixture: OpsFixture; run: ServiceRun; publicResponseHref?: string }) {
  const vendor = fixture.vendors.find((row) => row.id === run.vendorId)!;
  const contract = fixture.contractVersions.find((row) => row.id === run.contractVersionId)!;
  const stops = fixture.routeStops.filter((row) => row.serviceRunId === run.id).sort((a, b) => a.sequence - b.sequence);
  const links = fixture.serviceRunWorkOrders.filter((row) => row.serviceRunId === run.id);
  const responses = fixture.serviceRunResponses.filter((row) => row.serviceRunId === run.id).sort((a, b) => a.respondedAt.localeCompare(b.respondedAt));
  const latestCounter = [...responses].reverse().find((row) => ["countered", "stop_change_requested", "work_order_change_requested"].includes(row.response));
  return <div className={styles.page}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Service Run · {vendor.name}</p><h1>{stops.length} stops, {links.filter((row) => row.planned).length} Work Orders</h1><p>{formatDate(run.committedStartsAt ?? run.proposedStartsAt)} · Contract Version {contract.version} · {run.schedulingMode.replaceAll("_", " ")}</p></div>{publicResponseHref && run.status === "proposed" ? <Link className={styles.button} href={publicResponseHref}>Open Vendor response</Link> : <Link className={styles.secondaryButton} href="/app/service-runs">Back to planner</Link>}</header>
    <section className={styles.metrics}><div className={styles.metric}><span>Protected capacity</span><strong>{run.capacityUsedMinutes} min</strong></div><div className={styles.metric}><span>Drive / service</span><strong>{run.estimatedDriveMinutes} / {run.estimatedServiceMinutes}</strong></div><div className={styles.metric}><span>Potential truck rolls avoided</span><strong>{run.estimatedTripReduction}</strong></div><div className={styles.metric}><span>Estimated opportunity</span><strong>{money(run.estimatedOpportunity.amountMinor, run.estimatedOpportunity.currency)}</strong></div></section>
    <div className={styles.grid}><div className={styles.stack}>
      <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Recommendation explanation</h2><p>Scheduler {run.schedulerVersion} · {run.confidence} duration confidence</p></div><span className={styles.pill}>{run.status}</span></div><div className={styles.body}><p className={styles.explanation}>{run.recommendationExplanation}</p><div className={styles.detailGrid}><div className={styles.detail}><small>Governing agreement</small><strong>{contract.sourceAgreementReference} · v{contract.version}</strong></div><div className={styles.detail}><small>Value class</small><strong>{money(run.estimatedOpportunity.amountMinor, run.estimatedOpportunity.currency)} estimated opportunity—not realized</strong></div><div className={styles.detail}><small>Qualifications</small><strong>{run.requiredQualifications.join(" · ")}</strong></div><div className={styles.detail}><small>Authorization</small><strong>{money(run.expectedWorkValue.amountMinor, run.expectedWorkValue.currency)} expected authorized work value</strong></div></div></div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Route and exact Work Orders</h2><p>Each Work Order keeps its own outcome, follow-up, verification, cost, and lifecycle history.</p></div></div>{stops.map((stop) => { const store = fixture.stores.find((row) => row.id === stop.storeId)!; const stopLinks = links.filter((row) => row.routeStopId === stop.id); return <div className={styles.stop} key={stop.id}><h3>Stop {stop.sequence} · Store {store.storeNumber} · {store.name}</h3><p className={styles.stopMeta}>{formatDate(stop.committedArrivalAt ?? stop.proposedArrivalAt)} · {stop.estimatedDriveMinutes} travel min · {stop.estimatedServiceMinutes} service/buffer min · {stop.accessRequirements}</p>{stopLinks.map((link) => { const workOrder = fixture.workOrders.find((row) => row.id === link.workOrderId)!; return <div className={styles.work} key={link.id}><Link href={`/app/work-orders/${workOrder.id}`}>{workOrder.number}</Link><strong>{link.occurrenceId ? "PM" : "Reactive"}</strong><span>{workOrder.problem}</span></div>; })}</div>; })}</section>
    </div><aside className={styles.stack}>
      <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Hard constraints</h2><p>Commitment is blocked when any fails.</p></div></div><div className={styles.body}>{Object.entries(JSON.parse(run.constraintsJson) as Record<string, unknown>).filter(([, value]) => value === true).map(([key]) => <p key={key}>✓ {key.replaceAll(/([A-Z])/g, " $1").toLowerCase()}</p>)}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Vendor response history</h2><p>The original recommendation is immutable.</p></div></div><div className={styles.body}>{responses.length ? <ul className={styles.timeline}>{responses.map((response) => <li key={response.id}><strong>{response.response.replaceAll("_", " ")}</strong><span>{response.responderName} · {formatDate(response.respondedAt)}</span><span>{response.reasonDetail}</span><span>Travel {response.travelImpactMinutes >= 0 ? "+" : ""}{response.travelImpactMinutes} min · Due windows affected {response.dueWindowImpactCount} · Economic impact {money(response.economicImpact.amountMinor, response.economicImpact.currency)}</span></li>)}</ul> : <p className={styles.muted}>No response recorded yet.</p>}</div></section>
      {run.status === "countered" && latestCounter ? <section className={styles.panel}><div className={styles.panelHeader}><div><h2>Accept latest counter</h2><p>Server rechecks scope and PM due windows before commitment.</p></div></div><div className={styles.body}><form className={styles.form} action={`/api/ops/service-runs/${run.id}/accept-counter`} method="post"><input type="hidden" name="responseId" value={latestCounter.id} /><button className={styles.button} type="submit">Accept counterproposal</button></form></div></section> : null}
      <p className={styles.warning}>Estimated route value is never promoted to realized savings by acceptance alone. Combined visits, addressed Work Orders, and contract or invoice evidence are still required.</p>
    </aside></div>
  </div>;
}
