"use client";
import { useState } from "react";
import type { SelectOptionViewModel } from "./data-contract";
import styles from "./ops.module.css";
export function StorePicker({initial,defaultStoreId,searchable=false,initialCursor}:{initial:SelectOptionViewModel[];defaultStoreId?:string;searchable?:boolean;initialCursor?:string}){
 const [items,setItems]=useState(initial),[selected,setSelected]=useState(initial.find(s=>s.value===defaultStoreId)),[query,setQuery]=useState(""),[applied,setApplied]=useState(""),[next,setNext]=useState<string|undefined>(initialCursor),[trail,setTrail]=useState([""]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[searched,setSearched]=useState(false);
 async function load(q:string,cursor:string,history:string[]){if(busy)return;setBusy(true);setError("");try{const response=await fetch(`/api/ops/store-options?${new URLSearchParams({q,...(cursor?{cursor}:{})})}`),data=await response.json() as {items:SelectOptionViewModel[];nextCursor?:string;error?:string};if(!response.ok)throw new Error(data.error??"Could not load stores.");setItems(data.items);setNext(data.nextCursor);setTrail(history);setApplied(q);setSearched(true);}catch(e){setError(e instanceof Error?e.message:"Could not load stores.");}finally{setBusy(false);}}
 const choices=selected&&!items.some(s=>s.value===selected.value)?[selected,...items]:items;
 return <div><label className={styles.field} htmlFor="request-store"><span>Store <em>Required</em></span><select id="request-store" name="storeId" required value={selected?.value??""} onChange={e=>setSelected(choices.find(s=>s.value===e.target.value))}><option value="" disabled>Choose a store</option>{choices.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label>
 {searchable?<details><summary>Find another store</summary><label className={styles.field}>Store number, name or address<input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void load(query,"",[""]);}}} maxLength={160}/></label><button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>load(query,"",[""])}>{busy?"Searching…":"Search stores"}</button>{error?<p role="alert">{error}</p>:null}<p aria-live="polite">{!busy&&searched?(items.length?`${items.length} stores on this page`:"No matching stores. Try a different search."):""}</p>{trail.length>1?<button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>load(applied,trail[trail.length-2],trail.slice(0,-1))}>Back</button>:null}{next?<button type="button" className={styles.secondaryButton} disabled={busy} onClick={()=>load(applied,next,[...trail,next])}>More stores</button>:null}</details>:null}</div>;
}
