"use client";

import { useState, type FormEvent } from "react";
import { CheckCircle2, ChevronRight, PackageCheck, Store } from "lucide-react";
import styles from "./ops.module.css";

export interface StoreEquipmentSetupViewModel { storeId: string; storeLabel: string; addressLabel: string; action: string; backHref: string; groups: Array<{ id: string; name: string; pathLabel: string; templates: Array<{ id: string; name: string; expectedLifeLabel: string; componentLabel: string; alreadyAtStore: number }> }> }

export function StoreEquipmentSetup({ model }: { model: StoreEquipmentSetupViewModel }) {
  const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(undefined); const response = await fetch(model.action, { method: "POST", body: new FormData(event.currentTarget), credentials: "same-origin", headers: { "x-traceops-client": "store-equipment-setup" } }); const body = await response.json().catch(() => null) as { error?: string; redirectTo?: string } | null; if (!response.ok) { setPending(false); setError(body?.error ?? "The store equipment could not be created."); return; } window.location.assign(body?.redirectTo ?? model.backHref); }
  return <div className={styles.pageStack}><header className={styles.taxonomyHero}><div><p>Store setup</p><h1>What equipment is at this store?</h1><span>{model.storeLabel} · {model.addressLabel}</span></div><Store aria-hidden="true" size={30} /></header><section className={styles.storeTemplateIntro}><PackageCheck aria-hidden="true" size={24} /><div><h2>Select it and you’re done</h2><p>Enter a quantity only for equipment this store has. TraceOps creates the equipment and its standard component records automatically. You can personalize model and serial numbers later.</p></div></section><form action={model.action} method="post" onSubmit={submit} className={styles.storeTemplateForm}>{model.groups.map((group) => <section className={styles.storeTemplateGroup} key={group.id}><header><div><small>{group.pathLabel}</small><h2>{group.name}</h2></div></header><div>{group.templates.map((template) => <label className={styles.storeTemplateRow} key={template.id}><span><strong>{template.name}</strong><small>{template.componentLabel} · {template.expectedLifeLabel}{template.alreadyAtStore ? ` · ${template.alreadyAtStore} already recorded` : ""}</small></span><span>Quantity<input aria-label={`${template.name} quantity`} defaultValue="0" min="0" max="50" name={`quantity:${template.id}`} type="number" /></span></label>)}</div></section>)}{error ? <p className={styles.replacementError} role="alert">{error}</p> : null}<div className={styles.storeTemplateActions}><a className={styles.secondaryButton} href={model.backHref}>Skip for now</a><button className={styles.primaryButton} disabled={pending} type="submit">{pending ? "Creating equipment..." : "Create selected equipment"}<ChevronRight aria-hidden="true" size={17} /></button></div></form><p className={styles.storeTemplateFootnote}><CheckCircle2 aria-hidden="true" size={17} />Company templates are copied into this store. Later template edits do not silently rewrite existing store records.</p></div>;
}
