import Link from "next/link";
import type { OpsFixture, WarrantyCase } from "@/lib/ops/types";
import { recordedWarrantyDiagnosis } from "@/lib/ops/warranty-review";
import { recordedMoneyLabel } from "@/lib/ops/work-review";
import { formatOperationsDate, formatOperationsDateTime, DEFAULT_OPERATIONS_TIME_ZONE } from "@/lib/ops/local-time";
import { WorkReviewButton } from "@/components/workspace/work-review";
import { WarrantyDecisionForm } from "./warranty-decision-form";
import styles from "./warranty-finance-workspace.module.css";

const words = (value?: string) => value ? value.replace(/[_-]/g, " ") : "Not recorded";
const routing: Record<string, string> = { original_vendor_mandatory: "Use the original vendor", original_vendor_first_right_to_cure: "Give the original vendor the first chance to fix it", manufacturer_authorized_provider: "Use a manufacturer-authorized provider", any_approved_provider: "Any approved provider can do the repair", manual_review: "Facilities needs to choose the provider" };
const coverage: Record<string, string> = { pending_diagnosis: "Not decided — diagnosis needed", covered: "Repair covered by warranty", split: "Some costs covered", not_covered: "Customer responsible for this repair" };

export function WarrantyCaseWorkspace({ fixture, warrantyCase: item, canManage, returnQueue, updated }: { fixture: OpsFixture; warrantyCase: WarrantyCase; canManage: boolean; returnQueue?: string; updated?: boolean }) {
  const org = item.organizationId;
  const work = fixture.workOrders.find((row) => row.organizationId === org && row.id === item.workOrderId);
  const store = fixture.stores.find((row) => row.organizationId === org && row.id === work?.storeId);
  if (!work || !store) return <p role="alert">This warranty case is unavailable.</p>;
  const asset = fixture.assets.find((row) => row.organizationId === org && row.id === item.assetId && row.storeId === store.id);
  const component = fixture.components.find((row) => row.organizationId === org && row.id === item.componentId && row.assetId === asset?.id);
  const repair = fixture.repairItems.find((row) => row.organizationId === org && row.id === item.priorRepairItemId && row.assetId === asset?.id);
  const prior = fixture.workOrders.find((row) => row.organizationId === org && row.id === repair?.workOrderId && row.storeId === store.id);
  const terms = repair && prior ? fixture.appliedWarranties.filter((row) => row.organizationId === org && row.repairItemId === repair.id) : [];
  const manufacturer = fixture.manufacturerWarranties.find((row) => row.organizationId === org && row.id === item.manufacturerWarrantyId && row.assetId === asset?.id);
  const amendments = fixture.warrantyAmendments.filter((row) => row.organizationId === org && terms.some((term) => term.id === row.appliedWarrantyId));
  const vendor = fixture.vendors.find((row) => row.organizationId === org && row.id === item.obligatedVendorId);
  const diagnosis = recordedWarrantyDiagnosis(fixture, item);
  const date = (value?: string) => value ? (value.length <= 10 ? formatOperationsDate(value, store.timeZone ?? DEFAULT_OPERATIONS_TIME_ZONE) : formatOperationsDateTime(value, store.timeZone ?? DEFAULT_OPERATIONS_TIME_ZONE)) : "Not recorded";
  return <main className={`${styles.page} ${styles.warrantyReview}`}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Warranty review · Store {store.storeNumber}</p><h1>Check the diagnosis and warranty</h1><p><Link href={`/app/work-orders/${work.id}`}>{work.number}</Link> · {asset?.name ?? "Equipment not linked"}{component ? ` · ${component.name}` : ""}</p></div><Link className={styles.secondaryButton} href={returnQueue ?? "/app/warranties"}>{returnQueue ? "Back to your work list" : "All warranty cases"}</Link></header>
    {updated ? <p role="status" className={styles.notice}>Diagnosis and warranty decision saved.</p> : null}
    <p className={styles.notice}><strong>Reported problem:</strong> {work.problem}</p>
    <section className={styles.metrics} aria-label="Current warranty review"><div className={styles.metric}><span>Diagnosis</span><strong>{diagnosis?.diagnosis ? "Recorded" : "Not recorded"}</strong></div><div className={styles.metric}><span>Who pays?</span><strong>{coverage[item.coverageDecision]}</strong></div><div className={styles.metric}><span>Repair provider</span><strong>{vendor?.name ?? "Needs to be confirmed"}</strong></div><div className={styles.metric}><span>Invoice</span><strong>{item.invoiceHold ? "On hold" : "No warranty hold"}</strong></div></section>
    <nav className={styles.reviewNav} aria-label="Warranty review sections"><a href="#diagnosis">Diagnosis</a><a href="#prior-repair">Earlier repair</a><a href="#warranty-terms">Warranty terms</a><a href="#warranty-provider">Repair provider</a><a href="#warranty-decision">Record the decision</a></nav>
    <section className={styles.panel} id="diagnosis"><div className={styles.panelHeader}><div><h2>What failed this time?</h2><p>The current diagnosis is separate from the earlier repair.</p></div></div><div className={styles.body}>
      <p><strong>{work.number}:</strong> {work.problem}</p>
      {diagnosis?.diagnosis ? <><p><strong>{diagnosis.diagnosis}</strong></p><p>Recorded by {diagnosis.by} · {date(diagnosis.at)}</p><p><strong>Warranty decision reason:</strong> {diagnosis.reason ?? "Not recorded"}</p></> : <><p><strong>No diagnosis has been recorded for this warranty case.</strong> Ask the technician to confirm the cause. The earlier repair and warranty terms below help you decide whether this repair is covered.</p><Link className={styles.sectionLink} href={`/app/work-orders/${work.id}?view=visits`}>Review technician notes and visit outcomes →</Link></>}
      <p><Link href={`/app/work-orders/${work.id}?view=service`}>Contact or follow up with the repair provider →</Link></p>
    </div></section>
    <section className={styles.panel} id="prior-repair"><div className={styles.panelHeader}><div><h2>What was repaired before?</h2><p>Compare this recorded repair with the current diagnosis.</p></div></div><div className={styles.body}>{repair && prior ? <><p><Link className={styles.sectionLink} href={`/app/work-orders/${prior.id}?view=visits`}>{prior.number} · {date(repair.completionDate)}</Link> <WorkReviewButton href={`/app/work-orders/${prior.id}`} label={prior.number} context="Warranty review · earlier repair" /></p><div className={styles.evidence}><div className={styles.fact}><small>Recorded failure</small><strong>{words(repair.failureCode)}</strong><span>{words(repair.repairAction)}</span></div><div className={styles.fact}><small>Installed part</small><strong>{[repair.partManufacturer, repair.partModel].filter(Boolean).join(" · ") || "Part details not recorded"}</strong><span>{repair.serialNumber ? `Serial ${repair.serialNumber}` : "Serial number not recorded"}</span></div><div className={styles.fact}><small>Recorded repair cost</small><strong>{recordedMoneyLabel([repair.laborCost, repair.partCost])}</strong><span>Labor and parts recorded for the earlier repair.</span></div></div></> : <p>No earlier confirmed repair is linked to this case.</p>}</div></section>
    <section className={styles.panel} id="warranty-terms"><div className={styles.panelHeader}><div><h2>What do the warranty terms cover?</h2><p>These are the terms recorded for the earlier repair. They do not establish the cause of this problem.</p></div></div><div className={styles.body}>
      {amendments.length ? <p className={styles.notice}><strong>The original terms were corrected.</strong> Read the correction history below before relying on the dates or coverage shown here.</p> : null}
      {terms.length ? terms.map((term) => <article className={styles.coverageTerm} key={term.id}><div><strong>{words(term.coverageType)}</strong><p>{term.policySource}</p><p>Covered charges: {term.coveredCharges.map(words).join(", ") || "Not recorded"}</p><p>Original term: {date(term.startDate)} – {date(term.endDate)}</p><p>{routing[term.routingRule] ?? words(term.routingRule)}</p></div></article>) : <p>No repair-warranty terms are linked. Obtain the contract or vendor confirmation before deciding coverage.</p>}
      {manufacturer ? <article><h3>Manufacturer warranty</h3><p>{manufacturer.manufacturer} · {date(manufacturer.startDate)} – {date(manufacturer.expirationDate)}</p><p>Parts: {manufacturer.partsCoverage}. Labor: {manufacturer.laborCoverage}.</p><p>{manufacturer.authorizedProviderRule} {manufacturer.claimRequirements}</p></article> : <p>No manufacturer warranty is linked to this case.</p>}
      <details><summary>Why this case was flagged</summary><p>{item.detectionExplanation}</p><p>The system found related records. It has not confirmed that the same part failed again.</p></details>
      {amendments.length ? <div><h3>Correction history</h3>{amendments.map((amendment) => <p key={amendment.id}><strong>{words(amendment.amendmentKind)}</strong> · {amendment.reason} · {date(amendment.decidedAt)}</p>)}</div> : null}
    </div></section>
    <section className={styles.panel} id="warranty-provider"><div className={styles.panelHeader}><div><h2>Who should do the repair?</h2><p>{routing[item.routingRule] ?? words(item.routingRule)}</p></div></div><div className={styles.body}><p><strong>{vendor?.name ?? "Provider not yet confirmed"}</strong>{item.vendorResponseDueAt ? ` · Response due ${date(item.vendorResponseDueAt)}` : ""}</p>{canManage ? <details><summary>Change the required provider</summary><form className={styles.form} action={`/api/ops/warranties/${item.id}/routing`} method="post"><label>Provider requirement<select name="routingRule" defaultValue={item.routingRule}>{Object.entries(routing).map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label><label>Reason for the change<select name="reasonCode" defaultValue="management_exception"><option value="safety_emergency">Safety emergency</option><option value="product_loss_emergency">Product at risk</option><option value="vendor_decline">Original vendor declined</option><option value="vendor_response_sla_failure">Vendor missed the response deadline</option><option value="manufacturer_direction">Manufacturer requested the change</option><option value="management_exception">Management-approved exception</option></select></label><label>Explain the change<textarea name="reasonDetail" required /></label><button className={styles.secondaryButton} type="submit">Save provider requirement</button></form></details> : null}</div></section>
    <section className={styles.panel} id="warranty-decision"><div className={styles.panelHeader}><div><h2>{item.coverageDecision === "pending_diagnosis" ? "Record the diagnosis and who pays" : "Recorded warranty decision"}</h2><p>{item.invoiceHold ? "The invoice remains on hold." : "There is no warranty hold on the invoice."}</p></div></div><div className={styles.body}>{canManage && item.coverageDecision === "pending_diagnosis" ? <WarrantyDecisionForm returnQueue={returnQueue} caseId={item.id} /> : <><p>{coverage[item.coverageDecision]}</p>{canManage ? <details><summary>Update the decision or invoice hold</summary><p>The earlier decision stays in the audit history. Explain why this update is needed.</p><WarrantyDecisionForm returnQueue={returnQueue} caseId={item.id} initialCoverage={item.coverageDecision} diagnosis={diagnosis?.diagnosis} hold={item.invoiceHold} /></details> : null}{!canManage ? <p>Your role can review the evidence. Facilities must record or change the warranty decision.</p> : null}</>}</div></section>
    {canManage && terms[0] ? <details className={styles.panel}><summary className={styles.panelHeader}>Correct the earlier repair’s warranty terms</summary><div className={styles.body}><p>This saves an audited correction to the earlier repair.</p><form className={styles.form} action={`/api/ops/warranties/applied/${terms[0].id}/amend`} method="post"><label>Correction<select name="amendmentKind"><option value="accept_calculated">Confirm the original terms</option><option value="override_coverage">Correct this repair’s coverage</option><option value="add_manufacturer">Add manufacturer evidence</option><option value="mark_unavailable">Mark warranty unavailable</option></select></label><label>Reason<textarea name="reason" required /></label><label>Corrected terms<textarea name="termsNote" required /></label><button className={styles.secondaryButton} type="submit">Save warranty correction</button></form></div></details> : null}
  </main>;
}
