import Link from "next/link";

import { domainLabel } from "@/lib/product/domain-label";
import type { OpsFixture, WarrantyCase } from "@/lib/ops/types";
import styles from "./warranty-finance-workspace.module.css";

const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(amount/100);
const label = domainLabel;

export function WarrantyQueueWorkspace({fixture,cases}:{fixture:OpsFixture;cases:WarrantyCase[]}){
  const exposure=fixture.valueEvents.filter((event)=>cases.some((item)=>item.id===event.warrantyCaseId)&&event.category==="identified_exposure").reduce((sum,event)=>sum+event.amount.amountMinor,0);
  return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Spend & planning · Warranty safeguards</p><h1>Warranty center</h1><p>Review possible warranty coverage using prior repairs and the terms that applied.</p></div></header><section className={styles.metrics}><div className={styles.metric}><span>Open cases</span><strong>{cases.filter((item)=>!item.closedAt).length}</strong></div><div className={styles.metric}><span>Diagnosis required</span><strong>{cases.filter((item)=>item.diagnosisRequired).length}</strong></div><div className={styles.metric}><span>Invoice holds</span><strong>{cases.filter((item)=>item.invoiceHold).length}</strong></div><div className={styles.metric}><span>Identified exposure</span><strong>{money(exposure,"USD")}</strong></div></section><p className={styles.notice}><strong>Coverage alert, not a charge decision.</strong> Amounts under review are separate from confirmed credits or deductions. Review the diagnosis before deciding who is responsible.</p><section className={styles.panel}><div className={styles.panelHeader}><div><h2>Cases requiring evidence review</h2><p>Exact source records remain available for every detection.</p></div></div><div className={styles.tableWrap}>{cases.length?<table className={styles.table}><thead><tr><th>Case</th><th>Work Order / Store</th><th>Confidence</th><th>Coverage</th><th>Routing</th><th>Charge / hold</th></tr></thead><tbody>{cases.map((item)=>{const workOrder=fixture.workOrders.find((row)=>row.id===item.workOrderId);const store=fixture.stores.find((row)=>row.id===workOrder?.storeId);return <tr key={item.id}><td><Link href={`/app/warranties/${item.id}`}>Open warranty case</Link><div className={styles.lineMeta}>{label(item.status)}</div></td><td><Link href={`/app/work-orders/${item.workOrderId}`}>{workOrder?.number}</Link><div className={styles.lineMeta}>Store {store?.storeNumber} · {store?.name}</div></td><td><span className={item.confidence==="high"?styles.goodPill:styles.riskPill}>{item.confidence}</span><div className={styles.lineMeta}>{item.diagnosisRequired?"Diagnosis required":"Diagnosis recorded"}</div></td><td>{label(item.coverageDecision)}</td><td>{label(item.routingRule)}</td><td>{label(item.customerChargeStatus)}<div className={styles.lineMeta}>{item.invoiceHold?"Invoice held":"No warranty hold"}</div></td></tr>})}</tbody></table>:<p className={styles.empty}>No warranty cases are in this scope.</p>}</div></section></div>;
}

export { WarrantyCaseWorkspace } from "./warranty-case-workspace";
