/** Read-only HTTP smoke audit. Run against an already running local preview. */
export {};
const origin = process.argv[2] ?? "http://localhost:3010";
if (!["localhost", "127.0.0.1", "[::1]"].includes(new URL(origin).hostname)) {
  throw new Error("Use a local preview URL for this audit.");
}
const roots = ["overview", "action-center", "requests", "work-orders", "stores", "equipment", "vendors", "spend", "spend?basis=invoiced&period=12m&store=store-northline-104", "trends", "invoices", "pm", "lifecycle", "search?q=104", "stores/new", "work-orders/new", "vendors/vendor-northline-summit?visitPage=2", "work-orders?costMonth=2026-07"];
const paths = new Set(roots.map((route) => `/app/${route}`));
const results: { path: string; status: number; ms: number; bytes: number; error?: string }[] = [];
const recordPaths = new Set<string>();
async function check(path: string) {
  const start = performance.now();
  const response = await fetch(new URL(path, origin), { signal: AbortSignal.timeout(60_000) });
  const html = await response.text();
  const records = [...html.matchAll(/href="(\/app\/(?:work-orders|requests|stores|vendors|equipment|visits|invoices)\/[^"?#]+)(?:[?#][^"]*)?"/g)]
    .map((match) => match[1]).filter((href) => !/\/(new|accounting|import)$/.test(href));
  for (const href of [...new Set(records)].slice(0, 3)) recordPaths.add(href);
  const error = !response.ok ? `HTTP ${response.status}`
    : /We could not load this workspace|"digest":"(?!NEXT_REDIRECT|NEXT_NOT_FOUND)[^"]+"|:E\{"digest"/.test(html) ? "Rendered server error" : undefined;
  const result = { path, status: response.status, ms: Math.round(performance.now() - start), bytes: Buffer.byteLength(html), ...(error ? { error } : {}) };
  results.push(result);
  console.log(JSON.stringify(result));
  return html;
}
for (const path of [...paths]) {
  const html = await check(path);
  // Exercise links generated by the running presentation, including empty months.
  if (path === "/app/overview" || path.startsWith("/app/spend")) {
    for (const match of html.matchAll(/href="([^"]+)"/g)) {
      const href = match[1].replaceAll("&amp;", "&");
      if (href.startsWith("/app/work-orders?") || href.startsWith("/app/lifecycle?") || href.startsWith("/app/invoices?")) paths.add(href);
    }
  }
}
for (const path of paths) if (!results.some((row) => row.path === path)) await check(path);
for (const path of [...recordPaths]) if (!results.some((row) => row.path === path)) await check(path);
console.log(JSON.stringify({ checked: results.length, failures: results.filter((row) => row.error), timing: "Local development HTTP render; excludes client hydration." }));
if (results.some((row) => row.error)) process.exitCode = 1;
