"use client";
import { useEffect, useState } from "react";
import styles from "./public-workflows.module.css";
type Job={id:string;number:string;problem:string;scope:string;status:string;unavailable?:string};
export function OptionalVisitWork({token}:{token:string}) {
  const [rows,setRows]=useState<Job[]>([]),[name,setName]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState("");
  useEffect(()=>{const c=new AbortController();fetch(`/api/public/service-optional-work?${new URLSearchParams({token})}`,{signal:c.signal}).then(async r=>{if(!r.ok) throw new Error(); const d=await r.json() as {rows:Job[]};setRows(d.rows);}).catch(e=>{if(e.name!=="AbortError")setError("Could not load optional jobs. Refresh to try again.");});return()=>c.abort();},[token]);
  async function respond(job:Job,decision:string){setBusy(job.id);setError("");try{const r=await fetch("/api/public/service-optional-work",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,workId:job.id,decision,name})});const d=await r.json() as {status:string;error?:string};if(!r.ok)throw new Error(d.error);setRows(items=>items.map(i=>i.id===job.id?{...i,status:d.status}:i));}catch(e){setError(e instanceof Error?e.message:"Could not save. Refresh before trying again.");}finally{setBusy("");}}
  if(!rows.length&&!error)return null;
  return <section className={styles.card} aria-label="Optional jobs for this visit"><h2 className={styles.cardTitle}>Also available at this store</h2><p>Choose the extra jobs you can handle. Skipped jobs stay saved for another visit.</p>{rows.some(r=>r.status==="offered"&&!r.unavailable)?<label>Your name<input style={{display:"block",padding:10,width:"100%"}} value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label>:null}{rows.map(job=><article key={job.id} style={{padding:"16px 0",borderBottom:"1px solid #dce2e9"}}><strong>{job.number} · {job.problem}</strong><p>{job.scope}</p>{job.status!=="offered"?<strong>{job.status==="accepted"?"Accepted for this visit":"Skipped · saved for later"}</strong>:job.unavailable?<p>{job.unavailable}</p>:<div style={{display:"flex",gap:12,flexWrap:"wrap"}}><button className={styles.button} type="button" disabled={!!busy||!name.trim()} onClick={()=>respond(job,"accepted")}>Accept this job</button><button className={styles.secondaryButton} type="button" disabled={!!busy||!name.trim()} onClick={()=>respond(job,"skipped")}>Skip this job</button></div>}</article>)}{error?<p role="alert">{error}</p>:null}</section>;
}
