import {expect} from "vitest";
import {saveCapitalPlan,capitalPriceChoices} from "@/lib/ops/capital-planning";
import {buildNorthlinePresentationFixture} from "@/lib/ops/fixtures";
import type {OpsRepository} from "@/lib/ops/repository";
export async function capitalRegression(repository:OpsRepository) {
 const org="org-northline-demo",scope={organizationId:org},fixture=buildNorthlinePresentationFixture();
 const asset=fixture.assets.find(a=>a.status!=="retired"&&!fixture.workOrders.some(w=>w.assetId===a.id))!;
 expect(asset).toBeTruthy();
 const actor={organizationId:org,actorType:"user" as const,actorId:"membership-northline-facilities",actorName:"Jordan Lee"},svc={repository};
 const input={organizationId:org,assetId:asset.id,version:0,currency:"USD",priority:"flexible" as const,owner:"Facilities",reason:"Proactive modernization",status:"planned" as const,actor};
 const query={start:"2026-10",months:12,currency:"USD",search:asset.assetTag};
 await saveCapitalPlan(svc,input);
 let page=await repository.queryCapitalPlans(scope,query);
 expect(page.items.find(r=>r.assetId===asset.id)?.amountMinor).toBeUndefined();expect(page.items.find(r=>r.assetId===asset.id)?.targetMonth).toBeUndefined();
 expect(page.buckets.find(b=>b.month==="undated")).toMatchObject({count:1,missing:1,amountMinor:0});
 await saveCapitalPlan(svc,{...input,version:1,targetMonth:"2026-11",amountMinor:1200000});
 page=await repository.queryCapitalPlans(scope,query);expect(page.total).toBe(1);expect(page.buckets).toContainEqual({month:"2026-11",count:1,missing:0,amountMinor:1200000});
 await expect(saveCapitalPlan(svc,{...input,version:1})).rejects.toMatchObject({code:"CONFLICT"});
 await saveCapitalPlan(svc,{...input,version:2,targetMonth:"2027-02",sourceId:"keep-saved"});
 page=await repository.queryCapitalPlans(scope,query);expect(page.buckets).not.toContainEqual(expect.objectContaining({month:"2026-11"}));expect(page.buckets).toContainEqual({month:"2027-02",count:1,missing:0,amountMinor:1200000});
 expect((await repository.queryCapitalPlans(scope,{...query,months:3})).total).toBe(0);
 expect((await repository.queryCapitalPlans(scope,{...query,month:"2027-02"})).items.map(r=>r.assetId)).toEqual([asset.id]);
 expect((await repository.queryCapitalPlans({...scope,storeIds:[]},query)).total).toBe(0);
 expect((await repository.queryCapitalPlans({organizationId:"foreign"},query)).total).toBe(0);
 await expect(saveCapitalPlan(svc,{...input,version:3,organizationId:"foreign"})).rejects.toMatchObject({code:"FORBIDDEN"});
 await expect(saveCapitalPlan(svc,{...input,version:3,sourceId:"foreign-price"})).rejects.toMatchObject({code:"VALIDATION"});
 await saveCapitalPlan(svc,{...input,version:3,currency:"CAD",amountMinor:900000,targetMonth:"2027-02"});
 expect((await repository.queryCapitalPlans(scope,query)).total).toBe(0);
 expect((await repository.queryCapitalPlans(scope,{...query,currency:"CAD"})).buckets).toContainEqual({month:"2027-02",count:1,missing:0,amountMinor:900000});
 const race=await Promise.allSettled([saveCapitalPlan(svc,{...input,version:4}),saveCapitalPlan(svc,{...input,version:4})]);expect(race.filter(r=>r.status==="fulfilled")).toHaveLength(1);
 await saveCapitalPlan(svc,{...input,version:5,status:"cancelled"});
 expect((await repository.queryCapitalPlans(scope,query)).total).toBe(0);
 expect((await repository.queryLifecycleQueue(scope,{view:"history",search:asset.assetTag})).items.find(r=>r.id===asset.id)?.decision).toBe("Plan removed");
 expect((await repository.queryLifecycleQueue({...scope,storeIds:[]},{view:"review"})).total).toBe(0);
 expect((await repository.getCapitalFilters({...scope,storeIds:[]})).stores).toEqual([]);
 expect(await capitalPriceChoices(repository,org,asset.id)).toEqual(expect.any(Array));
 expect(await capitalPriceChoices(repository,"foreign",asset.id)).toEqual([]);
 const legacy=fixture.assets.find(a=>a.id!==asset.id&&fixture.lifecycleRecommendations.some(l=>l.assetId===a.id&&["replace","defer"].includes(l.userDecision))&&!fixture.replacementEvents.some(e=>e.assetId===a.id&&e.status==="completed"))!;
 await saveCapitalPlan(svc,{...input,assetId:legacy.id,status:"cancelled"});
 expect((await repository.queryCapitalPlans(scope,{...query,search:legacy.assetTag})).items.some(r=>r.assetId===legacy.id)).toBe(false);
 const priced=fixture.assets.find(a=>a.id!==asset.id&&a.id!==legacy.id&&a.status!=="retired"&&a.replacementEstimate)!;
 const choices=await capitalPriceChoices(repository,org,priced.id),choice=choices[0];expect(choice).toBeTruthy();
 await saveCapitalPlan(svc,{...input,assetId:priced.id,sourceId:choice.id,amountMinor:1});
 expect(await repository.getCapitalPlan(org,priced.id)).toMatchObject({amountMinor:choice.amountMinor,currency:choice.currency,costBasis:choice.basis,sourceId:choice.id});
 await saveCapitalPlan(svc,{...input,assetId:priced.id,version:1,sourceId:"keep-saved",targetMonth:"2027-01"});
 expect(await repository.getCapitalPlan(org,priced.id)).toMatchObject({amountMinor:choice.amountMinor,costBasis:choice.basis,sourceId:choice.id});
 expect(await repository.listCapitalPlanHistory(org,priced.id)).toHaveLength(2);
 expect(await repository.listCapitalPlanHistory("foreign",priced.id)).toEqual([]);
 await saveCapitalPlan(svc,{...input,assetId:priced.id,version:2,status:"considering",sourceId:"keep-saved"});
 expect((await repository.queryCapitalPlans(scope,{...query,search:priced.assetTag})).items.find(r=>r.assetId===priced.id)?.status).toBe("considering");
 await saveCapitalPlan(svc,{...input,assetId:priced.id,version:3,status:"approved",sourceId:"keep-saved"});
 expect((await repository.queryCapitalPlans(scope,{...query,search:priced.assetTag})).items.find(r=>r.assetId===priced.id)?.status).toBe("approved");
 await saveCapitalPlan(svc,{...input,assetId:priced.id,version:4,status:"completed",sourceId:"keep-saved"});
 expect((await repository.queryCapitalPlans(scope,{...query,search:priced.assetTag})).items).toHaveLength(0);
 expect(await repository.listCapitalPlanHistory(org,priced.id)).toHaveLength(5);


 await saveCapitalPlan(svc,{...input,version:6,targetMonth:"2029",amountMinor:1230000});
 const annual=await repository.queryCapitalPlans(scope,{...query,month:"2029"});
 expect(annual.buckets).toContainEqual({month:"2029",count:1,missing:0,amountMinor:1230000});
 expect(annual.items.map(r=>r.assetId)).toEqual([asset.id]);
 expect((await repository.queryCapitalPlans(scope,{...query,start:"2030-01",month:"overdue"})).items).toEqual([]);
 const risks=await repository.listOperatingRisks(scope);
 expect(risks.totalCount).toBeGreaterThan(0);
 expect(await repository.listOperatingRisks({...scope,storeIds:[]})).toEqual({items:[],totalCount:0});
 expect(await repository.listOperatingRisks({organizationId:"foreign"})).toEqual({items:[],totalCount:0});

}
