import {vendorWarrantyPolicyRegression} from "./vendor-warranty-policy-regression";
import {capitalRegression} from "./capital-regression";
import { storeVendorRegression } from "./store-vendor-regression";
import { coverageVersion, updateVendorCoverage } from "@/lib/ops/vendor-coverage";
import { recordVendorComplianceDocument } from "@/lib/ops/commands";
import { masterDocuments } from "@/lib/ops/compliance-documents";
import type { StoredFile } from "@/lib/ops/types";
import { expect } from "vitest";
import type { OpsRepository } from "@/lib/ops/repository";
import { createComplianceSchedule,runInspectionCycle,recordInspectionResult,createInspectionCorrection,setComplianceScheduleStatus,nextInspectionDate,replaceComplianceDocuments } from "@/lib/ops/compliance";
import { deliverInspectionEmail } from "@/lib/ops/compliance-delivery";
import type { ComplianceSchedule } from "@/lib/ops/compliance-types";
export async function complianceRegression(repository:OpsRepository) {
 const org="org-northline-demo",actor={organizationId:org,actorType:"user" as const,actorId:"membership-northline-facilities",actorName:"Jordan Lee"};
 const svc={repository,clock:{now:()=>"2026-09-27T12:00:00.000Z"}};
 const input={organizationId:org,storeId:"store-northline-104",name:"Custom inspection acceptance",instructions:"Check exits",requirementSource:"Company schedule",evidenceLabel:"Inspection report",kind:"inspection" as const,firstDueDate:"2026-09-26",intervalUnit:"months" as const,intervalCount:1,leadDays:14,handler:"internal" as const,membershipId:actor.actorId,evidenceRequired:1,escalationDays:0,escalationTo:"Facilities coordinator"};
 const template:StoredFile={id:`template-${crypto.randomUUID()}`,organizationId:org,storageKey:"blank-checklist",sha256:"a".repeat(64),originalName:"blank-checklist.pdf",contentType:"application/pdf",byteLength:6,status:"available",createdAt:svc.clock.now()};
 const s=await createComplianceSchedule(svc,input,actor,[template]);
 expect(nextInspectionDate({...s,firstDueDate:"2024-01-31"},"2024-01-31")).toBe("2024-02-29");
 expect(nextInspectionDate({...s,firstDueDate:"2024-01-31"},"2024-02-29")).toBe("2024-03-31");
 await expect(createComplianceSchedule(svc,{...input,firstDueDate:"2026-02-31"},actor)).rejects.toMatchObject({code:"VALIDATION"});
 let ticking=Date.parse(svc.clock.now());
 const first=await runInspectionCycle({...svc,clock:{now:()=>new Date(ticking++).toISOString()}},org,s.id);expect(first).toMatchObject({failed:0,errors:[]});expect(first.created).toBe(3);
 const page=await repository.queryInspections({organizationId:org},{today:"2026-09-27",scheduleId:s.id});expect(page.totalCount).toBe(4);expect(page.summary.overdue).toBe(1);expect(page.summary.upcoming).toBe(3);
 expect(masterDocuments((await repository.getInspection(org,page.items[0].id))!)).toEqual([template]);
 const revised={...template,id:`template-${crypto.randomUUID()}`,originalName:"revised-checklist.pdf"};
 await replaceComplianceDocuments(svc,s,[revised],actor);
 expect(masterDocuments((await repository.getComplianceSchedule(org,s.id))!)).toEqual([revised]);
 expect(masterDocuments((await repository.getInspection(org,page.items[0].id))!)).toEqual([template]);
 let i=page.items[0];expect(i.workOrderId).toBeTruthy();expect((await repository.inspectionForWork(org,i.workOrderId!))?.id).toBe(i.id);
 expect((await repository.queryInspections({organizationId:org,storeIds:[]},{today:"2026-09-27"})).totalCount).toBe(0);
 expect(await repository.getInspection("other",i.id)).toBeNull();
 const replay=await runInspectionCycle(svc,org,s.id);expect(replay.created).toBe(0);expect(replay.reminders).toBe(0);expect(replay.failed).toBe(0);
 const result={organizationId:org,inspectionId:i.id,version:0,status:"performed" as const,note:"Performed; awaiting report",performedDate:"2026-09-26",files:[]};
 await recordInspectionResult(svc,result,actor);
 expect((await repository.queryInspections({organizationId:org},{today:"2026-09-27",scheduleId:s.id})).summary.missing_docs).toBe(1);
 await expect(recordInspectionResult(svc,{...result,version:1,status:"passed"},actor)).rejects.toMatchObject({code:"VALIDATION"});
 await recordInspectionResult(svc,{...result,version:1,status:"passed",note:"Report reviewed; no findings",files:[{id:`file-${crypto.randomUUID()}`,organizationId:org,storageKey:"test-inspection",sha256:"a".repeat(64),originalName:"inspection-photo.png",contentType:"image/png",byteLength:6,status:"available",createdAt:svc.clock.now()}]},actor);
 expect((await repository.getInspection(org,i.id))?.status).toBe("passed");expect((await repository.getWorkOrder(org,i.workOrderId!))?.status).toBe("closed");
 await expect(recordInspectionResult(svc,result,actor)).rejects.toMatchObject({code:"CONFLICT"});
 expect((await repository.inspectionHistory(org,i.id)).filter(h=>h.eventType==="inspection.result_recorded")).toHaveLength(2);
 const sent:string[]=[];await deliverInspectionEmail({repository,baseUrl:"https://example.test",provider:{name:"fake",async send(email){sent.push(email.to);return {messageId:"fake"};}}},{id:"test",organizationId:org,aggregateType:"inspection",aggregateId:i.id,topic:"ops.compliance.reminder",payloadJson:"{}",attemptCount:0},svc.clock.now());expect(sent).toHaveLength(0);
 const second=page.items[1];await recordInspectionResult(svc,{...result,inspectionId:second.id,status:"action_needed",note:"Exit light failed"},actor);
 const failed=(await repository.getInspection(org,second.id))!;const correction=await createInspectionCorrection(svc,failed,"Repair exit light",actor);expect(correction?.id).toBeTruthy();
 await expect(recordInspectionResult(svc,{...result,inspectionId:second.id,version:2,status:"passed"},actor)).rejects.toThrow("corrective work");
 const vendors=await repository.listVendors({organizationId:org},"ColdLine",{limit:5});const vendor=vendors.items[0];
 const vendorFile={...template,id:`vendor-file-${crypto.randomUUID()}`,originalName:"insurance.pdf"};
 const vendorDocument=await recordVendorComplianceDocument(svc,{organizationId:org,vendorId:vendor.id,documentType:"insurance",reference:"Policy acceptance",reviewStatus:"pending",file:vendorFile,actor});
 expect((await repository.listVendorComplianceDocuments(org,vendor.id)).find(d=>d.id===vendorDocument.id)?.storedFileId).toBe(vendorFile.id);
 expect(await repository.getStoredFileById(org,vendorFile.id)).toEqual(vendorFile);
 expect(await repository.getStoredFileById("foreign",vendorFile.id)).toBeNull();
 await expect(recordVendorComplianceDocument(svc,{organizationId:org,vendorId:vendor.id,documentType:"insurance",reference:"Invalid file",reviewStatus:"pending",file:{...vendorFile,organizationId:"foreign"},actor})).rejects.toMatchObject({code:"VALIDATION"});
 const external=await createComplianceSchedule(svc,{...input,name:"Outside inspection",intervalUnit:"once",handler:"vendor",membershipId:undefined,vendorId:vendor.id},actor,[template]);
 expect((await runInspectionCycle(svc,org,external.id)).failed).toBe(0);
 i=(await repository.queryInspections({organizationId:org},{today:"2026-09-27",scheduleId:external.id})).items[0];
 expect(await repository.getLatestIssuanceForWorkOrder(org,i.workOrderId!)).toBeTruthy();expect((await repository.inspectionDelivery(org,i.id)).some(d=>d.topic==="ops.compliance.authorization")).toBe(true);
 const message={id:"test-send",organizationId:org,aggregateType:"inspection",aggregateId:i.id,topic:"ops.compliance.authorization",payloadJson:"{}",attemptCount:0};
 const transport={repository,baseUrl:"https://example.test",readAttachment:async()=>new TextEncoder().encode("report").buffer,provider:{name:"fake",async send(email:{to:string;text:string;attachments?:Array<{filename:string}>}){sent.push(email.to);expect(email.text).toContain("Work Order / Service Authorization");expect(email.attachments?.map(a=>a.filename)).toEqual(["blank-checklist.pdf"]);return {messageId:"fake"};}}};
 await deliverInspectionEmail(transport,message,svc.clock.now());expect(sent).toHaveLength(1);
 await setComplianceScheduleStatus(svc,external,"paused",actor);await deliverInspectionEmail(transport,message,svc.clock.now());expect(sent).toHaveLength(1);
 await runInspectionCycle({...svc,clock:{now:()=>"2026-10-28T12:00:00.000Z"}},org,s.id);
 expect(masterDocuments((await repository.latestInspection(org,s.id))!)).toEqual([revised]);
 const beforeCoverage=await repository.listVendorCoverage(org,vendor.id);
 const change={organizationId:org,vendorId:vendor.id,scopeIds:[input.storeId],expectedVersion:coverageVersion(beforeCoverage),actor};
 await updateVendorCoverage(svc,change);
 expect((await repository.listVendorCoverage(org,vendor.id)).map(row=>row.scopeId)).toEqual([input.storeId]);
 expect(await repository.listVendorCoverage("foreign",vendor.id)).toEqual([]);
 expect(await repository.vendorCoversStore(org,vendor.id,input.storeId)).toBe(true);
 expect(await repository.vendorCoversStore(org,vendor.id,"store-northline-105")).toBe(false);
 await expect(updateVendorCoverage(svc,change)).rejects.toMatchObject({code:"CONFLICT"});
 const current=await repository.listVendorCoverage(org,vendor.id);
 await expect(updateVendorCoverage(svc,{...change,scopeIds:["foreign-store"],expectedVersion:coverageVersion(current)})).rejects.toMatchObject({code:"VALIDATION"});
 expect(await repository.listVendorCoverage(org,vendor.id)).toEqual(current);
 await updateVendorCoverage(svc,{...change,scopeIds:[org],expectedVersion:coverageVersion(current)});
 expect((await repository.listVendorCoverage(org,vendor.id)).map(row=>row.scopeKind)).toEqual(["organization"]);
 expect(await repository.vendorCoversStore(org,vendor.id,"store-northline-105")).toBe(true);
 await storeVendorRegression(repository);
 await capitalRegression(repository);
 await (await import("./warranty-center-regression")).warrantyCenterRegression(repository);
 expect(nextInspectionDate({...s,intervalUnit:"once"} as ComplianceSchedule,s.firstDueDate)).toBeNull();
 await vendorWarrantyPolicyRegression(repository);
}
