import {expect} from "vitest";
import type {OpsRepository} from "@/lib/ops/repository";
import {createStoreTask,updateStoreTask,accessTask,markTaskSeen,taskIdentity} from "@/lib/ops/store-tasks";
import type {NewStoreTask} from "@/lib/ops/store-tasks";
export async function storeTaskRegression(r:OpsRepository) {
 const org='org-northline-demo',store='store-northline-104',now='2026-09-28T12:00:00.000Z';
 const manager={organizationId:org,actorType:'user' as const,actorId:'membership-northline-facilities',actorName:'Jordan Lee'};
 const local={...manager,actorId:'membership-northline-store-104',actorName:'Store manager'};
 const peer={...manager,actorId:'membership-northline-executive',actorName:'Executive'};
 const input:NewStoreTask={storeId:store,title:'Check two camera windows',instructions:'Confirm arrival and departure.',kind:'camera',assignment:'local',fallbackId:manager.actorId,priority:'urgent',dueAt:'2099-09-29T12:00:00Z',notifyRequester:false,windows:[{start:now,end:'2026-09-28T13:00:00Z',area:'Back door'},{start:'2026-09-28T14:00:00Z',end:'2026-09-28T15:00:00Z',area:'Front door'}]};
 const people=await r.listTaskPeople(org,store,'');expect(people.some(p=>p.id===local.actorId&&p.local)).toBe(true);expect(people.some(p=>p.id==='membership-northline-store-105')).toBe(false);expect(people.some(p=>p.role==='vendor_user')).toBe(false);
 expect((await r.listTaskPeople(org,store,'',true)).every(p=>p.local)).toBe(true);
 const privateTask=await createStoreTask(r,manager,{...input,kind:'general',windows:[],assignment:'person',assigneeId:peer.actorId});
 await expect(accessTask(r,org,privateTask.id,local.actorId)).rejects.toMatchObject({code:'FORBIDDEN'});
 await expect(createStoreTask(r,manager,{...input,dueAt:now},[],now)).rejects.toMatchObject({code:'VALIDATION'});
 const literal=await createStoreTask(r,manager,{...input,windows:[{start:'2026-09-28T13:00',end:'2026-09-28T15:30',area:''}]},[],now);expect(JSON.parse(literal.windowsJson)[0].start).toBe('2026-09-28T13:00');
 const t=await createStoreTask(r,manager,input,[],now);expect(t.workOrderId).toBeNull();
 await expect(accessTask(r,'other',t.id,manager.actorId)).rejects.toMatchObject({code:'NOT_FOUND'});
 await expect(accessTask(r,org,t.id,'membership-northline-store-105')).rejects.toMatchObject({code:'FORBIDDEN'});
 const query={...await taskIdentity(r,org,local.actorId),view:'shared' as const,now};
 expect((await r.queryStoreTasks({organizationId:org,storeIds:[store]},query)).items.some(x=>x.id===t.id)).toBe(true);
 expect((await r.queryStoreTasks({organizationId:org,storeIds:[]},query)).totalCount).toBe(0);
 await expect(updateStoreTask(r,manager,t.id,{action:'claim',expectedVersion:1})).rejects.toMatchObject({code:'FORBIDDEN'});
 let current=await updateStoreTask(r,local,t.id,{action:'claim',expectedVersion:1});
 expect((await r.queryStoreTasks({organizationId:org},query)).items.some(x=>x.id===t.id)).toBe(false);
 await expect(updateStoreTask(r,local,t.id,{action:'complete',expectedVersion:current.version,body:'Checked.',result:'done',findings:[]})).rejects.toMatchObject({code:'VALIDATION'});
 current=await updateStoreTask(r,local,t.id,{action:'reply',expectedVersion:current.version,body:'Which entrance?'},[],'2026-09-28T16:00:00Z');
 const own={...await taskIdentity(r,org,manager.actorId),view:'waiting' as const,now};
 expect((await r.queryStoreTasks({organizationId:org},own)).items.find(x=>x.id===t.id)?.newReply).toBe(1);
 await markTaskSeen(r,manager,t.id,'2026-09-28T16:01:00Z');expect((await r.queryStoreTasks({organizationId:org},own)).items.find(x=>x.id===t.id)?.newReply).toBe(0);
 current=await updateStoreTask(r,manager,t.id,{action:'reply',expectedVersion:current.version,body:'The rear service entrance.'});expect(current.claimantId).toBe(local.actorId);
 const findings=input.windows.map(()=>({start:'2026-09-28T13:05',end:'2026-09-28T15:20',result:'different' as const,notes:'Vendor not seen.'}));
 await expect(updateStoreTask(r,local,t.id,{action:'complete',expectedVersion:current.version,body:'Mismatch.',result:'done',findings})).rejects.toMatchObject({code:'VALIDATION'});
 current=await updateStoreTask(r,local,t.id,{action:'complete',expectedVersion:current.version,body:'No matching visit.',result:'attention',findings});expect(current.status).toBe('review');expect(JSON.parse((await r.listTaskMessages(org,t.id,0,'complete'))[0].findingsJson)[0].start).toBe('2026-09-28T13:05');
 await expect(updateStoreTask(r,local,t.id,{action:'review',expectedVersion:current.version})).rejects.toMatchObject({code:'FORBIDDEN'});
 current=await updateStoreTask(r,manager,t.id,{action:'send_back',expectedVersion:current.version,body:'Check the loading area.',dueAt:'2099-09-30T12:00:00Z'});expect(current.claimantId).toBe(local.actorId);
 current=await updateStoreTask(r,local,t.id,{action:'complete',expectedVersion:current.version,body:'All matched.',result:'done',findings:findings.map(f=>({...f,result:'matches'}))});expect(current.status).toBe('closed');
 expect((await r.listTaskMessages(org,t.id)).filter(m=>m.kind==='complete')).toHaveLength(2);
 const shared=await createStoreTask(r,manager,{...input,kind:'general',assignment:'responsible',windows:[],notifyRequester:true});
 const race=await Promise.allSettled([manager,peer].map(a=>updateStoreTask(r,a,shared.id,{action:'claim',expectedVersion:1})));expect(race.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(race.filter(x=>x.status==='rejected')).toHaveLength(1);
 let claimed=(await r.getStoreTask(org,shared.id))!;const winner=claimed.claimantId===peer.actorId?peer:manager;
 claimed=await updateStoreTask(r,winner,shared.id,{action:'complete',expectedVersion:claimed.version,result:'done',body:'Done.'});expect(claimed.status).toBe('review');
 claimed=await updateStoreTask(r,manager,shared.id,{action:'review',expectedVersion:claimed.version});expect(claimed.status).toBe('closed');
 await expect(updateStoreTask(r,manager,shared.id,{action:'review',expectedVersion:claimed.version-1})).rejects.toMatchObject({code:'CONFLICT'});
 const overdue=await createStoreTask(r,manager,{...input,kind:'equipment',windows:[],assignment:'person',assigneeId:local.actorId,fallbackId:peer.actorId,dueAt:'2026-09-01T12:00:00Z'},[],'2026-08-31T12:00:00Z');
 const mine={...await taskIdentity(r,org,peer.actorId),view:'mine' as const,now};expect((await r.queryStoreTasks({organizationId:org},mine)).items.some(t=>t.id===overdue.id)).toBe(true);
 const unable=await updateStoreTask(r,local,overdue.id,{action:'complete',expectedVersion:1,body:'Equipment inaccessible.',result:'unable'});expect(unable.status).toBe('review');expect((await r.queryStoreTasks({organizationId:org},mine)).items.some(t=>t.id===overdue.id)).toBe(false);
 await expect(updateStoreTask(r,manager,overdue.id,{action:'send_back',expectedVersion:unable.version,body:'Try again.',dueAt:now},[],now)).rejects.toMatchObject({code:'VALIDATION'});
 const reassigned=await updateStoreTask(r,manager,overdue.id,{action:'reassign',expectedVersion:unable.version,assignment:'person',assigneeId:peer.actorId,body:'Please help.'});expect(reassigned.assigneeId).toBe(peer.actorId);
 await expect(createStoreTask(r,manager,{...input,workOrderId:'wo-northline-103'})).rejects.toMatchObject({code:'VALIDATION'});
 await expect(createStoreTask(r,local,{...input,storeId:'store-northline-105'})).rejects.toMatchObject({code:'FORBIDDEN'});
}
